### ISSUE TITLE
make weekendDays customizable 

### ISSUE THREAD

**Issue by terryBaz** [aleksanderwozniak/table_calendar#104]
- 

In arabic countries the weekend is **friday and saturday**, so I would like to have a customizable weekends.
I already have a solution, let me know if you accept a PR.

- 

also for `StartingDayOfWeek startingDayOfWeek` i would like to add **saturday** to `enum StartingDayOfWeek { monday, sunday }`

**Comment by aleksanderwozniak** [comment]
Sure, go for it!

Side note tho - I am going on holidays, so I'll merge it later

**Comment by maxgmer** [comment]
Same here, need customWeekendBuilder and StartingDayOfWeek.saturday, has this been solved already/is going to be solved? (if not, I can start working on these features myself)

**Comment by terryBaz** [comment]
@maxgmer sorry for the delay,
waiting to merge the PR, meanwhile you could use : 
in `pubspec.yaml`
```yaml
table_calendar:
    git:
      url: git://github.com/terryBaz/table_calendar.git
      ref: weekend-days-customizable
```
and 
You could change the weekend days (default is `[DateTime.saturday, DateTime.sunday]`), you just need to use the `weekendDays` property (a list of `DateTime.xday`) like this :

```dart
TableCalendar(
  //...
  weekendDays: const [DateTime.friday, DateTime.saturday],
  //...
),
```
