### ISSUE TITLE
RenderFlex overflow

### ISSUE THREAD

**Issue by dgr1992** [aleksanderwozniak/table_calendar#105]
When I add the calendar like shown in the example I get following error Message:

════════ Exception Caught By rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 62 pixels on the bottom.

The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The yellow and black bars show up on the screen for a split second but than disappear.

What am I doing wrong?

**Comment by joaowd** [comment]
I'm having the same problem, this happens for example on a iPad and you are on Portrait mode.

**Comment by aleksanderwozniak** [comment]
This could be related to #38 or #60. Try specifying `rowHeight`.

**Comment by jdeltoft** [comment]
@aleksanderwozniak Thanks for the awesome package, first off.  

I have a question about this issue.  So for me changing rowHeight doesn't seem appropriate.  What I would like to do is apply a scale to the output Table.  I entered a flutter question on this actually:
https://github.com/flutter/flutter/issues/56687

Do you know of any way to maybe do this?

**Comment by jamesncl** [comment]
I'm also struggling to make table calendar scale to fit when there isn't enough room. I have a screen where there isn't quite enough room when there are 5 rows in a month, and the only solution I can find is to wrap it in a `SingleChildScrollView`. I've tried wrapping in combinations of `FittedBox` and `AspectRatio`, which seems like it should work, but the calendar refuses to respond to these size constraints.

This is an awesome library, but seems like there are elements which use fixed sizes, which unfortunately means ignore parent box constraints.

**Comment by Arcadie90** [comment]
The easiest solution I found is to add `FlexibleSpaceBar` widget to the `flexibleSpace` of the `AppBar`. Something like this:
```
AppBar(
            backgroundColor: constants.RED_COLOR,
            title: Text(
              formattedDate
            ),
            flexibleSpace: FlexibleSpaceBar(
              title: MyCalendarWidget
            )),
```

**Comment by aleksanderwozniak** [comment]
v3.0.0 introduces `shouldFillViewport` property, which I think might solve this issue without having to use `rowHeight`. There is a lot of changes in that release, but you can quickly test it by running [examples](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-beta/example/lib) from `3.0.0-beta` branch locally, and modifying the UI to imitate your situation.

If you want to use `3.0.0-beta` branch in your project, add this to `pubspec.yaml`:

```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: 3.0.0-beta
```

**Comment by aleksanderwozniak** [comment]
3.0.0 prerelease with updated API has been uploaded to pub.dev: https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0
