### ISSUE TITLE
onDaySelected only when tapped

### ISSUE THREAD

**Issue by lee-40square** [aleksanderwozniak/table_calendar#106]
It seems that the `onDaySelect` property is called when the widget is built. Is there a way to only trigger it when the user taps on the date? Alternately, what's the best practice to call a function based on an onTap event? I want to trigger an action whenever a user taps on a date.

**Comment by qaudaffyazmi** [comment]
looking for the same thing, just like calendarro onTap() feature

**Comment by aleksanderwozniak** [comment]
But it does get called only when user taps on a given date... Take a look at example project.

**Comment by lee-40square** [comment]
When I run it on my emulator and do a hot reload the `onDaySelect` is triggered, without any interaction with the UI. This makes development problematic since I have a route tied to `onDaySelect`. Thoughts or advice?

**Comment by aleksanderwozniak** [comment]
@lee-40square 
That should not happen. Can you post your code here then? Also, try running the example project and see if issue persists - it does not for me.

**Comment by lee-40square** [comment]
Thank you very much for your patience. I'm still new to Flutter/Dart and was making a noob mistake. I was instantiating the method `onDaySelected: _onDaySelected()` instead of calling it `onDaySelected: _onDaySelected`.  So, of course, the method was being called when the widget was being built.

Sorry about that. Problem solved.

**Comment by aleksanderwozniak** [comment]
No problem, I am glad you got it to work :)
