### ISSUE TITLE
Versions conflict on Intl

### ISSUE THREAD

**Issue by laxian** [aleksanderwozniak/table_calendar#107]
When flutter upgrade to 1.9.7. I got this error:

Running "flutter pub get" in xxx...                         
Because table_calendar 2.0.1 depends on intl ^0.15.7 and no versions of table_calendar match >2.0.1 <3.0.0, table_calendar ^2.0.1 requires intl ^0.15.7.

So, because aixue4 depends on both intl ^0.16.0 and table_calendar ^2.0.1, version solving failed.
pub get failed (1)
exit code 1

So. I downgrade flutter.

**Comment by laxian** [comment]
> Try to remove your `intl: ^0.16.0`
> In my case I use `flutter_localizations: sdk: flutter`
> I just remove that and it works

It dosen't work to me.

**Comment by aleksanderwozniak** [comment]
**Table Calendar** `2.0.2` should solve this issue, feel free to reopen if it doesn't help

**Comment by shinayser** [comment]
I can't make 2.0.2 work with current flutter stable ( v1.9.1+hotfix.4). It doesn't match the version that flutter_localizations requires:

```
Because table_calendar >=2.0.2 depends on intl ^0.16.0 and every version of flutter_localizations from sdk depends on intl 0.15.8, table_calendar >=2.0.2 is incompatible with flutter_localizations from sdk.
So, because mydenox_flutter depends on both flutter_localizations any from sdk and table_calendar ^2.0.2, version solving failed.

```

**Comment by aleksanderwozniak** [comment]
@shinayser 
Look here #113. Should get resolved this week.
