### ISSUE TITLE
Events from firebase or calendar

### ISSUE THREAD

**Issue by KeiShadow** [aleksanderwozniak/table_calendar#108]
Hello, i have question how to change an events when i have it from realtime database (firebase) or from Calendar? 
In my code Im using StreamSubscription and when the event change i want to calendar will change all events dependences on firebase events.
But there is no chance to change it, i was searching in your code and events are const.

Thx for help.

**Comment by hieuseesaa** [comment]
have you solved this problem?. Can you share the code?. Thank you
