### ISSUE TITLE
Add gestures

### ISSUE THREAD

**Issue by pmcarlos** [aleksanderwozniak/table_calendar#11]
Any chance to detect the vertical slide to change between calendar formats?
So when pull down the calendar month is displayed

**Comment by aleksanderwozniak** [comment]
Sure, I'll play around with it and see what we can get

**Comment by aleksanderwozniak** [comment]
After doing some research and fiddling with results, I've decided to make my own easy and reliable Swipe detection - and published it as a package. If you'd like to use it, you can find it here: https://pub.dartlang.org/packages/simple_gesture_detector

As for `TableCalendar`, SwipeToExpand should be working out of the box as of version `0.3.2`!

Keep in mind to have `availableCalendarFormats` list in correct order - from biggest format to smallest, eg:
```dart
availableCalendarFormats: [
  CalendarFormat.month,
  CalendarFormat.twoWeeks,
  CalendarFormat.week,
],
```

or

```dart
availableCalendarFormats: [
  CalendarFormat.month,
  CalendarFormat.week,
],
```

**Comment by pmcarlos** [comment]
I was just about to create a PR with this changes, I did using https://pub.dartlang.org/packages/swipedetector
but thats great you have already implemented
