### ISSUE TITLE
Choose year

### ISSUE THREAD

**Issue by Phuonghoang1001** [aleksanderwozniak/table_calendar#112]
i cant choose year without click buttons next or previous. Please help me! Thanks

**Comment by aleksanderwozniak** [comment]
Use `_calendarController.setFocusedDay()` with DateTime containing your desired year - more details [here](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarController/setFocusedDay.html).

Also check out general [API reference](https://pub.dev/documentation/table_calendar/latest/table_calendar/table_calendar-library.html).
