### ISSUE TITLE
Versions conflict on Intl

### ISSUE THREAD

**Issue by shriharip** [aleksanderwozniak/table_calendar#113]
Sorry, to open this again. But with flutter_localizations installed, I am not able to use the table_calendar as the version solving fails since localizations depend on intl 1.5.8 and table calendar uses 1.6. And it is almost impossible to remove either of them in my case :). 

Hence opening this issue again and hope to get it resolved.

**Comment by zenoachtig** [comment]
I ran into this as well, and the trick seems to be to update the internal Flutter packages, which will update flutter_localizations as well, which will bump its dependency to intl 1.6.

Try running `flutter update-packages --force-upgrade`, worked for me.

**Comment by shriharip** [comment]
> I ran into this as well, and the trick seems to be to update the internal Flutter packages, which will update flutter_localizations as well, which will bump its dependency to intl 1.6.
> 
> Try running `flutter update-packages --force-upgrade`, worked for me.

This worked for me too. But I do not know all the backlash :) from force upgrade. 
Anyways I leave it to @aleksanderwozniak  to either close this or look into this. 

@zenoachtig thanks again

**Comment by aleksanderwozniak** [comment]
@shriharip 
This will be fixed with next package update :)

**Comment by aleksanderwozniak** [comment]
TableCalendar `2.1.0` is available now, it should not have problems with intl dependency.
