### ISSUE TITLE
Error at installing  'A package may not list itself as a dependency.'

### ISSUE THREAD

**Issue by Liliana99** [aleksanderwozniak/table_calendar#117]
At the moment to install on pubspec.yaml, with versión => table_calendar: ^2.0.2
Shows this error 
" Running "flutter pub get" in table_calendar...                  
Error on line 27, column 3 of pubspec.yaml: A package may not list itself as a dependency."

I tried to install , another calendar to know , if I did any error to write on pubspec.ymal, but the another package works well.

**Comment by aleksanderwozniak** [comment]
Does your pubspec.yaml file start with `name: table_calendar`?

**Comment by Liliana99** [comment]
on my pubspec.yaml   I'd installed like this:

dependencies:
  table_calendar: ^2.0.2

**Comment by aleksanderwozniak** [comment]
In this case, I will need you to paste the whole pubspec.yaml content here as a code.
