### ISSUE TITLE
Mode week event error.

### ISSUE THREAD

**Issue by MarceloRab** [aleksanderwozniak/table_calendar#118]
When the calendar is in week mode, if I click on the 29th or 30th (if they are on the 1st and 2nd day each week), events from days 1 (Tuesday) through 5 (Saturday), next month, disappear.

In month mode this does not happen as no two month events appear at the same time.

**Comment by aleksanderwozniak** [comment]
I will need to see your code and screenshots, or even better - a video showing this behavior.

**Comment by MarceloRab** [comment]
I am already very pleased for your attention. 

I am already very pleased for your attention. How can I insert a short video here?

**Comment by MarceloRab** [comment]
Link - short video - https://drive.google.com/file/d/1L3nEKXUq4KsPPhquk8bFt3XkgskIT9mR/view?usp=sharing

**Comment by aleksanderwozniak** [comment]
Updating the month label when a different month gets selected is the expected behavior.

If you want to keep the events from both months, then you need to update `calendarController.events` accordingly.

**Comment by MarceloRab** [comment]
Even if you update the events, only the events of the selected month appear. This is the default. Note that by selecting a different month, the day number becomes clearer.

**Comment by aleksanderwozniak** [comment]
Sorry, my bad.

I've fixed it, the solution is already pushed to `dev` branch.

Let me know if it works correctly now.

**Comment by MarceloRab** [comment]
I may be asking something basic, but has an update been made?

Can I get her here already?

table_calendar:
     git:
       url: git: //github.com/aleksanderwozniak/table_calendar.git
       ref: dev

**Comment by aleksanderwozniak** [comment]
Yes, you should be able to use it now. Refresh your packages with `flutter pub get`. Make sure it gets fetched again.

**Comment by MarceloRab** [comment]
Sorry, but the behavior remains the same.

I was able to solve it this way:

` void _onVisibleDaysChanged(
      DateTime first, DateTime last, CalendarFormat format) {

    if (first.month == last.month && _isTwoMothVisible) {
      _agendaBloc.calendarController.setCalendarFormat(CalendarFormat.month);
    }

    if (first.month != last.month)
      _isTwoMothVisible = true;
    else
      _isTwoMothVisible = false;
  }`

`@override
  void initState() {

var date = DateTime.now();
    if (DateTime(date.year, date.month + 1, 0).weekday == 6) {
      _isTwoMothVisible = false;
    }

`

**Comment by aleksanderwozniak** [comment]
Both months can have and display events at the same time:

<img src="https://user-images.githubusercontent.com/22658673/65978405-ed975280-e473-11e9-9b66-153e976c108b.png" width=300>
<img src="https://user-images.githubusercontent.com/22658673/65978411-f1c37000-e473-11e9-9d4e-56f0d19b460c.png" width=300>

This ^ is taken from example project.

**Comment by MarceloRab** [comment]
What could be wrong in my code to explain this behavior?  

As shown here
https://drive.google.com/file/d/1L3nEKXUq4KsPPhquk8bFt3XkgskIT9mR/view?usp=sharing

**Comment by aleksanderwozniak** [comment]
The easiest way would be to compare your code to example project.

`outsideDaysVisible` should have no impact on this issue - but if it has, then you don't have the latest package version installed and you need to refresh it.

**Comment by MarceloRab** [comment]
Thanks a lot for the help. I had to manipulate some things because of the stream and the real time and I think there may be some problem building the events. Since I don't know the insides of design, it makes the problem very abstract. I will make some attempts and post here if I find a solution.

**Comment by MarceloRab** [comment]
Hi Alekander (@aleksanderwozniak ). It's working as you would like !!!

 Only with the 

```
CalendarStyle change (
          outsideDaysVisible: true,
```

Remembering that I'm using

table_calendar:
      git:
        url: git: //github.com/aleksanderwozniak/table_calendar.git
        ref: dev

**Comment by cuongdl** [comment]
Hi Team,

Why Month format is week, two weeks is month and week is two weeks?
![65978405-ed975280-e473-11e9-9b66-153e976c108b](https://user-images.githubusercontent.com/16604076/109931352-56cf6500-7cfb-11eb-8086-f247751f2beb.png)

Thank you!

**Comment by aleksanderwozniak** [comment]
@cuongdl 
Check this: https://github.com/aleksanderwozniak/table_calendar/issues/199#issuecomment-590004818
