### ISSUE TITLE
Date Range Picker

### ISSUE THREAD

**Issue by R1235** [aleksanderwozniak/table_calendar#119]
Hi,
Can you add a feature in this library selecting the date range. Ex selecting dates from 2 to 25 in a particular month to see all the events which are between 2 and 25.
Thanks.

**Comment by palomacorreia** [comment]
@R1235 
got any workaround?

**Comment by ReniDelonzek** [comment]
+1

**Comment by serendipity1004** [comment]
@aleksanderwozniak Hi, thanks for the library. We need this feature very desperately so I have added a pull request for this. If you want me to change anything regarding coding standard or w/e, please do tell me.

**Comment by aleksanderwozniak** [comment]
Let's follow this in #153
