### ISSUE TITLE
is there a way to make header clickable?

### ISSUE THREAD

**Issue by LinoAlejandro** [aleksanderwozniak/table_calendar#120]
i was thinking if there is a way to make header clickable, so it launches a dialog on tap

**Comment by aleksanderwozniak** [comment]
You mean just the 'month-year' label? I will need to add the callback then.

**Comment by LinoAlejandro** [comment]
hi alek, yes, a callback for click on month-year label, that would be awesome. Thank you very much for your time

**Comment by aleksanderwozniak** [comment]
This is now available with TableCalendar `2.2.1` :)

**Comment by LinoAlejandro** [comment]
i love you bro, thanks
