### ISSUE TITLE
when is markersBuilder or singlemarkerbuilder called? 

### ISSUE THREAD

**Issue by LinoAlejandro** [aleksanderwozniak/table_calendar#121]
i am adding dinamically events in the calendar, but when i added it with

setState(() { events = newEvents})

it doesn't triggers any of the markers builders

**Comment by aleksanderwozniak** [comment]
See [this](https://github.com/aleksanderwozniak/table_calendar/issues/86#issuecomment-536327384)

**Comment by LinoAlejandro** [comment]
thank you very much
