### ISSUE TITLE
Arrow left and right invisible and header tittle swap animated

### ISSUE THREAD

**Issue by bilaloz** [aleksanderwozniak/table_calendar#122]
how to do Arrow left and right invisible and header tittle swap animated thanks.

**Comment by aleksanderwozniak** [comment]
You can hide the header altogether with `headerVisible: false` and build your own widget on top of `TableCalendar`.

**Comment by bilaloz** [comment]
All right , but I touch swap header to next week so month , like body

**Comment by badaween-ahmed** [comment]
@aleksanderwozniak But how? Header is not a separate Widget right? How to build a custom header without the existing header title (month with the year)? It would be nice to use header as a  separate widget. I just want to add a 'jump to today button'.

**Comment by badaween-ahmed** [comment]
Okay, I found the solution. It's `_calendarController.focusedDay` and it needs to be wrapped inside a `Builder` for context otherwise it will throw `The getter 'month' was called on null.`

**Comment by hzbsccd** [comment]
@badaween-ahmed Have you settled the question: 'jump to today'? and how?

**Comment by badaween-ahmed** [comment]
@hzbsccd 
```dart
() {
         calendarController.setSelectedDay(
           DateTime(now.year, now.month, now.day),
            runCallback: true,
           );
       },
```
here is the code. 
also check this: https://github.com/aleksanderwozniak/table_calendar/issues/147#issue-515607196
