### ISSUE TITLE
StartingDayOfWeek not working except monday

### ISSUE THREAD

**Issue by maxgmer** [aleksanderwozniak/table_calendar#123]
StartingDayOfWeek.sunday causes an extra row of days to appear:
![Screenshot_2019-10-03-15-32-28-357_com example example](https://user-images.githubusercontent.com/24964174/66126984-653fbb80-e5f3-11e9-814a-5a41d792e47e.png)
Steps to reproduce: open your example project, set outsideDaysVisible to true, set startingDayOfWeek to StartingDayOfWeek.sunday. 

Then find a month where last month day is Saturday.

**Comment by maxgmer** [comment]
I am going to fix this along with adding StartingDayOfWeek.saturday

**Comment by aleksanderwozniak** [comment]
Have you tried it on the `dev` branch? 

Works properly for me:

<img src=https://user-images.githubusercontent.com/22658673/66129970-33c5f080-e5f1-11e9-90af-5270de620667.png width=300>

**Comment by maxgmer** [comment]
Yeah, sorry for my unattentiveness, seems to be working there. Then I'd get changes from `dev` and add a StartingDayOfWeek.saturday feature there.
