### ISSUE TITLE
The getter 'month' was called on null.

### ISSUE THREAD

**Issue by sumitgohil** [aleksanderwozniak/table_calendar#126]
Everytime I try to display the calendar, it gives me this error. Here is the Log. 
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building TableCalendar(dirty, state: _TableCalendarState#6a6ba(ticker inactive)):
The getter 'month' was called on null.
Receiver: null
Tried calling: month

User-created ancestor of the error-causing widget was: 
  Column file:///Users/sumitgohil/Documents/FlutterApps/flutter_app_demo/lib/main.dart:90:16
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _DateFormatPatternField.formatMonth (package:intl/src/intl/date_format_field.dart:443:36)
#2      _DateFormatPatternField.formatField (package:intl/src/intl/date_format_field.dart:367:16)
#3      _DateFormatPatternField.format (package:intl/src/intl/date_format_field.dart:244:12)
#4      DateFormat.format.<anonymous closure> (package:intl/src/intl/date_format.dart:255:57)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by GonzaloSaad** [comment]
Is the `TableCalendar` inside of a `StatelessWidget`?

**Comment by aleksanderwozniak** [comment]
@sumitgohil 
I will need to see your `build()` method. You can also check the example project and look up differences in code.

**Comment by sumitgohil** [comment]
Hello, I tried Copying the Exact code from Example and it works. I might have ended up with some silly blunder. Thank you so much.

**Comment by hjalm8** [comment]
Had the same issue.

 
Change
`TableCalendar(
      calendarController: CalendarController()),`

to

`TableCalendar(
      calendarController: _calendarController),`

**Comment by Xezolpl** [comment]
Hello i have the same issue but none of previous advices helped me. I get the same error code but my code looks like this: 
```dart
class CalendarWidget extends StatelessWidget   {
  final List<Measurement> measurements;

  const CalendarWidget(this.measurements, {Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var _events = Map<DateTime, List<dynamic>>();
    final _calendarController = CalendarController();

    ///There is only one measurement per day.
    measurements.forEach((element) {
      _events.addAll({
        element.date: [element]
      });
    });

    return TableCalendar(
      availableGestures: AvailableGestures.horizontalSwipe,
      initialCalendarFormat: CalendarFormat.month,
      startingDayOfWeek: StartingDayOfWeek.monday,
      calendarController: _calendarController,
      events: _events,
      headerStyle: HeaderStyle(
        centerHeaderTitle: true,
        formatButtonVisible: false,
      ),
      calendarStyle: CalendarStyle(
        canEventMarkersOverflow: true,
        todayColor: Colors.cyan[300],
        selectedColor: Colors.orange,
      ),
      onDaySelected: (date, events) {
        Router.navigator.pushNamed(Routes.measurementPage,
            arguments: MeasurementPageArguments(
                editedMeasurement:
                    events.isEmpty ? null : events.first as Measurement,
                date: DateTime.now()));
      },
      builders:
          CalendarBuilders(markersBuilder: (context, date, events, holidays) {
        return [
          Container(
              alignment: Alignment.center,
              child:
                  Icon(Icons.accessibility_new, size: 32, color: Colors.black)),
        ];
      }),
    );
  }
}
```
and I don't know why am I getting this error. 
It is thrown when e.g. rotation of the device changes or when i come back to route with this Calendar from the other one.
Is it caused by calendarController?
 I have a few differences with the example code - I operate on the StatelessWidget and my controller is marked as final. Could it cause this issue?

**Comment by rafaelmarinhos** [comment]
Same problem here!
I've been trying to solve this all day and nothing
HELP ME PLEASE!

**Comment by riyasm449** [comment]
Try TableCalendar() inside SingleChildScrollView()

example:
Widget build(BuildContext context) {  
  return Scaffold(  
    body: SingleChildScrollView(  
      child: Column(  
        children: <Widget>[  
          TableCalendar()  
        ],  
      ),  
    ),  
  );

**Comment by tharwatsamy** [comment]
I have the same issue and i am only using the widget itself with a controller

**Comment by aleksanderwozniak** [comment]
If you are creating new `CalendarController` instances in `build()` method, you should move it to `initState()`: https://github.com/aleksanderwozniak/table_calendar/issues/385#issuecomment-765041500.
