### ISSUE TITLE
Calendar screen scroll 

### ISSUE THREAD

**Issue by bilaloz** [aleksanderwozniak/table_calendar#127]
How to shrink calendar scrolling?
should be based on the status of the screen while browsing the listitem ? Is it possible ?

example like : https://github.com/pmcarlos/flutter_clean_Calendar/raw/master/calendar.gif

**Comment by aleksanderwozniak** [comment]
[Readme literally has just that at the top](https://github.com/aleksanderwozniak/table_calendar#table-calendar)

You will want to set current `CalendarFormat` to `CalendarFormat.week`:
```dart
setState(() {
  _calendarController.setCalendarFormat(CalendarFormat.week);
});
```

**Comment by andersonmendesdev** [comment]
> [Readme literally has just that at the top](https://github.com/aleksanderwozniak/table_calendar#table-calendar)
> 
> You will want to set current `CalendarFormat` to `CalendarFormat.week`:
> 
> ```dart
> setState(() {
>   _calendarController.setCalendarFormat(CalendarFormat.week);
> });
> ```
It is possible to stop this scrolling, for example I do not use the event view, I only need the calendar in month mode with marking the number of events in days, but I do not want to drag your finger to change to week mode, I wanted that and always stayed in month mode, is it possible?

**Comment by aleksanderwozniak** [comment]
You can set it whenever you detect a scrolling event.
