### ISSUE TITLE
New feature : load events on view changed

### ISSUE THREAD

**Issue by benoitverstraete** [aleksanderwozniak/table_calendar#13]
Hi,

Do you plan to implement a feature that allow the developer to load the `events` only when the calendar is swiped to the left or right (visibleRangeChanged for an example of the signature) ? It will avoid to load a complete set of unnecessary data, but only load "on demand".

Thanks a lot !

**Comment by aleksanderwozniak** [comment]
I've added `onVisibleDaysChanged` callback to version `1.0.0`.

It exposes the first and last of currently visible days.
You can use it like in [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart), it should work just as requested.
