### ISSUE TITLE
dynamically add data to the _holidays variable

### ISSUE THREAD

**Issue by ederluca** [aleksanderwozniak/table_calendar#131]
Good evening
Is it possible to include data in the holidays variable retrieved from the database?
I made the following structure:

`Future<Null> getCalendar() async {
    var url =
        "http://192.168.0.11/sistema/appCalendario.php?LgeOffID=1&LgeEmpID=115&bd=ac01";

    var client = new http.Client();
    try {
      final response = await client.get(url);
      final result = json.decode(response.body);

      setState(() {
        listholidays = result['Holidays'];
        int day = 0, month = 0, year = 0;
        
        for (int i = 0; i < listholidays.length; i++) {
          year = int.parse(listholidays[i]['year']);
          month = int.parse(listholidays[i]['month']);
          day = int.parse(listholidays[i]['day']);  

          _holidays = {
            DateTime(year, month, day): [listferiados[i]['FerDesc']],
          };
        }       
      });
    } finally {
      client.close();
    }
  }`
Where I have only the last inclusion I can't popular with many elements can anyone help me?

**Comment by aleksanderwozniak** [comment]
The culprit lays here:

```dart
_holidays = {
  DateTime(year, month, day): [listferiados[i]['FerDesc']],
};
```

You are overriding `_holidays` with a single entry every time (instead of adding new items to it).

However, for complete solution you will need to either use `dev` branch, or wait until I release next `TableCalendar` version.

**Comment by aleksanderwozniak** [comment]
Version `2.1.0` has been released. It adds support for dynamic holidays.

**Comment by blackbeario** [comment]
While I realize this is probably a Dart syntax issue, and isn't a problem with TableCalendar or the holidays variable directly, I am hoping someone can help me with the same problem of adding multiple items to my `_events` from Firestore. If I write this below, then I overwrite the DateTime with each entry in my forEach loop.
```events.forEach((event) =>
        _events = {
          event.scheduled: [event]
        }
      );```
But if I try something like `_jobs.addAll({event.scheduled: eventList})` or `_jobs.update(job.scheduled, job)` I get all sorts of type errors. Can anyone direct me on the correct way to do this?
