### ISSUE TITLE
TableCalendar not working with Dart >= 2.2.0

### ISSUE THREAD

**Issue by DevNico** [aleksanderwozniak/table_calendar#132]
If the used Dart SDK is >= 2.2.2 the TableCalendar widget doesn't work properly. If you tap on a day in the table nothing changes until you tap somewhere else a second time. If that place is the day again the callback `onDaySelected` is called twice.

**Comment by aleksanderwozniak** [comment]
Can you run `flutter doctor -v` and post the results here?

**Comment by DevNico** [comment]
I can't seem to reproduce the issue. Since posting this issue I changed a lot in my application and therefore don't know what was the original cause and therefore closing this issue.
