### ISSUE TITLE
How to get the value of selected date?

### ISSUE THREAD

**Issue by AnuragVadd** [aleksanderwozniak/table_calendar#139]
Hey aleksander! I am really enjoying this plugin. I just have a quick question - How do i get the date selected in the calendar? I want to implement a feature which lets the user jump to a specific page in my app but in order to implement that i need to get the date selected in the format of `DateTime`

**Comment by blackbeario** [comment]
The sample code uses this function, where `day` seems to be what you're looking for:

`  // This is called when a day is tapped on the calendar.
  void _onDaySelected(DateTime day, List events) {
    // do something else with day here
    setState(() {
      _selectedDay = day;
      _selectedJobs = events;
    });
  }`

**Comment by AnuragVadd** [comment]
I have  used a table calendar with builders. I want to pass the date selected inside the builder in another widget which is present outside the builder?

The builder of table calendar is defined here : 
`
         selectedDayBuilder: (context, date, _) {
          final DateTime datetime = date;
          return FadeTransition(
            opacity: Tween(begin: 0.0, end: 1.0).animate(_animationController),
            child: Container(
              margin: const EdgeInsets.all(4.0),
              padding: const EdgeInsets.only(top: 5.0, left: 6.0),
              color: Colors.deepOrange[300],
              width: 100,
              height: 100,
              child: GestureDetector(
                onDoubleTap: () async{
                  final PageRouteBuilder _route = PageRouteBuilder(
                      pageBuilder: (BuildContext context, _, __) {
                    return DayPageViewExample(dateToString(date));
                  });
                  await Navigator.pushAndRemoveUntil(context, _route, (Route<dynamic> r) => false);
                },
                child: Text(
                    '${date.day}',
                    style: TextStyle().copyWith(fontSize: 16.0),
                  ),
              ),
                ),
          );
        },
`

I have defined the table calendar inside a Row widget and below the calendar i have a `FlatButton` which is supposed to let the user pass the selected day to another page. 

I have been able to implement a `PageRoute` which requires the date selected by the user in the `selectedDayBuilder` but i am unable to pass that value to the `FlatButton` since it is only present inside the `selectedDayBuilder`. 

Can i get some suggestion on how i can pass the selected date `date` in the `selectedDayBuilder` to the `FlatButton`?

**Comment by aleksanderwozniak** [comment]
@AnuragVadd 
Two options here:
1) store a helper variable and set it when `_onDaySelected` is called (see @blackbeario's comment)
2) use `_calendarController.selectedDay` property directly in your `FlatButton`

**Comment by AnuragVadd** [comment]
Yep, works perfectly. Thanks for helping out!
