### ISSUE TITLE
Events not appearing

### ISSUE THREAD

**Issue by byronferguson** [aleksanderwozniak/table_calendar#14]
When I use the Map literal from the example folder to populate the events the expected event icons are painted. However, when I build the `TableCalendar` from a `StreamBuilder` that is returning a `Map<DateTime, List<String>>` no markers are painted.

**Comment by byronferguson** [comment]
The keys used a full timestamp, which is why they weren't passing the `if` condition to paint the markers. It might be usual for truncate time parts when checking for events.

**Comment by aleksanderwozniak** [comment]
@byronferguson Yes, that's correct.

I've upgraded `TableCalendar`'s behavior, it should now work no matter the 'time' part of `DateTime`.
