### ISSUE TITLE
Show events on load

### ISSUE THREAD

**Issue by sanders41** [aleksanderwozniak/table_calendar#141]
When the page is loaded if the current day has events it does not load them until the day is tapped. In the example project I know there is an example of how to do this, but in my case the event details are coming from an API and not hard coded in like the example. I can't find a way to get the events to show after they have been loaded from the API. Is this possible?

**Comment by SirLegui** [comment]
I believe you can load the content before creating the calendar itself, the same thing happened to me trying to add new events dynamically, but right now only works if you pre-charge the events

**Comment by aleksanderwozniak** [comment]
@sanders41 
Use `FutureBuilder` or `StreamBuilder`. This will ensure that `TableCalendar` widget gets build when data is ready.

For example something like this:
```dart
FutureBuilder(
  future: _fetchEvents(),
  builder: (context, snapshot) {
    if (!snapshot.hasData) {
      return CircularProgressIndicator();
    }

    final events = snapshot.data;

    return TableCalendar(
      calendarController: _calendarController,
      events: events,
      ... 
    );
  },
);
```

**Comment by RockinPaul** [comment]
Still experiencing the same. Trying to update TableCalendar with new events inside FutureBuilder but nothing happens until initState method will be called again (where I initialize the instance of CalendarController).

**Comment by sanders41** [comment]
Currently I am using a StreamBuilder, but this doesn't show the events until something is clicked.

**Comment by RockinPaul** [comment]
> Currently I am using a StreamBuilder, but this doesn't show the events until something is clicked.

Yep, it seems like the only workaround currently, as SirLegui mentioned - to put your FutureBuilder/StreamBuilder in parent widget, above the widget with TableCalendar inside, so the TableCalendar will be able to rebuild dynamically with the entire widget on data changes.

**Comment by aleksanderwozniak** [comment]
It behaves correctly for me without resorting to any workarounds. Make sure you are using `TableCalendar` version `2.1.0` - check in **both** `pubspec.yaml` and `pubspec.lock`.

Here is full, simple working example:
https://gist.github.com/aleksanderwozniak/1367892cbe39c25afda403b2300652ca

**Comment by sanders41** [comment]
I verified I am using 2.1.0. Doing it as in your example does show the events for the day on load. The problem I am having when doing it this way is no matter what day I click on the events that show are always for the current day.

**Comment by sanders41** [comment]
I was able to get it to work by creating a variable to track if it is the first time loading or not and only selecting the events based on DateTime if it is the first load.
