### ISSUE TITLE
how to make clickable false on specific date

### ISSUE THREAD

**Issue by basitsaleemmb** [aleksanderwozniak/table_calendar#143]
hi !
i want to make specific date to unclickable, how to do that?
regards

**Comment by aleksanderwozniak** [comment]
With **TableCalendar 2.2.0** you can now use `enabledDayPredicate`. If this function returns `false`, then the given `date` will be disabled.

```dart
enabledDayPredicate: (date) {
  return date.weekday != DateTime.sunday;
},
```

For example, this snippet disables all Sundays (or rather it enables all days except Sundays).

**Comment by riyasm449** [comment]
Thanks, it helps me a lot.

**Comment by aleksanderwozniak** [comment]
@riyasm449 
Glad it helps! Closing the other issue.
