### ISSUE TITLE
How to add a new Event?

### ISSUE THREAD

**Issue by AnuragVadd** [aleksanderwozniak/table_calendar#144]
I wanted to add events dynamically to this calendar and use these events to fetch to another screen. However, i am struggling to find a function which lets me add a new event. Could you point me to the exact function which lets me add a new event dynamically?

**Comment by aleksanderwozniak** [comment]
I would add a new event to your underlying data structure, and then rebuild the TableCalendar widget with updated `events` property.

**Comment by AnuragVadd** [comment]
hm.. i am not sure i understand what you meant, could you please elaborate?

**Comment by aleksanderwozniak** [comment]
@AnuragVadd 
Here is the complete example: https://gist.github.com/aleksanderwozniak/e9eb98bf28bd9fbb336039e1936c59aa

Note that it is just one way of doing it. My other example (mentioned by @joielechong) will also work there, you would just need to tailor it to your particular situation :)

Of course you can merge both of those examples and use `update` with Streams - which will result in better performance, albeit with more complicated code.

**Comment by AnuragVadd** [comment]
I have tried the add method in complete example. But the method `_BuildEventList` doesnt seem to be working. I have hardcoded some map values in it here - 
```
_selectedDay.subtract(Duration(days: 1)): ['task 1', 'task 2', 'task 3']
```.
