### ISSUE TITLE
Passing Date When Building Event List

### ISSUE THREAD

**Issue by malder08** [aleksanderwozniak/table_calendar#146]
Hi all! Sorry if this is a dumb question, I'm fairly new to Flutter. I was wondering how I could pass the date currently pressed on the calendar to the container that makes up the list in the code below. I need to be able to pass in the date so that I can access the corresponding Firestore Document with the information for that event. Thanks!

```
 Widget _buildEventList() {
    return ListView(
      children: _selectedEvents
          .map((event) => Container(
                decoration: BoxDecoration(
                  border: Border.all(width: 0.8),
                  borderRadius: BorderRadius.circular(12.0),
                ),
                margin: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 4.0),
                child: ListTile(
                  title: Text(event.toString()),
                  onTap: () => print('$event tapped!'),
                ),
              ))
          .toList(),
    );
  }
```

**Comment by aleksanderwozniak** [comment]
Take a look here: https://github.com/aleksanderwozniak/table_calendar/issues/139#issuecomment-546275377

**Comment by malder08** [comment]
That was exactly what I needed, thank you so much!
