### ISSUE TITLE
Multiple Initial Dates

### ISSUE THREAD

**Issue by LenvZyl** [aleksanderwozniak/table_calendar#153]
Are there any work arounds for Multiple Initial dates

**Comment by aleksanderwozniak** [comment]
Do you mean selection of multiple dates at once?

**Comment by Levi-ackerman** [comment]
@aleksanderwozniak  yes. Do you have any way to achieve  this image below ?
<img width="404" alt="Screen Shot 2019-11-17 at 21 28 01" src="https://user-images.githubusercontent.com/8068926/69041455-1c688880-0a22-11ea-833c-7e9bd18efa53.png">

**Comment by aleksanderwozniak** [comment]
Ah I see... Unfortunately there is no built-in support for multiple date selection at this moment. I will be adding it in the future.

**Comment by LenvZyl** [comment]
So What I did show multiple selected dates was to add the selected dates to events, and then modify the markersBuilder to display as if the date was selected.
And then when selecting a date, I am just adding it to events.
Works perfectly!

**Comment by andressilvac** [comment]
@LenvZyl that sounds great. Could you please share with us the code of your implementation?
Thank you!

**Comment by aleksanderwozniak** [comment]
I have added multiple selection in `3.0.0-beta` branch :rocket:

Here is how it works. You can use either multi-selection by tapping on individual dates, or you can select a continuous range of dates by tapping on a startDate and endDate.

| Multi-selection  | Range selection |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/22658673/106397947-5a2bb400-6410-11eb-97bb-03ba39aa37d3.png" width="250">  | <img src="https://user-images.githubusercontent.com/22658673/106397949-5c8e0e00-6410-11eb-8891-67fac9b41eb7.png" width="250"> |




**To use multi-selection:**

- Use `onDaySelected` callback to get the selected day. Add it to a collection (I'd recommend a `Set`*).
- Use `selectedDayPredicate` to tell the TableCalendar widget which days are selected. You will be given a DateTime object, so just check if it is present in your day collection - and return true/false.
- To clean the selection, you just need to reset the data inside collection (use `.clear()` on it). Rebuild the widget afterwards.

_* Actually, a `LinkedHashSet` with equality override would be even better - to compare just the date-part of DateTime object, as their time-part is redundant for us._

Here is a complete [example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_multi_example.dart) containing all of this.

**To use range selection:**

- Use `rangeSelectionMode` property. Set it to either `RangeSelectionMode.toggledOn`* or `RangeSelectionMode.enforced`.
- Create `rangeStart` and `rangeEnd` DateTime fields. Pass them to TableCalendar widget.
- Use `onRangeSelected` callback. Update both fields inside it. Rebuild the widget afterwards.

_* Range selection can be toggled on/off by longpressing a day cell in TableCalendar. When range selection mode is on, tapping will return ranges (`onRangeSelected`). When range selection is off, tapping will return single days (`onDaySelected`). To disable toggling on longpress, use `RangeSelectionMode.enforced` (always on), or `RangeSelectionMode.disabled` (always off)._

Here is a simple [example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_range_example.dart). Here is a bit more [complex example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_events_example.dart), starting in `RangeSelectionMode.toggledOff` state.

___

To use `3.0.0-beta` branch, add this to `pubspec.yaml`:

```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: 3.0.0-beta
```

**Comment by mees-brenzie** [comment]
> I have added multiple selection in `3.0.0-beta` branch 🚀
> 
> Here is how it works. You can use either multi-selection by tapping on individual dates, or you can select a continuous range of dates by tapping on a startDate and endDate.
> 
> Multi-selection	Range selection
> <img alt="" width="250" src="https://user-images.githubusercontent.com/22658673/106397947-5a2bb400-6410-11eb-97bb-03ba39aa37d3.png">	<img alt="" width="250" src="https://user-images.githubusercontent.com/22658673/106397949-5c8e0e00-6410-11eb-8891-67fac9b41eb7.png">
> **To use multi-selection:**
> 
> * Use `onDaySelected` callback to get the selected day. Add it to a collection (I'd recommend a `Set`*).
> * Use `selectedDayPredicate` to tell the TableCalendar widget which days are selected. You will be given a DateTime object, so just check if it is present in your day collection - and return true/false.
> * To clean the selection, you just need to reset the data inside collection (use `.clear()` on it). Rebuild the widget afterwards.
> 
> _* Actually, a `LinkedHashSet` with equality override would be even better - to compare just the date-part of DateTime object, as their time-part is redundant for us._
> 
> Here is a complete [example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_multi_example.dart) containing all of this.
> 
> **To use range selection:**
> 
> * Use `rangeSelectionMode` property. Set it to either `RangeSelectionMode.toggledOn`* or `RangeSelectionMode.enforced`.
> * Create `rangeStart` and `rangeEnd` DateTime fields. Pass them to TableCalendar widget.
> * Use `onRangeSelected` callback. Update both fields inside it. Rebuild the widget afterwards.
> 
> _* Range selection can be toggled on/off by longpressing a day cell in TableCalendar. When range selection mode is on, tapping will return ranges (`onRangeSelected`). When range selection is off, tapping will return single days (`onDaySelected`). To disable toggling on longpress, use `RangeSelectionMode.enforced` (always on), or `RangeSelectionMode.disabled` (always off)._
> 
> Here is a simple [example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_range_example.dart). Here is a bit more [complex example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_events_example.dart), starting in `RangeSelectionMode.toggledOff` state.
> 
> To use `3.0.0-beta` branch, add this to `pubspec.yaml`:
> 
> ```yaml
>   table_calendar:
>     git:
>       url: git://github.com/aleksanderwozniak/table_calendar.git
>       ref: 3.0.0-beta
> ```

@aleksanderwozniak Thank you very much for this feature! I really needed this.

I was looking into the beta branch and I noticed a lot of breaking changes. For example the CalendarController is now missing, the events list has been replaced with the eventLoader, the styling has been moved to one single object. I was wondering if there is a changelog available for this update, so I can see what the entirety of the update looks like before updating to the new version. 

Thank you!

**Comment by aleksanderwozniak** [comment]
@mees-brenzie 
v3.0.0 update is definitely a big one. I will be writing a proper guide for it, to explain some stuff. [Examples](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-beta/example/lib/pages) are also a great way to have a look at new API. 

Although it may seem like migrating would require a lot of work, it actually should be a rather straightforward and quick process. Many concepts from previous versions still apply, but are used in more flexible and performant ways.

Here is a list of some key features I thought were worth mentioning. You will find a list of most important API modifications underneath it.

____

Key features:
* Improved horizontal scrolling animation (no 'blank page' in between two pages).
* Horizontal swipe boundaries (firstDay and lastDay).
* Date range selection + background highlight.
* Multiple date selection.
* Selective builders - you can now return null in a builder, which will in turn make the widget use a default style. This allows you to selectively override day cell UI - more on that coming soon in examples. This also regards any builder - be it a day cell, a dow cell or a marker.
* Improved widget performance.
* Proper state handling on widget rebuilds - CalendarController posed some problems in previous versions.
* In general, more concise API.

____

Key modifications:
* CalendarController is gone. This results in a couple of changes:
  * `initialSelectedDay` became `selectedDayPredicate`. This allows to select multiple dates at once. Note that you also can have no selected date now. Basic usage is to store a `_selectedDay` field and update it via `onDaySelected` callback. https://github.com/aleksanderwozniak/table_calendar/blob/8f6f47c6006105c8f2e53c615847f136c2d0abb3/example/lib/pages/table_basics_example.dart#L27-L34 https://github.com/aleksanderwozniak/table_calendar/blob/8f6f47c6006105c8f2e53c615847f136c2d0abb3/example/lib/pages/table_multi_example.dart#L83-L86
  * There is a new required property called `focusedDay` - it is used to determine which year/month should be currently in view.
  * `initialCalendarFormat` became `calendarFormat`. To set the current format manually, just rebuild the widget with updated value.
  * Methods like `calendarController.previousPage()` and `calendarController.nextPage()` are replaced by a PageController. You can obtain it from the widget by using `onCalendarCreated` callback. Its disposing is handled by the widget, so no need to do it manually.
  * You can no longer use properties like `visibleDays`, `visibleEvents` or `visibleHolidays` - this is something that you have to handle yourself if needed.
* `startDay` and `endDay` are renamed to `firstDay` and `lastDay` respectively, and are both required. This allows to setup a range of available days; users will not be able to scroll past them.
* `events` map is replaced by `eventLoader`, which gives you a DateTime object and expects you to return a list of events that you want to assign to that date. You can still use the original map for that - but you have much more freedom now. Note that `LinkedHashMap` is the recommended map type to use.  https://github.com/aleksanderwozniak/table_calendar/blob/8f6f47c6006105c8f2e53c615847f136c2d0abb3/example/lib/pages/table_multi_example.dart#L81 https://github.com/aleksanderwozniak/table_calendar/blob/8f6f47c6006105c8f2e53c615847f136c2d0abb3/example/lib/pages/table_multi_example.dart#L41-L44
* `holidays` map is replaced by `holidayPredicate`, which operates in the same manner that `selectedDayPredicate` does.
* Callbacks don't return lists of events and holidays. If you need a list of events in `onDaySelected`, you can call the same thing you are using in `eventLoader` for single day selection, or you can adapt it for multiple day selection. https://github.com/aleksanderwozniak/table_calendar/blob/8f6f47c6006105c8f2e53c615847f136c2d0abb3/example/lib/pages/table_multi_example.dart#L54-L66

**Comment by netoedson** [comment]
The God of codes blesses you, man! 

Thank you very much.

**Comment by aleksanderwozniak** [comment]
Null safe 3.0.0 prerelease has been uploaded to pub.dev: https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0

**Comment by chitgoks** [comment]
Before, onCalendarCreated returns the first day, last day. But now it returns a PageController. but there is no function or property in the page controller to get the first day and last day. Is this possible?

**Comment by aleksanderwozniak** [comment]
> 
> 
> Before, onCalendarCreated returns the first day, last day. But now it returns a PageController. but there is no function or property in the page controller to get the first day and last day. Is this possible?

Your question was already asked in https://github.com/aleksanderwozniak/table_calendar/issues/441.

>
> 
> And ... the readme is fairly lacking. it does not mention about onVisibleDaysChanged and how to migrate to the new one.

As mentioned in https://github.com/aleksanderwozniak/table_calendar/issues/265#issuecomment-756141922, `onVisibleDaysChanged` is now split into [onPageChanged](https://pub.dev/documentation/table_calendar/3.0.0/table_calendar/TableCalendar/onPageChanged.html) and [onFormatChanged](https://pub.dev/documentation/table_calendar/3.0.0/table_calendar/TableCalendar/onFormatChanged.html). Both of them belong to the [basic setup](https://github.com/aleksanderwozniak/table_calendar/tree/v3.0.0#basic-setup) of TableCalendar, and as such are present in [every example](https://github.com/aleksanderwozniak/table_calendar/tree/v3.0.0/example/lib/pages).

**Comment by MrJai** [comment]
> * CalendarController is gone. This results in a couple of changes:
>   
>   * `initialSelectedDay` became `selectedDayPredicate`. This allows to select multiple dates at once. Note that you also can have no selected date now. Basic usage is to store a `_selectedDay` field and update it via `onDaySelected` callback. https://github.com/aleksanderwozniak/table_calendar/blob/8f6f47c6006105c8f2e53c615847f136c2d0abb3/example/lib/pages/table_basics_example.dart#L27-L34
>      https://github.com/aleksanderwozniak/table_calendar/blob/8f6f47c6006105c8f2e53c615847f136c2d0abb3/example/lib/pages/table_multi_example.dart#L83-L86
>   * There is a new required property called `focusedDay` - it is used to determine which year/month should be currently in view.
>   * `initialCalendarFormat` became `calendarFormat`. To set the current format manually, just rebuild the widget with updated value.
>   * Methods like `calendarController.previousPage()` and `calendarController.nextPage()` are replaced by a PageController. You can obtain it from the widget by using `onCalendarCreated` callback. Its disposing is handled by the widget, so no need to do it manually.
>   * You can no longer use properties like `visibleDays`, `visibleEvents` or `visibleHolidays` - this is something that you have to handle yourself if needed.

Thank you @aleksanderwozniak for such a detailed comment, explaining almost everything. One function that was very important to my app was `calendarController.setSelectedDate`. That helped me to manually trigger the date update. How can I update the selected date now without the controller, should I be using selectedDayPredicate?

Thanks,

**Comment by aleksanderwozniak** [comment]
@MrJai 
Correct, same concept applies as [here](https://github.com/aleksanderwozniak/table_calendar/tree/v3.0.0#adding-interactivity).

**Comment by vytautas-pranskunas-** [comment]
I have  a question
1) onVisibleDaysChanged used to return from / to dates which i used to laod range of events. no onPageChanged returns just focusedDate - what is it? first daty of the month or? How can i get last day of that page - shoudl i calculate it my self?

**Comment by MrJai** [comment]
> I have 2 a questions
> 
> 1. onVisibleDaysChanged used to return from / to dates which i used to laod range of events. no onPageChanged returns just focusedDate - what is it? first daty of the month or? How can i get last day of that page - shoudl i calculate it my self?
> 2. Previously there was CalendarController It is gone now... I used to use: setCalendarFormat before. How can is et calendar format dynmically now?

@vytautas-pranskunas- Let me try and reply to both questions, @aleksanderwozniak can correct me.

1. `onVisibleDaysChanged` now returns `focusedDate` that is actually the same date in previous or next view. For example if you are looking at week view and now Monday, May 3, 2021 is focused, if you swipe right you will have Monday, April 26, 2021 as focused day, and for future you will have Monday, May 10, 2021 as focusedDay. Ofcourse you can use this info to get start and end of the week/month depending on your view. I used to use onVisibleDaysChanged to get last Sunday when going in past and next Monday when going to future. Now I am doing it like this.

  ```
DateTime getLastSunday(DateTime focusedDay) {
    return focusedDay.add(Duration(days: (7 - focusedDay.weekday)));
  }

  DateTime nextMonday(DateTime focusedDay) {
    return focusedDay.subtract(Duration(days: (focusedDay.weekday - 1)));
  }

```

2. You can see the updated setCalendarFormat, or CalendarFormat flow in general, you can check this [doc](https://github.com/aleksanderwozniak/table_calendar/tree/v3.0.0#adding-interactivity).

```
calendarFormat: _calendarFormat,
onFormatChanged: (format) {
  setState(() {
    _calendarFormat = format;
  });
},
```

**Comment by desmeit** [comment]
> I have added multiple selection in `3.0.0-beta` branch 🚀
> 
> Here is how it works. You can use either multi-selection by tapping on individual dates, or you can select a continuous range of dates by tapping on a startDate and endDate.
> 
> Multi-selection	Range selection
> <img alt="" width="250" src="https://user-images.githubusercontent.com/22658673/106397947-5a2bb400-6410-11eb-97bb-03ba39aa37d3.png">	<img alt="" width="250" src="https://user-images.githubusercontent.com/22658673/106397949-5c8e0e00-6410-11eb-8891-67fac9b41eb7.png">
> **To use multi-selection:**
> 
> * Use `onDaySelected` callback to get the selected day. Add it to a collection (I'd recommend a `Set`*).
> * Use `selectedDayPredicate` to tell the TableCalendar widget which days are selected. You will be given a DateTime object, so just check if it is present in your day collection - and return true/false.
> * To clean the selection, you just need to reset the data inside collection (use `.clear()` on it). Rebuild the widget afterwards.
> 
> _* Actually, a `LinkedHashSet` with equality override would be even better - to compare just the date-part of DateTime object, as their time-part is redundant for us._
> 
> Here is a complete [example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_multi_example.dart) containing all of this.
> 
> **To use range selection:**
> 
> * Use `rangeSelectionMode` property. Set it to either `RangeSelectionMode.toggledOn`* or `RangeSelectionMode.enforced`.
> * Create `rangeStart` and `rangeEnd` DateTime fields. Pass them to TableCalendar widget.
> * Use `onRangeSelected` callback. Update both fields inside it. Rebuild the widget afterwards.
> 
> _* Range selection can be toggled on/off by longpressing a day cell in TableCalendar. When range selection mode is on, tapping will return ranges (`onRangeSelected`). When range selection is off, tapping will return single days (`onDaySelected`). To disable toggling on longpress, use `RangeSelectionMode.enforced` (always on), or `RangeSelectionMode.disabled` (always off)._
> 
> Here is a simple [example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_range_example.dart). Here is a bit more [complex example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-beta/example/lib/pages/table_events_example.dart), starting in `RangeSelectionMode.toggledOff` state.
> 
> To use `3.0.0-beta` branch, add this to `pubspec.yaml`:
> 
> ```yaml
>   table_calendar:
>     git:
>       url: git://github.com/aleksanderwozniak/table_calendar.git
>       ref: 3.0.0-beta
> ```

The simple example is not working. Where could I find a simple example to select multiple ranges?

**Comment by desmeit** [comment]
Is it also possible to set multiple Range selection with this plugin?
I want to select a range from January 1 to February 12 and March 14 to March 30 for example.
Is there an example for this purpose?

**Comment by aleksanderwozniak** [comment]
@vytautas-pranskunas- 

> 
> 
> I have few a questions
> 
>     1. onVisibleDaysChanged used to return from / to dates which i used to laod range of events. no onPageChanged returns just focusedDate - what is it? first daty of the month or? How can i get last day of that page - shoudl i calculate it my self?
> 
>     2. Previously there was CalendarController It is gone now... I used to use: setCalendarFormat before. How can is et calendar format dynmically now?
> 
>     3. style migration:
> 
> 
>     * is weekdayStyle == defaultTextStyle?
> 
>     * These are missing - how should i repleace them?
>       
>       * outsideStyle - i see outsideDecoration but it misses fontSize because it is boxDecoration
>       * unavailableStyle
>       * outsideWeekendStyle
>       * contentPadding

Points 1. and 2. have been pretty much covered by @MrJai, you can additionally check https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620. For point 3. refer to your original issue: https://github.com/aleksanderwozniak/table_calendar/issues/492#issuecomment-831824773


@desmeit 

> 
> 
> Is it also possible to set multiple Range selection with this plugin?
> I want to select a range from January 1 to February 12 and March 14 to March 30 for example.
> Is there an example for this purpose?

Yes, but you will need to write your custom logic using [onDaySelected](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/onDaySelected.html) and [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html). All available examples are [here](https://github.com/aleksanderwozniak/table_calendar/tree/master/example/lib).

**Comment by desmeit** [comment]
Thanks but I don't want to select ranges through onDaySelected. The ranges should already be selected from the beginning.
Should I work with rangeStartBuilder from calenderBuilders? I cannot find any example for such purpose. It is no problem to develop my own logic, but I don't understand how I can address different ranges.

**Comment by aleksanderwozniak** [comment]
@desmeit 
Correct, you will need to skip `rangeStartDay` and instead do everything manually inside the builders. I'd suggest using [prioritizedBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/prioritizedBuilder.html) in your case.

The basic concept is as follows: builder will give you a DateTime object called `day`. Check if this `day` belongs to any of your custom date ranges - if yes, then return a custom widget to highlights range selection. If no - return null to use the default UI.

**Comment by reju1021** [comment]
@desmeit Did you eventually succeed implementing it? If yes, would you mind sharing your code? I'm currently trying to implement the same.

**Comment by MuhammadSufyanMalik** [comment]
Hi,
I have a list of seven(can me month) days tasks, İ would like those days to be colored, differently.
I could not find, can any one help, thanks
