### ISSUE TITLE
onTap issue with custom dayBuilder

### ISSUE THREAD

**Issue by nsttu** [aleksanderwozniak/table_calendar#154]
When I use a cutstom dayBuilder i need to tab exectly on the daynumber. 
This is how my custom dayBuilder looks like: 
```dart
        dayBuilder: (context, date, _) {
          return ClipRRect(
              borderRadius: BorderRadius.circular(8.0),
              child: Container(
                width: double.infinity,
                height: double.infinity,
                padding: const EdgeInsets.symmetric(vertical: 4.0),
                alignment: Alignment.center,
                child: Text(
                  '${date.day}',
                  style: TextStyle().copyWith(fontSize: 18.0),
                ),
              ));
        },
```

I tested different width's en height's of the container but it doesn't  change a thing.

**Comment by aleksanderwozniak** [comment]
Try the same with
```dart
dayHitTestBehavior: HitTestBehavior.opaque,
```

**Comment by nsttu** [comment]
With HitTestBehavior.opaque it works like a charm. Should the dayHitTestBehavior be changed bij default when a custom dayBuilder is used?

**Comment by aleksanderwozniak** [comment]
I am glad this solves the issue :)

> Should the dayHitTestBehavior be changed bij default when a custom dayBuilder is used?

It depends. For example, try adding a border to your `Container` and you will no longer need to change the `dayHitTestBehavior`.
