### ISSUE TITLE
Request for option to change Calendar Format Animation duration.

### ISSUE THREAD

**Issue by pavel-birdy** [aleksanderwozniak/table_calendar#158]
Please give option to change Calendar Format Animation duration or curve. I am changing the format based on the events scroll (e.g scroll down to collapse to  `CalendarFormat.week` from month view) but the animation is too fast. It would be nice to have little more control here. Or maybe I didn't find that option.

**Comment by aleksanderwozniak** [comment]
Currently there is no option for specifying this animation's duration or curve. I will add it with upcoming release.

**Comment by vmeretin** [comment]
+++

**Comment by badaween-ahmed** [comment]
Any update on this? It wouldn't be hard to expose two parameters duration and curve.

**Comment by Gperez88** [comment]
Any update on this?

**Comment by aleksanderwozniak** [comment]
Added in `3.0.0-beta` as `formatAnimationDuration` and `formatAnimationCurve` - for more info refer [here](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-beta#usage).
