### ISSUE TITLE
Event Markers different colors

### ISSUE THREAD

**Issue by Michael-Pascale** [aleksanderwozniak/table_calendar#159]
Hi, 
I am trying to make a calendar application, and the events will have different(colored) tags. I want these events to show on the calendar with their tag color as the visible. I saw where I can set the color of the markers, but I could not find if this is possible. If it is not currently possible, could it please be added?

**Comment by aleksanderwozniak** [comment]
Currently this is not built-in, but you can achieve it by mixing those two comments:

https://github.com/aleksanderwozniak/table_calendar/issues/64#issuecomment-500489477
https://github.com/aleksanderwozniak/table_calendar/issues/67#issuecomment-524662136
