### ISSUE TITLE
onVisibleDaysChanged : doesn't exist

### ISSUE THREAD

**Issue by Nk54** [aleksanderwozniak/table_calendar#16]
Hello,
First, I like a lot your control.

I wanted to trigger a method when users swipe / change the displayed date.
I've taken a look to your exemple project, you use the onVisibleDaysChanged event for that purpose.

But Flutter tells me that The named parameter 'onVisibleDaysChanged' isn't defined.dart(undefined_named_parameter)

It is because on the Flutter widget page, the documentation tells to install 0.3.2 where the event did not exist yet.

May I suggest you to update it ? https://pub.dartlang.org/packages/flutter_calendar_carousel#-readme-tab-

It would be awesome because after a first reading, it doesn't seems obvious what your Widget can do. It's too bad because you did a great job.

Take care and thanks for the time you put into this Widget.

Another thing : it seems that on the version 1.0.0, the format doesn't change : it seems brocken : it was working on 0.3.2. The button does nothing and a vertical swipe trigger the animation but its animates to the same format.
It only refresh when you make a horizontal swipe gesture.

**Comment by aleksanderwozniak** [comment]
@Nk54 
It might be because of cached page content. It should be correct after you refresh the pub page (I assume you are talking about [this site](https://pub.dartlang.org/packages/table_calendar)).

Make sure you have the `1.0.0` version in your Flutter project. First of all go to `pubspec.yaml` and update: 
```yaml
dependencies:
  table_calendar: ^1.0.0
```

Then you can go to `pubspec.lock` file, to make sure you actually have the newest version. Search there for 'table_calendar'. It should look something like this:
```yaml
table_calendar:
  dependency: "direct main"
  description:
    name: table_calendar
    url: "https://pub.dartlang.org"
  source: hosted
  version: "1.0.0"
```

For CalendarFormat changes, make sure you have correct order of `availableCalendarFormats` property. It should be descending (from biggest to smallest), eg:
```dart
availableCalendarFormats: const [
  CalendarFormat.month,
  CalendarFormat.week,
],
```
I just checked it, FormatButton (and vertical swipes) should work correctly, provided that you have `availableCalendarFormats` in right order.

I'll be adding a more comprehensive 'How to' guide soon, so keep an eye for it! It will make `Table Calendar`'s possibilities clear.

Let me know if this helped you fix the issue.

**Comment by Nk54** [comment]
Hey, thank you for this quick answer.

Here is my code : 
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Agenda'),
      ),
      body: Container(
        padding: EdgeInsets.all(8),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            TableCalendar(
              availableCalendarFormats: const <CalendarFormat>[
                CalendarFormat.month,
                CalendarFormat.week
              ],
            ),
            Expanded(
              child: ListView(
                children: <Widget>[
                  Container(
                    margin: EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                    child: Card(
                      child: Container(
                        margin: EdgeInsets.all(8),
                        child: Text('element at a given date'),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

I've checked the pubspec and the lock, everything seems fine. I will try to create a gif tonight or tomorrow.

I wish you a good evening !

**Comment by aleksanderwozniak** [comment]
Ah, found the culprit. I've changed some of the internal logic and had a "hidden dependency" on `onFormatChanged` callback. You can actually see it for yourself with this code:
```dart
TableCalendar(
  onFormatChanged: (_) {},
  availableCalendarFormats: const [
    CalendarFormat.month,
    CalendarFormat.week,
  ],
),
```
This also explains why I didn't notice it earlier myself.

I've pushed the `1.0.1` update, so it should be all good now!
Thanks for the report!

Don't hesitate to ask if you have any further questions.

**Comment by Nk54** [comment]
It's fixed ! Awesome ! I really like this control. Thanks a lot !
It should be more famous as it works great and no need to set a height or full height : a real good point.

I close this.

I do have a question :) if you don't mind, I'd like to know what I could do to make it working with i18n (internationalization). I havn't played with i18n on Flutter yet. Once I will be confident with that, if your calendar doesn't provide a way to deal with i18n, I may send a pull request !
Good night :)

**Comment by aleksanderwozniak** [comment]
My pleasure :)

Honestly, I haven't really delved into i18n yet, but I imagine it shouldn't be that complicated. Probably just load up a locale and pass it to `TableCalendar`.
