### ISSUE TITLE
 colors for Saturday and Sunday

### ISSUE THREAD

**Issue by minikupa** [aleksanderwozniak/table_calendar#162]
Please allow me to set colors for Saturday and Sunday respectively.

**Comment by aleksanderwozniak** [comment]
You can use `CalendarBuilders` for more specific customization, for example:

```dart
builders: CalendarBuilders(
  weekendDayBuilder: (context, day, events) {
    return Center(
      child: Container(
        color: day.weekday == DateTime.sunday ? Colors.red[300] : Colors.orange[300],
        width: 40.0,
        height: 40.0,
        child: Center(
          child: Text('${day.day}'),
        ),
      ),
    );
  },
```
This will make Sundays use `Colors.red[300]` and Saturdays `Colors.orange[300]`.

**Comment by minikupa** [comment]
thank you! very much!

**Comment by lakshits11** [comment]
> You can use `CalendarBuilders` for more specific customization, for example:
> 
> ```dart
> builders: CalendarBuilders(
>   weekendDayBuilder: (context, day, events) {
>     return Center(
>       child: Container(
>         color: day.weekday == DateTime.sunday ? Colors.red[300] : Colors.orange[300],
>         width: 40.0,
>         height: 40.0,
>         child: Center(
>           child: Text('${day.day}'),
>         ),
>       ),
>     );
>   },
> ```
> 
> This will make Sundays use `Colors.red[300]` and Saturdays `Colors.orange[300]`.

Hello There, thanks for the help but I just want to change the color of text of Saturday and Sundays from red to black. Please help me. Thanks in advance.
