### ISSUE TITLE
动态改变startingDayOfWeek 的值不生效

### ISSUE THREAD

**Issue by 2697a** [aleksanderwozniak/table_calendar#164]
satrtingDayOfWeek:startWeek,

setState((){
this.startWeek = StartingDayOfWeek.monday;
});

**Comment by aleksanderwozniak** [comment]
I assume you want to be able to change the `StartingDayOfWeek` while app is running - this is not supported at this moment. This feature will be added in near future.

**Comment by zyllus17** [comment]
Use `startingDayOfWeek: StartingDayOfWeek.monday` inside `TableCalendar()` to start the day from monday.

**Comment by kingkangyu** [comment]
> I assume you want to be able to change the `StartingDayOfWeek` while app is running - this is not supported at this moment. This feature will be added in near future.

```
String currentLocale = Localizations.localeOf(context).toString();

....

TableCalendar(
locale: currentLocale,
startingDayOfWeek:currentLocale=='zh_CN'?StartingDayOfWeek.monday:StartingDayOfWeek.sunday,
)
```

`startingDayOfWeek` will not work if the Locale is changed.
but `locale: currentLocale` will work.
Am I right?

**Comment by ptrbrynt** [comment]
Is there an update on this please?

**Comment by aleksanderwozniak** [comment]
Added in `3.0.0` release.
