### ISSUE TITLE
Every time you switch to the second page, it is white

### ISSUE THREAD

**Issue by gaojuanjuan** [aleksanderwozniak/table_calendar#166]

**Comment by aleksanderwozniak** [comment]
Can you provide some more details? Do you mean switching to the next month?

**Comment by neestell** [comment]
@aleksanderwozniak The same issue. if I switch to the next month next page is white. You can see it on your gifs in readme

**Comment by aleksanderwozniak** [comment]
@neestell Not sure if this was meant by the author, but if that's the case, then this is a duplicate of #55. Closing for now. 

@gaojuanjuan feel free to reopen if you had something else in mind.
