### ISSUE TITLE
Feature proposal: Disable selected day style

### ISSUE THREAD

**Issue by Boehrsi** [aleksanderwozniak/table_calendar#167]
I'm currently using your plugin (btw. it's awesome, really nice work 👍) and I open a new view on tap (detail view for events). Additionally to the new view also the selected day changes, which is fine. But it gets highlighted which isn't need for my use case and confuses some of my users. 
I could adjust the style of the selected day with the `calendarStyle` property, but I don't know how to adjust the style dynamically for weekdays / weekends and so on. 
What do you think about a `calendarStyle` property to disable additional styling of the currently selected day completely?
Something simlar could be also useful for the "today highlighting".
I would propose something like:
```
calendarStyle: CalendarStyle(
              selectedHighlighting: false,
              todayHighlighting: false,
),
```

Additional information:

- table_calendar: ^2.2.1
- Flutter version: v1.12.13+hotfix.5

PS
Happy new year ;)

**Comment by Boehrsi** [comment]
I just had a look into the code and added a PR. Feedback would be much appreciated.

**Comment by aleksanderwozniak** [comment]
That's a nice idea, I like it :)

**Comment by aleksanderwozniak** [comment]
Version `2.2.2` with your PR has been released

**Comment by Boehrsi** [comment]
Thanks a lot. And thanks for your nice library :).
