### ISSUE TITLE
How to get displayed month?

### ISSUE THREAD

**Issue by AnuragVadd** [aleksanderwozniak/table_calendar#170]
I have a few json objetcs here - 
```
 "data": [
        {
            "status": true,
            "_id": "5df8aaae2f85481f6e31db59",
            "name": "updating new group",
            "created_date": "2019-12-17T10:15:10.772Z",
            "__v": 0
        },
        {
            "status": true,
            "_id": "5dfc712d790365d5a55deb2a",
            "name": "new group 1",
            "created_date": "2019-12-20T06:58:53.863Z",
            "__v": 0
        },
```

I have mapped the "created_date" parameter with "title". However, I want to fetch the json objects for only one month at a time. Is there a way to get the month which is currently displayed in the calendar? i.e. if displayed month is january 2020, is there a variable which keeps track of this month?

**Comment by aleksanderwozniak** [comment]
You can get the currently displayed month by using `_calendarController.focusedDay.month`
