### ISSUE TITLE
How to send a function (or API call) to _selectNext() and _selectPrevious methods,

### ISSUE THREAD

**Issue by AnuragVadd** [aleksanderwozniak/table_calendar#173]
I want to send the currently displayed month and year in order to fetch certain json objects which have a matching date parameter. I have tried to add a print value in those methods this way - 

```
   _selectPrevious() {
    print("PRINTING previous month");

    setState(() {
      widget.calendarController._selectPrevious();
    });
  }

   _selectNext() {
    print("PRINTING next month");

    setState(() {
      widget.calendarController._selectNext();
    });
  }
```

but it does not seem to be printing anything. Is there a way I can add a function inside these two methods so that I can send an API call as per the requirement? 

The API will essentially fetch certain json objects when i send `_calendarController.focusedDay.year` and `_calendarController.focusedDay.month`. for a certain month and populate the `_events` map on initState.

**Comment by aleksanderwozniak** [comment]
You can add those to `onVisibleDaysChanged` callback, this should do the job.

**Comment by AnuragVadd** [comment]
Got it. Thanks for helping out. Have a great Day !
