### ISSUE TITLE
_selectedDayCallback function should have a setState at the end

### ISSUE THREAD

**Issue by alpharpledez** [aleksanderwozniak/table_calendar#174]
Thank you for the amazing widget!

So here's a problem that I encountered.

I created a widget with TableCalendar inside a StatefulWidget's State, and passed it into a class that extends SliverPersistentHeaderDelegate class, the class is used inside the State. And I tried to use call controller.setSelectedDay in the delegate class with a custom button, (to change the date to 7 days ago) with setting runCallBack to true. The onDaySelected parameter includes a setState.
 
It was supposed to refresh and display the changed date after the setSelectedDay is called, but it never did.  After check, turns out the onDaySelected was indeed called but it did not refresh the calendar.

It turns out, when calling setSelectedDay, it goes to and _selectedDayCallBack, which ends up not using a setState unless the date moves to last/next month I assume.

I added a setState before the end of _selectedDayCallback, inside and that solves the problem

Please consider solving this problem. The method I used solved it, but I'm not sure if it's the perfect way. Hope this helps anyone else who encountered the same problem.

**Comment by aleksanderwozniak** [comment]
This should refresh properly when you include `setState` inside `onDaySelected` callback or inside the button's `onTap`.

I will think about making some changes tho - so that one does not need to use `setState`

**Comment by aleksanderwozniak** [comment]
Resolved with version `3.0.0`
