### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by FabricioMedeiros** [aleksanderwozniak/table_calendar#177]
Hello,

How can I put Portuguese Language in Calendar Table?

**Comment by RodolfoSilva** [comment]
```dart
TableCalendar(
  availableCalendarFormats: const {
    CalendarFormat.month: 'mês',
    CalendarFormat.week: 'semana',
    CalendarFormat.twoWeeks: '2 semanas',
  },
  locale: 'pt_BR',
  calendarController: _calendarController,
)
```

**Comment by FabricioMedeiros** [comment]
> @FabricioMedeiros you can use like this:
> 
> ```dart
> TableCalendar(
>   availableCalendarFormats: const {
>     CalendarFormat.month: 'mês',
>     CalendarFormat.week: 'semana',
>     CalendarFormat.twoWeeks: '2 semanas',
>   },
>   locale: 'pt_BR',
>   calendarController: _calendarController,
> )
> ```

Hello Rodolfo,

I tried to use your code, but the following error occurred: "Locale data has not been initialized, call initializeDateFormatting (<locale>)".

Do you know what it can be?

**Comment by FabricioMedeiros** [comment]
> @FabricioMedeiros you can use like this:
> 
> ```dart
> TableCalendar(
>   availableCalendarFormats: const {
>     CalendarFormat.month: 'mês',
>     CalendarFormat.week: 'semana',
>     CalendarFormat.twoWeeks: '2 semanas',
>   },
>   locale: 'pt_BR',
>   calendarController: _calendarController,
> )
> ```

Hello Rodolfo,

I resolved the problem "Locale data has not been initialized, call initializeDateFormatting ()". using initializeDateFormatting('pt_BR', null);

Your code works fine! Now the Table Calendar is in Portuguese!

Thanks a lot friend!

**Comment by aleksanderwozniak** [comment]
You can also find all details in the [readme](https://github.com/aleksanderwozniak/table_calendar#locale) and [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart)

**Comment by ronytesler** [comment]
I tried this and the text was not changed..
