### ISSUE TITLE
Change event style

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#178]
On my calendar there is one day a month that will be more important than the rest. 

How could I change the dot color? And how could I change it for a specific event?

**Comment by aleksanderwozniak** [comment]
You could assign a specific event to that particular day, and change the color based on the event.
Check this comment for concept: https://github.com/aleksanderwozniak/table_calendar/issues/91#issuecomment-524660817

**Comment by erperejildo** [comment]
That's good to know (I needed to have something like that as well) but what I need here is to change the status black dot color. So if I have 3 events that day and one is the important one, that should be on a different color

**Comment by erperejildo** [comment]
Also adding a `dayBuilder` requires me to add a `todayDayBuilder` and a `markersBuilder` to not loose the style I had

**Comment by aleksanderwozniak** [comment]
I answered your question in #183 

That's a valid point about the `dayBuilder`. I'll make an improvement there, so that it doesn't require setting up remaining builders - and uses `CalendarStyle` instead.

**Comment by erperejildo** [comment]
Hi @aleksanderwozniak.
Didn't want to create a new issue for this because it's not, but is this possible?
https://stackoverflow.com/questions/60100253/create-different-events-using-tablecalendar-in-flutter

**Comment by aleksanderwozniak** [comment]
Of course. From TableCalendar's perspective all that matters is that you provide events in `DateTime: List<Event>` form. Since you use `Event: List<DateTime>` you need to transform your data format to match the one I mentioned above.

You could take each `DateTime` from your list, supply it with `Event` and after that make `_events` map from all of these.

**Comment by erperejildo** [comment]
Ok, so basically they way I was thinking on: pass an List with all of them and when I need to update the day, pass 2 Lists, one to remove the previous dates and the new ones, right?

**Comment by aleksanderwozniak** [comment]
As long as the final outcome is a fresh `Map<DateTime, List<Event>>` you are good to go.

**Comment by erperejildo** [comment]
> As long as the final outcome is a fresh `Map<DateTime, List<Event>>` you are good to go.

looking into it now but it works to add new events, but I was thinking on how to remove the previous days. I guess the only way is going one by one and check it it was a payment day right (I have a paypmentDay property on each event)?

**Comment by jamisays** [comment]
Can we remove the event dots altogether?
