### ISSUE TITLE
Customize the Calendar Format Names

### ISSUE THREAD

**Issue by PaitoAnderson** [aleksanderwozniak/table_calendar#18]
Ability to customize the Full/Compact/Minimal text.

Going to send a PR after this, but I'm new to flutter so I'll probably butcher it a bit.

**Comment by aleksanderwozniak** [comment]
Added with #20 

Now, `availableCalendarFormats` property takes in a `Map<CalendarFormat, String>`.
Basically you just assign text to each format here and the rest is handled internally, without creating a new callback.

**Comment by aleksanderwozniak** [comment]
Ready to use in version `1.0.2`!

**Comment by PaitoAnderson** [comment]
Sweet! I just pulled it down, works great! Didn't expect a release so quickly, thank you!

**Comment by aleksanderwozniak** [comment]
Glad I could help :)
