### ISSUE TITLE
Set selected day in onVisibleDaysChanged

### ISSUE THREAD

**Issue by rivetingpeppermint** [aleksanderwozniak/table_calendar#180]
I want to automatically select the first date of each month whenever onVisibleDaysChanged is called, to mimic Apple's stock calendar app (selects first day of each month every time we switch months).

Here's what I've tried:
`void _onVisibleDaysChanged(DateTime first, DateTime last, CalendarFormat format)
{
    setState((){
        _selectedDay = first;
    });
 }`

This does change the list of events below the calendar to the first day of the month, but it doesn't apply selectedDayBuilder's widget to the first day of the month (the date doesn't look "highlighted" like the ones selected by tapping). How would one automatically select the first day of the month in the calendar and highlighting it as well?

**Comment by rivetingpeppermint** [comment]
Found it! I was supposed to use the calendar controller, something like this: `_calendarController.setSelectedDay(_selectedDay);`

Sorry for opening an issue about this.

**Comment by lnaie** [comment]
> Found it! I was supposed to use the calendar controller, something like this: `_calendarController.setSelectedDay(_selectedDay);`
> 
> Sorry for opening an issue about this.

Where is this method ```setSelectedDay``` and how do I get the reference to ```_calendarController```?
