### ISSUE TITLE
Marker when there are no events

### ISSUE THREAD

**Issue by AllanCoinaski** [aleksanderwozniak/table_calendar#182]
Hello, is it possible to add a marker in red when there are no events?

**Comment by aleksanderwozniak** [comment]
Markers are coded in a way that prevents them from rendering if there are no events. 

You can use `dayBuilder` to achieve it tho:

```dart
dayBuilder: (context, date, events) {
  if (events == null || events.isEmpty) {
    return Stack(
      alignment: Alignment.center,
      children: <Widget>[
        Text('${date.day}'),
        Positioned(
          bottom: 2.0,
          child: Container(
            height: 8.0,
            width: 8.0,
            decoration: BoxDecoration(
              color: Colors.red,
              shape: BoxShape.circle,
            ),
          ),
        ),
      ],
    );
  }

  return Center(child: Text('${date.day}'));
},
```

You will probably also want to specify `selectedDayBuilder` and `todayDayBuilder`, as well as set `dayHitTestBehavior` to opaque.

**Comment by AllanCoinaski** [comment]
Hello,

I can adapt using the Simple TableCalendar configuration (using Styles) ?

**Comment by aleksanderwozniak** [comment]
Yes, but for displaying a marker in the way you want to, you will need to use custom builders.

**Comment by AllanCoinaski** [comment]
Ok, thanks!!
