### ISSUE TITLE
Change event style

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#183]
How could I change the background for one of the events in the same day?

I want to have for example, tomorrow 3 events. 2 of them with a black background and the other one red

**Comment by aleksanderwozniak** [comment]
You can use `singleMarkerBuilder` for that purpose:

```dart
builders: CalendarBuilders(
  singleMarkerBuilder: (context, date, event) {
    return Container(
      height: 8.0,
      width: 8.0,
      margin: const EdgeInsets.all(0.5),
      decoration: BoxDecoration(
        // provide your own condition here
        color: (event as String).contains('B10') ? Colors.red : Colors.black,
        shape: BoxShape.circle,
      ),
    );
  },
),
```

**Comment by FullstackWEB-developer** [comment]
Hi @aleksanderwozniak 
I have simple similar question.
![image](https://github.com/aleksanderwozniak/table_calendar/assets/92151436/9121cb73-22a4-4ff9-8fba-0b0cb2ea84bc)
How can I adjust the style of dates with events like this screenshot?
![image](https://github.com/aleksanderwozniak/table_calendar/assets/92151436/3e0a547f-e23a-470d-8cda-c0c18feaab0a)
