### ISSUE TITLE
Is it possible to detect when did the month changed?

### ISSUE THREAD

**Issue by michealchow2324** [aleksanderwozniak/table_calendar#184]
is there any feature like onMonthSelected in the calendar builder?

**Comment by aleksanderwozniak** [comment]
Yes - you can use `onVisibleDaysChanged` callback.

**Comment by HinnaRutaba** [comment]
I created a custom calendar using builder function and onVisibleDaysChanged is not working properly, its giving the same month even when I go to next month using rightChevronIcon

**Comment by aleksanderwozniak** [comment]
@HinnaRutaba 
Please provide a code snippet which I can use to reproduce your issue.
