### ISSUE TITLE
Disable back/forward Icons

### ISSUE THREAD

**Issue by andresherrera12** [aleksanderwozniak/table_calendar#185]
Is it posible to disable back and forward buttons?

I need to hide forward button and back button to be a calendar icon and do nothing when I click on it. 

It must look like

![image](https://user-images.githubusercontent.com/29415118/73954565-fab7c880-48cf-11ea-980f-a738283abdfe.png)

**Comment by aleksanderwozniak** [comment]
I would suggest making a custom header then. [This](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1) is a nice starter.

**Comment by andresherrera12** [comment]
It works perfect for me. Thanks
