### ISSUE TITLE
Is it possible to change the outside dates color?

### ISSUE THREAD

**Issue by patthipati** [aleksanderwozniak/table_calendar#186]

**Comment by aleksanderwozniak** [comment]
Sure. You can use [outsideStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle/outsideStyle.html) if this is a simple style change, or you can use [outsideDayBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/outsideDayBuilder.html) if you have something more custom in mind.

**Comment by patthipati** [comment]
Thank you @aleksanderwozniak for Quick response outsideDayBuilder worked for me.
