### ISSUE TITLE
Change arrow color?

### ISSUE THREAD

**Issue by zyllus17** [aleksanderwozniak/table_calendar#188]
Is there any way to change the arrow colors? I was building my calendar for dark mode and the arrow are black and not quite visible.
![Screenshot_1581342847](https://user-images.githubusercontent.com/50977126/74156116-b44dcb00-4c3b-11ea-871b-0f60b9e95e5b.png)

I have highlighted the arrow in the picture

**Comment by aleksanderwozniak** [comment]
Use `leftChevronIcon` and `rightChevronIcon` properties of `HeaderStyle`:

```dart
rightChevronIcon: const Icon(Icons.chevron_right, color: Colors.white),
```
