### ISSUE TITLE
Highlight selected day's week?

### ISSUE THREAD

**Issue by mohitferrari** [aleksanderwozniak/table_calendar#189]
Is there a way to highlight the week of the selected day? Below is an example where 'T' is highlighted. I tried to use DowBuilder dowWeekdayBuilder but the weekday is passed as a string.
![Screenshot from 2020-02-11 08-52-12](https://user-images.githubusercontent.com/29878097/74208984-e39c2080-4cab-11ea-8554-f786eb62cf08.png)

**Comment by aleksanderwozniak** [comment]
`dowWeekdayBuilder` returns a Widget, so you can build anything there. This String can be used by your custom Widget:

```dart
dowWeekdayBuilder: (context, text) {
  if (text == 'Fri') {
    return Container(
      color: Colors.blue,
      child: Center(child: Text(text)),
    );
  } else {
    return Center(child: Text(text));
  }
},
```
This snippet will build FridayDOW with blue background.

**Comment by mohitferrari** [comment]
Thanks! It worked.
