### ISSUE TITLE
Events datetime

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#190]
I've followed some Yotube tutorial (https://www.youtube.com/watch?v=jhtKTKn6PlI) to create the events doing something like this:
```
if (encodedEvent != null) {
                                        if (_events[_calendarController
                                                .selectedDay] !=
                                            null) {
                                          _events[_calendarController
                                                  .selectedDay]
                                              .add(encodedEvent);
                                        } else {
                                          _events[_calendarController
                                              .selectedDay] = [encodedEvent];
                                        }
                                        prefs.setString(
                                            'events-${myInvestment["documentID"]}',
                                            json.encode(encodeMap(_events)));
                                        final snackBar = SnackBar(
                                            content: Text('Evento creado'));
                                        globalKey.currentState
                                            .showSnackBar(snackBar);
                                      }
```
The problem comes when these events are saved. They always take this time:
`12:00:00.000Z`
Despide the day is correct I'd say this is not the best way to create them.

I had a look to the working example on the repo but unfortunately didn't see any event creation option. Would be possible to add this as well to the example?

**Comment by aleksanderwozniak** [comment]
`12:00:00.000Z` is intentional here. Does it cause any troubles in your case?

**Comment by erperejildo** [comment]
Not anymore but I had to create a new property for time and use this instead

**Comment by erperejildo** [comment]
I gave it a workaround and this is what I ended with:
```
final date = new DateTime(
                        _calendarController.selectedDay.year, // this remains the same
                        _calendarController.selectedDay.month,
                        _calendarController.selectedDay.day,
                        DateFormat.jm().parse(event["time"]).hour, // 2:30 PM and gets 14
                        DateFormat.jm().parse(event["time"]).minute, // 2:30 PM and gets 30
                      );
                      setState(() {
                        if (_events[date] != null) {
                          _events[date].add(event);
                        } else {
                          _events[date] = [event];
                        }
                      });
```
Result:
> {2020-02-15 14:30:00.000: [{id: ad004dfa-5cf4-401d-9b0d-27fadb334719, text: almuerzo con familia, time: 2:30 PM, color: #2196f3, paymentDay: null}]}

So modifying the date before adding it as event gives me more manipulation powers.

DateFormat: https://pub.dev/packages/intl

**Comment by luizwalber** [comment]
I don't know if I understand your problem, but look at what I do to process my events:

To make things more easy to process I made my events a Map<String, List<Task> and for the keys I transform the date to a hash for the day ('yyyy-MM-dd')

```
String dateDayHash(DateTime day) {
  return day != null ? DateFormat('yyyy-MM-dd').format(day) : null;
}
```

This way my tasks are with the correct day/hour and I have a map to know the tasks for every day

by the way, I recover them like this

```
Future<Map<String, List<Task>>> getTasksNearMonthTasks(int month) async {
    Database db = await _instance.database;
    List<Task> taskList = [];
    String sql =
        '''(${Task.monthCol} = ? or ${Task.monthCol} = ? or ${Task.monthCol} = ?)"
    List<Map<String, dynamic>> databaseReturn = await db.query(Task.table,
        where: sql,
        whereArgs: [
          month - 1,
          month,
          month + 1
        ]);

    databaseReturn.forEach((Map<String, dynamic> taskMap) {
      taskList.add(Task.fromMap(taskMap));
    });

    return groupBy(taskList, (task) => dateDayHash(task.createdForDay));
  }
```
this way I recover every tasks from the current month and the months near it in the database and transform them into a map<hashForDay, List<Task>>, when the event 'onVisibleDaysChanged' is called I update the events like this:

```
void _onMonthChange(DateTime first, DateTime last, CalendarFormat format) {
    int month = last.day < 7 ? last.month - 1 : last.month;
    StoreProvider.of<AppState>(context).dispatch(getMonthlyTasks(month));
  }
```

**Comment by erperejildo** [comment]
After another workaround I found out that changing the hour would bring more issues, specially because we'd need more changes from the library and this'd bring breaking changes.

So I ended up doing some extra loops that I tried to avoid, but it's less painful.
