### ISSUE TITLE
Order events

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#193]
Is there any possible way to order the events by date? Since all of them are created using same hour I'd need to use the dateTime field I have created for each of them but I'm not sure how to avoid a extra loop every time I need to load the widget:
![Screenshot_1581980579](https://user-images.githubusercontent.com/5629919/74691189-18dfcb80-51e2-11ea-8428-c6d7717b2826.png)

**Comment by aleksanderwozniak** [comment]
TableCalendar will use the order in which you have passed your events. I would suggest sorting them once - then persisting them in correct order.

**Comment by erperejildo** [comment]
Fair enough. I was just wondering if it was possible somehow using this widget itself.
