### ISSUE TITLE
Can i just have the header?

### ISSUE THREAD

**Issue by lucas-sesti** [aleksanderwozniak/table_calendar#196]
I wanna know if can i have just the header of calendar, and remove all week and weekend days of calendar...

**Comment by aleksanderwozniak** [comment]
Do you mean hiding the bar which contains names of days (Mon, Tue, Wed, etc.)? You can use `renderDaysOfWeek: false` inside `CalendarStyle`.

**Comment by lucas-sesti** [comment]
Nooo, i want have just the header, remove all days just the month in header

**Comment by lucas-sesti** [comment]
Can i have this or not?

**Comment by aleksanderwozniak** [comment]
Removing the whole calendar content is not supported. The closest you can get is by using `CalendarFormat.week`, which will display the header + one row of days (one week).
