### ISSUE TITLE
Wrong calendar format

### ISSUE THREAD

**Issue by lucas-sesti** [aleksanderwozniak/table_calendar#199]
I'm using the table calendar, and i tried to set the calendar format to month, but what i got is:
![image](https://user-images.githubusercontent.com/11727165/75062243-31d9cc80-54c1-11ea-82fb-0804d947b3d0.png)

I set to "Week" and the button display Month, and when i try set the calendar format from calendar controller (in the first load), i got the error: 
The setter 'value=' was called on null.
Receiver: null
Tried calling: value=Instance of 'CalendarFormat'

I can't set the calendar format...

**Comment by aleksanderwozniak** [comment]
If you want to start the Table Calendar in week format, use `initialCalendarFormat: CalendarFormat.week` instead.

This button displays the *next* CalendarFormat by default. To change it, use `formatButtonShowsNext: false`. You can find this property inside `HeaderStyle` ([docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/HeaderStyle/formatButtonShowsNext.html)).

**Comment by lucas-sesti** [comment]
When i set "initialCalendarFormat: CalendarFormat.week" doesn't works too, every time is 2 weeks

**Comment by aleksanderwozniak** [comment]
`initialCalendarFormat` will work only on the first build. If you want to change the CalendarFormat later on, you will need to use `_calendarController.setCalendarFormat`, but make sure you do it outside of `build` method.

**Comment by junaid-umar** [comment]
I am facing same issue. CalendarFormat can be changed by calendarController.setCalendarFormat. But it will show wrong text. for week it will show month, for month text is 2 weeks and for 2 weeks is shows week text on top.

**Comment by junaid-umar** [comment]
formatButtonShowsNext: false worked for me

**Comment by lucas-sesti** [comment]
Yeah, i setted the wrong way and its working until now... probably have a name error in package

**Comment by kingkangyu** [comment]
> I am facing same issue. CalendarFormat can be changed by calendarController.setCalendarFormat. But it will show wrong text. for week it will show month, for month text is 2 weeks and for 2 weeks is shows week text on top.

pls try to add this to change the text of the switch button
```
TableCalendar(
  availableCalendarFormats: {
                    CalendarFormat.month : 'week', 
                    CalendarFormat.twoWeeks : 'month', 
                    CalendarFormat.week : '2 weeks',
                  },
)
```

**Comment by aleksanderwozniak** [comment]
@kingkangyu 
This is a wrong approach. Instead, use `formatButtonShowsNext: false`

> This button displays the _next_ CalendarFormat by default. To change it, use `formatButtonShowsNext: false`. You can find this property inside `HeaderStyle` ([docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/HeaderStyle/formatButtonShowsNext.html)).

**Comment by kingkangyu** [comment]
> approach

got it ,thank u

**Comment by kingkangyu** [comment]
> @kingkangyu
> This is a wrong approach. Instead, use `formatButtonShowsNext: false`
> 
> > This button displays the _next_ CalendarFormat by default. To change it, use `formatButtonShowsNext: false`. You can find this property inside `HeaderStyle` ([docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/HeaderStyle/formatButtonShowsNext.html)).

got it ,thank u

**Comment by lucas-sesti** [comment]
Got it too!, thank you, you will change in package? or i need change the availableCalendarFormats, dont make sense the month be week etc

**Comment by aleksanderwozniak** [comment]
There are two approaches to viewing it:

1. FormatButton displays next state `// formatButtonShowsNext: true (default)`

In that approach, you know what will happen after pressing the button. If it displays "Month" and you click on it -> TableCalendar will animate to month format. If it displays "Week" -> clicking will animate to week format. This means that your current format is different than what FormatButton is displaying.

2. FormatButton displays current state  `// formatButtonShowsNext: false`

In that approach, FormatButton will display current format. If TableCalendar is in month format, the button will display "Month". But you don't know what will happen after you click it -> it might animate to either one week format, or two week format.

Both approaches are equally valid, use the one that seems more intuitive to you.
