### ISSUE TITLE
First and Last Days

### ISSUE THREAD

**Issue by FabricioMedeiros** [aleksanderwozniak/table_calendar#200]
Hello, 

I need to get the first and last days when the Calendar is build the first time. Is this possible ? I know there's the onVisibleDaysChanged, and it work so fine!

But I need this same information, without user change the month.

**Comment by patthipati** [comment]
Yes i also need this

**Comment by masseelch** [comment]
Until this gets merged (if it will get merged) you can use my fork directly and switch back when and if @aleksanderwozniak merges my pr.

**Comment by aleksanderwozniak** [comment]
I'm not sure I like having `onVisibleDaysChanged` triggered on startup. I would prefer to have a separate callback like `onCreate` / `onCalendarCreated` (which can give the same data: firstDay, lastDay, calendarFormat - no problem).

This will help avoid situations where `onVisibleDaysChanged` got triggered even though it was unwanted.

Also, I am currently working on a bigger update which will modify existing properties, and I think I will break down `onVisibleDaysChanged` into two methods: `onMonthChanged` and `onCalendarFormatChanged`. This will give better context what is happening behind the scenes with TableCalendar.

**Comment by masseelch** [comment]
Your proposed `onCreate` / `onCalenderCreated` callback seems to fit better. 

If you want i am happy to help on this.

**Comment by aleksanderwozniak** [comment]
Sure, go for it. You can use similar approach as earlier, just add another callback property instead of using `onVisibleDaysChanged`.

Please name it `onCalendarCreated`.

**Comment by aleksanderwozniak** [comment]
@FabricioMedeiros @patthipati 
You can now use `onCalendarCreated` callback in TableCalendar version `2.2.3`

**Comment by FabricioMedeiros** [comment]
Hello @aleksanderwozniak and @masseelch , thank you guys! 

This changes you do work so fine! That's exactly what I need!  I have no words to thank you for your help.

This Widget is amazing and is helping me a lot in my app!

Thanks a lot friend!!!
