### ISSUE TITLE
Can I edit event style by  myself?

### ISSUE THREAD

**Issue by cn-Meepo** [aleksanderwozniak/table_calendar#201]
Can I edit event style by  myself ?  example: 
 _events = {
      DateTime(2020, 1, 2): [Widget,Widget,Widget]
}

**Comment by aleksanderwozniak** [comment]
Yes, you will need to use `markersBuilder` from [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/markersBuilder.html). You can't pass Widgets into `events` field.

**Comment by cn-Meepo** [comment]
@aleksanderwozniak sorry , I didn't look it carefully.
