### ISSUE TITLE
Is it possible to add support for Bikram Sambat Calendar

### ISSUE THREAD

**Issue by paurakhsharma** [aleksanderwozniak/table_calendar#205]
I am building a flutter app with internalization support. 
I have support for the Nepali language.
I have added the translations for events but I was wondering if I could change the calendar as well to Nepali. Similar to https://pub.dev/packages/nepali_date_picker

I understand this is difficult and probably not worthy to be added to the library.

So, can you please suggest to me how I could implement this without official support in the library?

**Comment by aleksanderwozniak** [comment]
<img src="https://user-images.githubusercontent.com/22658673/76144542-d8a59780-6081-11ea-99b1-e2f27461ca99.png" width="300">

You can get something like the picture above when you pass `'ne'` as `locale`.

The next thing you can do is either hide the header button by adding `formatButtonVisible: false` to `HeaderStyle`, or add your translation manually:
```dart
availableCalendarFormats: {
  // add your translation here
  CalendarFormat.month: 'Month', 
  CalendarFormat.twoWeeks: '2 weeks', 
  CalendarFormat.week: 'Week', 
},
```

The last step would be to change how each day is displayed. You can use `CalendarBuilders` for that - check [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart#L149) for more details. I think you will need to make a method which takes in a number (`date.day`) and returns a proper String in Nepali.

**Comment by paurakhsharma** [comment]
@aleksanderwozniak Awesome! Thank you, this should solve most of my problem
