### ISSUE TITLE
Empty calendar rows

### ISSUE THREAD

**Issue by mnbayan** [aleksanderwozniak/table_calendar#21]
Setting`startingDayOfWeek: StartingDayOfWeek.sunday` and `outsideDaysVisible: false` will result in an empty row in the calendar. Few examples of this are the months September and December 2019 as well as March 2020. I am using table_calendar version 1.0.2. 

See screenshot from the example project.

![flutter_table_calendar_102](https://user-images.githubusercontent.com/8461871/54895393-57013c00-4efa-11e9-9b3e-2a2b6b4bb0ed.png)

**Comment by aleksanderwozniak** [comment]
Thanks for the report!

It should be working properly on `dev` branch - I'll push an update later today.

**Comment by aleksanderwozniak** [comment]
Fixed with package version `1.1.0`
