### ISSUE TITLE
Different TextStyle for each day of the week

### ISSUE THREAD

**Issue by usashiki** [aleksanderwozniak/table_calendar#211]
Currently in `CalendarStyle` it's possible to customize the `TextStyle` for weekends, weekdays, and holidays, but I'd like a way to specify further if possible. Specifically, I'd like to be able to color Saturdays and Sundays different colors, but this doesn't appear to be possible currently. (Similarly for `DaysOfWeekStyle` in the header as well)

**Comment by aleksanderwozniak** [comment]
Check out #162 and [dowWeekendBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/dowWeekendBuilder.html).

**Comment by usashiki** [comment]
Ah, I didn't realize that was possible! Thanks so much for the prompt response!
