### ISSUE TITLE
Remove weekend from calendar

### ISSUE THREAD

**Issue by caiogranero** [aleksanderwozniak/table_calendar#212]
Hi,

I would like to remove Sunday from any calendar view, i set the weekend only as Sunday but i don't find any attribute to hide a specific weekday.

Is this possible?

**Comment by aleksanderwozniak** [comment]
Let me know if I understand this correctly - you want to have 6 days displayed in each row; Monday to Saturday, right? This is not supported at the moment. You can freely chose which weekday to start with and which weekdays are treated as weekend, but there will always be 7 days per week.

**Comment by caiogranero** [comment]
Yes, that's exactly what i want, okay :/

**Comment by ahmedryan** [comment]
How do I choose the weekdays, may you help please?

**Comment by caiogranero** [comment]
Hi @ahmedryan ,

TableCalendar has a property weekendDays, its an array of Days, you need to choose what you consider as Weekend, like this:

`TableCalendar(events: [], weekendDays: const [DateTime.sunday])`

**Comment by ahmedryan** [comment]
Thank you so much for the help @caiogranero. It's working :D
