### ISSUE TITLE
On click event of left and right Chevron Icon

### ISSUE THREAD

**Issue by HinnaRutaba** [aleksanderwozniak/table_calendar#215]
Greetings! I have been using this calendar api and I wanted to perform function when month and year change on calendar. I suppose this would be done if I access the click event on left and right chevron icon. So is there any function available where I can either access onTap event on left/right icons or programmatically sense when month and year change on calendar?
Thanks in advance!

**Comment by aleksanderwozniak** [comment]
You can use `onVisibleDaysChanged` for that - [docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/onVisibleDaysChanged.html)
