### ISSUE TITLE
Multiple date selector

### ISSUE THREAD

**Issue by HinnaRutaba** [aleksanderwozniak/table_calendar#216]
Hello! is there any method to select multiple dates?

**Comment by ConsultoriaOrganizacional** [comment]
I have the same question did you find any way to do it?

**Comment by wapchief** [comment]
holidayDayBuilder Seems to be feasible, set onDaySelected datas to holidays,But need close select and todayDay status.

**Comment by aleksanderwozniak** [comment]
Let's follow this in #153
