### ISSUE TITLE
good evening

### ISSUE THREAD

**Issue by aldikun17** [aleksanderwozniak/table_calendar#217]
im using laravel for api and when using a Map<DateTime,dynamic> insert my date from api with format yyyy-mm-dd datime.parse(key) in return a error with invalid date format. i just wanted to display my event in onload when navigator is visited. thanks for helping my. btw new in dart.

**Comment by aleksanderwozniak** [comment]
As long as you provide proper `DateTime` objects to `events` property of TableCalendar, it should work without any issues. Make sure there are no errors when creating the `DateTime` objects.

**Comment by aldikun17** [comment]
btw flutter dateformat is yyyy-mm-ddThh:mm:ssZ? do i need to format the datetime in that format to work

**Comment by aldikun17** [comment]
im returning a sample of json like this
{"success":200,"schedule":{"start_date":"2020-03-02T12:00:00.000000Z","event_title":"1 day event for tech support"}}

and trying to parse it like this new DateFormat.yMMMd().parse(key) and the error comes out 
either trying to read yyyy, mm or / at position 5.

**Comment by aldikun17** [comment]
i've done it for now with formatting and understand what map is
