### ISSUE TITLE
multiple events in same date

### ISSUE THREAD

**Issue by aldikun17** [aleksanderwozniak/table_calendar#218]
i already display my events onload but when a same date with multiple event it display on event on that day

**Comment by aleksanderwozniak** [comment]
To add a couple of events to the same date, simply specify them in a List:

```dart
_events = {
    DateTime(...): [Event1, Event2, Event3, ...],
};
```

Check [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart#L54) for more details.
