### ISSUE TITLE
onVisibleDaysChanged still returns days outside the month even outsideDaysVisible: false

### ISSUE THREAD

**Issue by mnbayan** [aleksanderwozniak/table_calendar#22]
`onVisibleDaysChanged`, as the name implies, should return the visible calendar days. This is not the case in the version 1.0.2 where the said method still returns the days outside the selected month even if `outsideDaysVisible` is set to `false`.

**Comment by aleksanderwozniak** [comment]
Good catch!

I've improved `onVisibleDaysChanged` behavior as you suggested. I'll push an update later today.
Note that `CalendarFormat.twoWeeks` and `CalendarFormat.week` will still display (and return) days outside of current month.

**Comment by aleksanderwozniak** [comment]
Changed with #24 

As of package version `1.1.0`, `onVisibleDaysChanged` will return the actually visible first and last day, as opposed to first and last cell in table.

**Comment by PrajwalCarnileo** [comment]
can i know now what can be done since onVissibledDaysChanged is removed?
