### ISSUE TITLE
How to disable selection the day before today?

### ISSUE THREAD

**Issue by lambertofn** [aleksanderwozniak/table_calendar#220]
Maybe someone here know how to disable selection the day before today?

Thank you.

**Comment by fxsalazar** [comment]
I think roughly is by using `enabledDayPredicate: (dt) => dt.isAfter(DateTime.now()),`

**Comment by aleksanderwozniak** [comment]
Other option would be to use `startDay`:
```dart
startDay: DateTime.now()
```

Closing for now, but feel free to reopen if needed.
