### ISSUE TITLE
how to disable left arrow to see old months

### ISSUE THREAD

**Issue by ccarbajo** [aleksanderwozniak/table_calendar#221]
can i catch event when user click right or left arrow?

Thanks in advance

**Comment by a619sachin** [comment]
I have same doubt @ccarbajo I wanted to clear events on month change. Did you get any solution?

**Comment by aleksanderwozniak** [comment]
@ccarbajo 
You can provide custom calendar header - use `headerVisible: false`. To control calendar's behavior use `previousPage()` and `nextPage()`.

@a619sachin 
For version `3.0.0` use `onPageChanged` callback.
For version `2.3.3` use `onVisibleDaysChanged` callback.
