### ISSUE TITLE
事件小圆点不能根据自己的条件来判断显示跟隐藏？

### ISSUE THREAD

**Issue by SuperZiLu** [aleksanderwozniak/table_calendar#224]
如题

**Comment by aleksanderwozniak** [comment]
From Google Translate:
`事件小圆点不能根据自己的条件来判断显示跟隐藏` -> `Event dots cannot be displayed or hidden according to their own conditions`
`如题` -> `As the title`

https://github.com/aleksanderwozniak/table_calendar/issues/67#issuecomment-524662136
