### ISSUE TITLE
Background for Header and Content

### ISSUE THREAD

**Issue by seansabe** [aleksanderwozniak/table_calendar#225]
At this point there's no option to set a background to the content of the calendar. Also, would be nice to have an independant background, border decoration, rounded corners, etc separately for header and content of the calendar.

**Comment by aleksanderwozniak** [comment]
Will be improved with #236.

At the moment you can use `HeaderStyle(decoration: ...)` to style the header and/or wrap the whole `TableCalendar` with `Container` and add decoration there.

**Comment by ventr1x** [comment]
This is basically the main need for a project of mine.
Even just putting a Card around it might not cut it.

Let me attach a screen from a customer:
![calendarScreen](https://user-images.githubusercontent.com/7974355/87016649-477d3380-c1cf-11ea-81e6-215a6a7dfe70.png)
:

**Comment by aleksanderwozniak** [comment]
Added in version `2.3.1`
