### ISSUE TITLE
On Click on outside month days onVisibleDaysChanged method calling how to block this

### ISSUE THREAD

**Issue by patthipati** [aleksanderwozniak/table_calendar#228]
i want to disable click event for the outside month days, because if onVisibleDaysChanged im calling service call to get the data of the next month which I don't want , i want just to say in the same month no action should be have

**Comment by patthipati** [comment]
i want to disable click event for the outside month days, because if onVisibleDaysChanged  im calling service call to get the data of the next month which I don't want , i want just to say in the same month no action should be have

**Comment by aleksanderwozniak** [comment]
You can try two approaches here:

1) Hide outside days altogether:

```dart
calendarStyle: CalendarStyle(
  outsideDaysVisible: false,
),
```

2) Keep them visible, but disabled:

```dart
enabledDayPredicate: (day) {
  final firstDay = DateTime.utc(_calendarController.focusedDay.year, _calendarController.focusedDay.month, 1);
  final lastDay = DateTime.utc(_calendarController.focusedDay.year, _calendarController.focusedDay.month + 1, 1)
      .subtract(const Duration(days: 1));

  return day.isAfter(firstDay) && day.isBefore(lastDay);
},
```

**Comment by patthipati** [comment]
i did in a different way, for outside day builder widget, I wrap with IgnorePointer Widget so that it will disable all click events.
