### ISSUE TITLE
the value of startingDayOfWeek and availableCalendarFormats have been changed already,but canlendar not changed

### ISSUE THREAD

**Issue by kingkangyu** [aleksanderwozniak/table_calendar#229]
```
String currentLocale = Localizations.localeOf(context).toString();

var currentI10n = CalToDoLocalizations.of(context);
....

TableCalendar(
  locale: currentLocale,
  startingDayOfWeek:currentLocale=='zh_CN'? 
  StartingDayOfWeek.monday:StartingDayOfWeek.sunday,
  availableCalendarFormats: {
                    CalendarFormat.month : currentI10n.switch1week, 
                    CalendarFormat.twoWeeks : currentI10n.switch1month, 
                    CalendarFormat.week : currentI10n.switch2week,
                  },
)
```
`startingDayOfWeek`  and `StartingDayOfWeek` will not work if the Locale of device is changed.
but `locale: currentLocale`will work always

What I met  was
1.
if Locale of the device is Chinese first .
Monday will be the first day .(working)
2.
I change the Locale to English
Sunday will be the first day.(working)
3.
but I try to change the Locale to Chinese again ,the start day will not be changed anymore.

I am not sure if I can do something to let it work.

thank you.

**Comment by aleksanderwozniak** [comment]
Changing `startingDayOfWeek` during runtime is not supported at the time - follow #164 for updates. 
Changing just the`locale` should work without any issues.

**Comment by kingkangyu** [comment]
> Changing `startingDayOfWeek` during runtime is not supported at the time - follow #164 for updates.
> Changing just the`locale` should work without any issues.

Thank you.
