### ISSUE TITLE
New feature: Option to set selectedDate

### ISSUE THREAD

**Issue by mnbayan** [aleksanderwozniak/table_calendar#23]
Hi,

First of all thanks for making this package public, it really helps me and is currently the best in its category.

I would like suggest an improvement to its current great functionalities. I will be great to have an option to set the *selectedDate* programmatically. I see right now that you provided an `initialDate` in the constructor which will then set the `_selectedDate` once. This will then be updated only when `onDaySelected` is triggered which requires a user tapping a date in the calendar. 

There are use cases in which the *selectedDate* needs to be updated programmatically and provide a UI feedback. For instance, I want to automatically set the first day of the month as *selectedDate* when page is changed. (see Google Calendar app)

With this, I'm thinking if `initialDate` can be renamed as `selectedDate` and use it for the purpose described above. Thanks!

**Comment by aleksanderwozniak** [comment]
I am glad you like it :)

I've added programmatic `selectedDay` with #24 
Update package version to `1.1.0` and you are set!

To achieve your desired effect, you can try something like this:
```dart
void _onVisibleDaysChanged(DateTime first, DateTime last, CalendarFormat format) {
  setState(() {
    if (format == CalendarFormat.month && _selectedDay.month != first.month) {
      _selectedDay = first;
    }
  });
}
```

Make sure to have `outsideDaysVisible` set to `false`, and of course link `_selectedDay` to `selectedDay` property of `TableCalendar` Widget.

Let me know if this does the trick!

**Comment by mnbayan** [comment]
Thanks so much. You are really helpful.
