### ISSUE TITLE
Locale to pt_BR

### ISSUE THREAD

**Issue by davirossini** [aleksanderwozniak/table_calendar#231]
How can I translate the calendar to pt_BR or pt_PT? I used locale to define pt but didn´t work.

**Comment by aleksanderwozniak** [comment]
You need to initialize `intl` ([readme](https://github.com/aleksanderwozniak/table_calendar#locale)) and then pass `'pt_BR'` as `locale` to TableCalendar widget. You will find all of that in [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart).


<img src=https://user-images.githubusercontent.com/22658673/79387300-b8fc6b80-7f6b-11ea-85d6-d1e3ae9ffce8.png width=300>

**Comment by diogomatheus** [comment]
I'm using the flutter_localizations and flutter_translate (pt_BR is one of my supported locales).
https://pub.dev/packages/flutter_translate

In this scenario, config the TableCalendar as follows:
locale: Localizations.localeOf(context).languageCode,
availableCalendarFormats: {
  CalendarFormat.month: translate('event.calendar.month'),
  CalendarFormat.week: translate('event.calendar.week')
}

**Comment by xhidnoda** [comment]
````
import 'package:intl/date_symbol_data_local.dart';


void main() {
  initializeDateFormatting().then((_) => runApp(YourStatefulWidget()));
}
````

And then:
````
  Widget _buildTableCalendar() {
    return TableCalendar(
      locale: 'pt_BR',
    )
}
````
