### ISSUE TITLE
Change color icons

### ISSUE THREAD

**Issue by carlinho11** [aleksanderwozniak/table_calendar#237]
How do I change the color of the back and forward icon?
![calendar](https://user-images.githubusercontent.com/38302156/79755020-c6f51800-82ee-11ea-84ab-ff45e5be3743.PNG)

**Comment by jacksonmajolo** [comment]
try:
 headerStyle: HeaderStyle(
            leftChevronIcon: Icon(Icons.chevron_left,
                color: Colors.red),
            rightChevronIcon: Icon(Icons.chevron_right,
                color: Colors.red)),

**Comment by alianando** [comment]
How can I remove those two icons??

**Comment by aleksanderwozniak** [comment]
@alianando 
At the moment you would have to create a custom header for TableCalendar.
Here is a simple [example](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1) how you can do this.

Feel free to open a new issue if you run into problems with it.
