### ISSUE TITLE
[Feature Request] Open access to private calendar control methods

### ISSUE THREAD

**Issue by morrica** [aleksanderwozniak/table_calendar#248]
I am implementing some calendar control UI outside of the UI built into the TableCalendar. Specifically, I am implementing alternate UI for selecting the the previous month, next month, and moving directly to the current month. All of this works fine using `CalendarController.setFocusedDay()`, however there is no animation between the calendar updates.

It would be very helpful if `TableCalendar._selectPrevious()` and `TableCalendar._selectNext()` were public so that we could directly call those and make use of the nice transition animations. Another way to handle this would be to make `CalendarController.setFocusedDay()` trigger the transition animations. That way it would be possible to trigger them when moving directly to any desired month.

Any help with this or implementing an alternate solution to my animation issue would be greatly appreciated.

**Comment by aleksanderwozniak** [comment]
This will be added with `3.0.0` release from `dev` branch, which alters the way `CalendarController` functions.

**Comment by aleksanderwozniak** [comment]
Landed in version `2.3.2`, as `calendarController.previousPage()` and `calendarController.nextPage()`.
