### ISSUE TITLE
SelectedDate is not getting "deselected", while navigating to other month.

### ISSUE THREAD

**Issue by TharaniP** [aleksanderwozniak/table_calendar#252]
Hi,
  SelectedDate is not getting deselected when i navigate to other month.
  
**Steps to reproduce:** 

Eg: Will take May month to reproduce the issue.

  1.   Select some date in May month . 
  2 . Navigating to June/other month.  
  3.  Go back to May month.
  4.  You can notice "previously selected date in May month is not get deselected." 

**Expected Result:** When user changes the month, selected date should get deselected.

**Comment by aleksanderwozniak** [comment]
This is the expected behavior. 

You can easily change it if you want, by using `_calendarController.setSelectedDay()` inside `onVisibleDaysChanged` callback.

**Comment by TharaniP** [comment]
Thanks for the update.

I have checked the default calendar apps in mobile. In those apps, selected date got deselected. Only current date was selected. I am expecting the same behaviour.

**Comment by aleksanderwozniak** [comment]
Like I said, it is very easy to add in your project, and having this option allows developers to define custom behaviors - for example selecting the first day of month whenever month gets changed.

Closing the issue now.
