### ISSUE TITLE
How can i add a background container in day name and date of a single day in week view??

### ISSUE THREAD

**Issue by alianando** [aleksanderwozniak/table_calendar#256]

**Comment by aleksanderwozniak** [comment]
Depends on your end goal. Have a look at [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html), especially `dowWeekdayBuilder`, `dowWeekendBuilder`, `dayBuilder`. You can change which days of the week are treated as weekend by using `weekendDays` property.
