### ISSUE TITLE
Change calendar layout

### ISSUE THREAD

**Issue by carlinho11** [aleksanderwozniak/table_calendar#257]
I would like to know how to add a border on the days, similar to day 1 to 9 of the attached image.
![1519e0af-bc69-4087-bd4d-70a724b11887](https://user-images.githubusercontent.com/38302156/81738184-af352d80-946f-11ea-8f8e-4a135249980b.jpg)

**Comment by aleksanderwozniak** [comment]
This is quite custom - try using `CalendarBuilders` for it. For example:
```dart
builders: CalendarBuilders(
  dayBuilder: (context, date, events) {
    if (date.day <= 9) {
      return Container(
        decoration: BoxDecoration(border: Border.all()),
        child: Center(child: Text('${date.day}')),
      );
    } else {
      return Center(child: Text('${date.day}'));
    }
  },
),
```
You may want to define other builders there as well.

**Comment by carlinho11** [comment]
It worked. Thank you!
