### ISSUE TITLE
How to disable onSelectedDay listener/callback?

### ISSUE THREAD

**Issue by DevyankShaw** [aleksanderwozniak/table_calendar#258]
I want only today's day to be selected and onSelectedDay shouldn't trigger i.e when users tap on other day's default implementation also shouldn't work like changing the shape and color of the selected day. How to achieve it?

**Comment by aleksanderwozniak** [comment]
Try using this:
```dart
calendarStyle: CalendarStyle(
  highlightSelected: false,
),
```

**Comment by DevyankShaw** [comment]
Thanks. It worked!
