### ISSUE TITLE
How to set the language is Chinese?

### ISSUE THREAD

**Issue by SunLongbri** [aleksanderwozniak/table_calendar#26]
如何将日历的语言设置为中文呢？我找了好长时间的属性，都没有找到，我想知道怎么设置。

**Comment by aleksanderwozniak** [comment]
Something like this?

<img src=https://user-images.githubusercontent.com/22658673/55224343-98eaf480-5210-11e9-803c-e3ca4255e02a.png width=300>

Also, please use English. I could only guess your request by the issue's title :p

**Comment by coolmarat** [comment]
Can you explain language customization in this calendar?

**Comment by aleksanderwozniak** [comment]
@SunLongbri  @coolmarat 
Locale support has been added with package version `1.1.2`

Here is a short how-to: https://github.com/aleksanderwozniak/table_calendar#locale
