### ISSUE TITLE
Call function when changing month

### ISSUE THREAD

**Issue by carlinho11** [aleksanderwozniak/table_calendar#261]
Is it possible to call a function as soon as I switch between months and get the month and year in that function?

**Comment by aleksanderwozniak** [comment]
You can use `onVisibleDaysChanged` callback for that. Check [API docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/table_calendar-library.html) for more info.

**Comment by carlinho11** [comment]
I managed to do the desired project, thank you!
