### ISSUE TITLE
dayBuilder starts each day at 12:00:00 instead of 00:00:00

### ISSUE THREAD

**Issue by shamilovtim** [aleksanderwozniak/table_calendar#263]
Every iteration of dayBuilder returns the correct day but at 12:00:00Z. I can't find what code is causing this or why it's doing that but I think it's a default part of the plugin. This should be configurable but the default setting should actually be 00:00. I can't imagine a correct use case for starting a day at 12:00.

**Comment by aleksanderwozniak** [comment]
This is intentional, especially since `dayBuilders` should care only if the supplied "day" is correct (year, month, day) . Have you run into any hurdles with it?

**Comment by shamilovtim** [comment]
This introduces flawed corner cases.

For instance, I have a calendar that I created from 07-01 to 08-01. When I coded "make me a calendar from 07-01 to 07-31" I did not mean from 07-01 12:00 omitting the first 12 hours of the first day and ending at halfway through the last day. In this example 07-01 11:00 is *not* part of this calendar. That matters because our events which we attach to the calendar use its callbacks, and its callbacks are passing a DateTime which is not inclusive of 12 hours from the start, and not inclusive of 12 hours of the end. Setting this to 00:00 fixes all of these problems. 

Regarding testing day. Testing date.day alone isn't good enough because for instance the 1st can reoccur on a calendar and the user needs to know whether they got day 07-01 and not day 08-01. Also testing date.day alone is a level of precision that isn't really appropriate for production level applications. We're going to want to know if an event is between xx-xx-xxZ or not, not whether an event happened on an integer day between 1-31.

**Comment by aleksanderwozniak** [comment]
Can you provide a concrete example with code snippet, where the `time` part being 12:00:00 has a negative impact on it?

**Comment by shamilovtim** [comment]
I want 07-01 00:00:00 - 07-31 23:59:59. This is what we think of as a month in the human world, and the business logic should mimic that. Instead I get 07-01 12:00:00 - 07-31 12:00:00. 

Here's more concrete though. My daybuilder where I map my business logic to the calendar and pass down the appropriate data to my nested builders. My business logic defines a real end of day because it uses real data. `date` of 12-05 12:00 passed down from the callback will not include 12-05 0:00 passed down from my real data. `cycle` will return `null`.

```
  dayBuilder: (context, date, list, controller) {
          // if the date being built has a Cycle object
          final cycle = cyclesState.cycles.firstWhere(
            (cycle) {
              return date.isBetween(cycle.startDate, cycle.endDate);
            },
            orElse: () => null,
          );

          return buildDay(date, day, cycle, true);
        },
```

**Comment by shamilovtim** [comment]
I am just going to do this `cycle.endDate.add(Duration(hours: 12))` as a work around for now

**Comment by aleksanderwozniak** [comment]
> I want 07-01 00:00:00 - 07-31 23:59:59. This is what we think of as a month in the human world, and the business logic should mimic that. Instead I get 07-01 12:00:00 - 07-31 12:00:00.
> 
> [...]

You will never get 07-01 00:00:00 - 07-31 23:59:59 because there is no way of telling which date is the last one. The time part will always be the same for each returned date, so the end date could be either 07-31 00:00:00, or 08-01 00:00:00, depending if you go for inclusive end date or exclusive end date. As far as calendar is concerned, the time part is redundant, so if you find 12:00:00 inconvenient, then simply truncate it to get 00:00:00.

This also solves your concrete example.
