### ISSUE TITLE
unselectedColor?

### ISSUE THREAD

**Issue by KJonesDevelopment** [aleksanderwozniak/table_calendar#264]
Is there any way to set the background of the dates when they are unselected similar to how selectedColor does for the selected day?  Thank you!

**Comment by aleksanderwozniak** [comment]
Do you mean background of not-selected-dates? You can use `dayBuilder` for that. Check out [CalendarBuilders docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html).

**Comment by KJonesDevelopment** [comment]
I totally misread how those builders worked. Thanks again; this is awesome.
