### ISSUE TITLE
onVisibleDaysChanged should return scroll direction

### ISSUE THREAD

**Issue by Phearun99** [aleksanderwozniak/table_calendar#265]
I want to know how onVisibleDaysChanged callback happen by Vertical scroll or Horizontal Scroll.

**Comment by xfy6238** [comment]
yes. I want it ,too. I don't use header. I customize the two buttons, click and swipe left and right in horizontal direction.

**Comment by lhannest** [comment]
I want to dismiss the calendar when the gesture is swipe up and it's already in the `CalendarFormat.week` state.

**Comment by aleksanderwozniak** [comment]
@Phearun99 @xfy6238 
Version `3.0.0` splits `onVisibleDaysChanged` into two callbacks: `onPageChanged` (horizontal scroll) and `onFormatChanged` (vertical scroll). This should make it easier to use.

@lhannest 
This is a bit more complex. I would suggest disabling vertical gestures in `TableCalendar`, wrapping it with `SimpleGestureDetector` and providing custom logic inside vertical swipe callback. 

You can use `swipeCalendarFormat()` to recreate default `TableCalendar`'s behavior. Check what is the current `calendarFormat` and if it matches `CalendarFormat.week` then simply hide the widget - I would suggest using `Visibility` widget for that.

This [example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-dev/example/lib/pages/persistence_example.dart) might be of some help.
