### ISSUE TITLE
swipeCalendarFormat

### ISSUE THREAD

**Issue by edwin-alvarez** [aleksanderwozniak/table_calendar#266]
trying to find out an option to jump from 4 to 3 to 2 to 1-week view, when swipeCalendarFormat is executed up and down, any advice? in my case I see it jumping from 4 to 1

**Comment by slava-mitin** [comment]
See availableCalendarFormats option of TableCalendar (but there is no option for 3 weeks):

```
TableCalendar {
  availableCalendarFormats: const {
    CalendarFormat.month: 'Month',  //format: button name
    CalendarFormat.twoWeeks: '2 weeks',
    CalendarFormat.week: 'Week',
  },
}
```

**Comment by edwin-alvarez** [comment]
Right, what I was thinking to do was to add the calendar inside an  SliverPersistentHeader and gracefully reduce the calendar height while the header was shrinking. I finished up changing the design.

**Comment by edwin-alvarez** [comment]
@aleksanderwozniak, Is there any way to implement this?

**Comment by aleksanderwozniak** [comment]
@edwin-alvarez 
If you are fine with jumping between month - 2 weeks - 1 week, then you have three ways to change between them. You can perform the swipe gesture, you can tap on format button inside the header, or you can use `calendarController.swipeCalendarFormat()`.

If on the other hand you want to have weekly increments between each change, than sadly the best you can do right now is settle for using just `CalendarFormat.twoWeeks`, and `CalendarFormat.week` formats.

I might add `CalendarFormat.threeWeeks` in the future, but that would still jump between month (i.e. 5/6 weeks) - 3 weeks - 2 weeks - 1 week.
