### ISSUE TITLE
How can I provide unavailable day data?

### ISSUE THREAD

**Issue by RenatoLucasMota** [aleksanderwozniak/table_calendar#268]
In my case it is not an agenda but just a calendar that I can select a day before or after the current date, but the 'onUnavailableDaySelected' function does not return a date like the 'onDaySelected' function and I would need it to be possible, it is it possible to create a bool to allow selecting previous dates?

**Comment by aleksanderwozniak** [comment]
This has been added in version `3.0.0`. Now `onUnavailableDaySelected` returns the selected day.
