### ISSUE TITLE
Change chevron icons

### ISSUE THREAD

**Issue by OpticNectar** [aleksanderwozniak/table_calendar#27]
Is there a way to change the chevron icons? I haven't seen a way to do it, but everything else is super customizable, so I wasn't sure if it was a hidden thing or something.

Awesome job on this btw!

**Comment by aleksanderwozniak** [comment]
Nice catch!

I improved chevron customization in version `1.1.1`, so just update the package and you are good to go!

**Comment by OpticNectar** [comment]
Awesome, thanks!!!!
