### ISSUE TITLE
[Example] Need using LinkedHashMap instead of Map with DateTime keys

### ISSUE THREAD

**Issue by slava-mitin** [aleksanderwozniak/table_calendar#270]
Hello, Aleksander. Thank you for the incredible calendar!

Provided example uses a map to store events:
`Map<DateTime, List> _events; //class _MyHomePageState`

Map key is DateTime. When it compares with other DateTime it using time. This causes to mismatch DateTime keys with the same date but different time. We can't get map value _events[DateTime] when time part is different.

Example uses DateTime keys produced from one so time of all the keys is the same and this behavior does not appear there. But if i load data from earlier created database and try to get _events[DateTime.now()] - it returns null though _events contains the same date with other time.

LinkedHashMap with custom equals and hashCode avoids using time in keys:
```
_events = LinkedHashMap(
            equals: (a,b) => (a.year == b.year  &&  a.month == b.month  &&  a.day == b.day),
            hashCode: (key) => (key.day * 1000000 + key.month * 10000 + key.year),
          );
```

P.S. 
I found this when trying to show/hide events list if selected day is visible/not visible. I think this might be the default behavior?
  ```
void _onVisibleDaysChanged(DateTime first, DateTime last, CalendarFormat format) {
    if (first.isBefore(_selectedDay)  &&  last.isAfter(_selectedDay)) {
     //show selected day events
    } else {
      //hide selected day events
    }
  }
```

**Comment by aleksanderwozniak** [comment]
This is a great suggestion! I've adapted examples to use `LinkedHashMap`.

As for the `onVisibleDaysChanged` behavior - I am keeping it the way it currently is, as it is a custom logic which will be different for each project based on design.

Thanks!
