### ISSUE TITLE
Text style for days with events

### ISSUE THREAD

**Issue by fstof** [aleksanderwozniak/table_calendar#271]
A useful feature would be to be able to set the text  style of dayz that have events.

This allows us to indicate events on a day without the normal dot marker

**Comment by fstof** [comment]
PR attached #269

**Comment by fstof** [comment]
Hi @aleksanderwozniak 
Any reason why this has not made its way into the 2.3.0 release of the package?

I would really like to not have to point my project to the master branch in pubspec.yaml

**Comment by aleksanderwozniak** [comment]
Hey @fstof 
You will find it alongside some other updates in `2.3.1`
