### ISSUE TITLE
Landscape Calendar Overflow

### ISSUE THREAD

**Issue by chitgoks** [aleksanderwozniak/table_calendar#274]
hi. how can the calendar work without overflow once it is in landscape mode

i tried to use SingleChildScrollView but when i swipe down to scroll, the dropdown selection 2 weeks/monthly/etc gets the event instead.

**Comment by aguilaair** [comment]
I'd also like to get some more info on this. Itried to set the calendar type dynamically but it unfortunately did not work.
```
availableCalendarFormats:
                          MediaQuery.of(context).size.height < 900
                              ? {CalendarFormat.week: 'Week'}
                              : {
                                  CalendarFormat.month: 'Month',
                                  CalendarFormat.twoWeeks: '2 weeks',
                                  CalendarFormat.week: 'Week'
                                },
                      initialCalendarFormat:
                          MediaQuery.of(context).size.height < 900
                              ? CalendarFormat.week
                              : CalendarFormat.month,
```
This is the code I tried

**Comment by fmayumi-tachibana** [comment]
I found a solution, I put the calendar in a listview, maybe it works for you.

**Comment by chitgoks** [comment]
i have not focused on the project since. if you got it to work please post it here and i will close this issue

**Comment by fmayumi-tachibana** [comment]
MediaQuery.of(context).orientation == Orientation.landscape
                ? Container(
                    height: 135,
                    child: ListView(
                        children: <Widget>[_buildTableCalendar(context)]))
                : _buildTableCalendar(context),

**Comment by fmayumi-tachibana** [comment]
```
MediaQuery.of(context).orientation == Orientation.landscape
                ? Container(
                    height: 135,
                    child: ListView(
                        children: <Widget>[_buildTableCalendar(context)]))
                : _buildTableCalendar(context),
```

**Comment by aleksanderwozniak** [comment]
Also using `rowHeight` should do the trick here.
