### ISSUE TITLE
自定义按钮, 触发日历水平滑动

### ISSUE THREAD

**Issue by xfy6238** [aleksanderwozniak/table_calendar#275]
I customize two buttons on the outside and click to realize the left and right sliding of the corresponding calendar, but I did not find the corresponding method. In the vertical direction , I used swipeCalendarFormat(isSwipeUp: false) this method realized. But What should I do in the horizontal direction

**Comment by aleksanderwozniak** [comment]
You can now use `previousPage()` and `nextPage()` for that.
