### ISSUE TITLE
markersBuilder stack order

### ISSUE THREAD

**Issue by dfdgsdfg** [aleksanderwozniak/table_calendar#276]
Can I change the Stack widget's order for a custom marker that is placed in the background?

### as-is

```
[
   MarkesBuilderResult(),   
   DayNumber(),
]
 ---
|    |
 ---
```

### wish
```
[
   DayNumber(),   
   MarkesBuilderResult(),   
]
 ---
| 1 |
 ---
```

**Comment by aleksanderwozniak** [comment]
You can use `CalendarBuilders` and return a `Stack` widget there. This will allow you to freely determine the order in which widgets should be rendered.

**Comment by divinemaredi** [comment]
> You can use `CalendarBuilders` and return a `Stack` widget there. This will allow you to freely determine the order in which widgets should be rendered.

I tried to use `CalendarBuilder` and return a `Stack` widget but I think the below implementation of how I did it is wrong:
 
![Calendar Table Screenshot #4](https://user-images.githubusercontent.com/65621952/108233470-7c317000-714c-11eb-8880-2b9018555008.PNG)

Ideally, I want to achieve something like this:

![Table Calendar Screenshot #5](https://user-images.githubusercontent.com/65621952/108234893-f0b8de80-714d-11eb-8c82-6ce96448901a.jpg)

Where my marker is a round, red container **behind/below** the day number.

So I have a question:

What's the correct implementation of stacking my custom marker (the round, red container) to be **below/behind** the day number?

Thanks in advance!

**Comment by aleksanderwozniak** [comment]
@divinemaredi 
I assume you want to have red background for days that contain events. For this, I would recommend using `dayBuilder` - check if given date has any event, and if true, then return something along these lines:
```dart
return Container(
  decoration: ..., // Your decoration
  child: Center(child: Text('${date.day}')),
);
```
