### ISSUE TITLE
why is todayDayBuilder triggered if selected day is not today?

### ISSUE THREAD

**Issue by chitgoks** [aleksanderwozniak/table_calendar#281]
behavior is weird. if it is named todayDayBuilder then it should be triggered if user selects on the date today, right?
i did a simple print and it gets triggered only if the selected day is not today.

**Comment by aleksanderwozniak** [comment]
This is because selected day has a higher priority than today. You can change that with `renderSelectedFirst: false` inside `CalendarStyle`.
