### ISSUE TITLE
Lock calendar format

### ISSUE THREAD

**Issue by carlinho11** [aleksanderwozniak/table_calendar#282]
I would like to know if it´s possible to configure for the calendar stay with the format "initialCalendarFormat: CalendarFormat.month", so that it is not possible to change the format with gestures?

I appreciate your attention!

**Comment by bisabel** [comment]
If you want make the "changing format button" just disappear, then apply this code:
`headerStyle: HeaderStyle(`
`centerHeaderTitle: true,`
`formatButtonVisible: false,`
`...`
`)`
and set the format you want with the `initialCalendarFormat : CalendarFormat.month`
