### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by khaledJabr** [aleksanderwozniak/table_calendar#283]
Hello,

Thanks for the great project! i'm very excited to use it. I'm new to dart/flutter and I want to experiment with the package by running the example code, but I keep getting the following error message

```
Compiler message:
lib/main.dart:147:22: Error: The argument type 'void Function(DateTime, List<dynamic>, List<dynamic>) Function()' can't be assigned to the parameter type
'void Function(DateTime, List<dynamic>)'.
 - 'DateTime' is from 'dart:core'.
 - 'List' is from 'dart:core'.
      onDaySelected: () => _onDaySelected,
                     ^
lib/main.dart:236:22: Error: The argument type 'Null Function(DateTime, List<dynamic>, dynamic)' can't be assigned to the parameter type 'void
Function(DateTime, List<dynamic>)'.
 - 'DateTime' is from 'dart:core'.
 - 'List' is from 'dart:core'.
      onDaySelected: (date, events, holidays) {
                     ^
```

Any tips on how to bypass this?

thanks

**Comment by HeXx123321** [comment]
The issue is that the callback function: _onDaySelected takes in only 2 parameters: DateTime first and List Events. List Holidays are not catered for. Going to raise this issue if I cant find it in the issue tracker.

**Comment by aleksanderwozniak** [comment]
Hi, thanks for reporting the problem. `master` branch contains a couple of not published changes, which are incompatible with the latest `2.2.3` version. I've made a separate `2.2.3-stable` branch which contains exactly the same code as published on pub.dev - please check the example project [there](https://github.com/aleksanderwozniak/table_calendar/blob/2.2.3-stable/example/lib/main.dart), or directly on pub.dev [example tab](https://pub.dev/packages/table_calendar/example).
