### ISSUE TITLE
How can i make the day of week and the event margin

### ISSUE THREAD

**Issue by cuong292** [aleksanderwozniak/table_calendar#289]
Hi, first of all thanks for your wonderful library.
Second of all, is there anyway to add some margin between the date of week and the event's dots. It's always on the bottom of the  circle bound and it's hard to see.thank you

**Comment by aleksanderwozniak** [comment]
Hi, in `CalendarStyle` you will find properties like `cellMargin`, `markersPositionBottom` and `markersAlignment`. Play around with these and you should get some nice results.
