### ISSUE TITLE
Format of days of week/header

### ISSUE THREAD

**Issue by OpticNectar** [aleksanderwozniak/table_calendar#29]
Sorry, another question.

Is there a way to change the format of the days of the week? I need it to just be the letter and not the first three. Also, I don't need it, but it probably wouldn't be bad to give people a build or options to change the format of the header too.

**Comment by aleksanderwozniak** [comment]
#31 adds format skeletons to Table Calendar version `1.1.3`.

You can find them in `HeaderStyle` and `DaysOfWeekStyle`.

Here is an official guide how to use `DateFormat` skeletons:
https://docs.flutter.io/flutter/intl/DateFormat-class.html

**Comment by OpticNectar** [comment]
@aleksanderwozniak Awesome thanks!

One question though, it may just be me, but I actually need to modify the header and weekday names for my project a little more. For example I need to make the header text uppercase and I need the week days to only be the first letter. What do you think passing the date into a function that lets the user modify the header/weekday text to their heart's content and return a string?

For Example:

```
TableCalendar(
  headerStyle: HeaderStyle(
    headerText: (dynamic locale, DateTime focusedDay) {
      return DateFormat.yMMMM(locale).format(focusedDay).toString().toUpperCase();
    }
  )
)
```

**Comment by aleksanderwozniak** [comment]
That's actually a much better idea! I'll make appropriate adjustments and push an update.

**Comment by coolmarat** [comment]
Can somebody provide an example how to localize days of week names to languages that not supported by default pls?

**Comment by aleksanderwozniak** [comment]
@coolmarat 
Let's keep one problem per one issue. Yours is not related to the original question, so you should open a new issue.

**Comment by aleksanderwozniak** [comment]
@OpticNectar 

I've added `TextBuilder`s with package version `1.1.4`. It should allow for complete text customization - both for Header and DOW panel.

Code below should do what you wanted to achieve:
```dart
TableCalendar(
  headerStyle: HeaderStyle(
    titleTextBuilder: (date, locale) => DateFormat.yMMMM(locale).format(date).toUpperCase(),
  ),
  daysOfWeekStyle: DaysOfWeekStyle(
    dowTextBuilder: (date, locale) => DateFormat.E(locale).format(date)[0],
  ),
),
```

**Comment by OpticNectar** [comment]
Perfect!!! Thanks a million!!!

**Comment by faridkzadeh** [comment]
Could you please provide me an example of how to change the format of the header? I like to have the first 3 letters. Not sure, if my problem related to this issue. When I change the language from "En" to "Fa". The format header is changing from 
<img width="311" alt="Screen Shot 2020-09-30 at 11 45 22 AM" src="https://user-images.githubusercontent.com/6954665/94708398-8c1df400-0312-11eb-87c0-2bfa04327c33.png">
the first 3 letters -in En - to full name -in Fa.
