### ISSUE TITLE
How to get changed month first date?

### ISSUE THREAD

**Issue by ShanmugavelGK** [aleksanderwozniak/table_calendar#290]
Hi dear, I want the name of the month when I change the month. Tell me a little bit about how to pick up.

**Comment by sushmitkumarpatil** [comment]
You can get it in "focusedDay" of calendar controller in date time format. For example:

Create a calendar controller `CalendarController _calendarController;`.

You can get selected months first date in onVisibleDaysChanged event.
 
`TableCalendar(
      calendarController: _calendarController,
      onVisibleDaysChanged: (start, end, format) {
        print(_calendarController.focusedDay);
      },
    );`
