### ISSUE TITLE
HeaderStyle - showLeftChevron 

### ISSUE THREAD

**Issue by Pawelek55** [aleksanderwozniak/table_calendar#291]
I want to ask about keys: showLeftChevron and showRightChevron in HeaderStyle class.
In repo is available, but in table_calendar: ^2.2.3 in class HeaderStyle i can't find this booleans?

**Comment by aleksanderwozniak** [comment]
You can find those in version 2.3.2 as `leftChevronVisible` and `rightChevronVisible`.
