### ISSUE TITLE
dayBuilder limitation

### ISSUE THREAD

**Issue by Etsurosu** [aleksanderwozniak/table_calendar#293]
`Hi,` 
First of all, thanks for your awesome work!

I'm currently using dayBuilder which, depending on a value in the state of the View (which contains the calendar) and for a certain number of days (while it's less than the value in the state) I must show a different background. 
So I have a value in my view builder that I increment for each day built (since we can't use setState during build in flutter)
Until here every thing is working fine.
The fact is if for any reason the calendar is rebuilding, this part of code doesn't work anymore since the view didn't rebuild.

Hope I've been clear, Check the small code snipet below:

```
View
void initState() {
    workDays = 10; // example value
    super.initState();
  }
  Widget build(BuildContext context) {
  int showedWorkDays = 0; // need a way to reset this value on every calendar rebuild
  TableCalendar(
    calendarController: calendarController,
    locale: 'fr_FR',
    startingDayOfWeek: StartingDayOfWeek.monday,
    availableCalendarFormats: const {
      CalendarFormat.month: '',
    },
    builders: CalendarBuilders(
       dayBuilder: (context, date, events) {
       if (showedWorkDays < workDays) {
         type = 3;
         showedWorkDays++;               
         return CalendarWorkDay(); // my custom day widget
       }
       return CalendarDay(); // my custom day widget
     },
  );
}
```

Thanks for your time and your understanding.

If there's an other way to achieve this, please let me know.

**Comment by Etsurosu** [comment]
Well, I made my own calendar with a similar implementation, I fixed my issue by passing to the dayBuilder function a boolean (isLastDay) for the current month, for example if I pass august(2020) as current month, the last day is 2020/07/06
if the last day is being created the is LastDay is true.

On this value == true, I reset the showedWorkDays to 0 once the day is built.

PS: I also provide the current month index to know if it is the current showed month (in the case of august this value is 8)

So thanks again for your work, I won't use your table_calendar for my actual projet but I'll probably use it again later in other and future projects

**Comment by aleksanderwozniak** [comment]
It feels like you could just check if `date.day < workDays` to get that behavior. Anyway, closing since issue is resolved.
