### ISSUE TITLE
Is this UI possible with the package?

### ISSUE THREAD

**Issue by zyllus17** [aleksanderwozniak/table_calendar#295]
Hi @aleksanderwozniak 
I was looking for a Calendar package to make a little complicated design in Flutter. I want to make a design like this for my app and I am finding it really difficult to make the months and year like the design below as well as the design of the weekly calendar like the one shown below? Is it possible to do this with your package? If yes, then can you plz tell me how to achieve the weekly calendar design and the month and year part of the screen, I have completed the other parts as of now.
![WhatsApp Image 2020-07-23 at 7 50 57 PM (1)](https://user-images.githubusercontent.com/50977126/90399498-a8decf00-e0b8-11ea-8bdb-bd9c65f43299.jpeg)

**Comment by code-gene** [comment]
You can always customize the calendar, I customized it for my project.

**Comment by zyllus17** [comment]
> make the months and year like the design below as well as the design of the weekly calendar like the one shown below.

I want to know how to do it. If you have an open source or any stuff where I can look for reference, it would be great.

**Comment by aleksanderwozniak** [comment]
@zyllus17 
Your monthly design is pretty much built-in, you just need to hide the default calendar header and provide a custom one - this [gist](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1) will be helpful. Of course you need to customize the style to match the design.

For weekly design lock the calendar format to `CalendarFormat.week`, hide the default header, and use `CalendarBuilders` to provide custom implementation for date cell UI.
