### ISSUE TITLE
Calendar day selection broken if built in release mode

### ISSUE THREAD

**Issue by dzsonni** [aleksanderwozniak/table_calendar#297]
Example app build in release mode without shrinking, causes weird rectangles to appear on day selection
[√] Flutter (Channel master, 1.21.0-10.0.pre.54, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.21.0-10.0.pre.54 at D:\Development\flutter
    • Framework revision d9637ed784 (8 days ago), 2020-08-11 23:51:03 -0400
    • Engine revision 6381b1511b
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\Development\AndroidSDK
    • Platform android-30, build-tools 30.0.1
    • Java binary at: D:\Development\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Development\AndroidStudio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

![table_calendar](https://user-images.githubusercontent.com/6988242/90766442-32c6ac00-e2f4-11ea-9aa9-07290fc53b9f.gif)

**Comment by aleksanderwozniak** [comment]
Hi, can you try running example code from [2.2.3 branch](https://github.com/aleksanderwozniak/table_calendar/blob/2.2.3-stable/example/lib/main.dart)?
