### ISSUE TITLE
dark mode and moth and year input. 

### ISSUE THREAD

**Issue by Vinayak27Mobility** [aleksanderwozniak/table_calendar#298]
Hi,

Is there any API to change to color of dots when referring to events. 
By default its black, I want to show white when app is in dark mode. 

----------------------------------------------------------------------------------------

Also is there any feature we can use to take input in month and year format just in case want to take user, calendar date six months down the line or 1 year then as per current implementation user has to scroll 6 or 12 times.

**Comment by zcooler** [comment]
```
return TableCalendar(
...
  calendarStyle: CalendarStyle(
    markersColor: Colors.deepOrange,
...
```

https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle/markersColor.html

**Comment by Vinayak27Mobility** [comment]
Thx @zcooler
