### ISSUE TITLE
how to prevent initial day selection (initialSelectedDay: null)

### ISSUE THREAD

**Issue by eldarkk** [aleksanderwozniak/table_calendar#299]
I want to prevent from initial day selecting. Don't tell its impossible please.

**Comment by aleksanderwozniak** [comment]
This is currently not supported, I'll add it to the list. Using null `initialSelectedDay` will change it into `DateTime.now()` internally. A potential workaround would be to use `renderSelectedFirst: false` inside `CalendarStyle`, but whether that helps you really depends on the reason you don't want the initial day selection.

**Comment by aleksanderwozniak** [comment]
@eldarkk 
Actually, inside `CalendarStyle` you can set `highlightSelected: false` - this will prevent visual highlighting of the selected day.

**Comment by aleksanderwozniak** [comment]
Version `3.0.0` allows null `selectedDay` - check this [example](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-dev/example/lib/pages/events_example.dart) for more details.

**Comment by dannu-uipep** [comment]
unable to add 3.0.0 in my pubspec file and the link you provided is broken. Please let me know what are the alternative solutions.
Thanks
