### ISSUE TITLE
DaysOfWeekStyle has no decoration property in pub package

### ISSUE THREAD

**Issue by iducool** [aleksanderwozniak/table_calendar#300]
I just downloaded package from pub and it's version is 2.2.3. I review that DaysOfWeekStyle has no decoration property however, Github code in master has this property available. I am assuming that property is added after package release. I can download code from github and use it howerver, I would prefer to get it from pub. Any plan to release new package?

Thanks a lot for this really awesome package.

**Comment by aleksanderwozniak** [comment]
That's correct - this is a part of new major release. For now, if that decoration property isn't a must for you, I would suggest using pub version as it is stable / not prone to unexpected changes.

**Comment by iducool** [comment]
To match with UI of my app, I want to set the background color of complete box of "DaysOfWeek". If there is another way of achieving it then I can use that. 
Sorry to ask you again but any tentative date of releasing new package? Just asking so, I can decide to wait or fallback on code.

**Comment by aleksanderwozniak** [comment]
Quick bump - you will find it now in version `2.3.1`
