### ISSUE TITLE
Calling the buildEventList from another widget

### ISSUE THREAD

**Issue by northonBarbosa** [aleksanderwozniak/table_calendar#301]
Hi!
How can I call the buildEventList from another Stateful Widget to return me the event list?

**Comment by aleksanderwozniak** [comment]
Hi Northon,

To get the event list you will need to use callbacks built into TableCalendar. Once you have the data, it is simply a matter of lifting state up and supplying that data into your other widget. You can see this in code in example project - `buildEventList` is a separate widget, non related to TableCalendar - it simply uses data obtained from TableCalendar.

**Comment by northonBarbosa** [comment]
Thanks!!
