### ISSUE TITLE
reduce space between days

### ISSUE THREAD

**Issue by qlssk8737** [aleksanderwozniak/table_calendar#303]
<img width="35" alt="Screen Shot 2020-08-27 at 5 28 34 PM" src="https://user-images.githubusercontent.com/65214196/91417044-2bbb1300-e88b-11ea-8bed-396a31361e33.png">

Is it possible to reduce space between days? I tried to do it with dayBuilder, but didn't work.

**Comment by aleksanderwozniak** [comment]
Try setting `rowHeight` to a desired value, this should solve it.
