### ISSUE TITLE
Delete the small gap between two days in a row

### ISSUE THREAD

**Issue by RobinLbt** [aleksanderwozniak/table_calendar#308]
I'm using the CalendarBuilders class to build custom days.
I'm just returning a red container without any padding or margin, but I still have a small white line (a small gap) between each day in a row. Is there a way to get rid of it ?

![Screenshot_20200908-192705](https://user-images.githubusercontent.com/25883677/92509009-d7f4e600-f209-11ea-9a67-4a0b88df4882.jpg)

**Comment by aleksanderwozniak** [comment]
This seems to be an issue within the Flutter itself. Here is a quick snippet using only built-in Flutter widgets:

```dart
GridView.builder(
  itemCount: 30,
  gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 7),
  itemBuilder: (context, i) {
    return Container(
      color: Colors.blue,
      child: Center(
        child: Text('${i + 1}'),
      ),
    );
  },
),
```

This doesn't happen always though. If you set `crossAxisCount` to 6 for example, the lines will disappear.

I'm afraid this issue is outside the scope of this package. You will need to wait for an official fix.

**Comment by mester9000** [comment]
Isn't that because the GridView has a basic padding? You can set the padding attribute to EdgeInsets.all(0).

**Comment by aleksanderwozniak** [comment]
GridView's padding applies to its outer container, not to its children. This small gap is unrelated to any padding setting.

**Comment by RobinLbt** [comment]
This is a strange behaviour and I didn't found any work around for the moment. I hope this will be fix soon

**Comment by aleksanderwozniak** [comment]
To anyone facing this problem: #382 might be a potential workaround for now.
