### ISSUE TITLE
Running example code gives message "Your app isn't using AndroidX"

### ISSUE THREAD

**Issue by carpiodanielj** [aleksanderwozniak/table_calendar#309]
The following message appears when running the example code found in `example `folder.
`[!] Your app isn't using AndroidX.`
`To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY .`

### flutter doctor result (run flutter doctor in terminal)
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [VersiÃ³n 10.0.17134.590], locale es-PE)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.6)
    X Unable to determine bundled Java version.
[√] Android Studio (version 4.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by aleksanderwozniak** [comment]
That's correct, AndroidX migration is planned with next release.
