### ISSUE TITLE
The argument type 'TableCalendar' can't be assigned to the parameter type 'Widget'.

### ISSUE THREAD

**Issue by Saiprasad122** [aleksanderwozniak/table_calendar#310]
Hi everyone,
I am getting this error while I use the table calendar plugin in flutter.
Please help if anyone got this error and solved it

**Comment by aleksanderwozniak** [comment]
This sounds a bit strange. Can you please paste your code here? Also, check out [example project](https://github.com/aleksanderwozniak/table_calendar/blob/2.2.3-stable/example/lib/main.dart) for details on how to use TableCalendar.
