### ISSUE TITLE
Open calendar view in popup with listview

### ISSUE THREAD

**Issue by Gaurangs** [aleksanderwozniak/table_calendar#316]
Hello,

- Is it possible to show and hide calendar on click button?
- Can I display calendar on popup window?
- I want to show the calendar in list format.

**Comment by aleksanderwozniak** [comment]
Hi.

1. Yes, you can build your widget tree conditionally. Use some boolean variable to toggle TableCalendar's visibility.
2. Yes, simply use `showDialog(...)` or `Navigator.push(...)`  and supply TableCalendar as a child.
3. I'm not sure what you mean about the list format. Perhaps you want something like [this](https://raw.githubusercontent.com/aleksanderwozniak/table_calendar/assets/table_calendar_styles.gif)? If that's the case then feel free to check out the [example project](https://github.com/aleksanderwozniak/table_calendar/blob/2.2.3-stable/example/lib/main.dart).
