### ISSUE TITLE
Refresh data when add or delete items

### ISSUE THREAD

**Issue by Nighthawk11120** [aleksanderwozniak/table_calendar#317]
It seems the only way to refresh the data shown for the selected day is to add a new item and then press the day you want again to see the changes.  How could I make the changes automatically change, without having to press the day again to see the changes?  Please note that I am using Cloud Firestore.

Thank you in advance.

**Comment by aleksanderwozniak** [comment]
You need to rebuild the widget with new data. Check out this [gist](https://gist.github.com/aleksanderwozniak/e9eb98bf28bd9fbb336039e1936c59aa) for reference.
