### ISSUE TITLE
The day header formate

### ISSUE THREAD

**Issue by faridkzadeh** [aleksanderwozniak/table_calendar#320]
I am new on the Flutter. When I change the language from "En" to "Fa"(Farsi). The day name format header is changing from displaying 3 letters to displaying the whole name. Is there a way that I can use FittedBox to reduce the text size? or just display the first later of the days? Just want to make it look nice! Really apprentice your help! 
Here is a screenshot. Some letters jump to the second line.

<img width="311" alt="Screen Shot 2020-09-30 at 11 45 22 AM" src="https://user-images.githubusercontent.com/6954665/94722300-1d966180-0325-11eb-892d-ddea4465ba04.png">

<img width="316" alt="Screen Shot 2020-09-30 at 11 45 09 AM" src="https://user-images.githubusercontent.com/6954665/94722714-aa411f80-0325-11eb-802b-753493a7c177.png">

**Comment by aleksanderwozniak** [comment]
Hi. Have a look at `DaysOfWeekStyle` - you will find styling options there.

You can use `dowTextBuilder` for String manipulation - for example truncate each day of the week to only 3 letters. Alternatively, you can set font size via `weekdayStyle` and `weekendStyle`.

**Comment by faridkzadeh** [comment]
> Hi. Have a look at `DaysOfWeekStyle` - you will find styling options there.
> 
> You can use `dowTextBuilder` for String manipulation - for example truncate each day of the week to only 3 letters. Alternatively, you can set font size via `weekdayStyle` and `weekendStyle`.

Thanks, I really appreciate your input. Is there a way to use FittedBox? I rather not use 'font-size' because not fair for a larger display. Truncate day to only 3 letters does not have meaning in other languages (Farsi and Arabic). I tried to use wordSpacing but did not help.

**Comment by aleksanderwozniak** [comment]
Ah, that would explain why the default formatting didn't truncate it.

Actually yes, you can use the `FittedBox`. In `CalendarBuilders` there is `dowWeekdayBuilder` which will allow you to use any custom widget for days of week. You can use separate `dowWeekendBuilder` as well if needed.

**Comment by faridkzadeh** [comment]
Got it! Thank you so much!
