### ISSUE TITLE
How can I make table_calendar's UI better in landscape/on a tablet?

### ISSUE THREAD

**Issue by tneotia** [aleksanderwozniak/table_calendar#321]
I've just finished setting up my calendar screen using this plugin and it looks great on mobile:
<details>

![Simulator Screen Shot - iPhone 11 Pro - 2020-09-30 at 20 24 23](https://user-images.githubusercontent.com/50850142/94753019-ef337900-035a-11eb-9cce-f8366f4898b3.png)
</details>
However, as soon as the user rotates to landscape or uses a tablet, it just becomes a mess: 
<details>

![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-09-30 at 20 24 56](https://user-images.githubusercontent.com/50850142/94753040-02464900-035b-11eb-8913-9dfb39d09e1e.png)
</details>
Is this problem intrinsic with the plugin itself or am I doing something wrong? If code is necessary I can add it, just wanted to know what the root cause of this issue is.. I am using custom builders if that helps any.

**Comment by tneotia** [comment]
Update: I seem to have fixed it by setting the rowHeight property to be 60, it might need tweaking for other implementations but that value looks good for me on landscape mode on a phone. I still need to test on a tablet but I think it will look the same, closing...

**Comment by aleksanderwozniak** [comment]
Wrapping the widget with a `SizedBox` might also be helpful here, although it really depends on what design you are going for.

**Comment by tneotia** [comment]
That's a good idea, I'll try that out too. Thanks!
