### ISSUE TITLE
Remove Chevron Icons

### ISSUE THREAD

**Issue by mester9000** [aleksanderwozniak/table_calendar#322]
Is it possible to remove the left and right chevrons? 
If I write this code :
          leftChevronIcon: Icon(null),
          rightChevronIcon: Icon(null)

It makes them disappear but they are still clickable. Is there a way to make them disappear and unclickable?

**Comment by aleksanderwozniak** [comment]
Hi, you will have to make a custom widget for calendar header. You can use this [gist](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1) for reference.

**Comment by mester9000** [comment]
Thanks!
