### ISSUE TITLE
setSelectedDay() in Dev branch

### ISSUE THREAD

**Issue by tazhar** [aleksanderwozniak/table_calendar#324]
Thanks for this package.

I have just switched to Dev to avoid the blank space during swipe as suggested in #55 

Is there any equivalent way to setting the date using the controller in the Dev branch.

My "Go to Today" button was using the following line on the Master branch:

`_calendarController.setSelectedDay(todayDate, animate: true, isProgrammatic: true);`

**Comment by aleksanderwozniak** [comment]
Hi, check this [example](https://github.com/aleksanderwozniak/table_calendar/blob/e7d4f34783e47e89d86bc4b289f39ddbefc66c14/example/lib/pages/complex_example.dart#L275). I also highly recommend migrating from `dev` to `3.0.0-dev` branch, on which this example is based.

**Comment by tazhar** [comment]
> Hi, check this [example](https://github.com/aleksanderwozniak/table_calendar/blob/e7d4f34783e47e89d86bc4b289f39ddbefc66c14/example/lib/pages/complex_example.dart#L275). I also highly recommend migrating from `dev` to `3.0.0-dev` branch, on which this example is based.

Thanks. I will use this example in the next build.
