### ISSUE TITLE
Show/Hide Weekend days

### ISSUE THREAD

**Issue by pavlos-elpidorou** [aleksanderwozniak/table_calendar#326]
Hello,
Is there a way to show/hide calendar weekend days on demand?

Thanks

**Comment by aleksanderwozniak** [comment]
Hi.
Currently this feature is not supported. If you want to, you can freely change which days act as "weekend days", as well as set starting day of the week, but there will always be seven visible days per each week.

**Comment by paulelpidorou** [comment]
is there an easy workaround for me to achieve this? i really need this feature :(

**Comment by aleksanderwozniak** [comment]
@paulelpidorou 
You could technically force the widget to clip at Friday width-wise; if you provide a [custom calendar header](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1) along with it, it should look and work as intended.

I'll probably add official support of this feature in the future, but can't give you any ETA at the moment.

**Comment by paulelpidorou** [comment]
Ok thanks. Will try it out 😊

**Comment by pavlos-elpidorou** [comment]
> 
> 
> @paulelpidorou
> You could technically force the widget to clip at Friday width-wise; if you provide a [custom calendar header](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1) along with it, it should look and work as intended.
> 
> I'll probably add official support of this feature in the future, but can't give you any ETA at the moment.

**Comment by pavlos-elpidorou** [comment]
@aleksanderwozniak i have created a pull request with this functionality. Check it out
https://github.com/aleksanderwozniak/table_calendar/pull/333
