### ISSUE TITLE
Only one event appears per date instead of multiple. 

### ISSUE THREAD

**Issue by ChristianConstantNel** [aleksanderwozniak/table_calendar#327]
Hi, I'm having a problem where the calendar is only showing one event per day, even with multiple events on that day. 

Below is my mapping function for the events. Each timeStamp is unique, and when printing the keys and the values of the events map everything shows up. 

Map<DateTime, List<dynamic>> _mapEvents() {
    Map<DateTime, List<dynamic>> events = {};
    for (dynamic game in widget.state.allGames) {
      if (game.status != GameStatus.declined)
        events.addAll({
          game.timestamp.toDate(): [game]
        });
    }
    return events;
  }

Any advice would be much appreciated.

**Comment by aleksanderwozniak** [comment]
Hi, 

It looks like you are adding only one event to every day.

You will need to transform `game.timestamp.toDate(): [game]` into `DateTime(year/month/day): [game1, game2, game3]` format - make a sublist of games that share the same date, and then pass that into `events`.

Check out example project for more:
https://github.com/aleksanderwozniak/table_calendar/blob/a18e93905ba8285e03e9ecf3925aac16a1269cd1/example/lib/main.dart#L62

**Comment by ChristianConstantNel** [comment]
Ah ha! That makes perfect sense! Thank you for the reply. 

Also your packages is literally one of my favourites and always a must have in my projects.

Keep up the great work!
