### ISSUE TITLE
Events Range Support

### ISSUE THREAD

**Issue by danagbemava** [aleksanderwozniak/table_calendar#329]
Does this package have support for displaying events over a range of days? 
Eg, if I have an event that spans a couple of days, how do I go about displaying that?

**Comment by aleksanderwozniak** [comment]
You would need to transform your data, so that each of those days points to that event.

`Event: [DateA, DateB, DateC]` needs to become `DateA: [Event, ...], DateB: [Event, ...], DateC: [Event, ...]`.

Note that each of those days can contain additional events.

**Comment by aleksanderwozniak** [comment]
Linking to #160
