### ISSUE TITLE
Feature request: Let todayColor override selectedColor, a new option?

### ISSUE THREAD

**Issue by sgon00** [aleksanderwozniak/table_calendar#33]
First, thank you very much for this advanced calendar package. Best one I can find so far. 

Now, my feature request is: Is that possible to provide an option to let todayColor override selectedColor? I think that is more native.

So far, I am using the following modified code: 

```dart
  Decoration _buildCellDecoration() {
    if (isToday) {
      return BoxDecoration(
        shape: BoxShape.circle,
        color: calendarStyle.todayColor,
      );
    } else if (isSelected) {
      return BoxDecoration(
        shape: BoxShape.circle,
        color: calendarStyle.selectedColor,
      );
    } else {
      return BoxDecoration(shape: BoxShape.circle);
    }
  }
```

Thanks a lot.

**Comment by aleksanderwozniak** [comment]
Added with #39.

Use `renderSelectedFirst` property of `CalendarStyle` to determine what should have a higher rendering priority.
