### ISSUE TITLE
The named parameter 'vsync' isn't defined.

### ISSUE THREAD

**Issue by noveleven** [aleksanderwozniak/table_calendar#330]
The named parameter 'vsync' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'vsync'.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale zh-Hans)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
[✓] Proxy Configuration
[✓] Connected device (1 available)

• No issues found!

**Comment by KishoreKittu467** [comment]
How did you solve it? this error is showing up for me as well!

<img width="925" alt="Screenshot 2021-02-10 at 10 23 23 AM" src="https://user-images.githubusercontent.com/23329312/107466442-03e61000-6b8a-11eb-9dce-dd3f68efc6dc.png">

**Comment by aleksanderwozniak** [comment]
@KishoreKittu467 
This is most probably IDE caching issue. Simply restart your IDE to solve it.

**Comment by KishoreKittu467** [comment]
Thanks @aleksanderwozniak it worked with similar answer from [here](https://stackoverflow.com/a/63584239/7349053) (1st step is not necessary). Just restarting IDE didn't work though. Hope it is helpful for others also 🙏🏻
