### ISSUE TITLE
Switching between the weeks

### ISSUE THREAD

**Issue by melwinlobo18** [aleksanderwozniak/table_calendar#332]
Thanks for the awesome package.

Is there any way to navigate to the next and the previous weeks? The buttons on the header do that (I have disabled the header for my project) but I was wondering if we wanted to do it manually using the "forward" and "backward" buttons, how should we do it?

**Comment by aleksanderwozniak** [comment]
Hi.

This should be helpful: https://github.com/aleksanderwozniak/table_calendar/issues/319

**Comment by melwinlobo18** [comment]
Thank you 😀
