### ISSUE TITLE
How to scroll to specific month or year

### ISSUE THREAD

**Issue by nvalakunde** [aleksanderwozniak/table_calendar#334]
Suppose I have list of months and year after selecting one of the month or year how to go to particular month of year of month.

**Comment by aleksanderwozniak** [comment]
You can use `calendarController.setFocusedDay(...)` if you want to simply navigate to a particular month/year, or use `calendarController.setSelectedDay(...)` for the same + selecting the given day.

**Comment by nvalakunde** [comment]
Thank you for the quick response,
I need to add something with this solution.
We need to add 
`initialSelectedDay: specificdaytotrack,`
to calendar widget
