### ISSUE TITLE
Select today's date by default

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#335]
First of all thanks for this awesome library. It works great but it doesn't select the current day when I display it. The `onDaySelected` works fine but it doesn't trigger the first time.

For example, you can see that I displayed the calendar table here but it shows no events for today:
<img width="370" alt="Screenshot 2020-10-16 at 17 36 33" src="https://user-images.githubusercontent.com/5629919/96278824-40d43880-0fd6-11eb-9c40-965a7aea753b.png">

I need to click again on today's date to display the events:
<img width="368" alt="Screenshot 2020-10-16 at 17 36 51" src="https://user-images.githubusercontent.com/5629919/96278844-4af63700-0fd6-11eb-97dc-a4124b035b2e.png">

**Comment by aleksanderwozniak** [comment]
Check out this line in example project, it does exactly what you want: https://github.com/aleksanderwozniak/table_calendar/blob/dde2919dad1d136c740465d6f538361932aea446/example/lib/main.dart#L108

You basically need to predefine your `selectedEvents` with data extracted from `events`. Use your initial selected day (`DateTime.now` is default) as a key.

**Comment by erperejildo** [comment]
thanks, that worked
