### ISSUE TITLE
[dev branch] PageView use animateToPage and nextPage with exception caught by rendering library

### ISSUE THREAD

**Issue by meritozh** [aleksanderwozniak/table_calendar#336]
Cannot use `Curves.decelerate`, otherwise it will throw rendering exception in my demo.

https://github.com/aleksanderwozniak/table_calendar/blob/0fb806a111d87a42a60745ffb463499e9d74a904/lib/src/calendar_controller.dart#L256

https://github.com/aleksanderwozniak/table_calendar/blob/0fb806a111d87a42a60745ffb463499e9d74a904/lib/src/calendar_controller.dart#L264

https://github.com/flutter/flutter/issues/47730#issuecomment-612625213

**Comment by aleksanderwozniak** [comment]
Does it happen when tapping on left/right arrow in calendar's header, or do you run into this issue elsewhere?

**Comment by meritozh** [comment]
> Does it happen when tapping on left/right arrow in calendar's header

Yes.

> or do you run into this issue elsewhere?

No.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L262

Here, delta is greater than `precisionErrorTolerance` because it's a upside-down `f(t) = t²` parabola

I just change it to `easeIn`, then exception gone.

**Comment by aleksanderwozniak** [comment]
Thanks for letting me know. I haven't run into this problem myself, but I've replaced the default curves to `easeOut`, which has a similar feeling to `decelerate`. This way the problem shouldn't appear anymore.
