### ISSUE TITLE
Feature request: Display current calendarFormat instead of _nextFormat(), a new option?

### ISSUE THREAD

**Issue by sgon00** [aleksanderwozniak/table_calendar#34]
I feel the current behavior is kinda weird. It always displays the `_nextFormat()`. I modified the code for now. I am currently using

```dart
String get formatButtonText => _availableCalendarFormats[calendarFormat];
```

in class CalendarLogic.

Would you like to provide a new option? Otherwise, I will have to modify the underlying package code. Thanks a lot.

**Comment by sgon00** [comment]
After the modification of #33 and this #34 (plus adding Chinese lunar calendar by hacking the code again), it will look like the following (I feel that is more nature):

![demo_s](https://user-images.githubusercontent.com/1555508/56136480-7523fe80-5fc5-11e9-8356-b09bcd1907a3.gif)

**Comment by aleksanderwozniak** [comment]
Sure! I'll add appropriate config options for both #33 and this issue.

Did you have to modify the source code for lunar calendar? Looking at the gif, it seems to me that you could just use [Custom Builders](https://pub.dartlang.org/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html) instead.

**Comment by aleksanderwozniak** [comment]
Added with #39.

Update Table Calendar to version `1.2.0`, then set `formatButtonShowsNext` property of `HeaderStyle` to false, and you've got it!

**Comment by sgon00** [comment]
@aleksanderwozniak thank you very much for adding the new options for this issue and issue #34. Sorry about the late reply. I just tried this package and then was busy on some other works. By following your suggestion, I also tried to add lunar calendar with just custom builders instead, it works very well. 
I just get one more question, how can I make the state go back to today view (make today selected) regardless which visible view I am on? I failed to find a way so far. 
Thank you very much for your help.

**Comment by aleksanderwozniak** [comment]
I am glad you like it!

Currently there is no option of going back to "today", but I have it on my todo-list, so I'll definitely implement it in near future.

**Comment by sgon00** [comment]
@aleksanderwozniak thank you very much for the quick reply. How can I get informed when this "go back to today" feature implemented? Can you (or I) open another issue for this feature so that I can subscribe it? Cheers. 😀👍

**Comment by aleksanderwozniak** [comment]
@sgon00 
Yes, you can (and should) open a new issue for this feature :)
