### ISSUE TITLE
How to set events in onCalendarCreated method because I need first and last date of canlendar to get the events

### ISSUE THREAD

**Issue by hirunsr** [aleksanderwozniak/table_calendar#341]

**Comment by aleksanderwozniak** [comment]
1) Store `events` variable in parent widget
2) Pass `events` as a property to TableCalendar
3) Inside `onCalendarCreated`:
- obtain events using `first` and `last`
- assign them to `events` variable
- wrap above in `setState()` (you might also need to wrap all of that in `SchedulerBinding.instance.addPostFrameCallback()`)

That should point you in the right direction.

**Comment by illuminated** [comment]
Just wanted to add an alternative solution to this as I had a similar problem. I'm pulling my events from database and I wanted to pull the current month's events on initializing the calendar widget (I'm starting with the full month view) and therefore I had to create to DateTime variables:
```
DateTime _firstDayCurrentMonth = DateTime.utc(DateTime.now().year, DateTime.now().month, 1);

DateTime _lastDayCurrentMonth = DateTime.utc(DateTime.now().year,DateTime.now().month+1, 1).subtract(Duration(days: 1));
```
and that's how I got my query boundaries for pulling the current month's events.
