### ISSUE TITLE
importing problems

### ISSUE THREAD

**Issue by code-gene** [aleksanderwozniak/table_calendar#343]
I am importing table_calender package in the same way as mentioned but it is not getting imported properly, header file shows an error that no such URI exists.

Between I have tried every  possible methods like restarting the editor and all, all other packages are working fine for me only this package is causing troubles.

**Comment by aleksanderwozniak** [comment]
Check in `pubspec.lock` file if the package is listed there, and if so - which version.
If you are using VSCode, try running `flutter pub get` in the terminal.

**Comment by code-gene** [comment]
`table_calendar:
    dependency: "direct main"
    description:
      name: table_calendar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"`

**Comment by code-gene** [comment]
![studio64_nJUC0tTX1F](https://user-images.githubusercontent.com/72328725/98493228-f0ac6700-225f-11eb-85ca-3425643f969c.png)

**Comment by Evyl1303** [comment]
try `flutter packages pub cache repair`

**Comment by code-gene** [comment]
It worked for me, Thanks.
