### ISSUE TITLE
NullPointerException / NoSuchMethodError

### ISSUE THREAD

**Issue by Evyl1303** [aleksanderwozniak/table_calendar#344]
NPE/NoSuchMethodError for  `_controller != null && _controller.visibleDays` in `CalendarController.visibleDays (package:table_calendar/src/calendar_controller.dart:39:7)`

**Comment by aleksanderwozniak** [comment]
I'm guessing you are using methods from `CalendarController` before the widget gets build. Try wrapping your code with `SchedulerBinding.instance.addPostFrameCallback()`, so that the widget is built first.

**Comment by Evyl1303** [comment]
Thank you! I'll try that :)
