### ISSUE TITLE
Calendar and Android X

### ISSUE THREAD

**Issue by sandrodisegni** [aleksanderwozniak/table_calendar#345]
Have you fully tested Table Calendar with Android X ? We are trying to migrate a project with your table calendar and we keep getting the Red Screen. We will post the logs but just wanted to make sure you have tried migrating an existing project to know that it should work.

Thanks

**Comment by aleksanderwozniak** [comment]
Correct, migrating a project shouldn't have any issues regarding TableCalendar. Please share your error logs.
