### ISSUE TITLE
How to get the selected day and how could i Holidays in the calendar  

### ISSUE THREAD

**Issue by riyasm449** [aleksanderwozniak/table_calendar#346]

**Comment by aleksanderwozniak** [comment]
You can use `onDaySelected` callback for that - [docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/OnDaySelected.html).

**Comment by riyasm449** [comment]
thanks! and one more help, how to disable dates, the disabled dates should not be selected

**Comment by aleksanderwozniak** [comment]
This trio should get you there:

- [startDay](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/startDay.html)
- [endDay](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/endDay.html)
- [enabledDayPredicate](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/enabledDayPredicate.html)

**Comment by riyasm449** [comment]
can i get any examples pls

**Comment by aleksanderwozniak** [comment]
`startDay` will disable every date before itself. `endDay` will disable every date after itself. Here is an example of `enabledDayPredicate`: https://github.com/aleksanderwozniak/table_calendar/issues/143#issuecomment-550342320
