### ISSUE TITLE
Is there way to detect date change(eg. Nov-11th 11:59pm to Nov-12th 12:am)

### ISSUE THREAD

**Issue by wchen38** [aleksanderwozniak/table_calendar#347]
I notice that if I let the app stay alive until the next day, the calendar won't update the highlighted current date. Is there way to highlight the correct date automatically when the time changes from 11:59pm to 12:00am? Great package btw.

Update:
After playing around with the package more. I ended up using a Stream API on DateTime object, and then listens for the current time to detect the date change. Once the current date changes to the next day, I would trigger a setState on events shown below. In my case, if there are no events on the selected day, I'm triggering a setState with an empty list. Not sure if this is the best way to do this. Let me know if anyone else have other ways to solve this.
```
setState(() {
          _events[_controller.selectedDay] = [];
        });
```

**Comment by aleksanderwozniak** [comment]
Hi there,

That's correct, the widget does not listen to current date changes, so you would need to add it yourself - your approach seems valid to me. I'm not exactly sure why you are setting `_events` to be an empty list, but that of course depends on what you want to achieve.
