### ISSUE TITLE
Removing the calendar formats does not stop the user to change the formate

### ISSUE THREAD

**Issue by faridkzadeh** [aleksanderwozniak/table_calendar#349]
This is a great project with great support! Thank you so much for your effort!
In my project, I have to display the calendar in a monthly format. As you can see in the code I set formatButtonVisible to false.
headerStyle: HeaderStyle(
      formatButtonVisible: false,

But the user still can change the formate to 2weeks or week by scrolling inside the calendar table. Is there a way to force the table format just in monthly format?
Appreciate the help!

![Screen Shot 2020-11-17 at 2 00 34 PM](https://user-images.githubusercontent.com/6954665/99434864-4d052b80-28dd-11eb-8f41-0737a1a89b67.png)

**Comment by aleksanderwozniak** [comment]
You need to use [availableCalendarFormats](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/availableCalendarFormats.html) alongside `formatButtonVisible: false`.

```dart
availableCalendarFormats: {
  CalendarFormat.month: 'Month',
}
```

**Comment by faridkzadeh** [comment]
It worked. Thanks again. I also tried using the below code and that worked as well - just take time until I notice I need to keep it outside of the builder - like _onDaySelected.
_calendarController.setCalendarFormat(CalendarFormat.month);
