### ISSUE TITLE
Day is both unavailable and outside current month, use unavilableBuilder.

### ISSUE THREAD

**Issue by jameswasher** [aleksanderwozniak/table_calendar#350]
If a date is both unavailable and outside the current month, then the builder uses the unavailable builder.  Is there a way to make it use the unavailable builder?

**Comment by aleksanderwozniak** [comment]
I'm guessing you want to use `outsideDayBuilder` when a date is unavailable and outside of current month. This is not achievable with TableCalendar, as `unavailableDayBuilder` has the highest priority and will even overwrite `selectedDayBuilder`.
