### ISSUE TITLE
How to add line for rowcell

### ISSUE THREAD

**Issue by manhlh** [aleksanderwozniak/table_calendar#351]
![download](https://user-images.githubusercontent.com/17887196/99621817-5fa56f00-2a5b-11eb-92a4-7443ac929115.png)
I want add line for each row.  Same below image. You have solution for this ?, i try with code, Tks.
`dayBuilder: (context, date, _) {
          return Container(         
            child: Column(            
              children: [
                Container(
                  padding: EdgeInsets.only(top: 20.0),
                  child: Align(
                    alignment: Alignment.topCenter,
                    child: Text("${date.day}"),
                  ),
                ),
                Divider()
              ],
            ),
          );
        },`

**Comment by aleksanderwozniak** [comment]
In TableCalendar `2.3.1` you will find a new property inside `CalendarStyle` which you can use for that:

```dart
contentDecoration: BoxDecoration(
  border: Border(bottom: BorderSide()), // customize
),
```

You might want to also set `contentPadding: EdgeInsets.zero`.

**Comment by burhanrashid52** [comment]
I am using version `v.3.0.2` and am not able to find `contentDecoration`. Seems like it is replaced with `defaultDecoration`. Now how to set padding to zero because we don't have `contentPadding: EdgeInsets.zero` property anymore. Any alternative ?

**Comment by burhanrashid52** [comment]
> I am using version `v.3.0.2` and am not able to find `contentDecoration`. Seems like it is replaced with `defaultDecoration`. Now how to set padding to zero because we don't have `contentPadding: EdgeInsets.zero` property anymore. Any alternative ?

Got it. It's `cellMargin`
