### ISSUE TITLE
onVisibleDaysChanged not called on flutter 1.22.4

### ISSUE THREAD

**Issue by khangpt** [aleksanderwozniak/table_calendar#353]
is it a issue? Or I make an any mistake ? I use table_calendar: ^2.3.1
Other callback with prefix "on...." are work perfectly, except "onVisibleDaysChanged"

Any suggestion for me? Thanks

**Comment by aleksanderwozniak** [comment]
This seems to be working for me without any issues. Have you checked [example](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart) project? Perhaps it will give you some clue what could be different/missing.

**Comment by marcosanson** [comment]
I see the same issue. Any suggestion?

**Comment by marcosanson** [comment]
I think I found, so I leave here this comment.

If you write the methods with the app running and you try it after an hot refresh, callback will not be fired.
If you exit from screen and go back to calendar it will fire correctly.

I think it's only a hot refresh issue.
Best,

**Comment by khangpt** [comment]
I think this is my mistake when building the project. When I do an clean command, it work fine. Thanks for your support :)

**Comment by aleksanderwozniak** [comment]
Version `3.0.0` now properly updates all callbacks during hot reload.
