### ISSUE TITLE
have a problem whit month on tableCalendar

### ISSUE THREAD

**Issue by demiantriebl** [aleksanderwozniak/table_calendar#354]
The following NoSuchMethodError was thrown building TableCalendar(dirty, state: _TableCalendarState#53e71(ticker inactive)):
The getter 'month' was called on null.
Receiver: null
Tried calling: month

this happens with i need to refresh, or change someting. but in first time works fine.   i use a List<CalendarController>() for managin few Table calendars. and in the listView use  the tableCalendar whit controller = _controller[index]

**Comment by aleksanderwozniak** [comment]
Hi, can you share a self-contained demo that I could use to reproduce the issue?

**Comment by aleksanderwozniak** [comment]
Check out https://github.com/aleksanderwozniak/table_calendar/issues/294, it should solve your problem.
