### ISSUE TITLE
Customize vertical spacing

### ISSUE THREAD

**Issue by code-gene** [aleksanderwozniak/table_calendar#355]
Hello everyone,

I just want to know how can I customize vertical spacing between the days of the calendar...?

Or 

Is there any way to control the size of the calendar for different resolution screen..?

**Comment by aleksanderwozniak** [comment]
Hi, you could use `rowHeight` property for that. `CalendarBuilders` might also come in handy, if you wrap adequate builders with `Padding` widget.
