### ISSUE TITLE
Can't even import table_calendar and lots of errors

### ISSUE THREAD

**Issue by adrict99** [aleksanderwozniak/table_calendar#356]
Hello, I added table_calendar: ^2.3.1 to my pubscpec.yaml, pub get, get dependencies, then import 'package:table_calendar/table_calendar.dart';

And just importing the package I get this in the console everytime:

`_/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/table_calendar.dart:8:8: Error: Error when reading '/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/simple_gesture_detector-0.1.4/lib/simple_gesture_detector.dart': The system cannot find the specific route.

import 'package:simple_gesture_detector/simple_gesture_detector.dart';
       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/src/calendar.dart:160:9: Error: Type 'SimpleSwipeConfig' not found.
  final SimpleSwipeConfig simpleSwipeConfig;
        ^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/src/calendar.dart:160:9: Error: 'SimpleSwipeConfig' isn't a type.
  final SimpleSwipeConfig simpleSwipeConfig;
        ^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/src/calendar.dart:207:31: Error: Getter not found: 'SwipeDetectionBehavior'.
      swipeDetectionBehavior: SwipeDetectionBehavior.continuousDistinct,
                              ^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/src/calendar.dart:205:36: Error: Method not found: 'SimpleSwipeConfig'.
    this.simpleSwipeConfig = const SimpleSwipeConfig(
                                   ^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/src/calendar.dart:517:12: Error: The method 'SimpleGestureDetector' isn't defined for the class '_TableCalendarState'.
 - '_TableCalendarState' is from 'package:table_calendar/table_calendar.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/table_calendar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SimpleGestureDetector'.
    return SimpleGestureDetector(
           ^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/src/calendar.dart:522:60: Error: The getter 'SwipeDirection' isn't defined for the class '_TableCalendarState'.
 - '_TableCalendarState' is from 'package:table_calendar/table_calendar.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/table_calendar-2.3.1/lib/table_calendar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SwipeDirection'.
              .swipeCalendarFormat(isSwipeUp: direction == SwipeDirection.up);
                                                          ^^^^^^^^^^^^^^_
`

I tried also importing simple_gesture_detector and didn't work.

This is part of my pubscpec.lock:

`table_calendar:
    dependency: "direct main"
    description:
      name: table_calendar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.1"`

what does direct main dependency means? can this package only be used on the main class? 

I also created this:

`@override
  void initState() {
    super.initState();
    _calendarController = CalendarController();
  }

  @override
  void dispose() {
    _calendarController.dispose();
    super.dispose();
  }`

And of course CalendarController _controller; under the State<Calendar>. and
> `@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            TableCalendar(
              calendarController: _calendarController,
            ),
          ],
        ),
      )
    );
  }`

**Comment by adrict99** [comment]
I downloaded again the table_calendar and the simple_gesture_detector package from pub.dev and pasted them in the route where my Android Studio said couldn't find them.

Then I was still having errors, deleted:
- .flutter-plugins
- .flutter-plugins-dependencies
- table_calendar: ^2.3.1 from pubspec.yaml


Pub get and get dependencies, closed everything, opened again, installed again table_calendar: ^2.3.1 in pubspec.yaml, pub get and get dependencies and it's working perfectly fine.

**Comment by aleksanderwozniak** [comment]
This sounds like some caching issue, glad you worked it out!
