### ISSUE TITLE
onCalendarCreated called multiple times

### ISSUE THREAD

**Issue by mobilegeekkk** [aleksanderwozniak/table_calendar#357]
Hi, onCalendarCreated called multiple times when calendar is being used in ListView and bunch of items below the calendar.
When we scroll down to the bottom and scrolls upwards, onCalendarCreated called again and it resets the data set on calendar.
Please look into this.

**Comment by aleksanderwozniak** [comment]
Hi, you can try this for a potential workaround: https://github.com/aleksanderwozniak/table_calendar/issues/294#issuecomment-736763804
