### ISSUE TITLE
Days of week Padding

### ISSUE THREAD

**Issue by cedricDevWP** [aleksanderwozniak/table_calendar#358]
Hi,

i tried adding padding on days of week but without success.

On the HeaderStyle there has the option headerPadding, is there something similar but for the days of week  ?

**Comment by aleksanderwozniak** [comment]
Hi, you can use `dowWeekdayBuilder` and `dowWeekendBuilder` from `CalendarBuilders` for that.

**Comment by cedricDevWP** [comment]
Thx i use dowWeekdayBuilder :)
