### ISSUE TITLE
How to custom button next/forward month ?

### ISSUE THREAD

**Issue by manhlhvm** [aleksanderwozniak/table_calendar#359]
I want custom button next/forward month, someone solution for this ? Tks.

**Comment by Paradoxu** [comment]
Did you find anything? I'm trying to implement this as well just by updating the state of the widget and setting a `setSelectedDay` from the controller, and weirdly works sometimes, or sometimes it jumps some months and show me the current month but with the days of the previous/future month, I don't know what to do, I have debugged and the data it's correct, guess this should be a feature for people who wants to build custom headers or just trigger the date from somewhere else outside the calendar widget.

**Comment by manhlhvm** [comment]
> Did you find anything? I'm trying to implement this as well just by updating the state of the widget and setting a `setSelectedDay` from the controller, and weirdly works sometimes, or sometimes it jumps some months and show me the current month but with the days of the previous/future month, I don't know what to do, I have debugged and the data it's correct, guess this should be a feature for people who wants to build custom headers or just trigger the date from somewhere else outside the calendar widget.

Tks you, i will try it.

**Comment by aleksanderwozniak** [comment]
You can now use `calendarController.previousPage()` and `calendarController.nextPage()` in TableCalendar version 2.3.2.
