### ISSUE TITLE
Exposing CalendarLogic to be customable

### ISSUE THREAD

**Issue by yifan** [aleksanderwozniak/table_calendar#36]
Hi @aleksanderwozniak , 

Thank you for the wonderful package. It feels that it would be a more powerful package if we can provide our own CalendarLogic than the default one. Is there any reason I shouldn't do this?

**Comment by aleksanderwozniak** [comment]
You would need to implement the whole logic by yourself - why would you want to do that? 

Do you find current implementation lacking?
