### ISSUE TITLE
Example code won't build

### ISSUE THREAD

**Issue by sgehrman** [aleksanderwozniak/table_calendar#360]
In android/app/build.gradle:

change this:

    classpath 'com.android.tools.build:gradle:4.1.1'

Otherwise it won't build:

Launching lib/main.dart on HD1905 in debug mode...
 lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Build file '/home/steve/google/table_calendar/example/android/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not open proj remapped class cache for 4ydtjyojdhilzdpjga8rkul2p (/home/steve/.gradle/caches/5.6.2/scripts-remapped/build_952wk09cjlx4xyomms7lgyg1s/4ydtjyojdhilzdpjga8rkul2p/proj016c9397e71a56ec48c54a2e61383932).
      > Could not open proj generic class cache for build file '/home/steve/google/table_calendar/example/android/app/build.gradle' (/home/steve/.gradle/caches/5.6.2/scripts/4ydtjyojdhilzdpjga8rkul2p/proj/proj016c9397e71a56ec48c54a2e61383932).
         > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by aleksanderwozniak** [comment]
Hi,
I tried applying your suggestions regarding gradle, but afterwards the project didn't build for me. Which Flutter channel and version are you using?
