### ISSUE TITLE
Change start and end date dynamically

### ISSUE THREAD

**Issue by kitoide** [aleksanderwozniak/table_calendar#365]
I am removing data that I inform on holidays: but in the calendar it is not cleared, how can I reset the appointments in the calendar?

**Comment by kitoide** [comment]
I am removing data that I inform on holidays: but in the calendar it is not cleared, how can I reset the appointments in the calendar?

**Comment by aleksanderwozniak** [comment]
Rebuild the widget with new data - [this](https://gist.github.com/aleksanderwozniak/e9eb98bf28bd9fbb336039e1936c59aa#file-add_event-dart-L54) might help you.
