### ISSUE TITLE
Change the display order

### ISSUE THREAD

**Issue by faridkzadeh** [aleksanderwozniak/table_calendar#366]
Thanks again for the awesome project!!
Is it possible to change the headers/ days display order? My calendar is in Farsi. So, we read from "right to left" instead of "left to right". I would like to change it. Could you please provide me direction?  For example instead of 
"Sun, Mon, .... Sat"
" 1.      2.             7" 
will be 
"Sat..., Mon, Sun" 
"7.        2.       1.    "

**Comment by aleksanderwozniak** [comment]
Try using `3.0.0-dev` branch with app running in RTL mode, it should work as expected.

**Comment by faridkzadeh** [comment]
Thanks a lot.
