### ISSUE TITLE
Changing the first day of month

### ISSUE THREAD

**Issue by faridkzadeh** [aleksanderwozniak/table_calendar#367]
My calendar is off (about 14 days + leaper day) from the current days. Is it possible to define/ set my first day? In the screenshots, my first day of the month is equal to Dec 14 and I would like to start from there.  My problem is how I can change the start day from Mon instead of Tue in this example. Is there a way to change firstDayOfMonth?

![Screen Shot 2020-12-20 at 9 08 02 AM](https://user-images.githubusercontent.com/6954665/102715357-e770da00-42a2-11eb-9253-4807835d8245.png)

 
![Screen Shot 2020-12-20 at 8 57 11 AM](https://user-images.githubusercontent.com/6954665/102715200-c22f9c00-42a1-11eb-9d5a-a536b000597e.png)

**Comment by aleksanderwozniak** [comment]
You could try using `CalendarBuilders` for that:

```dart
builders: CalendarBuilders(
  dayBuilder: (context, date, events) {
    final shiftedDate = date.add(Duration(days: 14));
    return Center(
      child: Text('${shiftedDate.day}'),
    );
  },
),
```

**Comment by faridkzadeh** [comment]
Thanks a lot.
