### ISSUE TITLE
Dates with events loose formatting

### ISSUE THREAD

**Issue by jain-aayush1123** [aleksanderwozniak/table_calendar#368]
![image](https://user-images.githubusercontent.com/50782898/102720177-cc40b180-4318-11eb-988c-d07eea24bb0b.png)

The dates with events fall back to default design style. I am able to put markers and format dates. But dates with events become black

**Comment by aleksanderwozniak** [comment]
[eventDayStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle/eventDayStyle.html) from `CalendarStyle` will allow you to customize those dates.

**Comment by jain-aayush1123** [comment]
works like a charm. thank you for the amazing library
