### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by joshbenaron** [aleksanderwozniak/table_calendar#369]
Hey,

Have you/are you planning to support null safety?

**Comment by aleksanderwozniak** [comment]
Hi, 

That's correct, I will be releasing a null-safe version.

**Comment by aleksanderwozniak** [comment]
Null safe 3.0.0 prerelease has been uploaded: https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0
