### ISSUE TITLE
The following NoSuchMethodError was thrown building TableCalendar(dirty, state:

### ISSUE THREAD

**Issue by serjomac** [aleksanderwozniak/table_calendar#370]
Hola tengo un problema que cuando tengo un table Calendar y un textField al levantar el teclado para escribir en el texfield, se rompe el table calendar con el sieguiente error.

`flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building TableCalendar(dirty, state:
flutter: _TableCalendarState#cf947):
flutter: The getter 'month' was called on null.
flutter: Receiver: null
flutter: Tried calling: month
flutter:
flutter: The relevant error-causing widget was:
flutter:   TableCalendar`

y el table calendar se ve de la siguiente manera
<img width="305" alt="Captura de pantalla 2020-12-26 a las 15 42 18" src="https://user-images.githubusercontent.com/15911827/103177899-5672a380-484c-11eb-9f81-45fba3509a71.png">

**Comment by aleksanderwozniak** [comment]
Hi, check this reply: https://github.com/aleksanderwozniak/table_calendar/issues/294#issuecomment-736763804
Alternatively, you can switch to version `3.0.0` and follow [this](https://github.com/aleksanderwozniak/table_calendar/blob/3.0.0-dev/example/lib/pages/persistence_example.dart) example.
