### ISSUE TITLE
Limit calendar showing range

### ISSUE THREAD

**Issue by thivankasarathchandra** [aleksanderwozniak/table_calendar#375]
Is it possible to specify the range that calendar show, stop user from go back and forward to limitless amount of months. 

For an instance can We set a parameter to a specific period, such as for a 1 year or  few months?

**Comment by abhaypatil87** [comment]
+1

**Comment by kendoboris** [comment]
+1, only allow the user to move back and forth to the previous and next month if the months are within the `startDay` and `endDay` range.

**Comment by aleksanderwozniak** [comment]
Let's follow this in #100
