### ISSUE TITLE
Calendar type picker is misaligned, i.e. 2 weeks shows the whole month, month shows one week

### ISSUE THREAD

**Issue by aidanstay** [aleksanderwozniak/table_calendar#377]
<img width="358" alt="Screen Shot 2021-01-08 at 11 49 10 AM" src="https://user-images.githubusercontent.com/4097991/104053014-ce738e80-51a7-11eb-89d9-947f6fcecb79.png">
<img width="361" alt="Screen Shot 2021-01-08 at 11 49 17 AM" src="https://user-images.githubusercontent.com/4097991/104053020-d03d5200-51a7-11eb-991a-7e2114f8bf80.png">
<img width="366" alt="Screen Shot 2021-01-08 at 11 48 22 AM" src="https://user-images.githubusercontent.com/4097991/104053028-d2071580-51a7-11eb-8e72-46621ca229bb.png">

**Comment by aleksanderwozniak** [comment]
Hi, this should clarify what's going on: https://github.com/aleksanderwozniak/table_calendar/issues/323
