### ISSUE TITLE
pt_BR locale not supported?

### ISSUE THREAD

**Issue by lcsvcn** [aleksanderwozniak/table_calendar#378]
I am trying with locale **"pt_BR"** - Brazilian Portuguese.

But I am receiving:
"Locale data has not been initialized, call initializeDateFormatting(<locale>)."

Am I missing something? Does it need some implementation to support this language?

**Comment by aleksanderwozniak** [comment]
You need to initialize it first: https://github.com/aleksanderwozniak/table_calendar#locale
