### ISSUE TITLE
issue with changing daysofweek color

### ISSUE THREAD

**Issue by wchen38** [aleksanderwozniak/table_calendar#379]
Below is a snippet of my calendar code, I though by changing the 'weekdaystyle' parameter then it would permanently  change the default color black. However, when there are events, and also when I click around the weekdays, the color becomes black.

In the attached image below, Day, 1, 4, 5, 7, contain events and the color is black when the calendar is initiated. Day 11 - 15 turn to black color after I clicked on those days.

Can anyone give me some feedback on what I can do to keep the weekday text color all the same?

Thank you!

```
TableCalendar( 
...
calendarStyle: CalendarStyle(
        todayColor: Util.btnColor,
        selectedColor: Util.navColor,
        weekendStyle: TextStyle().copyWith(
          color: Util.btnColor,
        ),
        weekdayStyle: TextStyle().copyWith(
          color: Util.btnColor,
        ),
        holidayStyle: TextStyle().copyWith(
          color: Util.btnColor,
        ),
        outsideDaysVisible: false,
      ),
    );
)
```

<img width="346" alt="Screen Shot 2021-01-09 at 6 14 22 PM" src="https://user-images.githubusercontent.com/10474017/104112825-4cb75a00-52a8-11eb-824e-bba3d32b0fd0.png">

**Comment by aleksanderwozniak** [comment]
Try adding `eventDayStyle: ...` as well.

**Comment by wchen38** [comment]
Thanks a lot for the tip. This helped!
