### ISSUE TITLE
Dart's Table component has a bisector width problem.

### ISSUE THREAD

**Issue by 49756916** [aleksanderwozniak/table_calendar#382]
When you set the background color for the items in each row of the Calendar, you can see that the separator line may appear. This should be a problem for the Table component, but if you put a Container around the Calendar and set its width to a multiple of 7, you should solve this problem.

**Comment by aleksanderwozniak** [comment]
That's correct. 

This might be a potential workaround for this issue. Unfortunately not every multiple of 7 will work - for example, 7 * 52 works well for me, but 7 * 50 does not, so there will be some trial and error to get it right.

Linking to #308.
