### ISSUE TITLE
markersBuilder spacing

### ISSUE THREAD

**Issue by AlessioDelConte** [aleksanderwozniak/table_calendar#383]
Hi all,
I'm trying to create my own markerBuilder using the suggested Positioned and Container, but the issue is that I want the dots for the events that I'm creating evenly spaced (as the default ones), but since I'm working with Positioned I cant hard code the positions for all the different screens. 
Is there a simple way to do this?

Here are 2 screenshots on two different devices (click to zoom):
<img src="https://user-images.githubusercontent.com/15822575/104838601-3a4aab00-58bc-11eb-8199-5d4c25d34b4a.png" width="120" height="200">

<img src="https://user-images.githubusercontent.com/15822575/104838604-40408c00-58bc-11eb-94cf-48df996e491f.png" width="120" height="200">

Thanks!

**Comment by AlessioDelConte** [comment]
Found a nice solution if anyone interested, use AlignPositioned (https://pub.dev/packages/align_positioned) to wrap your content instead of just Positioned, that permits to move with respect to the width of the parent widget, allowing a perfect positioning in every screen.
Enjoy!

**Comment by aleksanderwozniak** [comment]
I'll just add that it seems like using `singleMarkerBuilder` would also work fine for your use case.
