### ISSUE TITLE
any plan to support lunar calendar?

### ISSUE THREAD

**Issue by dingteddy** [aleksanderwozniak/table_calendar#384]
has any plan to support lunar calendar? thanks

**Comment by aleksanderwozniak** [comment]
As of now I don't have plans to add support for it - I might add it in the future.

What you can do now, is come up with a mapping function that transforms a given date from Gregorian to lunar, and then use `CalendarBuilders` with it to create your own UI - here is a similar idea: https://github.com/aleksanderwozniak/table_calendar/issues/367#issuecomment-757473342.
