### ISSUE TITLE
CalendarFormat which hides all days in the calendar

### ISSUE THREAD

**Issue by Ashhas** [aleksanderwozniak/table_calendar#386]
Hi, loving this package!

Would it be possible to have a ```CalendarFormat``` which hides all the days in calendar? So when calling something like `CalendarFormat.noDays` only the header and/or the events are displayed?

I have a design that needs something like and I am wondering if this is something that can already be achieved: 
![qweqweqwe](https://user-images.githubusercontent.com/32300569/105632466-8618c980-5e53-11eb-8c57-f2a74bdc4b86.png)

**Comment by aleksanderwozniak** [comment]
Hi,

To achieve this effect, you can hide the default calendar header and provide a custom one - then you can simply toggle the visibility of `TableCalendar` widget. Check out those links, they should help you get started:

- https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1
- https://github.com/aleksanderwozniak/table_calendar/issues/294#issuecomment-736763804

**Comment by Ashhas** [comment]
Hello, 

These links do help with changing the header, but my issue is with hiding the dates that display under the header (from the actual `TableCalendar`). 

For reference this part: 
![asdadqw dq](https://user-images.githubusercontent.com/32300569/105633168-65527300-5e57-11eb-9ddc-c72fdae7ad67.JPG)

**Comment by aleksanderwozniak** [comment]
That's exactly what you need to do. 

Wrap `TableCalendar` with `Visibility` widget - this will allow you to hide the widget, but if you stop there, you will also lose the header. To solve that, you can provide a custom header - and put it outside of the `Visibility` widget, so that it won't get hidden.

The rest is just managing the state between the header and calendar.

**Comment by Ashhas** [comment]
Aah I get it now. Thanks for the information, I should be able to implement it now.
