### ISSUE TITLE
Any plan to support multiple MarkersColor based on event?

### ISSUE THREAD

**Issue by Dharmik-Dalwadi** [aleksanderwozniak/table_calendar#389]
I want to Implement Multiple Markers Color based on events on the same date, Do you have any plan to implement this feature in the further release or have any suggestions on how to achieve this feature?

**Comment by aleksanderwozniak** [comment]
Check this: https://github.com/aleksanderwozniak/table_calendar/issues/183#issuecomment-582569009.
