### ISSUE TITLE
It does not have an attribute that tells me when I click on the date to return to the previous month

### ISSUE THREAD

**Issue by BVargas-AudiSoft** [aleksanderwozniak/table_calendar#390]
I made a solution in the calendar.dart file it is simple and I implemented it on my pc and it served for a new project. I hope you can incorporate it for better usability

![boton devolver](https://user-images.githubusercontent.com/71858983/106536618-324f5580-64cf-11eb-8a7e-44541d998fa0.png)
![boton two](https://user-images.githubusercontent.com/71858983/106536693-5ad74f80-64cf-11eb-875b-feb608208903.png)
![boton three](https://user-images.githubusercontent.com/71858983/106536774-75a9c400-64cf-11eb-9352-540695494c22.png)
![botom four](https://user-images.githubusercontent.com/71858983/106537035-ebae2b00-64cf-11eb-8b17-a9b7d1d57b18.png)
![botom five](https://user-images.githubusercontent.com/71858983/106537036-ebae2b00-64cf-11eb-96f5-a0c238ffc0e8.png)

Please, I would appreciate a lot if you modify that as it is very helpful

**Comment by BVargas-AudiSoft** [comment]
the name would be changed to OnMonthSelectedLeft thanks

**Comment by aleksanderwozniak** [comment]
You can achieve this without modifying the package by providing a [custom header](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1). CalendarController exposes `previousPage()` and `nextPage()`, which you can incorporate to your custom header if needed.

**Comment by BVargas-AudiSoft** [comment]
with dynamic builders?

**Comment by BVargas-AudiSoft** [comment]
Would I have to create a header and embed it in the headerStyle of table_calendar?

**Comment by BVargas-AudiSoft** [comment]
Just like what the calendar controller exposes is private like the table_calendar package

**Comment by aleksanderwozniak** [comment]
It sounds like you have an outdated version cached. Check in `pubspec.lock` what version `table_calendar` uses - it should say `version: "2.3.3"`. Try refreshing your packages with `flutter pub get`.

**Comment by BVargas-AudiSoft** [comment]
if you are right but my question is, to have a custom header should I inherit from this class to access its private methods?

**Comment by aleksanderwozniak** [comment]
Which private methods would you like to access?

You should create a separate widget and update it when `onVisibleDaysChanged` gets called.

```dart
class CustomCalendarHeader extends StatelessWidget {
  final DateTime headerDate;

  const CustomCalendarHeader({
    Key key,
    @required this.headerDate,
  })  : assert(headerDate != null),
        super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Center(
        child: Text(
          DateFormat.yMMMM().format(headerDate),
          style: TextStyle(fontSize: 20.0),
        ),
      ),
    );
  }
}
```
This is taken from https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1#file-custom_calendar_header-dart-L64. You just need to add previous / next buttons to it, and trigger `calendarController.previousPage()` / `calendarController.nextPage()` in their callbacks.

**Comment by aleksanderwozniak** [comment]
Closing this for now, but feel free to ask further if needed.
