### ISSUE TITLE
ETA on v3?

### ISSUE THREAD

**Issue by serendipity1004** [aleksanderwozniak/table_calendar#392]
you said you have added range selection function on V3.

We have to decide whether we will go with the 3.0 of this plugin or our own version of v2.

Is there a ETA for v3? If it is going to take too long we're going to have to go with alternative solution

**Comment by aleksanderwozniak** [comment]
You can already use this feature (and many others) with `3.0.0-beta` branch - more info [here](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-beta#usage).

**Comment by aleksanderwozniak** [comment]
Null safe prerelease has been uploaded to pub.dev: https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0.
