### ISSUE TITLE
focusedDay causing visible days offset in week format - 3.0.0beta

### ISSUE THREAD

**Issue by mees-brenzie** [aleksanderwozniak/table_calendar#393]
Really loving v3.0 so far! Thank you for this update.

I came across an issue where the visible days would we offsetted by a week when the calendar is in week format mode. It seems like is caused by the focusedDay variable. When it is set to a Monday the calendar will choose to show the previous week, instead of the week the focusedDay is in. For example: initializing the calendar with the CalendarFormat.week and focusedDay on 2021-02-08 will cause the calendar to show the week of 2021-02-01 till 2021-02-07. Offsetting the initial focusedDay to the Tuesday (2021-02-09) will result in the calendar showing the correct week.

**EDIT**: This behaviour also occurs when setting de focusedDay to a Monday in the week format. It will then change page to the previous week. This issue can also be fixed by adding 1 day to the focusedDay when a Monday is selected in the _onDaySelected_ callback. **However**, this leaves the issue when a Monday is on the last day of the month, it will display the next month on the top, instead of the selected month. For example, selecting Monday 31st of May will show June as the focused month. Which of course makes sense since the focusedDay is now set to June. Something to keep in mind while using this temp fix

Let me know if this makes sense and if it's reproducible.

**Comment by aleksanderwozniak** [comment]
Thanks for reporting this!

Which `startingDayOfWeek` are you using? Are you changing it during runtime? Does the issue persist after restarting (not hot reloading) Flutter?

**Comment by mees-brenzie** [comment]
Thank you for the quick response!

I am setting `StartingDayOfWeek.monday` in creation, but not changing it after. It does persist after restart. 

I am using `DateTime(...)`. Calling `.toUtc()` will change the date to one day prior 23:00, since my timezone is UTC +1. However, when I use a newly created UTC date (2021-02-08 00:00:00.000Z)
 it is still happens, it will show the week prior the focused date. The same goes for selecting a Monday, it will still jump to the previous week, since I directly store the` focusedDay` passed by the callback into a variable. UTC time does not seem to be an issue for the selected date.

**Comment by aleksanderwozniak** [comment]
Hmm, hours being at 00:00 can definitely be an issue due to daylight saving offsets; I did use 12:00 in previous versions for that exact reason. Using UTC should fix that though, as it omits this offset.

Can you try running the following code to see if the issue persists?

```dart
import 'package:flutter/material.dart';
import 'package:table_calendar/table_calendar.dart';

class TableBasicsExample extends StatefulWidget {
  @override
  _TableBasicsExampleState createState() => _TableBasicsExampleState();
}

class _TableBasicsExampleState extends State<TableBasicsExample> {
  CalendarFormat _calendarFormat = CalendarFormat.week;
  DateTime _focusedDay = DateTime.utc(2021, 2, 8);
  DateTime _selectedDay;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('TableCalendar - Basics'),
      ),
      body: Column(
        children: [
          TableCalendar(
            firstDay: DateTime.utc(2020, 10, 16),
            lastDay: DateTime.utc(2021, 3, 14),
            focusedDay: _focusedDay,
            calendarFormat: _calendarFormat,
            startingDayOfWeek: StartingDayOfWeek.monday,
            selectedDayPredicate: (day) {
              return isSameDay(_selectedDay, day);
            },
            onDaySelected: (selectedDay, focusedDay) {
              print('selected: $selectedDay');
              print('focused: $focusedDay');

              if (!isSameDay(_selectedDay, selectedDay)) {
                setState(() {
                  _selectedDay = selectedDay;
                });
              }

              _focusedDay = focusedDay;
            },
            onFormatChanged: (format) {
              if (_calendarFormat != format) {
                setState(() {
                  _calendarFormat = format;
                });
              }
            },
            onPageChanged: (focusedDay) {
              _focusedDay = focusedDay;
            },
          ),
          RaisedButton(
            child: Text('Focus today'),
            onPressed: () {
              setState(() {
                final now = DateTime.now();
                _focusedDay = DateTime.utc(now.year, now.month, now.day);
              });
            },
          ),
        ],
      ),
    );
  }
}
```

You can try this to obtain the current date in local time and convert it to UTC without changing the actual date:

```dart
final now = DateTime.now();
_focusedDay = DateTime.utc(now.year, now.month, now.day);
```

**Comment by aleksanderwozniak** [comment]
Ah, one more thing that can have an impact here - what dates are your `firstDay` and `lastDay`?

**Comment by mees-brenzie** [comment]
> Ah, one more thing that can have an impact here - what dates are your `firstDay` and `lastDay`?
```
firstday: DateTime.now().subtract(Duration(days: 365))
lastday: DateTime.now().add(Duration(days: 365))
```





> Hmm, hours being at 00:00 can definitely be an issue due to daylight saving offsets; I did use 12:00 in previous versions for that exact reason. Using UTC should fix that though, as it omits this offset.
> 
> Can you try running the following code to see if the issue persists?
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:table_calendar/table_calendar.dart';
> 
> class TableBasicsExample extends StatefulWidget {
>   @override
>   _TableBasicsExampleState createState() => _TableBasicsExampleState();
> }
> 
> class _TableBasicsExampleState extends State<TableBasicsExample> {
>   CalendarFormat _calendarFormat = CalendarFormat.week;
>   DateTime _focusedDay = DateTime.utc(2021, 2, 8);
>   DateTime _selectedDay;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('TableCalendar - Basics'),
>       ),
>       body: Column(
>         children: [
>           TableCalendar(
>             firstDay: DateTime.utc(2020, 10, 16),
>             lastDay: DateTime.utc(2021, 3, 14),
>             focusedDay: _focusedDay,
>             calendarFormat: _calendarFormat,
>             startingDayOfWeek: StartingDayOfWeek.monday,
>             selectedDayPredicate: (day) {
>               return isSameDay(_selectedDay, day);
>             },
>             onDaySelected: (selectedDay, focusedDay) {
>               print('selected: $selectedDay');
>               print('focused: $focusedDay');
> 
>               if (!isSameDay(_selectedDay, selectedDay)) {
>                 setState(() {
>                   _selectedDay = selectedDay;
>                 });
>               }
> 
>               _focusedDay = focusedDay;
>             },
>             onFormatChanged: (format) {
>               if (_calendarFormat != format) {
>                 setState(() {
>                   _calendarFormat = format;
>                 });
>               }
>             },
>             onPageChanged: (focusedDay) {
>               _focusedDay = focusedDay;
>             },
>           ),
>           RaisedButton(
>             child: Text('Focus today'),
>             onPressed: () {
>               setState(() {
>                 final now = DateTime.now();
>                 _focusedDay = DateTime.utc(now.year, now.month, now.day);
>               });
>             },
>           ),
>         ],
>       ),
>     );
>   }
> }
> ```
> 
> You can try this to obtain the current date in local time and convert it to UTC without changing the actual date:
> 
> ```dart
> final now = DateTime.now();
> _focusedDay = DateTime.utc(now.year, now.month, now.day);
> ```

Your example works fine, but I cannot quiet figure out what I am doing differently than this example.. I do indeed create the utc time that exact way, all the prints output the same data. I'm not sure what to make of it, but adding the 12 hours seems to do the trick. this is my code:

`class _Calendar extends StatefulWidget {
  @override
  __CalendarState createState() => __CalendarState();
}

class __CalendarState extends State<_Calendar> {
  DateTime _selectedDay;
  DateTime _focusedDay;
  CalendarFormat _calendarFormat = CalendarFormat.week;

  @override
  void didChangeDependencies() {
    final date = BlocProvider.of<EventCubit>(context).state.date;
    final utcDate = DateTime.utc(date.year, date.month, date.day);
    _selectedDay = utcDate;
    _focusedDay = utcDate;
    super.didChangeDependencies();
  }

  void _onDaySelected(DateTime selectedDay, DateTime focusedDay) {
    print('selected: $selectedDay');
    print('focused: $focusedDay');
    if (!isSameDay(_selectedDay, selectedDay)) {
      setState(() {
        _selectedDay = selectedDay;
      });
    }

    _focusedDay = focusedDay;
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Theme.of(context).cardColor,
      elevation: 1,
      borderRadius: BorderRadius.circular(BORDER_RADIUS),
      child: Padding(
        padding: EdgeInsets.all(8.0),
        child: Calendar(
          firstDay: DateTime.now().subtract(Duration(days: 365)),
          lastDay: DateTime.now().add(Duration(days: 365)),
          focusedDay: _focusedDay,
          calendarFormat: _calendarFormat,
          dowHeight: 30,
          selectedDayPredicate: (day) => isSameDay(day, _selectedDay),
          onDaySelected: _onDaySelected,
          onPageChanged: (day) => _focusedDay = day,
          onFormatChanged: (format) {
            if (_calendarFormat != format) {
              setState(() => _calendarFormat = format);
            }
          },
        ),
      ),
    );
  }
}`

Calendar widget
`// Flutter imports:
import 'dart:collection';

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

// Package imports:
import 'package:table_calendar/table_calendar.dart';

// Project imports:
import 'package:mr_einstein_flutter/utils/appLocalization.dart';

class Calendar extends StatefulWidget {
  const Calendar({
    Key key,
    @required this.firstDay,
    @required this.lastDay,
    @required this.focusedDay,
    @required this.onDaySelected,
    @required this.selectedDayPredicate,
    this.enabledPredicate,
    this.holidayPredicate,
    this.formatButtonVisible = true,
    this.shouldFillViewport = false,
    this.onPageChanged,
    this.onFormatChanged,
    this.eventLoader,
    this.calendarFormat = CalendarFormat.month,
    this.headerVisible = true,
    this.availableGestures = AvailableGestures.horizontalSwipe,
    this.markerBuilder,
    this.singleMarkerBuilder,
    this.dowHeight = 52,
    this.rowHeight = 46,
  }) : super(key: key);

  final DateTime firstDay;
  final DateTime lastDay;
  final DateTime focusedDay;
  final CalendarFormat calendarFormat;
  final bool headerVisible;
  final bool formatButtonVisible;
  final bool shouldFillViewport;
  final AvailableGestures availableGestures;
  final double dowHeight;
  final double rowHeight;

  final Function(DateTime) selectedDayPredicate;
  final Function(DateTime) enabledPredicate;
  final Function(DateTime) holidayPredicate;
  final Function(DateTime, DateTime) onDaySelected;
  final Function(DateTime) eventLoader;
  final Function(BuildContext, DateTime, List<dynamic>) markerBuilder;
  final Function(BuildContext, DateTime, dynamic) singleMarkerBuilder;
  final Function(DateTime) onPageChanged;
  final Function(CalendarFormat) onFormatChanged;

  @override
  _CalendarState createState() => _CalendarState();
}

class _CalendarState extends State<Calendar> {
  @override
  Widget build(BuildContext context) {
    return TableCalendar(
      firstDay: widget.firstDay,
      lastDay: widget.lastDay,
      focusedDay: widget.focusedDay ?? DateTime.now(),
      eventLoader: widget.eventLoader,
      locale: AppLocalizations.of(context).locale.toString(),
      onDaySelected: widget.onDaySelected,
      selectedDayPredicate: widget.selectedDayPredicate,
      enabledDayPredicate: widget.enabledPredicate,
      holidayPredicate: widget.holidayPredicate,
      onPageChanged: widget.onPageChanged,
      onFormatChanged: widget.onFormatChanged,
      headerVisible: widget.headerVisible,
      availableGestures: widget.availableGestures,
      calendarFormat: widget.calendarFormat,
      availableCalendarFormats: {
        CalendarFormat.month:
            AppLocalizations.of(context).translate('calendar_month'),
        CalendarFormat.week:
            AppLocalizations.of(context).translate('calendar_week')
      },
      startingDayOfWeek: StartingDayOfWeek.monday,
      calendarBuilders: CalendarBuilders(
        singleMarkerBuilder: widget.singleMarkerBuilder,
      ),
      daysOfWeekHeight: widget.dowHeight,
      rowHeight: widget.rowHeight,
      shouldFillViewport: widget.shouldFillViewport,
      calendarStyle: CalendarStyle(
        defaultTextStyle: Theme.of(context).textTheme.bodyText1,
        selectedDecoration: BoxDecoration(
            color: Theme.of(context).accentColor, shape: BoxShape.circle),
        selectedTextStyle:
            Theme.of(context).textTheme.bodyText1.copyWith(color: Colors.white),
        holidayDecoration: BoxDecoration(
            border: Border.all(color: Theme.of(context).accentColor, width: 2),
            shape: BoxShape.circle),
        holidayTextStyle: const TextStyle(color: const Color(0xFFBFBFBF)),
        todayDecoration: BoxDecoration(
            color: Colors.grey.withOpacity(0.4), shape: BoxShape.circle),
        todayTextStyle:
            Theme.of(context).textTheme.bodyText1.copyWith(color: Colors.white),
        weekendTextStyle: Theme.of(context)
            .textTheme
            .bodyText1
            .copyWith(color: Theme.of(context).accentColor),
      ),
      daysOfWeekStyle: DaysOfWeekStyle(
        dowTextFormatter: (date, locale) =>
            DateFormat.E(locale).format(date)[0],
        weekdayStyle: TextStyle(
          color: Theme.of(context).textTheme.bodyText1.color.withOpacity(0.6),
          fontSize: 12,
          fontWeight: FontWeight.normal,
        ),
        weekendStyle: TextStyle(
          color: Theme.of(context).accentColor.withOpacity(0.6),
          fontSize: 12,
          fontWeight: FontWeight.normal,
        ),
      ),
      headerStyle: HeaderStyle(
        headerMargin: EdgeInsets.symmetric(horizontal: 16),
        formatButtonVisible:
            widget.formatButtonVisible && widget.onFormatChanged != null,
        formatButtonShowsNext: false,
        formatButtonDecoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20),
          color: Theme.of(context).accentColor,
        ),
        formatButtonTextStyle:
            Theme.of(context).textTheme.caption.copyWith(color: Colors.white),
        leftChevronVisible: false,
        leftChevronIcon: Icon(Icons.chevron_left,
            color: Theme.of(context).textTheme.headline1.color),
        leftChevronMargin: EdgeInsets.zero,
        rightChevronVisible: false,
        rightChevronIcon: Icon(Icons.chevron_right,
            color: Theme.of(context).textTheme.headline1.color),
        rightChevronMargin: EdgeInsets.zero,
        titleTextStyle: Theme.of(context).textTheme.headline1,
      ),
    );
  }
}
`

**Comment by aleksanderwozniak** [comment]
`firstDay` and `lastDay` seem to be the culprits.

Try setting them to:
```dart
final now = DateTime.now();
final firstDay = DateTime.utc(now.year, now.month, now.day).subtract(Duration(days: 365));
final lastDay = DateTime.utc(now.year, now.month, now.day).add(Duration(days: 365));
```

or to:

```dart
final now = DateTime.now();
final firstDay = DateTime.utc(now.year - 1, now.month, now.day);
final lastDay = DateTime.utc(now.year + 1, now.month, now.day);
```

You can put it inside either `build()` or `initState()`.

**Comment by mees-brenzie** [comment]
> `firstDay` and `lastDay` seem to be the culprits.
> 
> Try setting them to:
> 
> ```dart
> final now = DateTime.now();
> final firstDay = DateTime.utc(now.year, now.month, now.day).subtract(Duration(days: 365));
> final lastDay = DateTime.utc(now.year, now.month, now.day).add(Duration(days: 365));
> ```
> 
> or to:
> 
> ```dart
> final now = DateTime.now();
> final firstDay = DateTime.utc(now.year - 1, now.month, now.day);
> final lastDay = DateTime.utc(now.year + 1, now.month, now.day);
> ```
> 
> You can put it inside either `build()` or `initState()`.

Wow! That fixed everything! Thank you! You are a true legend.
Just to clarify for my personally, are other dates depending on the first and last date, that is effects the focusedDate?

**Comment by aleksanderwozniak** [comment]
I'm glad it works now :)

Yes, there is a bit of internal logic that has to handle relations between `firstDay`, `lastDay` and `focusedDay`. In previous versions it didn't matter that much, but now I had to include PageView widget (to get rid of that "blank page" between horizontal swipes) and it is quite tricky to get right with three different calendar formats (month, two weeks, week). 

As the internal mechanics need to precisely calculate difference between those days, having them in uniform UTC format is really important - I'll make sure to include a section about it in the v3 guide.

You can also read about this here: https://api.flutter.dev/flutter/dart-core/DateTime-class.html

> To find out how much time is between two DateTime objects use difference, which returns a Duration object:
> 
> ```
> var difference = berlinWallFell.difference(moonLanding);
> assert(difference.inDays == 7416);
> ```
> 
> The difference between two dates in different time zones is just the number of nanoseconds between the two points in time. **It doesn't take calendar days into account. That means that the difference between two midnights in local time may be less than 24 hours times the number of days between them, if there is a daylight saving change in between**. If the difference above is calculated using Australian local time, the difference is 7415 days and 23 hours, which is only 7415 whole days as reported by inDays.

I really wish it was simpler, but sadly daylight saving offsets exist and make working with DateTimes harder :p

**Comment by aleksanderwozniak** [comment]
Actually I've decided to add a simple mechanism that makes sure incoming dates are correctly set up - now all should work fine, without having to explicitly use `DateTime.utc(...)`.

**Comment by aleksanderwozniak** [comment]
Closing, as this looks to be resolved
