### ISSUE TITLE
Month, 2 Weeks and Week should be translated by Locale?

### ISSUE THREAD

**Issue by lcsvcn** [aleksanderwozniak/table_calendar#394]
Hi I noticed that the words "Month", "2 Weeks", "Week" isn't translated. It is possible to be changed as I change locale?

![Screenshot from 2021-02-09 15-44-16](https://user-images.githubusercontent.com/6011385/107411802-b916ba80-6aed-11eb-8223-54374b01724c.png)

If yes and I can help switching this I would be glad!

**Comment by aleksanderwozniak** [comment]
This is something you will need to handle yourself. Just like in #395, use `availableCalendarFormats` for this:
```dart
availableCalendarFormats: {
  CalendarFormat.month: localizedMonth,
  CalendarFormat.week: localizedWeek,
},
```

**Comment by lcsvcn** [comment]
Hi, Aleksander 

I have found out how to do this in a comment inside your code

I have open a PR to add to the documentation:

https://github.com/aleksanderwozniak/table_calendar/pull/396
