### ISSUE TITLE
Is there a way to lock the TableCalendar in one single mode?

### ISSUE THREAD

**Issue by lcsvcn** [aleksanderwozniak/table_calendar#395]
Hi, Aleksander

Is there a way to lock the calendar mode to **Week**, **Two Weeks** or **Month**?

I would like to disable user choice in order to keep a screen design, is there any way to do this?

Maybe adding a flag, **canSwitchMode** or a enum **MODE.lockedWeek**, **MODE.lockedTwoWeeks**, **MODE.lockedMonth**, **MODE.unlocked**.

**Comment by aleksanderwozniak** [comment]
Hi,

You can use `availableCalendarFormats` for that:

```dart
availableCalendarFormats: {
  CalendarFormat.month: '',
},
```

This will lock the calendar just to month format.

**Comment by lcsvcn** [comment]
Hi, Aleksander 

I have found out how to do this in a comment inside your code

I have open a PR to add to the documentation:

https://github.com/aleksanderwozniak/table_calendar/pull/396
