### ISSUE TITLE
Events are added whenever the screen is redrawn.

### ISSUE THREAD

**Issue by kindkmj** [aleksanderwozniak/table_calendar#398]
Can we stop that method?
I don't want the event to be added.
![스크린샷 2021-02-10 오후 5 12 28](https://user-images.githubusercontent.com/41276448/107482536-28121300-6bc3-11eb-9fe5-8a87bec0a432.png)

![스크린샷 2021-02-10 오후 5 12 57](https://user-images.githubusercontent.com/41276448/107482576-395b1f80-6bc3-11eb-9188-e0d9a1636a15.png)

Why does it keep adding?
How can we stop them?

**Comment by aleksanderwozniak** [comment]
What do you mean? They aren't being added anywhere. 

`events` are there for convenience. This is a list of events that are associated with `date`. You can use them if you want to, but of course you don't have to. `markersBuilder` will be called for every visible day cell.
