### ISSUE TITLE
Ability to handle size dynamically

### ISSUE THREAD

**Issue by pasblin** [aleksanderwozniak/table_calendar#399]
Hi,

It is possible to open and close the calendar for example by putting it on top of a listview and scrolling up to make it collapse?

Regards.

**Comment by aleksanderwozniak** [comment]
Hi,

Sure, you just need to update the current `calendarFormat`. 

By default, the calendar will recognize vertical swipes and change its format automatically - if you want to put it inside a `ListView`, you can disable the default behavior by using `availableGestures: AvailableGestures.horizontalSwipe`. This will let you provide a custom behavior for vertical drags with, for example, the help of a `ScrollController`.

**Comment by pasblin** [comment]
Hi, 
Thanks for answer so soon.
I have for example this: ( the calendar isnt into listview) 

`children: [
                    CalendarView(),
                    Expanded(child: ListEventsView())]`

When listview is scrolling up i detect with a scrollcontroller and the possibility of doing something like this would be nice:

`scrollController.addListener(() {
      if(_scrollController.position.userScrollDirection == ScrollDirection.forward) {
       calendar.collapse();
    });`

with some kind of sliver style animation.

Regards

**Comment by aleksanderwozniak** [comment]
Hmm you could try using `AnimatedSize` or `AnimatedContainer` for this, with the idea of setting calendar's height to 0 when you detect user scrolling.

**Comment by pasblin** [comment]
But i would like ser the calendar week Mode may be ? Not Close It
completely

**Comment by pasblin** [comment]
Something like this:
https://dribbble.com/shots/6933071-Improved-Calendar-app

**Comment by aleksanderwozniak** [comment]
For this you can simply update the current `calendarFormat` to `CalendarFormat.week` inside the scroll listener.

**Comment by pasblin** [comment]
Ok i Will try , thx ;)

**Comment by pasblin** [comment]
It works thx.
