### ISSUE TITLE
Update documentation to include properties description.

### ISSUE THREAD

**Issue by SaurabhMhaisekar** [aleksanderwozniak/table_calendar#4]
Hello, 

Please update the readme file to include what each properties does. It is very hard to exactly find what options can be used to customize. thank you

**Comment by aleksanderwozniak** [comment]
I've added extensive documentation. It can be found on [API reference](https://pub.dartlang.org/documentation/table_calendar/latest/table_calendar/table_calendar-library.html).
Docs should also be visible inside your editor.

Let me know if you have any further questions!
