### ISSUE TITLE
Set Visible Month

### ISSUE THREAD

**Issue by OpticNectar** [aleksanderwozniak/table_calendar#40]
Is there not a way to set the current visible month without setting "selectedDay"?

**Comment by aleksanderwozniak** [comment]
Added with #84.

Update the package to version `2.0.0`, then follow [these steps](https://github.com/aleksanderwozniak/table_calendar#installation).

Use this:
```dart
setState(() {
  _calendarController.setFocusedDay(DateTime(year, month));
});
```
