### ISSUE TITLE
How to Remove/Disable the Header

### ISSUE THREAD

**Issue by divinemaredi** [aleksanderwozniak/table_calendar#401]
Is it possible to remove the Calender header? As shown on the attached screenshot:

![Table Calendar Screenshot #1](https://user-images.githubusercontent.com/65621952/107953414-c6c3b880-6fa3-11eb-9c84-34bc76672253.jpg)

**Comment by aleksanderwozniak** [comment]
Yes, simply use `headerVisible: false` for that.

**Comment by divinemaredi** [comment]
Perfect! Thanks!
