### ISSUE TITLE
How to Connect Days and Indicate Current Day with a Dot

### ISSUE THREAD

**Issue by divinemaredi** [aleksanderwozniak/table_calendar#402]
Hi again.

Based on the attached screenshot, I'm trying to replicate the UI which has 2 things I'd like to implement:

1. The days that have events are connected with a line and 
2. The current day is indicated using a dot

![Calendar Table Screenshot #2](https://user-images.githubusercontent.com/65621952/107956678-291eb800-6fa8-11eb-8193-9e712c8e9516.PNG)

So I just wanted to know if these 2 things can be implemented? If so, how can I go about doing that? 

Thanks a lot in advance!

**Comment by aleksanderwozniak** [comment]
You can achieve this by using [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html). Those three might be helpful, but it really depends on the specifics of your design:

- [dayBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/dayBuilder.html)
- [todayDayBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/todayDayBuilder.html)
- [markersBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/markersBuilder.html)

**Comment by divinemaredi** [comment]
Thanks for the response!

I'll have a look at the links you gave 👍🏼
