### ISSUE TITLE
Support for partial months

### ISSUE THREAD

**Issue by edwardaux** [aleksanderwozniak/table_calendar#403]
Firstly, thanks for a great library... absolutely love it.

Not sure if this is supported or not, but I've got a requirement to scroll the monthly calendar so that the first row isn't always the first week of the month. eg. I'd like to put the current day in the first row. 

eg. When the date is, say, the 16th Feb, then the calendar might look like:
```
FEBRUARY
15 16 17 18 19 20 21
22 23 24 25 26 27 28
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
```
where the 1st, 2nd, etc are all from March. Is this something that might be doable? Thanks.

**Comment by aleksanderwozniak** [comment]
Hi, check this issue: https://github.com/aleksanderwozniak/table_calendar/issues/367

**Comment by edwardaux** [comment]
oh, that looks like that's going to work perfectly. Thanks very much!
