### ISSUE TITLE
Documentation is Missing

### ISSUE THREAD

**Issue by divinemaredi** [aleksanderwozniak/table_calendar#404]
Hi there, I don't know if it's only happening on my side but when I try to access the API docs, flutter responds with this message:

![Table Calendar Screenshot #3](https://user-images.githubusercontent.com/65621952/108199564-e551bd00-7125-11eb-8cfd-2703c64eb096.PNG)

So I'd kindly like to know how I can fix this if it's only me?

Thanks.

**Comment by divinemaredi** [comment]
Okay seems I just had to click "Check other versions" of the package 👍🏼

**Comment by olistik** [comment]
@divinemaredi I suppose the problem persists.
The _latest_ and _2.3.3_ links are broken: https://pub.dev/documentation/table_calendar/latest/table_calendar/table_calendar-library.html
And the only one currently working is https://pub.dev/documentation/table_calendar/2.3.2/

**Comment by aleksanderwozniak** [comment]
There seems to be some issue with pub.dev at the moment, I have no idea why the docs for 2.3.3 are missing now.

As a temporary solution please use [docs for 2.3.2](https://pub.dev/documentation/table_calendar/2.3.2/table_calendar/table_calendar-library.html). This definitely is not ideal, but docs for 2.3.2 are actually exactly the same as docs for 2.3.3.

**Comment by aleksanderwozniak** [comment]
Looks like the [docs for 2.3.3](https://pub.dev/documentation/table_calendar/latest/) are available again.
