### ISSUE TITLE
New Feature: Support recurring event

### ISSUE THREAD

**Issue by tuyen-vuduc** [aleksanderwozniak/table_calendar#407]
Hi,

Do we have any plan to support recurring event?

Regards.

**Comment by aleksanderwozniak** [comment]
Hi,

You can use [3.0.0-beta](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-beta#installation) for this feature - here is a [short tutorial](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-beta#cyclic-events).

If you want to get this in 2.3.3, you will need to prepare the data beforehand, by yourself. You will need to create a `Map<DateTime, List<T>>`, and handle recurring events manually.

**Comment by tuyen-vuduc** [comment]
@aleksanderwozniak Thanks a lot for your info.
