### ISSUE TITLE
Feature request: Option/Callback to disable eventless dates

### ISSUE THREAD

**Issue by byronferguson** [aleksanderwozniak/table_calendar#41]
We can currently style dates based on whether any events are passed into the builder; however, it would be advantageous to remove selection on dates which do not have events.

**Comment by aleksanderwozniak** [comment]
I am not sure what is your desired effect. Can you elaborate?

**Comment by aleksanderwozniak** [comment]
You can use `enabledDayPredicate` for this effect. Check if a given DateTime object has any events, and if not - return false.

If you just want to style eventless dates differently, without actually disabling them, then you can use `CalendarBuilders`.
