### ISSUE TITLE
Day builder

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [aleksanderwozniak/table_calendar#411]
I have posted few features request recently however all of them can be solved with custom day builder.

However in order not to create everything from scratch it would be awesome to have example template. Then I could wrap days with gesture detector and other features. 

Maybe all this is available already - just cannot find proper api docs.

**Comment by aleksanderwozniak** [comment]
Answered to your other questions, they can be achieved without using custom builders. 
Here is a simple example of one of those builders though:

https://github.com/aleksanderwozniak/table_calendar/blob/5721feea4e555af6a8ab6d75f373fba173cd27f1/example/lib/main.dart#L220-L235
