### ISSUE TITLE
Supporting holidays spanning many days.

### ISSUE THREAD

**Issue by IronforgeAsh** [aleksanderwozniak/table_calendar#412]
I'm looking into using this, and I have a design I have to follow: 
![image](https://user-images.githubusercontent.com/63781155/108850819-aca95c00-75db-11eb-9881-c4efc1ad1175.png)

As you can see, there are some colored ranges, these are holiday periods for various people.

I figured it would be good to ask here, while I'm also looking into it. 

If I find a solution ill post it here :)

**Comment by aleksanderwozniak** [comment]
You can try using [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html) for that - `dayBuilder` seems to be a good fit. I would check if the `date` is within the holiday range, and if so - then return stylized calendar cell.

**Comment by IronforgeAsh** [comment]
Yeah, I've got close to what I need, but it seems like the builders render in an order I did not expect.

![image](https://user-images.githubusercontent.com/63781155/108863218-de74ef80-75e8-11eb-980e-835cd65a5d25.png)
```
              markersBuilder: (context, date, events, holidays) {
              final children = <Widget>[];

              BorderRadius radius = BorderRadius.zero;

              if (isStartDayOfPhase(date)) {
                radius = BorderRadius.horizontal(left: Radius.circular(25));
              } else if (isEndDayOfPhase(date)) {
                radius = BorderRadius.horizontal(right: Radius.circular(25));
              }

              if (events.isNotEmpty) {
                children.add(
                  Container(
                    margin: const EdgeInsets.symmetric(vertical: 8),
                    decoration: BoxDecoration(
                      color: getPhaseColor(date),
                      borderRadius: radius,
                    ),
                    width: 60,
                    height: 60,
                    child: Container(),
                  ),
                );
              }

              return children;
            },
```

Is there a way to change the render order? Ideally, I want:

Events
Today
Selected Date

instead of
Today
Selected Date
Events

**Comment by aleksanderwozniak** [comment]
Unfortunately event markers will always be rendered on top of cell content. You can return a Stack in `markersBuilder`, but in your case I would still go with `dayBuilder`. Here is a somewhat similar example:
https://github.com/aleksanderwozniak/table_calendar/blob/5721feea4e555af6a8ab6d75f373fba173cd27f1/example/lib/main.dart#L236-L248

To have selected day with range background you could use a Stack in `selectedDayBuilder`.

**Comment by IronforgeAsh** [comment]
Added support to do this without needing to use another day builder.

https://github.com/aleksanderwozniak/table_calendar/pull/413

**Comment by aleksanderwozniak** [comment]
Thanks for submitting a PR, however I'm not too keen on adding new features to v2 since [v3 has already been published](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0).

This is also already built into v3 - you can use `rangeHighlightBuilder` to achieve the same result, because it renders behind the cell content.

**Comment by aleksanderwozniak** [comment]
I assume this is solved and can be closed now - feel free to reopen if otherwise.
