### ISSUE TITLE
How do  i change header text color for weekend

### ISSUE THREAD

**Issue by fremfi** [aleksanderwozniak/table_calendar#414]
I can't seem to find a way to change the red color for sat and sun to  black. see image below;
<img width="301" alt="Screen Shot 2021-02-23 at 10 36 22 PM" src="https://user-images.githubusercontent.com/20648834/108943846-90331100-7627-11eb-89c0-2e170919fdf3.png">

**Comment by aleksanderwozniak** [comment]
You can use the following:
```dart
daysOfWeekStyle: DaysOfWeekStyle(
  weekendStyle: TextStyle(color: Colors.black),
),
```

**Comment by fremfi** [comment]
Thanks
