### ISSUE TITLE
How do focus viewport to my custom date?

### ISSUE THREAD

**Issue by pqtrong17** [aleksanderwozniak/table_calendar#415]
I wanna first screen appear according my custom date (not `DateTime.now()` or initialSelect). How do make it?

**Comment by pqtrong17** [comment]
I tried 
```
calendarController.nextPage();
```
but it not working.

Here my table calendar:
```
TableCalendar(
            calendarController: controller.calendarController,
            startingDayOfWeek: StartingDayOfWeek.monday,
            headerVisible: false,
            initialCalendarFormat: CalendarFormat.week,
            // initialSelectedDay: DateTime.now().add(Duration(days: DateTime.now().weekday)),
            calendarStyle: CalendarStyle(
              selectedColor: blueMainColorApp,
            ),
          ),
```

**Comment by aleksanderwozniak** [comment]
You can use `calendarController.setFocusedDay()` for this.

For example, add those lines to `initState`:
```dart
SchedulerBinding.instance.addPostFrameCallback((_) {
  _calendarController.setFocusedDay(...);
});
```

You can also switch to [v3 of the package](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0) and use [focusedDay](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-nullsafety#basic-setup) property of the widget itself.

**Comment by aleksanderwozniak** [comment]
I assume this can be closed now - feel free to reopen if otherwise.
