### ISSUE TITLE
Displaying  events from stream on launch

### ISSUE THREAD

**Issue by doodatales** [aleksanderwozniak/table_calendar#416]
I'm having trouble displaying events automatically on launch when the events are pulled from a stream in the main build widget.  In the example app, the _selectedDay is initiated to today (DateTime.now()), and "today"'s events are automatically pulled since the events are hard coded.  However when the events are pulled in from a stream, no events are displayed until you click on a date, including today's date.  Any advice on this?

**Comment by aleksanderwozniak** [comment]
Sounds like a duplicate of #278, feel free to reopen if otherwise.

**Comment by doodatales** [comment]
Thanks so much, don't know how I missed that.
