### ISSUE TITLE
Russian locale support?

### ISSUE THREAD

**Issue by Tamerlanchiques** [aleksanderwozniak/table_calendar#417]
Whats about Russian locale support?

**Comment by aleksanderwozniak** [comment]
Check out [this section](https://github.com/aleksanderwozniak/table_calendar#locale).

**Comment by KrillioSokolov** [comment]
@aleksanderwozniak, it haven't work. I've done all by instruction. I found samples of code for Portuguese and implemented it and It works. But when I try to use Russian or Ukrainian or Belorussia it wont. I've even try Iraq and its work) but not with 'ru_RU' 
<img width="542" alt="Screenshot 2021-03-14 at 17 35 38" src="https://user-images.githubusercontent.com/23337273/111074459-b3950180-84eb-11eb-8fd0-6c8555925d5c.png">
<img width="408" alt="Screenshot 2021-03-14 at 17 36 22" src="https://user-images.githubusercontent.com/23337273/111074478-cc051c00-84eb-11eb-8f9f-1489da684bd9.png">
<img width="1080" alt="Screenshot 2021-03-14 at 17 36 46" src="https://user-images.githubusercontent.com/23337273/111074486-daebce80-84eb-11eb-8e33-f9ea248dc5aa.png">
