### ISSUE TITLE
Add type to calendar

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [aleksanderwozniak/table_calendar#418]
It would be good if we can specify type for events.
e.g. I am adding List<Orders> to events but on day selected I am receiving List<dynamic>.
If there would be functionality to specify generic type like: TableCalendar<Order>... I would not have to cast to Order... It would be super awesome.

**Comment by aleksanderwozniak** [comment]
Generic types have been [added in v3](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0) - here is [more info](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0#events) on that. Note that you will need to be on `flutter channel beta` in order to use v3.
