### ISSUE TITLE
Swipe day to next day

### ISSUE THREAD

**Issue by AFAS-HHO** [aleksanderwozniak/table_calendar#419]
Would be good if we can swipe from day to day, so the user doesn't have to press on the day itself.

Some way to swipe on the content of the day to go to next/previous day. Just like you can do on the week itself (w/ CalendarFormat.week)

E.g.:
![image](https://user-images.githubusercontent.com/52655616/109644131-61e89080-7b55-11eb-9166-ea23b6419bed.png)

**Comment by aleksanderwozniak** [comment]
You could use [SimpleGestureDetector](https://pub.dev/packages/simple_gesture_detector) for that. Wrap the content of the day with it, and provide `onHorizontalSwipe` callback. Inside that callback [update the selected day](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarController/setSelectedDay.html) to either a previous or next day, depending on swipe direction.

**Comment by AFAS-HHO** [comment]
Thanks for the pointers.
Unfortunately it doesn't allow for animated behaviour, so I examined the behaviour of sliding through the weeks and came up with the following:
( selectedDate is the current selected date set from from onDaySelected )

```dart
         AnimatedSwitcher(
            // same as sliding week, so sliding in next week is in sync with the day sliding in
            duration: const Duration(milliseconds: 350),
            switchInCurve: Curves.decelerate,
            transitionBuilder: (child, animation) {
              return SlideTransition(
                position: Tween<Offset>(
                        begin: Offset(daySwipeTransitionOffsetValue, 0),
                        end: const Offset(0, 0))
                    .animate(animation),
                child: child,
              );
            },
            layoutBuilder: (currentChild, _) => currentChild,
            child: Dismissible(
              key: ValueKey("Content$selectedDate"),
              resizeDuration: null,
              onDismissed: (direction) {
                // Set value of offset for next item to it feels like it's sliding in the next day
                daySwipeTransitionOffsetValue =
                    direction == DismissDirection.endToStart ? 1 : -1;
                // Change selected day (forward/backwards) depending on swipe direction
                _calendarController.setSelectedDay(
                  direction == DismissDirection.startToEnd
                      ? selectedDate.subtract(const Duration(days: 1))
                      : selectedDate.add(const Duration(days: 1)),
                  runCallback: true,
                );
              },
              child: content(),
            ),
          ),

**Comment by Somtobro** [comment]
@AFAS-HHO 
Hey bro, I'm trying to achieve exactly the same thing but there's no controller anymore.
I tried to use pageview builder to achieve this but got stuck. Would appreciate your help

**Comment by Somtobro** [comment]
@AFAS-HHO 
Hey bro, I'm trying to achieve exactly the same thing but there's no controller anymore.
I tried to use pageview builder to achieve this but got stuck. Would appreciate your help
