### ISSUE TITLE
Empty or null events list

### ISSUE THREAD

**Issue by philipjbousfield** [aleksanderwozniak/table_calendar#42]
A minor issue, but a null or empty events list (map) results in an exception. If I populate with 1 dummy event, the issue disappears.

**Comment by aleksanderwozniak** [comment]
Are you sure about empty `events` map throwing an exception? It is the default value:
```dart
TableCalendar({
  ...
  this.events = const {},
  ...
```

**Comment by philipjbousfield** [comment]
Aleksander,

 

My mistake, it was just null that raises an exception.

 

Thanks for the very speedy reply.

 

Phil

**Comment by aleksanderwozniak** [comment]
No problem
