### ISSUE TITLE
Add events with the same days to the same list

### ISSUE THREAD

**Issue by HasanMuslemani** [aleksanderwozniak/table_calendar#423]
So I have a list of events that I'm grabbing from a database all with a DateTime attached to them. How do I create lists where each event with the same Date gets added to the same list?

A stripped-down example of how my model is represented:

class Event {
     DateTime dateTime;
     String name;
}

A stripped-down example of the results from the database:

[Event("jan. 5", "event 1"), Event("feb. 6", "event 2"), Event("jan. 5", "event 3"), Event("jan. 6", "event 4"), Event("feb. 6", "event 7"),];

Obviously the dates would be actual DateTime values but this was just for an example. How would I create the lists so all the events with the same day get added to the same list?

**Comment by HasanMuslemani** [comment]
Ok, so just to follow up I think I might've figured out a solution so if someone can just let me know if I'm on the right track. I would create a DateTime(year, month, day) using my dateTime property (basically strip out the time) then check if that DateTime is equal to null in my events map? So like:

var date = DateTime(dateTime.year, dateTime.month, dateTime.day);

if (_events[date] == null) {
//create new list
} else {
//clone the list and add the new value
}

Is this the way to go about this?

**Comment by aleksanderwozniak** [comment]
For v2.3.3 I'd suggest using something like [groupBy](https://stackoverflow.com/questions/54029370/flutter-dart-how-to-groupby-list-of-maps).

For [v3.0.0](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0), something like this would be sufficient:
```dart
eventLoader: (day) {
  return eventList.where((event) => isSameDay(day, event.dateTime));
},
```
where `eventList` is your list from database.

**Comment by HasanMuslemani** [comment]
@aleksanderwozniak Exactly what I needed, thank you so much!!
