### ISSUE TITLE
Possible typo on the name of DayBuilder parameter.

### ISSUE THREAD

**Issue by SametSahin10** [aleksanderwozniak/table_calendar#424]
I've migrated to the null safe version of the package (table_calendar: ^3.0.0-null-safety.1). While adapting my codebase to the new version, the name of the DayBuilder parameter got my attention. `dowBuilder`. Is this a typo? Shouldn't it be `dayBuilder`?. I've searched for the meaning of **dow** but I couldn't find anything related.

```
/// Custom builder for days of the week labels (Mon, Tue, Wed, etc.).
final DayBuilder? dowBuilder;
```

**Comment by aleksanderwozniak** [comment]
"dow" is supposed to mean "days of (the) week" - `dowBuilder` is used to specify those labels between the calendar's header and body. In previous versions this was split into two separate builders: [dowWeekdayBuilder](https://pub.dev/documentation/table_calendar/2.3.3/table_calendar/CalendarBuilders/dowWeekdayBuilder.html) (for Mon-Fri) and [dowWeekendBuilder](https://pub.dev/documentation/table_calendar/2.3.3/table_calendar/CalendarBuilders/dowWeekendBuilder.html) (for Sat-Sun). I figured it was a bit redundant, so this is now merged into just one builder.

In general builders have been updated a bit. `dayBuilder` is now renamed to [defaultBuilder](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/CalendarBuilders/defaultBuilder.html), to better convey what it is doing - this is a builder with the **lowest** rendering priority, meaning that it will get overridden by everything else (selected day, holidays, etc.). [prioritizedBuilder](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/CalendarBuilders/prioritizedBuilder.html) is its counterpart with the **highest** rendering priority. You can also return `null` in those builders - in that case the builder will be skipped for given condition, allowing a mix-and-match approach.

**Comment by SametSahin10** [comment]
Okay, I think I get it now. Thanks for the response. table_calendar is a great package. I appreciate the effort. ✌️
