### ISSUE TITLE
calendar "eats" scrolling events

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [aleksanderwozniak/table_calendar#427]
Hi,

when i set calendar available calendar format to: ```availableCalendarFormats: const {CalendarFormat.month: 'month'},``` calendar works as expected - is not shrinking while swiping over it (dos not change to 2 weeks and week) - however it also "eatc" gesture like scrolling and it is annoying because calendar takes big space of window and when i want to scroll down i have to grab screen place without calendar. 
I would expect if calendar is not "shrinakble" it should not listen for moving gestures just for day gestures.

**Comment by aleksanderwozniak** [comment]
Hi,

You can use `availableGestures: AvailableGestures.horizontalSwipe` to prevent the widget from catching vertical swipes.

**Comment by vytautas-pranskunas-** [comment]
I really love how your calendar is built ant maintained :) 
Thanks
