### ISSUE TITLE
Feature Request - Callback onChangeMoth

### ISSUE THREAD

**Issue by andersonmendesdev** [aleksanderwozniak/table_calendar#428]
Wouldn't it be possible to add a callback for when the calendar month changes? Example when navigating from one month to the other the callback is triggered.

**Comment by aleksanderwozniak** [comment]
You can use [onPageChanged](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/TableCalendar/onPageChanged.html) for this in v3.0.0

**Comment by andersonmendesdev** [comment]
@aleksanderwozniak Thank you, I will check.

**Comment by aleksanderwozniak** [comment]
I think this can be closed by now, feel free to reopen if otherwise.
