### ISSUE TITLE
setSelectedDay not working properly

### ISSUE THREAD

**Issue by dcarriola** [aleksanderwozniak/table_calendar#431]
Hi, I have the following code:

```
onHeaderTapped: (_) => _calendarController.setSelectedDay(
        DateTime.now(),
        runCallback: true,
),
```

but when I updated the package to version 2.3.3, it stopped working. There's no animation going to the date specified but the onDaySelected function is called correctly. Am I doing something wrong? Please, let me know.
Thanks!

Flutter v.2.0.2
Dart v.2.12.1
Package v.2.3.3

**Comment by aleksanderwozniak** [comment]
Hi,

You might need to add a `setState()` (or its equivalent for the state management you use) in there, to trigger the calendar widget to rebuild.

**Comment by dcarriola** [comment]
Yeah, that was missing. Thanks!!!
