### ISSUE TITLE
dayBuilder

### ISSUE THREAD

**Issue by herman-the-worm** [aleksanderwozniak/table_calendar#432]
Hello,

dayBuilder in 2.3.3 is not pushing changes onto today cell and any other normal day cells. 

It does add the size of the container and changes the shape, but it is not possible to decrease the size of the cell in the day builder (container, width, height parameters) as it is not applying changes to make them smaller.

Any fix that you could think of?

@aleksanderwozniak

**Comment by aleksanderwozniak** [comment]
Hi,

You will need to provide other builders (like `todayDayBuilder`, `selectedDayBuilder`, etc.) as well, as `dayBuilder` only affects day cells that aren't already set by anything else. If you want to use a single builder that overrides every calendar cell regardless of its status (today/selected/default/etc.), then you will need to use [v3.0.0](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.1) - it has a [prioritizedBuilder](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/CalendarBuilders/prioritizedBuilder.html) just for that.

**Comment by herman-the-worm** [comment]
Thanks for your reply.

If I have only dayBuilder active and all other builders disabled I can see the changes for all calendar cells. 

What I am trying to do is change the shape to BoxShape.circle and then shrink the size of it.

it does change all calendar cells to box shape.circle but whenever I change the width and height of the container that builds the cell not changes whatsoever are applied.

**Comment by herman-the-worm** [comment]
@aleksanderwozniak

**Comment by aleksanderwozniak** [comment]
I assume you are setting width/height of that cell container - I'd suggest trying to wrap the container in a `Center` widget, or using a `margin` property instead.

**Comment by herman-the-worm** [comment]
@aleksanderwozniak Thank you I will try to apply this in my code

**Comment by herman-the-worm** [comment]
It worked.

This issue can be closed now 

Thanks again @aleksanderwozniak
