### ISSUE TITLE
Locale 'ru_RU' doesn't work and throw an error. InitializeDateFormatting has beed used.

### ISSUE THREAD

**Issue by KrillioSokolov** [aleksanderwozniak/table_calendar#433]
@aleksanderwozniak, Russian locale haven't work. I've done all by instruction. I found samples of code for Portuguese and implemented it and It works. But when I try to use Russian or Ukrainian or Belorussia it wont. I've even try Iraq and its work) but not with 'ru_RU' 
<img width="542" alt="Screenshot 2021-03-14 at 17 35 38" src="https://user-images.githubusercontent.com/23337273/111074459-b3950180-84eb-11eb-8fd0-6c8555925d5c.png">
<img width="408" alt="Screenshot 2021-03-14 at 17 36 22" src="https://user-images.githubusercontent.com/23337273/111074478-cc051c00-84eb-11eb-8f9f-1489da684bd9.png">
<img width="1080" alt="Screenshot 2021-03-14 at 17 36 46" src="https://user-images.githubusercontent.com/23337273/111074486-daebce80-84eb-11eb-8e33-f9ea248dc5aa.png">

_Originally posted by @KrillioSokolov in https://github.com/aleksanderwozniak/table_calendar/issues/417#issuecomment-798928612_

**Comment by aleksanderwozniak** [comment]
Can you check if `locale: 'ru_RU'` works for you in example project? It doesn't seem to have any issues on my end:

<img src=https://user-images.githubusercontent.com/22658673/111078572-7124f200-84f6-11eb-8f49-096f96dc691f.png width=300>

**Comment by KrillioSokolov** [comment]
It seems like it won't work with intl localisation... initializeDateFormatting conflicting with

 [
      const AppLocalizationDelegate(),
      GlobalMaterialLocalizations.delegate,
      GlobalWidgetsLocalizations.delegate,
      GlobalCupertinoLocalizations.delegate,
    ];

**Comment by aleksanderwozniak** [comment]
I just tried it on the example project - looks like you can safely remove the conflicting `initializeDateFormatting()` if you are using `localizationsDelegates`. Doing so still allowed me to use `locale: 'ru_RU'` without any hiccups.

**Comment by Artem-Sobolev** [comment]
> I just tried it on the example project - looks like you can safely remove the conflicting `initializeDateFormatting()` if you are using `localizationsDelegates`. Doing so still allowed me to use `locale: 'ru_RU'` without any hiccups.

The problem is not solved with deleting `initializeDateFormatting()` in main function. The problem remains if there is a need to use some functions from intl package with table_calendar widget. I've also tried polish and spanish locale and they work fine but russian locale doesn't work.

**Comment by aleksanderwozniak** [comment]
@Artem-Sobolev 
Please try running the [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart) with `'ru_RU'` locale and see if the problem is still present.

**Comment by KrillioSokolov** [comment]
![Uploading Screenshot 2021-03-16 at 18.12.26.png…]()

**Comment by Artem-Sobolev** [comment]
> For header locale works perfectly in Russian, but not for weekdays. It's strange...
> 
> <img alt="Screenshot 2021-03-16 at 18 13 57" width="497" src="https://user-images.githubusercontent.com/23337273/111342701-60ee4d80-8683-11eb-806d-af6474bf044f.png">

So, it seems I have found the root of the problem for myself. The problem was in calling 
```dowTextBuilder: (date, locale) {
          return DateFormat.E(locale)
              .format(date)
              //.substring(0, 3) <- here is the problem
              .toLowerCase();
        }
```
so the issue isn't actually in this package or something but in my code. Here as you can see I'm trying to cut the string and only take first three letters. And here is the trick: in english you have for example "mon, tue, wed and etc", but in russian you get "пн, вт, ср, чт..." thus you can't take the third letter when taking a substring. It was a bit confusing to find since debug console messages didn't point on this line but after few shenanigans I've finally found it. After I've found this line I went through all similar lines of code and fixed them where it is needed.

**Comment by KrillioSokolov** [comment]
> > For header locale works perfectly in Russian, but not for weekdays. It's strange...
> > <img alt="Screenshot 2021-03-16 at 18 13 57" width="497" src="https://user-images.githubusercontent.com/23337273/111342701-60ee4d80-8683-11eb-806d-af6474bf044f.png">
> 
> @KrillioSokolov So, it seems I have found the root of the problem for myself. The problem was in calling
> 
> ```
> dowTextBuilder: (date, locale) {
>           return DateFormat.E(locale)
>               .format(date)
>               //.substring(0, 3)
>               .toLowerCase();
>         }
> ```
> 
> so the issue isn't actually in this package or something but in my code. Here as you can see I'm trying to cut the string and only take first three letters. And here is the trick: in english you have for example "mon, tue, wed and etc", but in russian you get "пн, вт, ср, чт..." thus you can't take the third letter when taking a substring. It was a bit confusing to find since debug console messages didn't point on this line but after few shenanigans I've finally found it. After I've found this line I went through all similar lines of code and fixed them where it is needed and now everything works fine.

Looks like we copy code from the medium, where table calendars was compared)) because I've the same lines of code))

**Comment by Tamerlanchiques** [comment]
@aleksanderwozniak Just ran table_calendar/example and ru_RU locale works fine for me so never mind.

**Comment by Tamerlanchiques** [comment]
But, 2 weeks / week / month selector didn't translated.

**Comment by aleksanderwozniak** [comment]
Looks like this can be closed now.

@Tamerlanchiques 
You need to provide your own translations for the format button: https://github.com/aleksanderwozniak/table_calendar#specifying-a-language. Use `availableCalendarFormats` for that.
