### ISSUE TITLE
migration guide from 2.x.x to 3.0.0

### ISSUE THREAD

**Issue by killerm250m** [aleksanderwozniak/table_calendar#434]
since there is breaking changes in version 3.0.0 I can't use this library, is there are any tutorial to migrate the library ?

Thank you.

**Comment by aleksanderwozniak** [comment]
Yes, for now you can refer to https://github.com/aleksanderwozniak/table_calendar/issues/153#issuecomment-772881560 for info on updating the package to v3.0.0

**Comment by killerm250m** [comment]
> Yes, for now you can refer to [#153 (comment)](https://github.com/aleksanderwozniak/table_calendar/issues/153#issuecomment-772881560) for info on updating the package to v3.0.0

Thank you

**Comment by Boehrsi** [comment]
@aleksanderwozniak I'm sorry for commenting on this closed issue, but I was searching for the least intrusive way of asking you if there is already a release date for the 3.0.0 version.
I'm currently looking forward to the stable release, to migrate one of my production apps to the new version. Thanks for the awesome library by the way and I really like the direction the 3.0.0 version is going. 👍

**Comment by aleksanderwozniak** [comment]
@Boehrsi 
Probably in a couple of days, I basically want to add some more info to the README

**Comment by aleksanderwozniak** [comment]
@Boehrsi 
Stable 3.0.0 release has been published today!

**Comment by Boehrsi** [comment]
@aleksanderwozniak 
Thanks a lot for the info. I'm already migrating, awesome job!

**Comment by mshivkumar** [comment]
> Yes, for now you can refer to [#153 (comment)](https://github.com/aleksanderwozniak/table_calendar/issues/153#issuecomment-772881560) for info on updating the package to v3.0.0

can i use v3.0.0-beta in my production app?

**Comment by aleksanderwozniak** [comment]
@mshivkumar 
v3.0.0-beta was a temporary branch, you can use [stable v3.0.0](https://pub.dev/packages/table_calendar/versions/3.0.0) now.
