### ISSUE TITLE
Change Calendar Format on Orientation Change

### ISSUE THREAD

**Issue by HasanMuslemani** [aleksanderwozniak/table_calendar#435]
How do I change the format of the calendar from month view to week view when the phone goes from portrait to landscape? I know about MediaQuery.of(context).orientation and the calendarController.setCalendarFormat() but I'm not sure where to use them.

**Comment by aleksanderwozniak** [comment]
Try supplying a different `initialCalendarFormat` whenever the orientation is changed. You can use something like `OrientationBuilder` for that.
