### ISSUE TITLE
Create events by period

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#436]
I have a rent period selection for which I can create notifications. For that I can pass the days that I need to create events to but if I select a period of 2 years to have a weekly rent for example, that's consuming too much process.

Is there any way to make this process easier/lighter?

![Screenshot_1615849843](https://user-images.githubusercontent.com/5629919/111232763-1077e100-85ec-11eb-9e47-4f29a2b46859.png)

**Comment by aleksanderwozniak** [comment]
Checkout [this feature](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-nullsafety#cyclic-events) of v3.0.0

**Comment by erperejildo** [comment]
Sorry, I had to fix manually almost 500 errors when upgrading to Flutter 2...

It works fine, thanks

**Comment by erperejildo** [comment]
@aleksanderwozniak can you update the link?

**Comment by aleksanderwozniak** [comment]
https://github.com/aleksanderwozniak/table_calendar/tree/v3.0.0#cyclic-events
