### ISSUE TITLE
Animation on long press

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [aleksanderwozniak/table_calendar#437]
Hello,

I have tested in real life user long press action and it is not clearly visible either something happened or not. I was thinking to add 2 things on top of long press. 1. Vibrate - this is stright forward 2. Play some animations around pressed day. So if there any easy way to grab pressed day coordinates and use them in animation later?

**Comment by aleksanderwozniak** [comment]
Hi,

For vibration - you can trigger it inside the `onDayLongPressed` callback.

For animation - I would suggest using a `prioritizedBuilder` and comparing the `day` from the builder to the `selectedDay` from the long press callback. If they match, then you can return some animated widget there, and if they don't - then return `null` to let the remaining calendar cells render unchanged.

**Comment by vytautas-pranskunas-** [comment]
Hi, i will try. But cannot find prioritizedBuilder. It is not under builders...

**Comment by vytautas-pranskunas-** [comment]
Also is there a way to use default cell builder because from what i see in your repo it is private ```_CellWidget ``` because i would not like to rebuild cell from scratch i just need to add additional anmation. So it would be cool if i can say something like:
```
return daysMatch
   ? MyAnimatiendCellWidget(child: TableCalendar.defaultCellWidget(context))
   : TableCalendar.defaultCellWidget(context)
```

you know what i mean?

**Comment by vytautas-pranskunas-** [comment]
So I added a cell but problem is that everything i return from builder is in-between that cell scope i mean i cannot play animation higher than cell because it hides under.

**Comment by aleksanderwozniak** [comment]
[prioritizedBuilder](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/CalendarBuilders/prioritizedBuilder.html) is a part of v3.0.0, same for returning `null` from builders. In v2.3.3 you might need to use a couple of builders to achieve the same, as `dayBuilder` has lower priority than `selectedDayBuilder` for example. You will also need to return a default cell UI instead of `null`.


> 
> 
> So I added a cell but problem is that everything i return from builder is in-between that cell scope i mean i cannot play animation higher than cell because it hides under.

I'm not sure I follow, but if you want to have the animation as a separate widget above the calendar cell, then you can use a Stack widget inside the builders - this will allow you to have something rendered on top (or below) of the cell.

**Comment by vytautas-pranskunas-** [comment]
```
Stack widget inside the builders 
```

Exactly - i tried to use Stacj but stack boundaries ends within cell. I mean if day cell if 30x30px high for example so i can animate only within that area otherways animated widget gets hidden.

**Comment by vytautas-pranskunas-** [comment]
> Stack widget inside the builders 

Exactly - i tried to use Stack but stack boundaries ends within cell. I mean if day cell if 30x30px high for example so i can animate only within that area otherways animated widget gets hidden. Otherways it would very easy to atchieve desired result

**Comment by aleksanderwozniak** [comment]
Try setting Stack's `clipBehavior` to `Clip.none`, this should do the trick.

**Comment by vytautas-pranskunas-** [comment]
Thanks again for your help. I have completed the task with this result (maybe it would be interesting for others)

```
builders: CalendarBuilders(selectedDayBuilder: (context, date, events) {
                _triggerOpacityAaimation();

                return Stack(clipBehavior: Clip.none, children: [
                  ...[
                    _store.shouldSelectedDayPlay
                        ? Observer(
                            builder: (_) => AnimatedPositioned(
                                duration: Duration(seconds: 1),
                                curve: Curves.easeOutQuart,
                                top: _store.addEventAnimationPosition,
                                left: 9,
                                child: AnimatedOpacity(
                                    opacity: _store.addEventAnimationOpacity,
                                    duration: Duration(seconds: 1),
                                    curve: Curves.easeInQuint,
                                    child: Icon(Icons.event_available, color: CustomColors.carePurple, size: 24))))
                        : Container()
                  ],
                  AnimatedContainer(
                    key: _selectedDayKey,
                    duration: const Duration(milliseconds: 250),
                    decoration: BoxDecoration(shape: BoxShape.circle, color: CustomColors.carePurple),
                    margin: const EdgeInsets.all(6.0),
                    alignment: Alignment.center,
                    child: Text(
                      date.day.toString(),
                      style: TextStyle(color: CustomColors.careWhite, fontSize: Settings.mainFontSize),
                    ),
                  )
                ]);
              }),
```
