### ISSUE TITLE
How about adding headerBuilder

### ISSUE THREAD

**Issue by huzhiren** [aleksanderwozniak/table_calendar#44]
Fatastic project, fully customizable.
I think it would be better to be able to customize the header as well, though you can set `headerVisible` to false and added your own in the beginning.

**Comment by aleksanderwozniak** [comment]
Hmm, I am not sure how it would work out with the rest of the project. Can you tell me what end-result you would like to achieve?

**Comment by huzhiren** [comment]
Oh, thank you,  I think the header is somehow customizable.
it is headerStyle.titleTextBuilder
