### ISSUE TITLE
update start date, and end date on next page or previous page

### ISSUE THREAD

**Issue by killerm250m** [aleksanderwozniak/table_calendar#441]
I am using the version table_calendar: ^3.0.0-nullsafety.1

**Comment by aleksanderwozniak** [comment]
Do you really need to update those on page change? Those properties are there specifically to provide some boundaries to page changing. What is the purpose of updating them?

**Comment by killerm250m** [comment]
> Do you really need to update those on page change? Those properties are there specifically to provide some boundaries to page changing. What is the purpose of updating them?

I am getting calendar data/events from api, the api i send to it needs start date and end date i get those values based on the current calendar format, in version 2.3.3 there was no proplem using onVisibleDayChanged but in the 3.0.0 it's seems the method is removed and now i can not get the start date and end date.

**Comment by aleksanderwozniak** [comment]
Ah, I thought you meant `firstDay` and `lastDay` properties of the widget.

That's correct, in v3.0.0 you should use [onPageChanged](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/TableCalendar/onPageChanged.html) instead. It provides only the focused day, but that's sufficient to calculate the start and end manually. For example this will give you the first day of the visible month:
```dart
final firstDayOfMonth = DateTime.utc(focusedDay.year, focusedDay.month, 1);
```
I'd also suggest keeping this range a bit wider (span of 3 months sounds good) to prevent unexpected changes in the UI during horizontal scrolling.

**Comment by aleksanderwozniak** [comment]
Seems like this can be closed by now.

**Comment by CodingWithTashi** [comment]
It doest make sense, This solution work only with month preview. for week and two week preview, first date and last date not able to calculate

**Comment by Jihadik** [comment]
@aleksanderwozniak sorry for resurrecting this thread, but in month mode my calendar could show more days than the first day of month, for example. And the same thing with the last day of month. Also it depends on the calendar representation.

It will be very convenient to have a callback to get displayed dates range. Or at least have some utilities that from the focused date compute what is the first and what is the last date.

Also, could you pin-point to these functions in your code so as a workaround we could quickly just copy-paste from there?

**Comment by Jihadik** [comment]
Okay, I found [`_getVisibleRange`](https://github.com/aleksanderwozniak/table_calendar/blob/a0b44ae18ea6b1a7d84898f8b5090c50a8cbb115/lib/src/widgets/calendar_core.dart#L203-L214). It will be nice to have access to this function.

**Comment by eldarkk** [comment]
> Ah, I thought you meant `firstDay` and `lastDay` properties of the widget.
> 
> That's correct, in v3.0.0 you should use [onPageChanged](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/TableCalendar/onPageChanged.html) instead. It provides only the focused day, but that's sufficient to calculate the start and end manually. For example this will give you the first day of the visible month:
> 
> ```dart
> final firstDayOfMonth = DateTime.utc(focusedDay.year, focusedDay.month, 1);
> ```
> 
> I'd also suggest keeping this range a bit wider (span of 3 months sounds good) to prevent unexpected changes in the UI during horizontal scrolling.

but how to get 1st visible day of calendar (not 1st day of month) ?

**Comment by khaledsawan** [comment]
any update ?

**Comment by ChrisElliotUK** [comment]
For anyone struggling with this, you can do everything with onPageChanged. I’ve added a sample to help. Probably worth putting this in a demo somewhere.

```
 onPageChanged: (focusedDay) {
                final firstDayOfMonth =
                    DateTime(focusedDay.year, focusedDay.month, 1);
                final lastDayOfMonth = DateTime(
                  focusedDay.year,
                  focusedDay.month + 1,
                  0,
                );

                // The calendar always shows a full week so if the firsr day
                //of the month is not a monday, the calendar will show the
                //last week of the previous month.
                final firstDay = firstDayOfMonth.weekday == 1
                    ? firstDayOfMonth
                    : firstDayOfMonth.subtract(
                        Duration(days: firstDayOfMonth.weekday - 1),
                      );
                final lastDay = lastDayOfMonth.weekday == 7
                    ? lastDayOfMonth
                    : lastDayOfMonth.add(
                        Duration(days: 7 - lastDayOfMonth.weekday),
                      );


              },
```
