### ISSUE TITLE
Discussion: This library has no tests at all?

### ISSUE THREAD

**Issue by nerder** [aleksanderwozniak/table_calendar#444]
After reporting a bug I was attempting to fix the issue myself but I don't really feel confident in contribute to it since there are no tests. Keeping in mind that we really do appreciate the work done here, since we are using this from more than a year in production. I'm not attempting in any way to undermine the quality or the effort taken in making this library, but at this stage is really not easy to be to contribute it.

How other people feeling about this? There is any plan to add some tests, at least in a basic unitary level, for the core functionalities such as the ones in `calendar_controller` code?

**Comment by aleksanderwozniak** [comment]
That's a valid observation. In that case maybe you could contribute some tests? I'd be more than happy to review them.

On a side note - CalendarController is removed in [v3.0.0](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.1), which is right around the corner. See the changelog for more details.

**Comment by swissonid** [comment]
@aleksanderwozniak I saw that the CalendarController is removed, what is the alternative for it?

**Comment by aleksanderwozniak** [comment]
@swissonid 
Rebuilding the widget with updated values - check 
[this readme](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-nullsafety#usage) and #434

**Comment by aleksanderwozniak** [comment]
@swissonid 
Rebuilding the widget with updated values - check [this readme](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-nullsafety#usage) and #434

**Comment by burhanrashid52** [comment]
@aleksanderwozniak if you are interested then I can contribute some tests for `CellContnent` or 1-2 end-to-end integration tests.

**Comment by aleksanderwozniak** [comment]
@burhanrashid52 
Thanks. I'm already working on a test suite myself, but if I end up needing some extra help, I'll reach out to you.

**Comment by aleksanderwozniak** [comment]
A test suite has now been added - closing.
