### ISSUE TITLE
Is it possible to redraw the TableCalendar after changing startingDayOfWeek on the settings screen?

### ISSUE THREAD

**Issue by uchidacode** [aleksanderwozniak/table_calendar#446]
First of all, thank you. I'm using it very conveniently.

It seems that the Table Calendar cannot be redrawn even if I set the value in another widget and return to the original widget. Is there any way?

For example, if 0 is passed as an argument, I want to start on Monday, if it is 1, I want to start on Sunday.

```dart
TableCalendar(
  startingDayOfWeek: widget.startingDayOfWeek == 0
      ? StartingDayOfWeek.monday
      : StartingDayOfWeek.sunday),
```

**Comment by aleksanderwozniak** [comment]
Hi, as mentioned in https://github.com/aleksanderwozniak/table_calendar/issues/164, you will need to use [v3.0.0](https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.1) for this. 

Closing as a duplicate issue.

**Comment by uchidacode** [comment]
Thank you!!
