### ISSUE TITLE
_getVisibleDays() for CalendarFormat.twoWeeks shows the repeated week.

### ISSUE THREAD

**Issue by VrundaAgs** [aleksanderwozniak/table_calendar#447]
We have faced a problem while swiping next in calendar.
The calendar was showing as visible dates the weeks:
21st - 3rd
28th - 10th
![Screenshot 2021-03-25 at 5 51 19 PM](https://user-images.githubusercontent.com/79691862/112472082-b668df80-8d92-11eb-8ec9-852473649486.png)
![Screenshot 2021-03-25 at 5 51 39 PM](https://user-images.githubusercontent.com/79691862/112472114-c1bc0b00-8d92-11eb-8ce6-d1309c42d639.png)

**Comment by VrundaAgs** [comment]
i want to stop repeating week while swipe to next page.

**Comment by aleksanderwozniak** [comment]
This is a duplicate of https://github.com/aleksanderwozniak/table_calendar/issues/17, please check there.
