### ISSUE TITLE
How to get rid of little border between cells?

### ISSUE THREAD

**Issue by Artem-Sobolev** [aleksanderwozniak/table_calendar#448]
![Screenshot](https://user-images.githubusercontent.com/22013580/112605014-81ef3500-8e1f-11eb-81c1-89d7093d0aa1.png)

So, as you can see on the picture I have a little line between highlighted cells. I've tried to set margin to zero and border to null but this doesn't help. How can I remove it?

**Comment by aleksanderwozniak** [comment]
Check out #308, there are more details on this.
Closing as a duplicate issue.

**Comment by Artem-Sobolev** [comment]
@aleksanderwozniak oh, thank you! Haven't found this issue because I was searching for 'border' in issue title) So, from what I've read it seems like the problem is in Flutter itself, isn't it?

**Comment by aleksanderwozniak** [comment]
No problem!

Yeah, this is sadly an issue with Table and GridView widgets, so not much can be done about it without modifying those widgets. Placing TableCalendar in an outer Container (as in #382) did seem to work, but you might need to test this on a couple of different devices.
