### ISSUE TITLE
Get event from json

### ISSUE THREAD

**Issue by aachan13** [aleksanderwozniak/table_calendar#45]
I love this package so much cause it help me out through college tasks..

But, is there a way to get the events from json? so its not hard coded like the example.. Thanks..

```
 @override
  void initState() {
    super.initState();
    _selectedDay = DateTime.now();
    _events = {
      DateTime.parse("2019-03-31") : ['Event A6', 'Event B6'],
      DateTime.parse("2019-03-15") : ['Event A7', 'Event B6'],
      DateTime.parse("2019-03-02") : ['Event A6', 'Event B6'],
      DateTime.parse("2019-03-13") : ['Event A6', 'Event B6'],
    };
    _selectedEvents = _events[_selectedDay] ?? [];
    _visibleEvents = _events;

    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 400),
    );

    _controller.forward();
  }
```

**Comment by aleksanderwozniak** [comment]
That's actually really nice that you have Flutter-related tasks in college!

Getting data from JSON isn't really related to `TableCalendar`, but here is a general outline:

- Receive the JSON
- Decode JSON content to regular Dart objects
- Map those into correct format for `TableCalendar`, eg. each `DateTime` gets a `List` of `Events`, and then they are grouped into a single `Map` object

```dart
myEvents = {
DateTimeA : [EventA1, EventA2, ...],
DateTimeB : [EventB1, EventB2, ...],
...
}
```

**Comment by aachan13** [comment]
woah thanks.. 

what is the format of table calendar date actually?
is it yyyy mm dd?

**Comment by JavierDuarteC** [comment]
Hey. Im trying to add events dynamically to my calendar, but it doesnt update, after onVisibleDaysChanged I get a data map from an API. Can I get some Help on updating the events? Thanks.

**Comment by aleksanderwozniak** [comment]
@JavierDuarteC 
Take a look here #86
