### ISSUE TITLE
Do the plugin has support for making multiple dates selection?

### ISSUE THREAD

**Issue by mshivkumar** [aleksanderwozniak/table_calendar#452]
So what i'm saying is for now i'm allowed to select a single date, but what if i want to select multiple dates of a week can i do that using this plugin? do Table Calendar plugin has a support for that?

I'm adding an image for reference below.

![calendar_reference](https://user-images.githubusercontent.com/28510296/113140348-eeb26700-9245-11eb-986d-08c984fbb55f.png)

**Comment by aleksanderwozniak** [comment]
Yes, please check out #153 for more info.

Closing as a duplicate issue.

**Comment by mshivkumar** [comment]
Thanks @aleksanderwozniak for such a quick response, and really nice of you to include an example as well for the same, it proved very helpful 🙂.
