### ISSUE TITLE
Unsupported operation: Cannot set value in unmodifiable Map

### ISSUE THREAD

**Issue by hangari123** [aleksanderwozniak/table_calendar#454]
i am using easy_localization api in flutter
but if i use initializeDateFormatting() method before starting MyApp()
An error occurs (Unsupported operation: Cannot set value in unmodifiable Map)

how can i do that?

this is my code

void main() {

  **initializeDateFormatting()**.then((_) => runApp(EasyLocalization(
      supportedLocales: [Locale('en', 'US'), Locale('ko', 'KR')],
      path: 'assets/translations', // <-- change patch to your
      fallbackLocale: Locale('ko', 'KR'),
      child: MyApp()
  ),));

  print("앱실행");
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'MaterialApp_title'.tr(),

      **localizationsDelegates: context.localizationDelegates,**
      supportedLocales: context.supportedLocales,
      locale: context.locale,

      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: SelectMenu(),
    );
  }
}

**Comment by aleksanderwozniak** [comment]
You might want to check out https://github.com/aleksanderwozniak/table_calendar/issues/433

**Comment by aleksanderwozniak** [comment]
Seems like this can be closed by now.
