### ISSUE TITLE
How to pass events and custom styling to those events in 3.0.0-beta version of this app?

### ISSUE THREAD

**Issue by mshivkumar** [aleksanderwozniak/table_calendar#457]
In the previous version of the app ie. 2.3.3 the events function used to take events as Map<DateTime, List<dynamic>> and this is what i was passing to the marker function in version 2.3.3.

```
 Map<DateTime, List<dynamic>> _getSelectedDatesEvents() {
    if (widget.schedules != null) {
      for (var schedule in widget.schedules) {
        events[schedule.date] = [
          schedule.workFromHome && !schedule.canChangePlan,
          schedule.workFromHome
        ];
      }
    }
    return events;
  }
```

which would return me the  Map<DateTime, List<dynamic>> of events.

**BUT**  in version 3.0.0-beta the eventsLoader takes a list<dynamic> and also gives a DateTime parameter to the function so i'm just not able to figure out how can i use this new DateTime parameter with my existing _getSelectedDatesEvents() and return a list<dynamic> rather than a Map<DateTime, List<dynamic>> .

**AND** previously the markersBuider used to take a list of widgets, below is the code i've added for reference that how i was previously passing the markers to markersBuilder.        

```
 markersBuilder: (_, date, events, holidays) {
        return [
          Positioned(
              top: 12,
              right: 12,
              child: CircularContainer(
                  size: 5, 
                  color: events.first
                      ? Colors.transparent
                      : events[1]
                      ? Colors.transparent
                      : Colors.green))
        ] ;
      },
```

Below is the code reference on how i'm passing the markers now.

```
 markerBuilder: (_, date, events) {
        return Positioned(
            top: 12,
            right: 12,
            child: CircularContainer(
                size: 5,
                color: events.first  // getting an error  at this part
                    ? Colors.transparent
                    : events[1]
                        ? Colors.transparent
                        : Colors.green));
      }
```

But after the changes to the recent version of the plugin ie version 3.0.0-beta i'm not even able to access the .first property on the events list inside the markerbuilder function.

Any help on this would really be appreciated.

**Comment by aleksanderwozniak** [comment]
Please check out the README and examples for 3.0.0 version, they have all the details you are looking for.

**Comment by mshivkumar** [comment]
But when i'm trying to pass custom styling to events all my dates are getting marked as events.

**Comment by aleksanderwozniak** [comment]
Try wrapping your code with `if (events.isNotEmpty) {...}`. This will prevent assigning event markers to days without events.

**Comment by aleksanderwozniak** [comment]
Seems like this can be closed by now.
