### ISSUE TITLE
selectedTextStyle & selectedDecoration are not working

### ISSUE THREAD

**Issue by UjjwaRaijada** [aleksanderwozniak/table_calendar#458]
on clicking on a date, that date is not getting highlighted.
version ^3.0.0-nullsafety.1

selectedTextStyle: Theme.of(context).textTheme.bodyText2!.copyWith(
    color: Colors.orange,
),
selectedDecoration: BoxDecoration(
  borderRadius: BorderRadius.all(Radius.circular(25)),
  border: Border.all(color: Colors.pink),
  color: Colors.pink,
),

**Comment by aleksanderwozniak** [comment]
Have you fully completed the setup from README? 
https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-nullsafety#adding-interactivity

You can also check the provided examples.

**Comment by nehal076** [comment]
This link is broken

**Comment by UjjwaRaijada** [comment]
> This link is broken

share your code where you are having problem.
