### ISSUE TITLE
How can i not mark weekend and previous days as selected in multiselect mode?

### ISSUE THREAD

**Issue by mshivkumar** [aleksanderwozniak/table_calendar#459]
I want the user to not be able to choose weekend and previous days ie. when the user selects either any weekend day/days or previous day/days that particular date should not be marked as selected and neither should be add to the list of selected days.

**Comment by aleksanderwozniak** [comment]
You can simply not add the tapped day to the `selectedDays` list/set, if the given day is a weekend. Multi-selection example will be easy to modify for this.

**Comment by aleksanderwozniak** [comment]
Seems like this can be closed by now.
