### ISSUE TITLE
Hide previous days from calendar

### ISSUE THREAD

**Issue by Mallikarjun-0369** [aleksanderwozniak/table_calendar#46]
Is there a way to hide previous days showing from table calendar, i need the current and futures day should be shown,

**Comment by aleksanderwozniak** [comment]
@Mallikarjun-0369 
You can now update to version `1.2.3` and use `startDay` and `endDay` properties:

```dart
onUnavailableDaySelected: () {
  print('Out of bounds!');
},
startDay: DateTime(2019, 6, 10),
endDay: DateTime(2019, 6, 22),
```
