### ISSUE TITLE
Bug in the header calendar type text

### ISSUE THREAD

**Issue by kingfisher-tech** [aleksanderwozniak/table_calendar#460]
hey there, thanks for the great package! looks like there's an issue with the calendar type in the header, the default is showing "2 weeks" but it goes to the month view. I am using: table_calendar: ^3.0.0-nullsafety.1

also related, would it be possible to add a parameter to remove the calendar type rounded button from the header? I see the header can be removed entirely, but I would like to keep the header and remove the rounded text widget that says "2 weeks" (I imagine others would find this feature useful as well)

![Screen Shot 2021-04-05 at 6 18 33 PM](https://user-images.githubusercontent.com/66177912/113633690-6106bb00-963b-11eb-8191-11f4d3b2418a.png)

**Comment by motu2119** [comment]
> hey there, thanks for the great package! looks like there's an issue with the calendar type in the header, the default is showing "2 weeks" but it goes to the month view. I am using: table_calendar: ^3.0.0-nullsafety.1

Isn't this the correct specification?
I mean, if you press "2 weeks", it will switch to two weeks, right?

**Comment by aleksanderwozniak** [comment]
@kingfisher-tech 
What @motu2119 said is right, this is supposed to switch to the displayed format on button tap. You can change this behavior (or hide the format button) - see [HeaderStyle docs](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/HeaderStyle-class.html) for more info.
