### ISSUE TITLE
v2.3.3 to 3.0.0 so many changes

### ISSUE THREAD

**Issue by chitgoks** [aleksanderwozniak/table_calendar#463]
so many properties removed and new ones added.
can you please update the change log on what is the equivalent of the removed property?

e.g.
void _onVisibleDaysChanged(DateTime first, DateTime last, CalendarFormat format)  to what?

_onDaySelected(DateTime day, List<dynamic> events)  to _onDaySelected(PageController pageController) but how can we get the day object now?

**Comment by aleksanderwozniak** [comment]
Please check out #434. You can also refer to README and examples for additional info.

**Comment by chitgoks** [comment]
Hi.  the readme is lacking. it does not mention about how to migrate onVisibleDaysChanged. that property does not exist anymore.
