### ISSUE TITLE
Show weeknumber?

### ISSUE THREAD

**Issue by Reitenator** [aleksanderwozniak/table_calendar#464]
Could it, at some time, perhaps be implemented a way to show the week number as well? 

E.g. here: 
![image](https://user-images.githubusercontent.com/12460284/114260600-44210d80-99d6-11eb-8206-5f3e4e34fa7e.png)

My suggestion is to show the week number to be raised and the text color could be the same as  the weekday names (mon,tue,wed, etc.).

**Comment by aleksanderwozniak** [comment]
Yeah, I think something like this could be added as a future enhancement. I have no plans on working on it though.

**Comment by jaredbaszler** [comment]
This is pretty easily done using the built in calendar builders.  I use `prioritizedBuilder` and then this.  This also requires you to handle and draw the circular highlights that are native to the calendar for ranges, current day, etc as well.  

Yes, it would be nice to have a week number setting to turn on to make this easier but definitely doable now.  

```
if (isMonday)
  Align(
    alignment: Alignment.bottomRight,
    child: Text(
      data.getWeek(day)?.accountingPeriod?.toString() ?? '',
      //'18',
      style: const TextStyle(
        fontSize: 10,
        color: larsonRed,
      ),
    ),
  )
```

![image](https://user-images.githubusercontent.com/9924084/139697233-864d19b8-314c-4a5c-9b6d-75fd50abb28a.png)
