### ISSUE TITLE
Question. What triggers the number of events thumbnail

### ISSUE THREAD

**Issue by chitgoks** [aleksanderwozniak/table_calendar#466]
Please see image. I have migrated the code to v3.0.0 but the only thing lacking is this one. it does not show any
![ss](https://user-images.githubusercontent.com/3955470/114383077-b4d74e00-9bbf-11eb-84a8-5dc8f9e482e9.png)

**Comment by aleksanderwozniak** [comment]
You can use `markerBuilder` to display custom event markers.

**Comment by chitgoks** [comment]
Thanks got it working. I switched to a different approach. It's weird in v3 if i put in a datetime object to the map, the key returns a date string format without Z

but in the eventLoader() function, the day returns with a Z, hence i get nothing since it cant find any in the map.

**Comment by aleksanderwozniak** [comment]
Are you using a [LinkedHashMap](
https://github.com/aleksanderwozniak/table_calendar#events) for the events map? It will make date comparison easier.

**Comment by chitgoks** [comment]
no just map. i used string date this time for v3.0.0

does it make a differ3nc e between map and linkedhashmap? i thought the
diff is the sequence when items are added.

**Comment by chitgoks** [comment]
@aleksanderwozniak  quick question. ive managed to wrap up 99% of the migration. my remaining issue is with the dates of sun and saturday, they are not colored red. only the label Sat and Sun are red. Do the numbers that fall under sat and sun need to be configured in some other property?

This is what i did
daysOfWeekStyle: DaysOfWeekStyle(
        weekendStyle: TextStyle(color: Colors.red[600])
      ),

**Comment by aleksanderwozniak** [comment]
That's because [DaysOfWeekStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/DaysOfWeekStyle-class.html) is for Mon Tue Wed (etc.) labels. What you need to use here is [CalendarStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle-class.html).

**Comment by chitgoks** [comment]
thank you . that did it :D
