### ISSUE TITLE
Event Day Decoration & Event Marker at Bottom Issue

### ISSUE THREAD

**Issue by mahesh-nadar** [aleksanderwozniak/table_calendar#467]
![Events](https://user-images.githubusercontent.com/51945043/114414326-5795c980-9bcc-11eb-94c9-11b6a4e4242f.jpeg)

I had a requirement to have different decoration (Filling the cell with color based on the event occupancy percent) for days with events and also the total number of events per day at the bottom. In version 2.3, I was able to do the fill color decoration via daybuilder for days that had events and marker builder for the bottom marker.

In version 3.0 - Iam able to do either the event day decoration or event marker at bottom not both. Can this be done in this version? Am I missing anything?

**Comment by aleksanderwozniak** [comment]
You should be able to do both. Are you using `CalendarBuilders`? Have a look at `markerBuilder`, `defaultBuilder` and `prioritizedBuilder`.

**Comment by mahesh-nadar** [comment]
Yes. Im using CalendarBuilders. In version 3.0 only markerBuilder accepts events as a input while both defaultBuilder and prioritizedBuilder has the day as input. Hence I can't use defaultBuilder or prioritizedBuilder for event based decoration.

**Comment by aleksanderwozniak** [comment]
You can, if you call your `eventLoader` function inside those builders. Since it will give you events assigned to the given `day`, you can just check if those events exist: 
- if they do, then you have a day cell with events -> use your custom UI
- if they don't, then you can return `null` to use the default styling

**Comment by mahesh-nadar** [comment]
Yes. you are correct. Thanks for the help.
