### ISSUE TITLE
Add button go to today date

### ISSUE THREAD

**Issue by lcsvcn** [aleksanderwozniak/table_calendar#470]
Please, add a button to go to the today day.

The button should be changed by Locale too, to show "Today" in the users language.

When clicked it should animate to the current week/month and select the current date.

It should hide if today is already selected.

It can be placed where the month button is right now (if there is no button to switch between modes) or placed in the left of the month/week button.
<img width="281" alt="Captura de Tela 2021-04-12 às 18 21 46" src="https://user-images.githubusercontent.com/6011385/114464313-f8c85400-9bbb-11eb-9e58-1feff5d94b05.png">

**Comment by aleksanderwozniak** [comment]
Seems like this can be closed by now.
