### ISSUE TITLE
Help: Week View Only - Place Header somewhere else AND padding above days of week and below day numbers

### ISSUE THREAD

**Issue by beachpebble** [aleksanderwozniak/table_calendar#473]
1. I want to place the Calendar header as a subtitle in the App Bar is there a way I can separate the header physically? or maybe even just the text from the header (March 2021) and still have it functional? 
2. I would like more padding overtop of the days of the week and below the numbers of the days. I have tried rowHeight and it creates space between the days of the week and the numbers of the days. I tried setting dowheight  and this adds padding below the days of the week increasing the gap between the days of the week and the numbers, the days of the week seem anchored to the top tho and this really doesn't help. I do not want space between the days of the week and the numbers, I want it above and below but can not seem to make it happen. Can you suggest a way this might work?
3. The isTodayHighlighting. Is it possible to make this wrap the day of the week and the number? Can I change the shape of it to rectangle maybe and add a radius to make it oval??

**Comment by aleksanderwozniak** [comment]
1. Check the [complex example](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/pages/complex_example.dart) to see how to provide a custom calendar header.
2. To add some padding around the TableCalendar widget, you can just wrap it with Padding widget.
3. You can make a custom UI that wraps both the day of the week and the day cell number by using [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html).

**Comment by beachpebble** [comment]
Thank-you! I did manage to get the calendar working as I want it to. Yay! And thank-you for this plugin! 

Note: Padding widget was the wrong widget to use, Container worked better for wrapping the Calendar Table, because I could color a container and could not color a padding widget.

Two more questions!
1. Can you provide an example for the focusedDayBuilder? I am a relative newbie and while documentation is excellent I'm not great at translating flutter documentation into code yet.
2. Is there an easy way to capitalize the Days of the Week? I can't seem to find a way to apply toUppercase().

And thank-you again for your help, your calendar is awesome.

**Comment by aleksanderwozniak** [comment]
[This](https://github.com/aleksanderwozniak/table_calendar/tree/v3.0.0#custom-ui-with-calendarbuilders) should be helpful. You can use that exact code (with minor modifications) to capitalize days of the week.

I suppose you mean [selectedBuilder](https://pub.dev/documentation/table_calendar/3.0.0/table_calendar/CalendarBuilders/selectedBuilder.html)? Once again, you can use code from aforementioned `dowBuilder` as a guide, it will be really similar. Use `day.day` for the day number.

**Comment by aleksanderwozniak** [comment]
Seems like this can be closed by now.
