### ISSUE TITLE
Table Calender size

### ISSUE THREAD

**Issue by neuralnetworkdumper** [aleksanderwozniak/table_calendar#474]
All the examples I've seen have the calendar at the same size, is there any way to increase the size of the calendar to take up more screen real-estate? I don't see anything in the API docs regarding increasing the size.

For example:
![image](https://user-images.githubusercontent.com/82493637/114659828-9eec9900-9d37-11eb-9b05-57b9ca71d0a4.png)

**Comment by aleksanderwozniak** [comment]
Check out [shouldFillViewport](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/shouldFillViewport.html). You might want to also use [sixWeekMonthsEnforced](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/sixWeekMonthsEnforced.html).

**Comment by desmeit** [comment]
shouldFillViewport is a good option but it looks not so nice because the days are not square.
I'm searching for a solution, it would be nice if you could scroll vertically.
Most users have their phones on portrait, which makes vertical scrolling a good option.
