### ISSUE TITLE
External setState resets Calendar 

### ISSUE THREAD

**Issue by supamunkey** [aleksanderwozniak/table_calendar#475]
Placing the `TableCalendar` into a Stateful widget and calling `setState` resets the navigational state of the calendar.

**Comment by aleksanderwozniak** [comment]
Sounds like you are not updating a [focusedDay variable](https://github.com/aleksanderwozniak/table_calendar#updating-focusedday) in your widget. You might want to check out the [basic setup](https://github.com/aleksanderwozniak/table_calendar#basic-setup) section of README.

**Comment by supamunkey** [comment]
Yea, I read more into it and realized you moved a bit of the state management outside of the widget itself.
