### ISSUE TITLE
Three weeks calendar format

### ISSUE THREAD

**Issue by campadellos** [aleksanderwozniak/table_calendar#477]
Hi.

Now it is possible to have week, two weeks and month calendar format. Is there an easy way to get to three weeks format?

I edited the code, and there are only a few places to change... Is the any interest?

**Comment by supamunkey** [comment]
The better solution is to make it n number of weeks.

**Comment by campadellos** [comment]
Yes, but that is more complex to do, especially with weeks more than 4 I think

**Comment by aleksanderwozniak** [comment]
Adding more calendar formats might come with tricky edge cases and hard to detect bugs. Let's keep the existing formats intact for now.
