### ISSUE TITLE
Changing firstDay results in unwanted behavior // version: "3.0.0"

### ISSUE THREAD

**Issue by Mexerware** [aleksanderwozniak/table_calendar#479]
Hi Guys,

when changing the firstDay with another month (earlier this case) and do a setState on it, it results in a totally unwanted behavior I guess:

In below example, the firstDay is initial 2021/04/01. When selecting 2021/04/10 the firstDay will be changed into month 03 (2021/03/16 here). When doing so, the calendar content/page jumps into march (but april is still focused here). Also, the March gets called "April" in the header. When scrolling between March and April, the March keeps the name "April".

I hope it's clear, what I want to tell you. Be free to test it out with below example code.

```
  DateTime focused = DateTime.utc(2021, 04, 16);
  DateTime selected = DateTime.utc(2021, 04, 16);
  DateTime first = DateTime.utc(2021, 04, 1);
  DateTime last = DateTime.utc(2021, 04, 30);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TableCalendar(
        focusedDay: focused,
        firstDay: first,
        lastDay: last,
        calendarFormat: CalendarFormat.month,
        availableCalendarFormats: {CalendarFormat.month: "month"},
        selectedDayPredicate: (dateTime) => dateTime == selected,
        onDaySelected: (selectedDateTime, focusedDateTime) => setState(() {
          selected = selectedDateTime;
          if (selected == DateTime.utc(2021, 04, 16))
            last = DateTime.utc(2021, 05, 16);
          else if (selected == DateTime.utc(2021, 04, 30))
            first = DateTime.utc(2021, 04, 5);
          else if (selected == DateTime.utc(2021, 04, 10))
            first = DateTime.utc(2021, 03, 16);
        }),
        onPageChanged: (focusedDateTime) => focused = focusedDateTime,
      ),
    );
  }
```

Version used: 3.0.0

Cheers

**Comment by aleksanderwozniak** [comment]
Hi,

`firstDay` and `lastDay` aren't really supposed to be changed after the initial setup, they are used to define scroll boundaries of the calendar.

What is the end goal that you have in mind?

**Comment by Mexerware** [comment]
In my case the range is hooked to the events that are stored.
When an event is added/changed/removed my app automatically updates `firstDay` and `lastDay` to always have only the dates selectable and also navigatable to that are in the range of the stored events.

Changing the `lastDay` works fine as far as I have seen.

For now, I solved it by using a ValueKey with firstDay, but that may be not the way everyone can work with.

**Comment by aleksanderwozniak** [comment]
In that case I think this can be closed now.
