### ISSUE TITLE
How to customized the size of tableCell?

### ISSUE THREAD

**Issue by dearxiaomu** [aleksanderwozniak/table_calendar#48]
The default calendar is a little big to me. I need a tighter layout calendar. I return a SizedBox in dayBuilder but it didn't work. Is there anyway to change the size of cell and  header?

**Comment by aleksanderwozniak** [comment]
You can now use `rowHeight` parameter -> update package to version `1.2.1` and you're set!

**Comment by dearxiaomu** [comment]
Thanks for your update. The width of calendar can be constrained by a `ConstrainedBox` outside. And it's better to add `headerHeight` and `weekdayHeight` parameter.

**Comment by aleksanderwozniak** [comment]
DOW row height is super simple, just use your desired fontSize:
```dart
daysOfWeekStyle: DaysOfWeekStyle(
  weekdayStyle: TextStyle(fontSize: 8),
  weekendStyle: TextStyle(fontSize: 8),
),
```

Header height is a bit more complex due to having many widgets, but it can be tailored to suit any needs:
```dart
headerStyle: HeaderStyle(
  titleTextStyle: TextStyle(fontSize: 8),
  leftChevronMargin: EdgeInsets.all(0),
  rightChevronMargin: EdgeInsets.all(0),
  leftChevronPadding: EdgeInsets.all(0),
  rightChevronPadding: EdgeInsets.all(0),
),
```
Just fiddle with those settings and you will get your results.
