### ISSUE TITLE
Getting events as needed without loading the whole database

### ISSUE THREAD

**Issue by perojas3** [aleksanderwozniak/table_calendar#480]
I know I how I cant request the earliest date and latest date, to get the interval to be able to be shown.
But afterwards, I'm not sure if I can load the the events as I need them, instead of loading the whole database.
I thought of requesting the data in eventLoader, but is synchronous, while requesting data is asynchronous.
I usually put a CircularProgressIndicator while data is loading.
There is any way to do this?

**Comment by aleksanderwozniak** [comment]
I would recommend using something like a StreamBuilder, and rebuilding TableCalendar widget when a batch of data is available. This will also allow you to display a progress indicator while data is loading.

**Comment by perojas3** [comment]
And requesting the data in eventLoader?

**Comment by aleksanderwozniak** [comment]
No, you request the data manually, and once StreamBuilder rebuilds TableCalendar with new data, you apply that data in `eventLoader`. For example like this:
```dart
return events[day] ?? [];
```

`eventLoader` is not for fetching any data from outside sources. It is used to assign a list of events to a given DateTime object inside the calendar.

**Comment by perojas3** [comment]
Ok, where I detect when a page to a new month has been turn, to start requesting the data?

**Comment by aleksanderwozniak** [comment]
Check the provided [readme](https://github.com/aleksanderwozniak/table_calendar#basic-setup) and examples.

**Comment by perojas3** [comment]
Ok, I just though that asking the whole database when you are only going to watch one month was wasteful.
But it looks like it's working ok.

**Comment by aleksanderwozniak** [comment]
There is no need to load the whole database. You can fetch a subset of data, for example `onPageChanged` callback can be used for that.

**Comment by perojas3** [comment]
> There is no need to load the whole database. You can fetch a subset of data, for example `onPageChanged` callback can be used for that.

This is exactly what I need, thanks.

**Comment by pcj** [comment]
Using onPageChanged and StreamBuilder really should be one of the core examples IMHO.
