### ISSUE TITLE
Create event example

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#481]
Examples are great but since I moved to new version lots of things changed and I'm having different issues trying to refactor my code.

Can you provide a quick example for events creation?

**Comment by erperejildo** [comment]
For example, this works:    
```
  kEvents[DateTime.now()]!.add(
        Event('New event'),
      );
```

But this doesn't:
```
  kEvents[_selectDay]!.add(
        Event('New event'),
      );
```

I'm working on the example

**Comment by erperejildo** [comment]
I think I figured it out. All events in same day need to have same hour like this:

 ```
 var _selectedTime = TimeOfDay(hour: 12, minute: 0);
 _selectedDay = new DateTime(
      DateTime.now().year,
      DateTime.now().month,
      DateTime.now().day,
      _selectedTime.hour,
      _selectedTime.minute,
    );
   
 _createEvent() {
    if (kEvents[_selectedDay] == null) {
      kEvents[_selectedDay!] = [];
    }
    setState(() {
      kEvents[_selectedDay]!.add(
        Event(
          id: "be8e60ca-2007-4a9b-a90d-e0355032b71d",
          text: 'New event',
          realTime: DateTime.now().toString(),
          time: "12:00",
          color: "#ff9800",
          paymentDay: false,
          billable: false,
          invoiceInfo: {},
        ),
      );
    });
  }
```

**Comment by erperejildo** [comment]
Despite above code works I only see the new events when I change the day. If the day has no events I don't see the created ones

**Comment by aleksanderwozniak** [comment]
There should be no changes related to addition of new events.

Beware of using `[...]!.` on a Map, you might be accessing a null value. `kEvents.update(...)` is a viable alternative, just like in https://gist.github.com/aleksanderwozniak/e9eb98bf28bd9fbb336039e1936c59aa

Not sure why you need to set the time to 12 hour, properly set up LinkedHashMap should handle DateTime objects comparison.

**Comment by erperejildo** [comment]
I added new events but they didn't show up. I thought it was because I was creating them with `DateTime.now()` so every time I clicked on the day to get all of them it was showing everything on that day by `DateTime.now()` (being different from the one created).

So I tried a fixed hour-minutes and it worked

**Comment by aleksanderwozniak** [comment]
> 
>     * **The event doesn't appear**

Do you mean on the event list below the calendar? You might need to also update the `_selectedEvents` field when adding a new event.

**Comment by erperejildo** [comment]
Correct.

How should I update it? What I call is `_createEvent()`. Should I update it by calling another function or how?

**Comment by aleksanderwozniak** [comment]
Well, you can start by analyzing the code in `onDaySelected(...)`. Like I mentioned, you need to update the data behind `_selectedEvents` field, as that data is used for the event ListView.

You can add your new event directly to the existing ones in `_selectedEvents`.

**Comment by erperejildo** [comment]
> You can add your new event directly to the existing ones in `_selectedEvents`.

how can I do that. I can push new events to `kEvents` but not to `_selectedEvents` (or I don't know how)

**Comment by aleksanderwozniak** [comment]
Just do the same thing as in example:

https://github.com/aleksanderwozniak/table_calendar/blob/129f7b0a01c9d9e6865822cb66ef5e9c61d02a71/example/lib/pages/events_example.dart#L52-L64

`_selectedEvents.value` will allow you to modify the data held by `_selectedEvents`.

**Comment by erperejildo** [comment]
Sorry, I thought I also shared that function. This is what I had:

```
void _onDaySelected(DateTime selectedDay, DateTime focusedDay) {
    if (!isSameDay(_selectedDay, selectedDay)) {
      setState(() {
        _selectedDay = new DateTime(
          selectedDay.year,
          selectedDay.month,
          selectedDay.day,
          _selectedTime.hour,
          _selectedTime.minute,
        );
        _focusedDay = _selectedDay;
      });
      _selectedEvents.value = _getEventsForDay(_selectedDay!);
    }
  }
```

It's basically the same

**Comment by aleksanderwozniak** [comment]
So one option would be to use
```dart
_selectedEvents.value = _getEventsForDay(_selectedDay!);
```
when you are adding the new event, right?

Again:

> 
> `_selectedEvents.value` will allow you to modify the data held by `_selectedEvents`.

**Comment by erperejildo** [comment]
Perfect, calling that from the creation function worked
