### ISSUE TITLE
_getEventsForDay triggers many times

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#482]
This triggers once for each event we have in the calendar. Also when we create an event. Is that normal?

<img width="638" alt="Screenshot 2021-04-17 at 10 53 08" src="https://user-images.githubusercontent.com/5629919/115107484-5d443400-9f6b-11eb-919c-a919f1a40365.png">

**Comment by aleksanderwozniak** [comment]
This is normal, each visible day cell calls the `eventLoader` on page rebuild. That's why you get a DateTime object (day) and return a list of events (to assign to that day).

Don't perform heavy calculations in it, use it just to provide the list of events for a day - for example like this:
```dart
return events[day] ?? [];
```
