### ISSUE TITLE
Forcing the first day of displayed calendar

### ISSUE THREAD

**Issue by campadellos** [aleksanderwozniak/table_calendar#483]
Is there a way to force the first day shown of the calendar? For instance, in my particular case, the calendar should start with the 19th of April.

**Comment by aleksanderwozniak** [comment]
Use [focusedDay](https://github.com/aleksanderwozniak/table_calendar#basic-setup)

**Comment by campadellos** [comment]
Yeah, I realized my problem is that focusedDay is not enough because I use the three weeks format (see #477). Since this is not standard, I close the issue.
