### ISSUE TITLE
Feature request - subscribe to public calendar

### ISSUE THREAD

**Issue by tylerdurden-87** [aleksanderwozniak/table_calendar#484]
First of all, I'd like to thank for this extremely useful package. Has helped out app a lot. Was curious if it is possible right now or if not to add this feature in: which is to be able to subscribe to a public calendar using the generated URL that google calendar produces when sharing a calendar to the public. 

Thank you

**Comment by aleksanderwozniak** [comment]
Hi,

This is something beyond the scope of this package. You can of course still use it to display events from Google calendar, but you will have to first retrieve them by yourself.
