### ISSUE TITLE
show only months ( Jan to Dec)

### ISSUE THREAD

**Issue by tot14883** [aleksanderwozniak/table_calendar#486]
Hi, Thank for your library that awesome. So it's useful for me and any developer.

I want to show only the 12 months of the years and select years in the calendar .
How can I do it?

**Comment by aleksanderwozniak** [comment]
Hi, for something like a month picker or year picker you might need to use another widget. 

You can of course provide the selected month/year to TableCalendar later on, by setting the `focusedDay` property.
