### ISSUE TITLE
How can I make special occasions unselectable

### ISSUE THREAD

**Issue by osmaneser** [aleksanderwozniak/table_calendar#487]
How can I make it unclickable for special dates,

```

final blockDates = [
DateTime(2021, 04, 01),
DateTime(2021, 04, 03),
DateTime(2021, 04, 20),
DateTime(2021, 04, 10)
];


```
I have a list of these days. I want to prevent them from clicking

**Comment by osmaneser** [comment]
I found method.
I used enabledDayPredicate property.

sorry for creating unnecessary issues.

**Comment by quetool** [comment]
@osmaneser Can you please share your solution?

**Comment by quetool** [comment]
I just found a way, thanks!
