### ISSUE TITLE
Calendar marker style by date?

### ISSUE THREAD

**Issue by jdeltoft** [aleksanderwozniak/table_calendar#488]
Is there a way to change the color of markers by date (like grey for past days from DateTime.now()) ?  I changed color with:

```
...
                calendarStyle: CalendarStyle(
                  markerDecoration: BoxDecoration(
                    color: Colors.blue,
                    borderRadius: BorderRadius.circular(7),
                   ),
                 ),
...
```

**Comment by aleksanderwozniak** [comment]
You can use [singleMarkerBuilder](https://pub.dev/documentation/table_calendar/3.0.0/table_calendar/CalendarBuilders/singleMarkerBuilder.html) for that, you can even return `null` from it, to use the default style - [like here](https://github.com/aleksanderwozniak/table_calendar/tree/v3.0.0#custom-ui-with-calendarbuilders).

**Comment by jdeltoft** [comment]
ah, ok, thanks. Will give it a try

**Comment by jdeltoft** [comment]
Hmmm, it would be good to have more CalendarBuilder examples?  Something like this?

`                  calendarBuilders: CalendarBuilders(
                    dowBuilder: (context, day) {
                      if (day.isBefore(DateTime.now())) {
                        calendarStyle: CalendarStyle(
                          markerDecoration: BoxDecoration(
                            color: Colors.blue,
                            borderRadius: BorderRadius.circular(7),

                          ),
                        );
                      }
                      return null;
                    },
                  ),
`

**Comment by jdeltoft** [comment]
```
                  calendarBuilders: CalendarBuilders(
                    singleMarkerBuilder: (context, day, _) {
                      if (day.isBefore(DateTime.now().subtract(Duration(days: 1)))) {
                        return Padding(
                          padding: const EdgeInsets.only(left: 1.0),
                          child: Container(
                            width: 8,
                            height: 8,
                              decoration: BoxDecoration(
                                  color: Colors.black87,
                                borderRadius: BorderRadius.all(Radius.circular(20))
                            ),
                          ),
                        );
                      } else {
                        return Padding(
                          padding: const EdgeInsets.only(left: 1.0),
                          child: Container(
                            width: 8,
                            height: 8,
                            decoration: BoxDecoration(
                                color: Colors.blue,
                                borderRadius: BorderRadius.all(Radius.circular(20))
                            ),
                          ),
                        );
                      }
                    },
                  ),
```
