### ISSUE TITLE
Markers no longer showing in 3.0.0

### ISSUE THREAD

**Issue by Jwiggiff** [aleksanderwozniak/table_calendar#489]
![image](https://user-images.githubusercontent.com/18373514/116492332-fc213800-a869-11eb-9541-0b27c7452fd5.png)
As you can see there is an event on the 28th (and there is one on the 29th) yet there are no markers showing. I've commented out any marker-related properties so it uses default and it still does not show.

**Comment by aleksanderwozniak** [comment]
The issue will be most likely in `eventLoader`. Check out the [events guide](https://github.com/aleksanderwozniak/table_calendar/tree/v3.0.0#events), you might need to replace your events Map (if you are using one) with a LinkedHashMap.

**Comment by Jwiggiff** [comment]
Ah I figured it out, thanks! The issue ended up being utc vs. local time in my map

**Comment by Schinwinkwinsky** [comment]
I'm having the same problem and I believe that's because of UTC configuration. If I debug the project as UTC-0 on emulator, the events are showed. But if I change the system UTC, the events miss. What exactly did you do, @Jwiggiff ?
