### ISSUE TITLE
custom number of days in each month

### ISSUE THREAD

**Issue by muzammilkhn123** [aleksanderwozniak/table_calendar#490]
Please guide me if I want to show 7 days of next month after last date of every month, how can I achieve this? 
E.G: after 30th of April, I want to show 7 more tiles in last. So that I can show data of 1st week of May in month of April.

**Comment by aleksanderwozniak** [comment]
Try using [sixWeekMonthsEnforced](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/sixWeekMonthsEnforced.html). If this doesn't achieve the results you want, you will need to adapt the source code.

**Comment by muzammilkhn123** [comment]
okay.
