### ISSUE TITLE
Migrating from 2 to 3

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [aleksanderwozniak/table_calendar#492]
Hi, i saw this migration guide: https://github.com/aleksanderwozniak/table_calendar/issues/434 but it says nothing about style migration. I have styled calendar

![image](https://user-images.githubusercontent.com/3918999/116856325-43595100-abfb-11eb-9e8f-ac24b35d725b.png)

As you can see all is red except 1 line - selmargin.
Where all this moved and how to refactor styles?

```
CalendarStyle(
        selectedStyle: TextStyle(color: CustomColors.careWhite, fontSize: Settings.mainFontSize),
        todayStyle: TextStyle(color: CustomColors.careWhite, fontSize: Settings.mainFontSize),
        weekdayStyle: TextStyle(fontSize: Settings.mainFontSize),
        weekendStyle: TextStyle(fontSize: Settings.mainFontSize, color: CustomColors.imperialRed),
        holidayStyle: TextStyle(fontSize: Settings.mainFontSize),
        outsideHolidayStyle: TextStyle(fontSize: Settings.mainFontSize, color: CustomColors.pageGrey500),
        outsideStyle: TextStyle(fontSize: Settings.mainFontSize, color: CustomColors.pageGrey500),
        unavailableStyle: TextStyle(fontSize: Settings.mainFontSize, color: CustomColors.pageGrey300),
        outsideWeekendStyle:
            TextStyle(fontSize: Settings.mainFontSize, color: CustomColors.imperialRed.withOpacity(0.6)),
        todayColor: CustomColors.carePurple.withOpacity(0.7),
        selectedColor: CustomColors.carePurple,
        markersColor: CustomColors.imperialRed,
        markersMaxAmount: 1,
        markersPositionBottom: 3,
        cellMargin: EdgeInsets.all(editView ? 3 : 6),
        contentPadding: EdgeInsets.only(bottom: 4, left: editView ? 2 : 8, right: editView ? 2 : 8));
  }
```

**Comment by desmeit** [comment]
same issue here

**Comment by vytautas-pranskunas-** [comment]
I was able to migrate many of properties but these left:

 - is weekdayStyle == defaultTextStyle?
 - These are missing - how should i repleace them?
    - outsideStyle - i see outsideDecoration but it misses fontSize because it is boxDecoration
    - unavailableStyle
    - outsideWeekendStyle
    - contentPadding

**Comment by aleksanderwozniak** [comment]
Check out [API docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/table_calendar-library.html) for more info on available properties. You are looking for [CalendarStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle-class.html).


> 
> 
> I was able to migrate many of properties but these left:
> 
>     * is weekdayStyle == defaultTextStyle?

Correct.

> 
>     * These are missing - how should i repleace them?
>       
>       * outsideStyle - i see outsideDecoration but it misses fontSize because it is boxDecoration
>       * unavailableStyle
>       * outsideWeekendStyle
>       * contentPadding

- [outsideTextStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle/outsideTextStyle.html)
- [disabledTextStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle/disabledTextStyle.html)
- For this one you will need to use [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html)
- You can wrap TableCalendar widget with Padding widget

**Comment by vytautas-pranskunas-** [comment]
Thanks for your quick responsesn. I have another question.
