### ISSUE TITLE
How do you load Events from an API

### ISSUE THREAD

**Issue by tawani** [aleksanderwozniak/table_calendar#494]
I can't seem to find any example of how to load Events from a REST API in 3.0.0
Is there an example anywhere using a Future or something? 
Also, how to reload the Events when the Calendar format changes or the month changes

**Comment by aleksanderwozniak** [comment]
> 
> 
> I can't seem to find any example of how to load Events from a REST API in 3.0.0
> Is there an example anywhere using a Future or something?

You can use things like FutureBuilder or StreamBuilder for this.

> Also, how to reload the Events when the Calendar format changes or the month changes

Use `onPageChanged` and `onFormatChanged` callbacks, make sure your `eventLoader` has the correct data.

**Comment by tawani** [comment]
Do you have a simple example? 
Even using a simple API like `https://jsonplaceholder.typicode.com` and assigning random dates will help a lot.

**Comment by aleksanderwozniak** [comment]
This should give you a general idea:

1. Wrap TableCalendar with some builder widget (e.g. StreamBuilder) that will trigger a rebuild every time there is new data available.
2. Synchronously provide your newly acquired data into TableCalendar by using `eventLoader`.
3. Detect page changes with `onPageChanged`. Use it to trigger API calls that fetch new data.
4. Once your API call finishes, your builder widget will automatically rebuild TableCalendar and give it new data - and so the cycle continues.

Check out [this gist](https://gist.github.com/aleksanderwozniak/1367892cbe39c25afda403b2300652ca) - it is a bit old, but the concept is similar. `events` will be replaced by `eventLoader`, and `_fetchEvents()` will go to `onPageChanged` callback.

**Comment by woehrer12** [comment]
@tawani Can you Post your Example here when you finish?

**Comment by dJani97** [comment]
Would it be possible in the future to also have an asynchronous `eventLoader`?

**Comment by mofukommit** [comment]
Can you please add an example of how to retrieve events from an API asynchronously? as @dJani97 said! This could be helpful for all of us. Please don't just close the issues without any explanation. Thank you! I used your multi example, it's perfect but still got issues with retrieving events and creating events from API.
