### ISSUE TITLE
Random available dates

### ISSUE THREAD

**Issue by UjjwaRaijada** [aleksanderwozniak/table_calendar#495]
Is it possible to have random active days rather than firstDay & lastDay?

**Comment by aleksanderwozniak** [comment]
Not sure I follow. You can set `firstDay` and `lastDay` to random DateTimes, as long as `lastDay` is not before the `firstDay`.

**Comment by UjjwaRaijada** [comment]
I want to show only 5 random dates as active.
For example : 
    04 / 01 / 2022, 
    07 / 01 / 2022, 
    09 / 01 / 2022, 
    12 / 01 / 2022
    20 / 01 / 2022,
Rest of the dates will remain inactive.

is it possible to do this.

**Comment by aleksanderwozniak** [comment]
Yes, you can use [enabledDayPredicate](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/enabledDayPredicate.html) for that.

**Comment by UjjwaRaijada** [comment]
if someone wants to know how to use enableDayPredicate
https://stackoverflow.com/questions/51683646/how-do-i-use-the-selectabledaypredicate-to-limit-my-datepicker-to-only-weekdays
