### ISSUE TITLE
Multiple calendars on a scrolling page

### ISSUE THREAD

**Issue by alecsam** [aleksanderwozniak/table_calendar#496]
How can I use multiple calendars in a ListView? I need to have multiple calendars on the page and scroll that page.

**Comment by aleksanderwozniak** [comment]
Simply place them in your ListView and disable vertical swiping for each of them: https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/availableGestures.html - use `AvailableGestures.horizontalSwipe`.

**Comment by alecsam** [comment]
Thank you! I've just discovered that and it works.
