### ISSUE TITLE
calendarStyle border radius

### ISSUE THREAD

**Issue by Elblassy** [aleksanderwozniak/table_calendar#498]
when i change calendarStyle for selectedDecoration to this 
```dart
calendarStyle: CalendarStyle(
        selectedDecoration: BoxDecoration(
          shape: BoxShape.rectangle,
          color: Const.SECONDARY_COLOR,
          borderRadius: BorderRadius.all(Radius.circular(12)),
        )
```

and begin to select day i get this error:
```
The following assertion was thrown building AnimatedContainer(duration: 250ms, Alignment.center, bg: BoxDecoration(shape: circle), margin: EdgeInsets.all(6.0), clipBehavior: Clip.none, dirty, dependencies: [_EffectiveTickerMode], state: _AnimatedContainerState#32241(ticker active, AlignmentGeometryTween(Alignment.center → Alignment.center), bg: DecorationTween(BoxDecoration(color: Color(0xffff653f), borderRadius: BorderRadius.circular(12.0)) - BoxDecoration(shape: circle)), margin: EdgeInsetsGeometryTween(EdgeInsets.all(6.0) → EdgeInsets.all(6.0)))):
package:flutter/src/painting/box_decoration.dart': Failed assertion: line 131 pos 12: 'shape != BoxShape.circle ||
     borderRadius == null': is not true.
```

**Comment by juanlabrador** [comment]
Me too!

**Comment by aleksanderwozniak** [comment]
This seems to be an issue with how AnimatedContainer interpolates between two decorations.

For now add this to your code:
```dart
defaultDecoration: BoxDecoration(
  shape: BoxShape.rectangle,
  borderRadius: BorderRadius.all(Radius.circular(12)),
),
```
You will need to do the same for other cell decorations as well (if you are using them).

**Comment by Chiaope** [comment]
> This seems to be an issue with how AnimatedContainer interpolates between two decorations.
> 
> For now add this to your code:
> 
> ```dart
> defaultDecoration: BoxDecoration(
>   shape: BoxShape.rectangle,
>   borderRadius: BorderRadius.all(Radius.circular(12)),
> ),
> ```
> 
> You will need to do the same for other cell decorations as well (if you are using them).

I tried adding the defaultDecoration and it still did not seem to work.
Below is my code

calendarStyle: CalendarStyle(
          defaultDecoration: BoxDecoration(
            shape: BoxShape.rectangle,
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
          isTodayHighlighted: true,
          selectedDecoration: BoxDecoration(
            color: Colors.amberAccent,
            shape: BoxShape.rectangle,
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
          todayDecoration: BoxDecoration(
            color: Colors.blueAccent,
            shape: BoxShape.rectangle,
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
        ),
      ),
