### ISSUE TITLE
repetition on even and odd weeks

### ISSUE THREAD

**Issue by Al6or** [aleksanderwozniak/table_calendar#499]
Hello, I've only been in flutter for two months.
And so a stupid question arises.
How can you make a recurrence on odd and even weeks?
For example, Monday is an even week: (event 1, event 2). and on Monday of an odd week: (event 166, event 90)

**Comment by Al6or** [comment]
Oh lol, it worked like that
 ```
eventLoader: (day) {
              if (day.weekday == DateTime.monday && day.weekOfYear% 2 == 0) {
                return [Event ('Cyclic event')];
              }
              return [];
            },
```

are there any other ways?

**Comment by aleksanderwozniak** [comment]
This looks fine to me.

Alternatively, you could prepare a `Map<DateTime, List<Event>>` ahead of time, and use it in `eventLoader` to only access the data - like this:
```dart
eventLoader: (day) {
  return events[day] ?? [];
},
```
