### ISSUE TITLE
Allow user to give custom color for days of week. 

### ISSUE THREAD

**Issue by SaurabhMhaisekar** [aleksanderwozniak/table_calendar#5]
Currently there is no provision for user to give custom color for days, it takes default value of gray which cannot be changed. Please add functionality to do so. Same can be said about weekend days. This is very important as not allowing user to change color can break their theme.

**Comment by aleksanderwozniak** [comment]
I will add more customization with next patch, which should be up soon!

**Comment by aleksanderwozniak** [comment]
Every style should be customizable as of version `0.3.0`.

To update - add to pubspec.yaml:

```yaml
dependencies:
  table_calendar: ^0.3.0
```

then run `flutter packages get`.
