### ISSUE TITLE
default marker dots stay dark if system theme dark

### ISSUE THREAD

**Issue by leemcloughlin** [aleksanderwozniak/table_calendar#500]
Using default styles for marker dots if the system theme is dark the marker dots are dark and invisible. Text changes to a light colour under a dark theme.

As a workaround I've given my calendar a markerDecoration with a color that looks OK under both dark and light themes

    calendarStyle: CalendarStyle(
      markerDecoration: const BoxDecoration(
        color: Colors.lime,
        shape: BoxShape.circle,
      ),

**Comment by aleksanderwozniak** [comment]
You can check what is the current theme and apply styling accordingly:

```dart
markerDecoration: BoxDecoration(
  shape: BoxShape.circle,
  color: Theme.of(context).brightness == Brightness.light
      ? Colors.grey[800]
      : Colors.grey[200],
),
```

**Comment by F-CODEV** [comment]
We need to set a color from colorScheme

```
final colorScheme = Theme.of(context).colorScheme;
markerDecoration: BoxDecoration(
                shape: BoxShape.circle,
                color: colorScheme.primary,
              ),
```

But it can't be because it must be constant
