### ISSUE TITLE
How to change event day's colors and remove market that event days?

### ISSUE THREAD

**Issue by tijnar** [aleksanderwozniak/table_calendar#502]
I am displaying events to the calendar using eventLoader and it is perfectly working fine. Now I want to change the color of the event day and remove the markers.  I was searching if there is any `eventDecoration` or `eventTextStyle` just like `todayDecoration` and `todayTextStyle` inside `CaledarStyle`. But found nothing which styles the event days. 

I tried using `caledarBuilders` but I am not able to achieve my requirement. Is there any solution for this?

**Comment by tijnar** [comment]
I did this using `caledarBuilder`.
here is my code. 

```
calendarBuilders: CalendarBuilders(prioritizedBuilder: (context, date, date1) {
          List<Duty> duties = Provider.of<DutyProvider>(context).duties; 


for (int i = 0; i < duties.length; i++) {
            if (duties[i].from.day == date.day) {
              return Container(
                alignment: Alignment.center,
                decoration: date.day == DateTime.now().day
                    ? BoxDecoration(
                        shape: BoxShape.circle,
                        color: mainColor,
                      )
                    : null,
                child: Text(
                  date.day.toString(),
                  style: date.day == DateTime.now().day ? TextStyle(color: Colors.white) : TextStyle(color: mainColor),
                ),
              );
            }
          }
          return null;
        }),
```

But I wonder, is this the better approach ?. This overrides  my all  `caledarStyle` properties.

**Comment by aleksanderwozniak** [comment]
Try using [defaultBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/defaultBuilder.html). Similar concept, but different rendering order; remember to return `null` in it as well, when you don't want to override the default style. Might be better for your use case.
