### ISSUE TITLE
Disable formatAnimation

### ISSUE THREAD

**Issue by mrxten** [aleksanderwozniak/table_calendar#506]
Please add FormatAnimation.none with just returning `_buildWrapper` in `_buildCalendarContent`.
It need for self-controlling size animation of calendar.
Thanks.

**Comment by aleksanderwozniak** [comment]
Looks like you are talking about a previous version.

v3.0.0 works a bit differently internally, and there is no `FormatAnimation` enum anymore. You can use [formatAnimationDuration](https://pub.dev/documentation/table_calendar/3.0.0/table_calendar/TableCalendar/formatAnimationDuration.html) and [formatAnimationCurve](https://pub.dev/documentation/table_calendar/3.0.0/table_calendar/TableCalendar/formatAnimationCurve.html) to control it.
