### ISSUE TITLE
dotted line below days

### ISSUE THREAD

**Issue by ronytesler** [aleksanderwozniak/table_calendar#508]
What's the best way to implement this dotted line below the days of week?

![image](https://user-images.githubusercontent.com/9344207/119245199-004a2800-bb80-11eb-82ce-12c1a396907b.png)

**Comment by aleksanderwozniak** [comment]
There is a couple ways. Try the `decoration` first, and if it doesn't work then go with `dowBuilder`:

- https://pub.dev/documentation/table_calendar/latest/table_calendar/DaysOfWeekStyle/decoration.html
- https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/dowBuilder.html
