### ISSUE TITLE
Centering of focusedDay in week format

### ISSUE THREAD

**Issue by prabs3257** [aleksanderwozniak/table_calendar#509]
In the week format the focused day that is the current day is not the centered day in the horizontal view how can i make the focused day centered everytime

**Comment by aleksanderwozniak** [comment]
Focused day is not supposed to be the middle day of the week (if that's what you are asking about).

You can, however, calculate the middle day of the week using the focused day, and then used that for what you need - https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620 is similar.
