### ISSUE TITLE
Is the vertical swipe to change the calendar format gone in v3.0.0?

### ISSUE THREAD

**Issue by tneotia** [aleksanderwozniak/table_calendar#511]
You used to be able to swipe vertically to switch between 1 week, 2 weeks, and month. This seems to be gone in the latest version unless I'm missing something.

**Comment by aleksanderwozniak** [comment]
You need to rebuild the widget with proper format: 
```dart
calendarFormat: _calendarFormat,
onFormatChanged: (format) {
  setState(() {
    _calendarFormat = format;
  });
},
```

**Comment by tneotia** [comment]
Thanks, that fixed it. Appreciate the quick response.
