### ISSUE TITLE
"Event" definition conflicts because is defined also at googleapis

### ISSUE THREAD

**Issue by AirtonLucianoAragao** [aleksanderwozniak/table_calendar#514]
Hi.

I tried to insert your code at my app but there is a conflict with googleapi because there is also an "Event" defined.

I got this message (truncated)
The argument type 'List<Event> Function(DateTime) (where Event is defined in /home/luciano/AndroidStudioProjects/temporada_admin/lib/utils.dart)' can't be assigned to the parameter type 'List<Event> Function(DateTime) (where Event is defined

**Comment by AirtonLucianoAragao** [comment]
Edit: Full message
{List<Event> Function(DateTime) eventLoader}
Function that assigns a list of events to a specified day.

The argument type 'List<Event> Function(DateTime) (where Event is defined in /home/luciano/AndroidStudioProjects/temporada_admin/lib/utils.dart)' can't be assigned to the parameter type 'List<Event> Function(DateTime) (where Event is defined in /home/luciano/.pub-cache/hosted/pub.dartlang.org/googleapis-0.55.0/lib/people/v1.dart)'

**Comment by aleksanderwozniak** [comment]
You can change the class name from "Event" to something else.

**Comment by AirtonLucianoAragao** [comment]
> You can change the class name from "Event" to something else.

Thanks a lot. I'd already tried this but did something wrong. Now it worked like a charm. 

Thanks a lot.
