### ISSUE TITLE
Your examples are too few

### ISSUE THREAD

**Issue by LinMaris** [aleksanderwozniak/table_calendar#515]
Your example does not match the picture

**Comment by aleksanderwozniak** [comment]
[Events example](https://github.com/aleksanderwozniak/table_calendar/blob/0bd7c55d46c41e2caf62e06ffa337b0a72ef6701/example/lib/pages/events_example.dart) is exactly that.

If you want the UI on the right, then [here](https://github.com/aleksanderwozniak/table_calendar/blob/5721feea4e555af6a8ab6d75f373fba173cd27f1/example/lib/main.dart) is the old example, which you can easily update to the newer version by following the provided [guide](https://github.com/aleksanderwozniak/table_calendar/blob/0bd7c55d46c41e2caf62e06ffa337b0a72ef6701/README.md#basic-setup) and new examples.
