### ISSUE TITLE
Undefined class 'CalendarController'.

### ISSUE THREAD

**Issue by AirtonLucianoAragao** [aleksanderwozniak/table_calendar#517]
Hi.

I am facing this issue: Undefined class 'CalendarController'.
Try changing the name to the name of an existing class, or creating a class with the name 'CalendarController'. 

Here are pubspec.yaml and pubspec.lock

dependencies:
  flutter:
    sdk: flutter
  provider:
  cloud_firestore: ^0.14.4
  firebase_analytics:
  firebase_core: ^0.5.3
  cupertino_icons: ^1.0.0
  uuid: ^2.2.2
  firebase_messaging: ^6.0.9
  shared_preferences:
  intl: ^0.17.0
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12
  url_launcher: ^5.5.0
  table_calendar: ^3.0.0
  table_calendar:
    dependency: "direct main"
    description:
      name: table_calendar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
May someone help ?

Thanks

**Comment by ryan-holder** [comment]
CalendarController isn't used anymore. Have a look at the readme and [this comment](https://github.com/aleksanderwozniak/table_calendar/issues/153#issuecomment-772881560).

**Comment by scheung38** [comment]
Hi @aleksanderwozniak which version should we use?


```
 table_calendar:  
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: 3.0.0-beta
```

or


` table_calendar: ^3.0.0-nullsafety.0`
