### ISSUE TITLE
how to feed api data alerady parse and in streambuilder into eventLoader

### ISSUE THREAD

**Issue by CaydenD** [aleksanderwozniak/table_calendar#518]
I have pulled data from an api and have it parsed and in the format of map<datatime, list<event>> but I cant seem to figure out how to take this data or the snapshot.data and feed it to the event loader.

**Comment by CaydenD** [comment]
I already referred to the rest of the open and closed tickets to see if there was a solution already posted and this was the main post I referred to in trying to solve my problem 

//____________________________start post__________________________________________________

This should give you a general idea:

Wrap TableCalendar with some builder widget (e.g. StreamBuilder) that will trigger a rebuild every time there is new data available.
Synchronously provide your newly acquired data into TableCalendar by using eventLoader.
Detect page changes with onPageChanged. Use it to trigger API calls that fetch new data.
Once your API call finishes, your builder widget will automatically rebuild TableCalendar and give it new data - and so the cycle continues.
Check out this gist - it is a bit old, but the concept is similar. events will be replaced by eventLoader, and _fetchEvents() will go to onPageChanged callback.

//_____________________________end post_________________________________________________

I'm confused on how to provide the data to event loader as stream builder makes the snapshot available to the the widget and eventloader calls a function with different parameters.

**Comment by aleksanderwozniak** [comment]
You can just transform the data from snapshot to match the `eventLoader`. Check out https://github.com/aleksanderwozniak/table_calendar#events for details.
