### ISSUE TITLE
How to setup markerbuilders?

### ISSUE THREAD

**Issue by mexxarDev** [aleksanderwozniak/table_calendar#519]
I've been looking through old documents on how to set up custom colored event markers on the calendar. It seems on previous versions the table_calendar took a "markerbuilder" property, but the newest version doesn't seem to accept it the same way.

Any support with this would be greatly appreciated.

**Comment by MatteoAntolini** [comment]
You can add this to `TableCalendar` : 

`calendarBuilders: CalendarBuilders(
                markerBuilder: (context, dateTime, events) => YourWidget()),`
