### ISSUE TITLE
Set selectedDay Bubble height/shape

### ISSUE THREAD

**Issue by beachpebble** [aleksanderwozniak/table_calendar#521]
Sorry, I'm a newbie and a bit slow. This might seem obvious to more experience coders but is eluding me.

How can I set the selected day bubble height to look like this?
<img width="408" alt="Screen Shot 2021-06-13 at 8 17 56 PM" src="https://user-images.githubusercontent.com/10665584/121834815-8e4b9700-cc84-11eb-99f5-51aad605c4cb.png">

I have done this:
`                selectedDecoration: BoxDecoration(
                  shape: BoxShape.rectangle,
                  color: Colors.white70,
                  borderRadius: BorderRadius.all(
                    Radius.circular(20),
                  ),`

But clearly there is no way to set height in a box decoration. And I am trying to match the design shown above which is an elongated rectangle with radius. Not a square or a circle. None of the code examples shows how to use the Focused Day Builder and I am a newbie, not an experienced coder. How do I get to and change the shaped of container which this BoxDecoration property applies to? I don't want to change any functionality, just the style.

**Comment by DmitrijsD** [comment]
Use CalendarBuilders with your own widgets

**Comment by beachpebble** [comment]
ie. "We're not beginner friendly. Figure it out in your own." 

Why even waste the time to reply if you aren't going to supply an example? Must be nice to have so much free time.

**Comment by aleksanderwozniak** [comment]
Using `CalendarBuilders` is the right suggestion. An example is right there in the [README](https://github.com/aleksanderwozniak/table_calendar#custom-ui-with-calendarbuilders).

**Comment by dmitdu** [comment]
> ie. "We're not beginner friendly. Figure it out in your own."
> 
> Why even waste the time to reply if you aren't going to supply an example? Must be nice to have so much free time.

Wow, I'm really sorry for not providing you working example for your needs! Maybe next time spend more time on the FIRST page of documentation and checking already provided examples, instead of typing long questions and somehow expecting "examples". If you say you are a newbie, don't expect others to be your mommy.

**Comment by Somtobro** [comment]
@beachpebble 
Did you later achieve that interface?
I need something exactly like that
