### ISSUE TITLE
formatButtonVisible Not Available

### ISSUE THREAD

**Issue by AnasAshir** [aleksanderwozniak/table_calendar#522]
I want to remove the Format Button from the calendar but the option (formatButtonVisible) is not available. It is present in the guide but not available in implementation. I'm using table_calendar 3.0.0

**Comment by aleksanderwozniak** [comment]
You will find it in [HeaderStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/HeaderStyle-class.html).

**Comment by AnasAshir** [comment]
Found it! Thank You.
