### ISSUE TITLE
Sync events from device calendar

### ISSUE THREAD

**Issue by henry8th** [aleksanderwozniak/table_calendar#524]
Hi there! thanks for the great library

How would you suggest going about syncing / concurrently adding events to the device calendar when adding events to the inapp calendar?

Thank you

**Comment by aleksanderwozniak** [comment]
Hi,

For something like this you would need to use additional package that allows you to access the device calendar. After that, syncing the TableCalendar widget with the device calendar shouldn't be too complex - you just need to use the proper data in `eventLoader`.

**Comment by henry8th** [comment]
Thanks you :)
