### ISSUE TITLE
focusedDay only shows current date

### ISSUE THREAD

**Issue by janithcooray** [aleksanderwozniak/table_calendar#525]
I've been debugging this code for a while. and I thought that this might be a problem in my coding on updating the value. but when I set the value to DateTime.utc(2021, 6, 14) the calendar only displays the current date (2021,6,20). I even tried restarting the debugging session a few times. but the calendar seems to be responsive in other ways. only displays the incorrect focused date. i don't even have errors to show.

>focusedDay: DateTime.utc(2021, 6, 14),

**Flutter Version**
Flutter 2.2.1

**Debugging**
on Physical Android device with android 11 (stock GO).

```
//Widget Parent
TableCalendar(
                  firstDay: DateTime.utc(2010, 10, 16),
                  lastDay: DateTime.utc(2030, 3, 14),
                  focusedDay: DateTime.utc(2021, 6, 14),
                  selectedDayPredicate: (day) {
                    return isSameDay(_selectedDay, day);
                  },
                  onDaySelected: (selectedDay, focusedDay) {
                    log(selectedDay.day.toString());
                    if (!isSameDay(_selectedDay, selectedDay)) {
                      // Call `setState()` when updating the selected day
                      setState(() {
                        //_selectedDay = selectedDay;
                        //_focusedDay = focusedDay;
                      });
                    }
                  },
                )

```

**Expected Output**
Calendar Displaying (2021, 6, 14) 

**Actual Output**
Calendar Displaying (2021, 6, 20) - current date

**Log Output**
nothing!

**Comment by aleksanderwozniak** [comment]
You might be mistaking focused day for selected day. This code controls which day is selected in the calendar - [API docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/selectedDayPredicate.html):
```dart
selectedDayPredicate: (day) {
  return isSameDay(_selectedDay, day);
},
```

You need to uncomment this part:
```dart
onDaySelected: (selectedDay, focusedDay) {
  log(selectedDay.day.toString());
  if (!isSameDay(_selectedDay, selectedDay)) {
    // Call `setState()` when updating the selected day
    setState(() {
      //_selectedDay = selectedDay;
      //_focusedDay = focusedDay;
    });
  }
},
```

and properly set the focused day:
```dart
focusedDay: _focusedDay
```

**Comment by janithcooray** [comment]
> You might be mistaking focused day for selected day. This code controls which day is selected in the calendar - [API docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/selectedDayPredicate.html):
> 
> ```dart
> selectedDayPredicate: (day) {
>   return isSameDay(_selectedDay, day);
> },
> ```
> 
> You need to uncomment this part:
> 
> ```dart
> onDaySelected: (selectedDay, focusedDay) {
>   log(selectedDay.day.toString());
>   if (!isSameDay(_selectedDay, selectedDay)) {
>     // Call `setState()` when updating the selected day
>     setState(() {
>       //_selectedDay = selectedDay;
>       //_focusedDay = focusedDay;
>     });
>   }
> },
> ```
> 
> and properly set the focused day:
> 
> ```dart
> focusedDay: _focusedDay
> ```

```
onDaySelected: (selectedDay, focusedDay) {
  log(selectedDay.day.toString());
  if (!isSameDay(_selectedDay, selectedDay)) {
    // Call `setState()` when updating the selected day
    setState(() {
      //_selectedDay = selectedDay;
      //_focusedDay = focusedDay;
    });
  }
},
```
_selectedDay & _focusedDay has nothing to do with this. that is why I have commented those lines out. 

I'm debugging the code and I need it to display the following:
focusedDay: DateTime.utc(2021, 6, 14).

**Comment by janithcooray** [comment]
Works after moving into a separate stateful widget. it didn't work when it's with other widgets inside a stateful class.
