### ISSUE TITLE
How to add an event with many days

### ISSUE THREAD

**Issue by AirtonLucianoAragao** [aleksanderwozniak/table_calendar#526]
Hi.

Is there a way to add an event with a duration of many days like a hotel room booking or I have to add the same event at each day between check-in and check-out ?

Thanks a lot.

**Comment by aleksanderwozniak** [comment]
You can do something like [this](https://github.com/aleksanderwozniak/table_calendar#cyclic-events), but use booking date range instead of event repetition.
