### ISSUE TITLE
Detect if the selected day is outside

### ISSUE THREAD

**Issue by desmeit** [aleksanderwozniak/table_calendar#528]
Hello,

is there a way to detect if the selected Day within selectedBuilder is outside?
I defined a color in the outsideBuilder and I want to avoid that the color is changing if I click on a day from the outside area.

**Comment by aleksanderwozniak** [comment]
Hi, you can compare month of `day` and `focusedDay`. If they are not the same, then you have an outside day cell.

**Comment by desmeit** [comment]
thanks
