### ISSUE TITLE
Plugin is not testable (DateTime.now)

### ISSUE THREAD

**Issue by ploth** [aleksanderwozniak/table_calendar#529]
Hey! Thanks for your work!

We are doing visual UI testing in one of our projects. With [line 583](https://github.com/aleksanderwozniak/table_calendar/blob/master/lib/src/table_calendar.dart#L583) we have no chance to mock the todays date. It would be very nice to be able to pass the date of today to `TableCalendar(...)`.

Best!

**Comment by aleksanderwozniak** [comment]
Hi Pascal,

I've added `current-day` branch to this repo. Please check it out and let me know if that works as expected; once all is good I'll publish it as an official update.

**Comment by ploth** [comment]
Thank you! Works perfectly!

**Comment by aleksanderwozniak** [comment]
Perfect! Thanks for the feedback.

You will find `currentDay` property in `3.0.1` release.
