### ISSUE TITLE
Extracting "Visible" First / Last Date

### ISSUE THREAD

**Issue by SaadKaleem** [aleksanderwozniak/table_calendar#531]
Hello, I need to be able to extract the "visible" First date and last date, that the user is currently looking at. (I don't mean the `firstDay` and `lastDay` of the calendar settings - as that would disable the page change (which is not what I want))

The reason for this is that I want to query an API with the first date and last date to get a range of events, but only for those dates, that the user is currently looking at, and then when the page changes - I want to query the API again with the updated first/last date.

Is there is a way to do this? I really can't think of a way to do this from `focusedDay`, surely - there might be a way to expose these dates from the calculations done for the UI? or perhaps, another way to tackle this from my side?

Best Regards.

**Comment by aleksanderwozniak** [comment]
Hi Saad, check out this comment: https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620.

**Comment by SaadKaleem** [comment]
> Hi Saad, check out this comment: [#441 (comment)](https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620).

Hi Aleksander, 

Apologies for the duplicate issue - Thanks, I've understood your past comment, and is certainly doable manually. I guess my only query is: was there a specific rationale not to expose `getVisibleRange()` result in [calendar_core.dart](https://github.com/aleksanderwozniak/table_calendar/blob/master/lib/src/widgets/calendar_core.dart) via a callback in the recent version? I believe this was accessible in older versions.

Personally, for me, this issue is resolved.

**Comment by boranmohamed** [comment]
> > Hi Saad, check out this comment: [#441 (comment)](https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620).
> 
> Hi Aleksander,
> 
> Apologies for the duplicate issue - Thanks, I've understood your past comment, and is certainly doable manually. I guess my only query is: was there a specific rationale not to expose `getVisibleRange()` result in [calendar_core.dart](https://github.com/aleksanderwozniak/table_calendar/blob/master/lib/src/widgets/calendar_core.dart) via a callback in the recent version? I believe this was accessible in older versions.
> 
> Personally, for me, this issue is resolved.

@SaadKaleem  it doesn't work well when the date is in the second row in CalendarFormat.twoWeeks ... it gives me the range of the next week

**Comment by musthafa1996** [comment]
For anyone still looking for a way to get the visible date range of the TableCalendar, please check this comment
https://github.com/aleksanderwozniak/table_calendar/issues/702#issuecomment-2718023823
