### ISSUE TITLE
Type of Calendar not locale

### ISSUE THREAD

**Issue by agrigera** [aleksanderwozniak/table_calendar#532]
It would be nice if Month, 2 Weeks and Week would change along with locale option.
Best plugin

**Comment by aleksanderwozniak** [comment]
You can do this manually, by using [availableCalendarFormats](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/availableCalendarFormats.html) property.

Check out https://github.com/aleksanderwozniak/table_calendar#specifying-a-language.

**Comment by agrigera** [comment]
Yes I did that and the Months and Days are in the right language, the problem is with the format of the Calendar (Month, 2 Weeks and Week) those doesn´t change with the locale.
I can't now but I'll attach a picture of the problem tomorrow

**Comment by aleksanderwozniak** [comment]
Like mentioned above and in the README, this has to be done manually through `availableCalendarFormats`. You can use localization method of your choice.
