### ISSUE TITLE
How to set focused day manually (_focusedDAY)

### ISSUE THREAD

**Issue by Dekhnar** [aleksanderwozniak/table_calendar#541]
Hello I need to be abble to set programmatically focused day, before it was possible by using :
controller.setSelectedDay.
Currently i'm using a reactive variable for manage this.

**Comment by aleksanderwozniak** [comment]
You can just rebuild the widget with updated `focusedDay` - [docs](https://github.com/aleksanderwozniak/table_calendar#basic-setup).

**Comment by Dekhnar** [comment]
Yes that what I did with my own variable.
