### ISSUE TITLE
How to use in GetX?

### ISSUE THREAD

**Issue by Jacky-Xu** [aleksanderwozniak/table_calendar#542]
in GetX
translations: TranslationService(),
locale: TranslationService.locale, 

If don’t use the Intl plugin, how should set the language?

**Comment by abehbatre** [comment]
initializeDateFormatting('in'); // indonesian
final locale = 'in'; // indonesian
------
 >> locale: locale,

**Comment by aleksanderwozniak** [comment]
With `locale` property [as usual](https://github.com/aleksanderwozniak/table_calendar#locale), but you may not need to initialize it - https://github.com/aleksanderwozniak/table_calendar/issues/433#issuecomment-800248973.
