### ISSUE TITLE
Table Calendar has intermittent date range rendering issues 

### ISSUE THREAD

**Issue by Desync-o-tron** [aleksanderwozniak/table_calendar#544]
I canabalized one of the examples and combined it with a list to make it easier for the user to select commonly used date ranges. The only thing I'm doing in my code that's different is that I edit  `focusedDay: _focusedDay, rangeStartDay: _rangeStart, rangeEndDay: _rangeEnd,` outside of both `onDaySelected` and `onRangeSelected`. 

Here is what the problem looks like:
![image](https://user-images.githubusercontent.com/35696371/125180274-33935580-e1c6-11eb-888f-7681a2dca047.png) ![image](https://user-images.githubusercontent.com/35696371/125180276-368e4600-e1c6-11eb-8f59-e12a0cc0be69.png)

As you can see, the ranges are not continuous. Also this is intermittent. It was exhibiting this problem the other night at 11:50PM and at 12:05AM I noticed it went away. It comes and goes.

##################################
My code is below:
`
import 'package:flutter/material.dart';
import 'package:table_calendar/table_calendar.dart';

final int kLookAheadYears = 5; //TO-DO make this shared btwn this n createEvent
final kToday = DateTime.now();
// final kToday = DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day - 1);

// final kToday = DateTime.now().add(Duration(days: 1)); //for testing
final kLastDay =
    DateTime(kToday.year + kLookAheadYears, kToday.month, kToday.day);

enum PresetTimeFrames {
  Today,
  Tomorrow,
  ThisWeek,
  ThisWeekend,
  ThisMonth,
  Custom
}

class TableRangeExample extends StatefulWidget {
  @override
  _TableRangeExampleState createState() => _TableRangeExampleState();
}

class _TableRangeExampleState extends State<TableRangeExample> {
  DateTime _focusedDay = kToday;
  DateTime? _selectedDay;
  DateTime? _rangeStart;
  DateTime? _rangeEnd;
  //TODO implement static-ness, but also don't allow that to bork things if someone keeps the app open for a day.
  PresetTimeFrames timeFrame = PresetTimeFrames.ThisWeek;
  @override
  Widget build(BuildContext context) {
    return SimpleDialog(
        title: const Text(
          'Choose Your Dates',
          textAlign: TextAlign.center,
        ),
        children: [
          Container(
            child: Column(
              children: [
                RadioListTile<PresetTimeFrames>(
                  value: PresetTimeFrames.Today,
                  title: Text("Today"),
                  groupValue: timeFrame,
                  onChanged: (_) {
                    setState(() {
                      timeFrame = PresetTimeFrames.Today;
                      _selectedDay = kToday;
                      _rangeStart = null;
                      _rangeEnd = null;
                    });
                  },
                ),
                RadioListTile<PresetTimeFrames>(
                  value: PresetTimeFrames.Tomorrow,
                  title: Text("Tomorrow"),
                  groupValue: timeFrame,
                  onChanged: (_) {
                    setState(() {
                      timeFrame = PresetTimeFrames.Tomorrow;
                      _selectedDay =
                          DateTime(kToday.year, kToday.month, kToday.day + 1);
                      _rangeStart = null;
                      _rangeEnd = null;
                    });
                  },
                ),
                RadioListTile<PresetTimeFrames>(
                  value: PresetTimeFrames.ThisWeek,
                  groupValue: timeFrame,
                  title: Text("This Week"),
                  onChanged: (_) {
                    setState(() {
                      timeFrame = PresetTimeFrames.ThisWeek;
                      _selectedDay = null;
                      _focusedDay = kToday;
                      _rangeStart = kToday;
                      // _rangeStart = kToday.add(Duration(days: 1));
                      _rangeEnd =
                          DateTime(kToday.year, kToday.month, kToday.day + 7);
                    });
                  },
                ),
                RadioListTile<PresetTimeFrames>(
                  value: PresetTimeFrames.ThisWeekend,
                  groupValue: timeFrame,
                  title: Text("This Weekend"),
                  onChanged: (_) {
                    setState(() {
                      //I just want to have friday and saturday..
                      //it would be cool to add holidays but youknow..time(;
                      late final fri, sat;
                      if (kToday.weekday < DateTime.saturday) {
                        fri = fridayOf(kToday);
                        sat = saturdayOf(kToday);
                      } else if (kToday.weekday == DateTime.saturday) {
                        fri = null;
                        sat = saturdayOf(kToday);
                      } else if (kToday.weekday == DateTime.sunday) {
                        //weeks start on monday for some reason..
                        //so we'll fast fwd to monday to get the coming weekend
                        final mon = kToday.add(Duration(days: 1));
                        fri = fridayOf(mon);
                        sat = saturdayOf(mon);
                      }
                      timeFrame = PresetTimeFrames.ThisWeekend;
                      _focusedDay = kToday;
                      _selectedDay = null;
                      _rangeStart = fri;
                      _rangeEnd = sat;
                    });
                  },
                ),
                RadioListTile<PresetTimeFrames>(
                  value: PresetTimeFrames.ThisMonth,
                  groupValue: timeFrame,
                  title: Text("This Month"),
                  onChanged: (_) {
                    setState(() {
                      timeFrame = PresetTimeFrames.ThisMonth;
                      _selectedDay = null;
                      _rangeStart = kToday;
                      _rangeEnd =
                          DateTime(kToday.year, kToday.month + 1, kToday.day);
                    });
                  },
                ),
                RadioListTile<PresetTimeFrames>(
                  value: PresetTimeFrames.Custom,
                  groupValue: timeFrame,
                  title: Text("Custom"),
                  onChanged: (_) {
                    setState(() {
                      timeFrame = PresetTimeFrames.Custom;
                    });
                  },
                ),
              ],
            ),
            decoration: BoxDecoration(
              border: Border(
                  // top: BorderSide(color: Colors.grey[300]!),
                  ),
            ),
          ),
          Container(
            width: MediaQuery.of(context).size.width * .99,
            child: TableCalendar(
              firstDay: kToday,
              lastDay: kLastDay,
              focusedDay: _focusedDay,
              selectedDayPredicate: (day) => isSameDay(_selectedDay, day),
              rangeStartDay: _rangeStart,
              rangeEndDay: _rangeEnd,
              calendarFormat: CalendarFormat.month,
              rangeSelectionMode: RangeSelectionMode.enforced,
              availableCalendarFormats: {CalendarFormat.month: 'Month'},
              availableGestures: AvailableGestures.horizontalSwipe,
              onDaySelected: (selectedDay, focusedDay) {
                if (!isSameDay(_selectedDay, selectedDay)) {
                  setState(() {
                    _selectedDay = selectedDay;
                    _focusedDay = focusedDay;
                    _rangeStart = null; // Important to clean those
                    _rangeEnd = null;
                    // preselected timeframe logic below
                    timeFrame = PresetTimeFrames.Custom;
                  });
                }
              },
              onRangeSelected: (start, end, focusedDay) {
                setState(() {
                  _selectedDay = null;
                  _focusedDay = focusedDay;
                  _rangeStart = start;
                  _rangeEnd = end;
                  // preselected timeframe logic below
                  timeFrame = PresetTimeFrames.Custom;
                });
              },
              onPageChanged: (focusedDay) {
                _focusedDay = focusedDay;
              },
            ),
          ),
        ]);
  }
}

/// Returns a list of [DateTime] objects from [first] to [last], inclusive.
List<DateTime> daysInRange(DateTime first, DateTime last) {
  final dayCount = last.difference(first).inDays + 1;
  return List.generate(
    dayCount,
    (index) => DateTime.utc(first.year, first.month, first.day + index),
  );
}

DateTime weekdayOf(DateTime time, int weekday) =>
    time.add(Duration(days: weekday - time.weekday));
DateTime fridayOf(DateTime time) => weekdayOf(time, DateTime.friday);
DateTime saturdayOf(DateTime time) => weekdayOf(time, DateTime.saturday);
`

**Comment by aleksanderwozniak** [comment]
This might be caused by time zones and daylight saving offset, especially if you noticed it went away right after midnight. Try using `normalizeDate()` before providing a date to TableCalendar widget.

For example:
```dart
_rangeStart = normalizeDate(kToday);
```

**Comment by Desync-o-tron** [comment]
Thankee! That Worked.
