### ISSUE TITLE
Day decoration priority

### ISSUE THREAD

**Issue by jpsanmiguel** [aleksanderwozniak/table_calendar#546]
Hi! Right now I am working in an app with this awesome calendar, but I am having a little issue. When a day is a holiday but also is outside, it always takes the holiday TextStyle, is there a way to use both at the same time? If a day is a holiday but is also outside of current month?

**Comment by aleksanderwozniak** [comment]
You can use `CalendarBuilders` for that.

**Comment by jpsanmiguel** [comment]
Oh, thanks
