### ISSUE TITLE
Avoid blank space when swipping between two months

### ISSUE THREAD

**Issue by adriende** [aleksanderwozniak/table_calendar#55]
This is a great project!
But is it possible to reduce the time between 2 months when we swipe horizontally ?
I would like to avoid the "blank" space between the two months.

**Comment by Wonny-L** [comment]
how about using pageview?

**Comment by aleksanderwozniak** [comment]
`PageView` won't work here since it requires constant height, while *Table Calendar* features vertical autosizing.

**Comment by Camerash** [comment]
Is there any updates on this, or other possible workarounds?

**Comment by rtmzshw** [comment]
is anyone found a sulotion yet? it is very critical

**Comment by billy124** [comment]
Did anyone manage to get a fix for this?


Thank you

**Comment by billy124** [comment]
> is anyone found a sulotion yet? it is very critical

Hey did you find a workaround at all or did you use a different repo?

**Comment by apripy** [comment]
I've worked around this by using a PageView with 3 children: one for the week/month before, one for the current week/month and one for the week/month after.

I've used a ScrollEndNotification to detect when the user has finished scrolling, it then updates the controller of the "middle" page to make it show the next/previous one and update the state to rebuild the "previous" and "next" pages with new initialDate.

I had to put it in a fixed height container otherwise it wouldn't show.

It's a hack. It works smoothly from what I've tested, but I'd rather have a built-in support for this.

**Comment by manhtuan1712** [comment]
> I've worked around this by using a PageView with 3 children: one for the week/month before, one for the current week/month and one for the week/month after.
> 
> I've used a ScrollEndNotification to detect when the user has finished scrolling, it then updates the controller of the "middle" page to make it show the next/previous one and update the state to rebuild the "previous" and "next" pages with new initialDate.
> 
> I had to put it in a fixed height container otherwise it wouldn't show.
> 
> It's a hack. It works smoothly from what I've tested, but I'd rather have a built-in support for this.

Hi, can i get your example code, thanks.

**Comment by aleksanderwozniak** [comment]
I think I may have a solution. I still need to think it through, but stay tuned for upcoming updates!

**Comment by Pannkaaka** [comment]
> I think I may have a solution. I still need to think it through, but stay tuned for upcoming updates!

Any updates?

**Comment by aleksanderwozniak** [comment]
I got it to work :)

It does, however, require more changes than I imagined. The whole process can take a while, since I'm doing this in my free time.

**Comment by Camerash** [comment]
Any updates to this?

**Comment by xiprox** [comment]
I would be very interested to know as well. While it's not a deal-breaker in the app we are about to launch, it would be so much better to have this improved.

**Comment by dexcell** [comment]
Any update on this issue?

**Comment by XinyueZ** [comment]
waiting for a branch or temp solution.

**Comment by aleksanderwozniak** [comment]
Demo version has landed! 
You can try it by adding this to `pubspec.yaml` file:

```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: dev
```

**Comment by rwozniak** [comment]
@aleksanderwozniak I have just checked the latest dev version and the month swiping works great! But I can see that a lot of other stuff has also changed - do you plan to update docs/examples soon and create an official release?

**Comment by aleksanderwozniak** [comment]
@rwozniak 
Sure, I will be updating everything accordingly after official release. I am keeping things in this state for a short trial period; there probably will be some additional small changes.

**Comment by craggy2593** [comment]
@aleksanderwozniak  Great job on getting the smooth scrolling, after making some of the other changes going on (setSelectedDay and initialCalendarFormat namely), it works great. Hopefully see it released soon 🤞

One query though, noticed in the calendar controller, there is a new function `_getCalendarHeight`, that enforces a `dowHeight` of 16.  Can this be toggled based on whether days of week are rendered? We have a calendar where we don't render the days of the week, and this caused there to be additional padding around the calendar (so `rowHeight + 16.0` in this case).

**Comment by aleksanderwozniak** [comment]
@craggy2593 great to hear it works well! Thanks for spotting the `dowHeight` issue, I've missed it when I was working on new implementation - this of course will be toggled. 

I plan to release the `3.0.0` version in near future. There are some breaking changes incoming and I need to ensure all is running properly before releasing the update.

**Comment by essarn** [comment]
Will there be any more breaking changes introduced to the `dev` branch before the next release? Is there an expected date for when this version will be released?

**Comment by devharis** [comment]
Any estimated release date of version `3.0.0`? @aleksanderwozniak

**Comment by spareblock** [comment]
So, I'm using dev branch and the swipe between months works but vertical swipe to switch calendar format stopped working and I can't figure out why....

**Comment by cuongloveit** [comment]
wait for release :D

**Comment by jamesdixon** [comment]
Hi there, just wanted to check on this and see if there were any updates? Thanks for all of your great work!

**Comment by aleksanderwozniak** [comment]
I've added `3.0.0-dev` branch which contains major internal rework. In the following days I will publish a null-safe version of it.

This makes current `dev` branch deprecated - if you currently use it, consider migrating to this version.

As far as I know, null-safe prereleases can't be used in Flutter's stable channel yet - if you don't want to change your channel to beta, you can use reworked version by adding following lines to pubspec.yaml:

```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: 3.0.0-dev
```

You will find updated examples [here](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-dev/example/lib).

**Comment by aleksanderwozniak** [comment]
Null safe 3.0.0 prerelease has been uploaded to pub.dev: https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0

For those who don't want to update to null safety yet, there is `3.0.0-beta` branch, on which the published version is based.

**Comment by krymtn** [comment]
On 2.3.3 is still same, I'm not using null safety. do you have any solution for this? because old versions are gone @aleksanderwozniak

**Comment by sandamil** [comment]
Any update on this issue? is posible to avoid blank space when swipping between two months? I can't
get it
