### ISSUE TITLE
Events Marks only been showed when Android System TimeZone is GMT +0

### ISSUE THREAD

**Issue by Schinwinkwinsky** [aleksanderwozniak/table_calendar#551]
Hello, everybody

I'm facing a problem with Events marks. I was testing Events on emulator and everything was ok. But when I run on my device, the Events marks were not been showed. I figured out that was the System TimeZone that on emulator is default GMT +0, but on my device is GMT -3. If I change my device TimeZone to GMT +0, the Events marks are showed properly.

Did anyone face a problem like this or know what it could be causing this?

**Comment by aleksanderwozniak** [comment]
Hi,

You will need to debug the code you are passing to the `eventLoader` property. As long as you properly provide a list of events for a given `day`, everything will be displayed correctly. Have a look at the [events guide](https://github.com/aleksanderwozniak/table_calendar#events) and provided examples.

**Comment by Schinwinkwinsky** [comment]
Thank you for the answer, but I figured out what was causing the problem.

The LinkedHashMap's key must be a UTC date and it must have only the date. No hours, minute, seconds, etc. We was getting the date of the Event and setting the LikedHashMap's key calling `onlyDate()` and `toUtc()` methods. The `toUtc()` method turns the date to UTC but it changes the date's hour based on local time (Android System TimeZone). That was causing the problem.
