### ISSUE TITLE
How to hide button from header?

### ISSUE THREAD

**Issue by iqtedar123** [aleksanderwozniak/table_calendar#554]
I want to hide the 2 weeks button from the header completely.
How would I do that?
Thanks.

![image](https://user-images.githubusercontent.com/12553327/127233998-8d74fad7-e933-4f74-a1e1-e1df8899c742.png)

**Comment by martipello** [comment]
headerStyle: HeaderStyle(
                  titleTextStyle: WordskiiText.h6Style.copyWith(height: 1.2),
                  formatButtonShowsNext: false,
                  formatButtonVisible: false,
                  titleCentered: false,
                  headerPadding: EdgeInsets.only(bottom: 16),
                  headerMargin: EdgeInsets.zero,
                ),

**Comment by iqtedar123** [comment]
> headerStyle: HeaderStyle(
> titleTextStyle: WordskiiText.h6Style.copyWith(height: 1.2),
> formatButtonShowsNext: false,
> formatButtonVisible: false,
> titleCentered: false,
> headerPadding: EdgeInsets.only(bottom: 16),
> headerMargin: EdgeInsets.zero,
> ),

Thanks. That worked. Closing issue.
