### ISSUE TITLE
How do I get the first and last date of the current page

### ISSUE THREAD

**Issue by JonSnow1077** [aleksanderwozniak/table_calendar#555]
![flutter_01](https://user-images.githubusercontent.com/62605414/127303156-ef03ac3f-ac2a-4997-b8fa-4e4704feb9d8.png)

Can anyone tell me how can i get the first and last date of the current page?

**Comment by aleksanderwozniak** [comment]
Check out this comment: https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620
