### ISSUE TITLE
Hide change format button?

### ISSUE THREAD

**Issue by ab36245** [aleksanderwozniak/table_calendar#558]
Hi,

This is a nice widget. It does some things in a cleaner way than others I've looked at.

Is there a way to hide the change format button (the button which cycles through Week, Month, Two Weeks)? I want to be able to offer the user a way to change format in another way. The custom example image on the pub.dev image suggests this is possible but I haven't worked out how.

I have tried simply leaving onFormatChange null but that still draws the button and then generates an error when the user selects it:

```
Using `FormatButton` without providing `onFormatChanged` will have no effect.
'package:table_calendar/src/table_calendar.dart':
Failed assertion: line 466 pos 21: 'widget.onFormatChanged != null'
```

Am I going to have to redraw the header myself in some way?

Thanks

**Comment by Katekko** [comment]
TableCalendar(headerStyle: HeaderStyle(formatButtonVisible: false));

**Comment by ab36245** [comment]
I'd missed the HeaderStyle. Thanks for the help!
