### ISSUE TITLE
when headerVisible is false how do you change calendarFormat?

### ISSUE THREAD

**Issue by gitumar** [aleksanderwozniak/table_calendar#560]
In the complex_example.dart file there is a custom header used which removes the default header that includes the calendar format. How do I include the calendar format option in the custom header used in the complex_example.dart?

**Comment by aleksanderwozniak** [comment]
You simply need to rebuild TableCalendar widget with updated format - [docs](https://github.com/aleksanderwozniak/table_calendar#adding-interactivity).
