### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by Ankit0080** [aleksanderwozniak/table_calendar#562]
TableCalendar(
                      firstDay: DateTime.utc(2020, 4, 16),
                      lastDay: DateTime.utc(2030, 3, 14),
                      focusedDay: DateTime.now(),
                      calendarFormat: _calendarFormat,
                      selectedDayPredicate: (day) {
                        return isSameDay(_selectedDay, day);
                      },
                      onDaySelected: (selectedDay, focusedDay) {
                        print("selected date is " + selectedDay.toString());
                        if (!isSameDay(_selectedDay, selectedDay)) {
                          setState(() {
                            _selectedDay = selectedDay;
                            _focusedDay = focusedDay;
                          });
                        }
                      },
                      onPageChanged: (focusedDay) {
                        _focusedDay = focusedDay;
                      },
                      locale: 'en_US',
                      calendarStyle: CalendarStyle(
                          outsideDaysVisible: false,
                          weekendTextStyle: TextStyle(
                              color: Colors.red,
                              fontFamily: 'NotoSansMedium',
                              fontSize: AppFontSize.font_medium),
                          defaultTextStyle: TextStyle(
                              color: Colors.black,
                              fontFamily: 'NotoSansMedium',
                              fontSize: AppFontSize.font_medium)),
                      daysOfWeekStyle: DaysOfWeekStyle(
                        weekdayStyle: TextStyle(
                            color: Colors.black,
                            fontFamily: 'NotoSansMedium',
                            fontSize: AppFontSize.font_medium),
                      ),
                      headerStyle: HeaderStyle(
                          titleCentered: true,
                          formatButtonVisible: false,
                          titleTextStyle: TextStyle(
                              color: Colors.black,
                              fontFamily: 'NotoSansMedium',
                              fontSize: AppFontSize.font_medium)),
                    ),
                    

I am using this calendar and whenever i am selecting date outside the month the calendar is automatically sliding or returning to current month

**Comment by aleksanderwozniak** [comment]
You need to correctly setup the widget - [docs](https://github.com/aleksanderwozniak/table_calendar#updating-focusedday).

**Comment by Ankit0080** [comment]
i have followed the basic example provided in project  guide but still having the same issue

**Comment by aleksanderwozniak** [comment]
> Setting `focusedDay` to a static value means that whenever **TableCalendar** widget rebuilds, it will use that specific `focusedDay`. You can quickly test it by using hot reload: set `focusedDay` to `DateTime.now()`, swipe to next month and trigger a hot reload - the calendar will "reset" to its initial state. To prevent this from happening, you should store and update `focusedDay` whenever any callback exposes it.

You need to change your `focusedDay`, as in your code it is always set to `DateTime.now()` on each rebuild.
