### ISSUE TITLE
How to change next previous button color ?

### ISSUE THREAD

**Issue by rmarquet21** [aleksanderwozniak/table_calendar#563]
Hello,
I want to change next and previous button to white but I don't find the style to change the color.

![image](https://user-images.githubusercontent.com/43928856/128390289-746bf53a-e2ab-4568-aa50-6bff34994d2d.png)

If you can help me thanks !

**Comment by aleksanderwozniak** [comment]
Hi, you can use [leftChevronIcon](https://pub.dev/documentation/table_calendar/3.0.0/table_calendar/HeaderStyle/leftChevronIcon.html) to provide a custom icon widget (same for right chevron).
