### ISSUE TITLE
How to highlight some special dates in TableCalendar view?

### ISSUE THREAD

**Issue by hasancse91** [aleksanderwozniak/table_calendar#564]
Thanks for your awesome package, it's very useful!
I have a question. Please have a look below UI design which have to achieve:

![calendar_screenshot](https://user-images.githubusercontent.com/3769029/128504840-e34d1bdc-8d07-4255-9940-701c6854b041.png)

Here `12 Jun` is `today`. I've already achieved this UI by customizing `todayDecoration`. But I couldn't customize the date 3, 5, 6 and 10 June.

Suppose user has some special days in every month. We have to mark those special days with green color like above design. How can we implement this logic and UI design?

Thanks in advance for your help.

**Comment by hasancse91** [comment]
After exploring some closed issues and example project I find the solution. It's really great!

```
// First of all I need to prepare a days `Set` to be highlighted. For my case these data will coming from remote server.

  final Set<DateTime> _selectedDays = LinkedHashSet<DateTime>(
    equals: isSameDay,
    hashCode: getHashCode,
  );
  _selectedDays.add(DateTime(2021, 6, 3));
  _selectedDays.add(DateTime(2021, 6, 5));
  _selectedDays.add(DateTime(2021, 6, 6));
  _selectedDays.add(DateTime(2021, 6, 10));

TableCalendar(
  focusedDay: kToday.value,
  firstDay: kFirstDay.value,
  lastDay: kLastDay.value,
  onDaySelected: _onDayTapped,
  startingDayOfWeek: StartingDayOfWeek.monday,
  selectedDayPredicate: (day) => _selectedDays.contains(day),
)
```
Main checking and highlighting logic implemented here:
`selectedDayPredicate: (day) => _selectedDays.contains(day),`

I hope my this comment will help someone in future.
Happy coding...

**Comment by Ankit0080** [comment]
@hasancse91  I tried running this code for showing special dates but nothing happend in calendar
