### ISSUE TITLE
Block certain dates selection

### ISSUE THREAD

**Issue by giaur500** [aleksanderwozniak/table_calendar#568]
I need to use calendar for my booking app. And I want to allow to make booking for certain dates, which are free. Other should be grayed/disabled and not possible to select.

Is it possible to do with this widget? There's no example for that

**Comment by aleksanderwozniak** [comment]
> Is it possible to do with this widget? There's no example for that

Yes, it's possible - there are [docs for that](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/enabledDayPredicate.html) and for other properties/features.
