### ISSUE TITLE
Does the library has Desktop View? Or its mobile only?

### ISSUE THREAD

**Issue by siba2893** [aleksanderwozniak/table_calendar#569]
I'm preparing to build a web and mobile app and I was thinking in using Flutter all the way. But a part of it is that at Desktop I need a full fledge calendar view, to display events and what not.

**Comment by aleksanderwozniak** [comment]
It should work properly on all compatible platforms - you can see them listed [here](https://pub.dev/packages/table_calendar), at the top of the page.
