### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by somfinso** [aleksanderwozniak/table_calendar#570]
We have local calendar which i was thinking use with table calender..In which one box will have one date as nornal date and one is our local language..Is theere possible way( english :1, local :༡)

Suggest me..you suggestion will highly appcreated by 
Thankinh you

**Comment by aleksanderwozniak** [comment]
You can use [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html) to customize day cells to your needs.
