### ISSUE TITLE
Calendar UI error when changing month and selecting first day of month

### ISSUE THREAD

**Issue by andrewiansteven** [aleksanderwozniak/table_calendar#571]
I have been looking at using the table_calendar, however there appears to be a bug if you switch months and select the first day of the month. For example, I set the selected date as todays date  (Tuesday 17th August).

<img width="302" alt="Screenshot 2021-08-17 at 16 56 48" src="https://user-images.githubusercontent.com/17761614/129760064-82f7fc15-562d-479e-9156-246efec8d572.png">

 I then select previous month using the previous chevron. I have the calendar format set as month. 

<img width="299" alt="Screenshot 2021-08-17 at 16 57 02" src="https://user-images.githubusercontent.com/17761614/129760062-2ff72732-6275-4c62-acd7-8ef6de748b76.png">

 If I then select the first day of the month (Thursday 1st July), for some reason the calendar UI breaks and only shows 3 dates at the bottom of the widget. 

<img width="306" alt="Screenshot 2021-08-17 at 16 57 11" src="https://user-images.githubusercontent.com/17761614/129760055-c399484c-f9b8-4142-aecd-9ada00defdbd.png">

I am not sure why this happens as selecting any other date other than the first day of the month works as you would expect. Can you look into this as soon as possible please as I would like to continue using this widget, however I need a quick fix otherwise I will have to look at alternative solutions.

**Comment by aleksanderwozniak** [comment]
Do you also have this issue when running the example project?

**Comment by andrewiansteven** [comment]
Turns out it was my own fault. I was setting the firstDay and lastDay based on the selected date, which can change all the time. By using static values, this fixed the issue.
