### ISSUE TITLE
Minimum Date and Maximum Date

### ISSUE THREAD

**Issue by Ankit0080** [aleksanderwozniak/table_calendar#573]
I want to set current month as minimum and allow user to swipe next three months only . Suppose current month in January then user should not be able to go back and if i swipe right user should not be go outside april. Does this calendar support this functionality.?

This is my Code

TableCalendar(
                      firstDay: DateTime.utc(2020, 4, 16),
                      lastDay: DateTime.utc(2021, 10, 31),
                      focusedDay: DateTime.now(),
                      calendarFormat: _calendarFormat,
                      startingDayOfWeek: StartingDayOfWeek.monday,
                      selectedDayPredicate: (day) {
                        return isSameDay(_selectedDay, day);
                      },
                      onDaySelected: (selectedDay, focusedDay) {
                        print("selected date is " + selectedDay.toString());

                        widget.dateSelectionCallback.onDateSelected(
                            selectedDay.toString(), widget.landingType);
                        Navigator.pop(context);

                        if (!isSameDay(_selectedDay, selectedDay)) {
                          setState(() {
                            _selectedDay = selectedDay;
                            _focusedDay = focusedDay;
                          });
                        }
                      },
                      onPageChanged: (focusedDay) {
                        _focusedDay = focusedDay;
                      },
                      locale: 'en_US',
                      calendarStyle: CalendarStyle(
                          outsideDaysVisible: false,
                          weekendTextStyle: TextStyle(
                              color: Colors.red,
                              fontFamily: 'NotoSansMedium',
                              fontSize: AppFontSize.font_medium),
                          defaultTextStyle: TextStyle(
                              color: Colors.black,
                              fontFamily: 'NotoSansMedium',
                              fontSize: AppFontSize.font_medium)),
                      daysOfWeekStyle: DaysOfWeekStyle(
                        weekendStyle: TextStyle(
                            color: Colors.black,
                            fontFamily: 'NotoSansMedium',
                            fontSize: AppFontSize.font_medium),
                        weekdayStyle: TextStyle(
                            color: Colors.black,
                            fontFamily: 'NotoSansMedium',
                            fontSize: AppFontSize.font_medium),
                      ),
                      headerStyle: HeaderStyle(
                          titleCentered: true,
                          formatButtonVisible: false,
                          titleTextStyle: TextStyle(
                              color: Colors.black,
                              fontFamily: 'NotoSansMedium',
                              fontSize: AppFontSize.font_medium)),
                    ),

**Comment by aleksanderwozniak** [comment]
Yes, check [this section](https://github.com/aleksanderwozniak/table_calendar#basic-setup) for details.

**Comment by Ankit0080** [comment]
@aleksanderwozniak No i am talking about to set it dynamically using Locale but the first date and max date are not accepting Locale dates

**Comment by aleksanderwozniak** [comment]
What do you mean by "locale dates"?

You can set `firstDay` to DateTime.now() and `lastDay` to DateTime.now() + 3 months.

**Comment by Ankit0080** [comment]
Can you show me ? i think it's not working the +3 month thing . I generally do it using Java Locale but seems like this package doesn't support Locale

**Comment by Ankit0080** [comment]
i was able to do it using this code 
firstDay: DateTime.utc(2020, 4, 16),
                      lastDay: DateTime.utc(
                          DateTime.now().year, DateTime.now().month + 2),

but when using this code  it is counting next three months from current date. i don't want to set minimum and max date using date i want to set min and max month

Suppose current month is September then the calendar should show September ,october, november but it is sliding till december because of the  current date

**Comment by Ankit0080** [comment]
@aleksanderwozniak  I figured it out somehow. Thanks for the wonderful library . I am closing this issue
