### ISSUE TITLE
Can't find option to customize event dot on calendar

### ISSUE THREAD

**Issue by AzarouAmine** [aleksanderwozniak/table_calendar#574]
I can't find the option to customize the dot added on a date in the calendar if an event exists. Perhaps I haven't paid enough attention. However, if this doesn't exist, can it be implemented?

**Comment by aleksanderwozniak** [comment]
Have a look at [CalendarStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle-class.html) and [CalendarBuilders](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html). Event dots are called "markers" there.
