### ISSUE TITLE
Ability to scroll per day if CalendarFormat.week is selected

### ISSUE THREAD

**Issue by martiina** [aleksanderwozniak/table_calendar#575]
As title says.

Is there possibility for example to scroll daily. At the moment, the Pageview scrolls all 7 days at once.
Is there some workaround for that or core file changes are needed?

**Comment by aleksanderwozniak** [comment]
By design the chosen format == scrolling increment, so for week format you will scroll by a week, while for month format you will scroll by a month. To use day by day scrolling you would need to make some changes in internal files.
