### ISSUE TITLE
table_calendar: ^3.0.2 Selector for today and selected date 

### ISSUE THREAD

**Issue by Vinayak27Mobility** [aleksanderwozniak/table_calendar#577]
selectedBuilder: (context, date, events) =>
                                    Container(
                                        alignment: Alignment.center,
                                        decoration: BoxDecoration(
                                            color: Colors.red,
                                            borderRadius:
                                            BorderRadius.circular(100.0)),
                                        child: Text(date.day.toString(),
                                            style: Theme.of(context)
                                                .textTheme
                                                .headline5)),
                                todayBuilder: (context, date, events) =>
                                    Container(
                                        alignment: Alignment.center,
                                        decoration: BoxDecoration(
                                            color: Color(AppConstants.bgGreen),
                                            borderRadius:
                                                BorderRadius.circular(100.0)),
                                        child: Text(
                                          date.day.toString(),
                                          style: Theme.of(context)
                                              .textTheme
                                              .headline5,
                                        ))

Please advice! Thanks.

**Comment by aleksanderwozniak** [comment]
What exactly is the issue?

**Comment by Vinayak27Mobility** [comment]
The selector is not working for selected date. If I try to select other date it take today builder which is green color.

**Comment by aleksanderwozniak** [comment]
Please check if this also happens when you run the example project, this might be the expected result depending on the way you configure the widget.

**Comment by jigarfumakiya** [comment]
Yes, it happens with the example project.
Having the same issue here

**Comment by aleksanderwozniak** [comment]
I am not able to reproduce this. Can you post your TableCalendar widget configuration here? It would also be helpful to post a short video that showcases what exactly happens.

**Comment by jigarfumakiya** [comment]
@aleksanderwozniak 
Here is my code

```
TableCalendar(
          focusedDay: _homeController.highLightDate,
          firstDay: DateTime.utc(2010, 10, 16),
          lastDay: DateTime.utc(2030, 3, 14),
          calendarFormat: CalendarFormat.week,
          startingDayOfWeek: StartingDayOfWeek.monday,
          calendarStyle: const CalendarStyle(
              isTodayHighlighted: true,
              canMarkersOverflow: true,
              selectedTextStyle: TextStyle(backgroundColor: Colors.amber),
              selectedDecoration: BoxDecoration(color: Colors.amber)),
          onCalendarCreated: (pageController) {
            _homeController.calenderController = pageController;
          },
          availableGestures: AvailableGestures.horizontalSwipe,
          headerVisible: false,
          onDaySelected: (selectedDay, focusedDay) {
            print(focusedDay);
            _homeController.calenderDateChange(focusedDay);
          },
          // dayHitTestBehavior: HitTestBehavior.deferToChild,
        );
```

Here is the video 

https://user-images.githubusercontent.com/11865669/132406544-7b8c090c-48d8-48cb-b812-60575753c94f.mov


Here are the logs I am getting in AS

![Screenshot 2021-09-08 at 1 56 36 AM](https://user-images.githubusercontent.com/11865669/132406582-dcfae486-8b1b-4537-b801-ce0e2aee6d66.png)

**Comment by jigarfumakiya** [comment]
@aleksanderwozniak 
Let me know if you need anything else.

**Comment by aleksanderwozniak** [comment]
@jigarfumakiya 
You need to correctly setup the widget: https://github.com/aleksanderwozniak/table_calendar#adding-interactivity

Check [basics example](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/pages/basics_example.dart) for more info.
