### ISSUE TITLE
Feature Request: Go Back to Today Callback

### ISSUE THREAD

**Issue by sgon00** [aleksanderwozniak/table_calendar#58]
*(As a discussion from another issue, file this new feature request for tracking.)*
A callback function to let the calendar go back to today view and make today selected too. 
Thank you very much.

**Comment by evanchen2914** [comment]
You can just call `setState` with `selectedDay = DateTime.now()`

**Comment by evanchen2914** [comment]
Just do

```
setState(() {
    DateTime now = DateTime.now();
    selectedDay = DateTime(now.year, now.month, now.day);
});
```

**Comment by aleksanderwozniak** [comment]
Added with #84.

Update the package to version `2.0.0`, then follow [these steps](https://github.com/aleksanderwozniak/table_calendar#installation).

If you want to go back to today and select it:
```dart
setState(() {
  _calendarController.setSelectedDay(DateTime.now());
});
```

If you want to go back to today, select it, and then trigger `onDaySelected` callback (NOTE: if you are using `setState()` in the callback, then you can omit it here):
```dart
setState(() {
  _calendarController.setSelectedDay(DateTime.now(), runCallback: true);
});
```

If you want to go back to today, but without changing the SelectedDay:
```dart
setState(() {
  _calendarController.setFocusedDay(DateTime.now());
});
```
