### ISSUE TITLE
Date Selection Range

### ISSUE THREAD

**Issue by Vinayak27Mobility** [aleksanderwozniak/table_calendar#580]
Hi,

When we change mode of the Calendar like Month view and 2Week View, Can we get the date range which is visible on the screen? 

![image](https://user-images.githubusercontent.com/25246946/132281272-38453795-2ec7-4fc1-a8a3-8355f687c213.png)

In Above the range will be 29th Aug to 11 Sep and 

![image](https://user-images.githubusercontent.com/25246946/132281381-3b96af38-6dc8-46e2-a2cc-bde3d34cb785.png)

In Above the range will be 29th Aug to 2nd Oct. thanks.

**Comment by aleksanderwozniak** [comment]
Check out this comment for details: https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620

**Comment by Vinayak27Mobility** [comment]
Is it working for 2 weeks mode , how to get start and end date when 2 weeks is set?
