### ISSUE TITLE
Error: Failed assertion: line 131 pos 12: 'shape != BoxShape.circle || borderRadius == null': is not true.

### ISSUE THREAD

**Issue by ousvat** [aleksanderwozniak/table_calendar#583]
When I give to `CalendarStyle()` a `selectedDecoration` with a `borderRadius: BorderRadius.circular(8)` and I change the selected date, I receive this error for a moment:

```
The following assertion was thrown building AnimatedContainer(duration: 250ms, Alignment.center, bg: BoxDecoration(shape: circle), margin: EdgeInsets.all(6.0), clipBehavior: Clip.none, dirty, dependencies: [_EffectiveTickerMode], state: _AnimatedContainerState#ad4cc(ticker active, AlignmentGeometryTween(Alignment.center → Alignment.center), bg: DecorationTween(BoxDecoration(color: MaterialColor(primary value: Color(0xfff44336)), borderRadius: BorderRadius.circular(8.0)) → BoxDecoration(shape: circle)), margin: EdgeInsetsGeometryTween(EdgeInsets.all(6.0) → EdgeInsets.all(6.0)))):
'package:flutter/src/painting/box_decoration.dart': Failed assertion: line 131 pos 12: 'shape != BoxShape.circle || borderRadius == null': is not true.

```

**Comment by aleksanderwozniak** [comment]
This happens, because by default decorations in CalendarStyle use `BoxShape.circle`.

To solve this, you can add `BoxShape.rectangle` to each decoration property that you are using (`defaultDecoration`, `todayDecoration`, etc.).

**Comment by ousvat** [comment]
Yeah.. but i want to have kind of oval shape on selected day.

**Comment by aleksanderwozniak** [comment]
That's the point of using `BoxShape.rectangle`. You need it to use `borderRadius`, just as the error message says.

**Comment by ousvat** [comment]
> That's the point of using `BoxShape.rectangle`. You need it to use `borderRadius`, just as the error message says.

I have put the `BoxShape.rectangle` and set a `borderRadius` and everything works good till I change the selected day. There is a second when I get the error I mentioned above.

**Comment by ousvat** [comment]
Ah... I got it now... even if I don't want to custom the other decorations I need to put at least `BoxDecoration(boxShape: BoxShape.rectangle)` to each of them... This can give you headache but it work for me. Thanks.

**Comment by aleksanderwozniak** [comment]
I agree, it would be best if it didn't require setting all the remaining decorations as well - I'll look into it.

**Comment by payelpaul121999** [comment]
no working your tips bro

**Comment by ziagit** [comment]
boxShape property is not defined

**Comment by ziagit** [comment]
> no working your tips bro

If you are using TableCalendar and you want a rounded selected day instead of borderRadius use shape: BoxShape.rectangle or shape: BoxShape.circle.

**Comment by Izudinalqasam** [comment]
you need to set `defaultDecoration` same with boxDecoration you want with default color @payelpaul121999 , for example

```dart
 calendarStyle: CalendarStyle(
          selectedDecoration: BoxDecoration(
            shape: BoxShape.rectangle,
            color: ColorName.toGreenMain,
            borderRadius: BorderRadius.circular(5),
          ),
          defaultDecoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(5),
          ),
        ),
```

**Comment by s99chandra** [comment]
> This happens, because by default decorations in CalendarStyle use `BoxShape.circle`.
> 
> To solve this, you can add `BoxShape.rectangle` to each decoration property that you are using (`defaultDecoration`, `todayDecoration`, etc.).

like this:

```
calendarStyle: CalendarStyle(
        todayDecoration: BoxDecoration(
          color: Colors.orange,
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(10),
        ),
        selectedDecoration: BoxDecoration(
          color: Colors.orange,
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(10),
        ),
        weekendDecoration: BoxDecoration(
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(10),
        ),
        defaultDecoration: BoxDecoration(
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(10),
        ),
      ),
```

**Comment by CanadianN1nj4** [comment]
There's still a problem if you want to have different shapes for different decorations. For example I want to have a circle for today, but I want to have rectangle for selected. Unless everything is the same shape it still causes the error.

**Comment by NiroopNife** [comment]
The problem still exists when switching between months

**Comment by rajatiota** [comment]
calendarStyle: CalendarStyle(
        todayDecoration: BoxDecoration(
          color: Colors.orange,
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(10),
        ),
        selectedDecoration: BoxDecoration(
          color: Colors.orange,
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(10),
        ),
        weekendDecoration: BoxDecoration(
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(10),
        ),
        defaultDecoration: BoxDecoration(
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(10),
        ),
      ),
      this works for current month but when you select next month date error is still exists

**Comment by rajatiota** [comment]
> calendarStyle: CalendarStyle( todayDecoration: BoxDecoration( color: Colors.orange, shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ), selectedDecoration: BoxDecoration( color: Colors.orange, shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ), weekendDecoration: BoxDecoration( shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ), defaultDecoration: BoxDecoration( shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ), ), this works for current month but when you select next month date error is still exists

i found solution myself - **### outsideDecoration**  change in it also

outsideDecoration: BoxDecoration(
shape: BoxShape.rectangle,
borderRadius: BorderRadius.circular(10),
),

**Comment by JuanFGQ** [comment]
in 

> > calendarStyle: CalendarStyle( todayDecoration: BoxDecoration( color: Colors.orange, shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ), selectedDecoration: BoxDecoration( color: Colors.orange, shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ), weekendDecoration: BoxDecoration( shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ), defaultDecoration: BoxDecoration( shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ), ), this works for current month but when you select next month date error is still exists
> 
> i found solution myself - **### outsideDecoration** change in it also
> 
> outsideDecoration: BoxDecoration( shape: BoxShape.rectangle, borderRadius: BorderRadius.circular(10), ),

In addition with past anwers this solve my problem.

**Comment by ahammamlho** [comment]
Hi @aleksanderwozniak 👋
I faced the same error and tried many of the suggestions above. What finally solved it for me was making sure every decoration (including outsideDecoration) explicitly uses both:

```
borderRadius: BorderRadius.circular(8),
shape: BoxShape.rectangle,
```

So for example:
```
outsideDecoration: BoxDecoration(
  color: Colors.white,
  borderRadius: BorderRadius.circular(8),
  shape: BoxShape.rectangle,
),
```

Even if I didn’t want to customise some decorations (like weekend or outside), adding shape: BoxShape.rectangle + borderRadius to all of them fixed the issue.
