### ISSUE TITLE
How to add custom numbers according to locale.

### ISSUE THREAD

**Issue by RohanYadav15** [aleksanderwozniak/table_calendar#586]
In calendar i want to show the date but with different number format according to the locale like १,२,३,४,५ not 1,2,3,4,5 . Is there any possible way to do it?

**Comment by aleksanderwozniak** [comment]
You can use [CalendarBuilders ](https://pub.dev/documentation/table_calendar/3.0.2/table_calendar/CalendarBuilders-class.html)for this. Check out https://github.com/aleksanderwozniak/table_calendar/issues/342 for more info.

**Comment by RohanYadav15** [comment]
Thanks a lot, i got it!!
