### ISSUE TITLE
markerBuilder not showing december month data in calendar

### ISSUE THREAD

**Issue by selvas1998** [aleksanderwozniak/table_calendar#588]
As per our UI implemenation, we tried to build your table calendar and show some events in calendar. But we faced some issues on markerBuilder, some events in december month not showing. I checked the map of events, that particular events are there, but marker builder does not call when that particular date is arrived.

Note: December 25 to 31 (these are the dates not showing as a marker in calendar)

**Comment by selvas1998** [comment]
![calendar-issue](https://user-images.githubusercontent.com/44501196/134632042-fce56fbe-88da-4a0e-9998-d70f64882622.jpg)

**Comment by selvas1998** [comment]
![calendar-issue](https://user-images.githubusercontent.com/44501196/134632403-f9cc9034-ab0f-4192-bfd2-1bc7eefb34e2.jpg)

**Comment by aleksanderwozniak** [comment]
Check how your `lastDay` property is set up, it seems to be the [reason](https://github.com/aleksanderwozniak/table_calendar#basic-setup).

**Comment by selvas1998** [comment]
Awesome it works. Thank you for your response.

**Comment by Ankit0080** [comment]
@selvas1998 I am also trying to get events from backend inside list which i need to show on calendar . I want to mark those dates for particular month in calendar in circle. Can you please share your code or help me out here. I am new to flutter
