### ISSUE TITLE
FillViewPort Configuration: Stretch gesture detector, keep the calendar not stretched

### ISSUE THREAD

**Issue by nivisi** [aleksanderwozniak/table_calendar#589]
Hello! Thanks for a great package 🙂

I need to achieve the following appearance and behaviour in my app (see the vid).

Although, when I use the `shouldFillViewport` property, I have no control on whether the widget itself must be stretched. The behaviour on the video is achieved by adding a `GestureDetector` below the Calendar and controlling the `PageController` of the Calendar.

Am I missing something and is there an easier way?

https://user-images.githubusercontent.com/33932162/134721838-4f3823da-2695-4de8-9fbf-ee2a1c840dca.mov

**Comment by nivisi** [comment]
> At this moment I'm not willing to change the core

Sure, no problem. Just keep in mind that someone needs such a behaviour 😀

> Which deprecated methods of PageController do you mean?

[jumpToWithoutSettling](https://api.flutter.dev/flutter/widgets/ScrollPosition/jumpToWithoutSettling.html) of the `ScrollPosition` class. If we use the common `jumpTo` or `animateTo`, the calendar will reset the scroll when the finger gesture stops.

**Comment by aleksanderwozniak** [comment]
Hmm I see... I'll think about this. For now though - closing the issue.
