### ISSUE TITLE
Doubts on onVisibleDaysChanged changed to onPageChanged

### ISSUE THREAD

**Issue by selvas1998** [aleksanderwozniak/table_calendar#591]
Before that 3.0.0 version, onVisibleDaysChanged field have firstDate and lastDate include outsideDaysVisible: true. But now onPageChanged doesn't have any first and last date in that field. So, How do I get that include outsideDays?

**Comment by aleksanderwozniak** [comment]
Check out https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620 for more info. You can calculate the outside days in a similar fashion.

**Comment by selvas1998** [comment]
Okay, I will check. Thanks for your response. As of now, I'll close this.
