### ISSUE TITLE
Spacing between dow strip and the view where all month dates are present

### ISSUE THREAD

**Issue by moksh-mahajan** [aleksanderwozniak/table_calendar#592]
I want to add some sapcing between days of week strip and first row of the month days. Is it possible to do so?

**Comment by aleksanderwozniak** [comment]
Try using [daysOfWeekHeight](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/daysOfWeekHeight.html) together with [dowBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/dowBuilder.html) for this.

**Comment by moksh-mahajan** [comment]
Thanks! It worked.
