### ISSUE TITLE
Calendar random error

### ISSUE THREAD

**Issue by Ankit0080** [aleksanderwozniak/table_calendar#599]
This code was working fine suddenly  In release mode the calendar screen is  blank and in debug mode it's working

  @override
  void initState() {
    _focusedDay = DateTime.now();
    super.initState();

  }

TableCalendar(
                      firstDay:
                          DateTime.utc(_startYear, _startMonth, _startDate),
                      lastDay: DateTime.utc(_endYear, _endMonth, _endDate),
                      focusedDay: _focusedDay,
                      rowHeight: 45,
                      calendarFormat: _calendarFormat,
                      startingDayOfWeek: StartingDayOfWeek.monday,
                      selectedDayPredicate: (day) {
                        return isSameDay(_selectedDay, day);
                      },
                      onDaySelected: (selectedDay, focusedDay) {
                        print("selected date is " + selectedDay.toString());
                        var dayOfWeek = DateFormat.EEEE().format(selectedDay);
                        // widget.foodDateSelectionCallback.onFoodDateSelected(
                        //     selectedDay.toString().split(" ")[0], dayOfWeek);
                        // Navigator.pop(context);

                        if (!isSameDay(_selectedDay, selectedDay)) {
                          setState(() {
                            _selectedDay = selectedDay;
                            _focusedDay = focusedDay;
                          });
                        }
                      },
                      onPageChanged: (focusedDay) {
                        _focusedDay = focusedDay;
                        presentMonth = focusedDay.month.toString();
                        getCalendarEvents();
                        //Helper.showToast(presentMonth);
                      },
                      locale: 'en_US',
                      calendarStyle: CalendarStyle(
                          outsideDaysVisible: false,
                          weekendTextStyle: TextStyle(
                              color: Colors.red,
                              fontFamily: 'PoppinsMedium',
                              fontSize: AppFontSize.font_medium),
                          defaultTextStyle: TextStyle(
                              color: Colors.black,
                              fontFamily: 'PoppinsMedium',
                              fontSize: AppFontSize.font_medium)),
                      daysOfWeekStyle: DaysOfWeekStyle(
                        weekendStyle: TextStyle(
                            color: Colors.black,
                            fontFamily: 'PoppinsMedium',
                            fontSize: AppFontSize.font_medium),
                        weekdayStyle: TextStyle(
                            color: Colors.black,
                            fontFamily: 'PoppinsMedium',
                            fontSize: AppFontSize.font_medium),
                      ),
                      headerStyle: HeaderStyle(
                          titleCentered: true,
                          formatButtonVisible: false,
                          titleTextStyle: TextStyle(
                              color: Colors.black,
                              fontFamily: 'PoppinsMedium',
                              fontSize: AppFontSize.font_medium)),
                    ),

**Comment by aleksanderwozniak** [comment]
> error isSameDat(focusday,lastday)|| focusday.isBefore(lastDay) is not true

Looks like your `_focusedDay` is after your `lastDay`. It has to be between the `firstDay` and the `lastDay` in order for the widget to work properly.
