### ISSUE TITLE
Custom builder causes RenderFlex overflowed on smaller sized device

### ISSUE THREAD

**Issue by sgon00** [aleksanderwozniak/table_calendar#60]
Hi, I am not sure if I should consider dealing with smaller sized device or not. Today, I am testing a device which has a resolution of 470x960. The plugin works fine on modern devices. But when I test on this particular smaller resolution device, I got the following screenshot: 

![flutter_02](https://user-images.githubusercontent.com/1555508/58630687-cccabf00-8312-11e9-858c-c2739f64382e.png)

I have removed the extra texts on other builders and just keep it on `todayDayBuilder` just to make the screenshot clear. 

The code is basically:

```dart
        todayDayBuilder: (context, date, _) {
          return Container(
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: _color,
            ),
            margin: const EdgeInsets.all(6.0),
            alignment: Alignment.center,
            child: Column(
              children: <Widget>[
                Text(
                  '${date.day}',
                  style: _textstyle
                ),
                Text(
                  _getLunarDayCN(date),
                  style: _textstyle2
                )
              ],
            )
          );
        },
```

I checked #38 issue. I don't think I can use any of the two solutions. Should I just drop the support of this particular resolution 470x960?

Thanks a lot.

**Comment by aleksanderwozniak** [comment]
Take a look at #48, it should come in handy.

**Comment by sgon00** [comment]
Thank you very much for the quick reply and solution. After adding `rowHeight` property, It works pretty well. Thanks. 😀👍
