### ISSUE TITLE
How to detect next month is visible?

### ISSUE THREAD

**Issue by ambogatyrev** [aleksanderwozniak/table_calendar#600]
For example, screenshot shows the weekly calendar format (September - October). So how i can detect the october month is visible?

![image](https://user-images.githubusercontent.com/79789858/137874881-ede81b75-92f1-416d-a0a2-3998074822fc.png)

Thanks!

**Comment by aleksanderwozniak** [comment]
You can use `focusedDay` for this - check out the [docs](https://github.com/aleksanderwozniak/table_calendar#basic-setup).
