### ISSUE TITLE
Locale data has not been initialized, call initializeDateFormatting(<locale>).

### ISSUE THREAD

**Issue by kaijiemu** [aleksanderwozniak/table_calendar#601]
TableCalendar(
            locale: 'zh_CN',
            firstDay: DateTime.utc(2010, 10, 16),
            lastDay: DateTime.utc(2030, 3, 14),
            focusedDay: DateTime.now(),
          )

增加了locale: 'zh_CN'，就报错了

The following LocaleDataException was thrown building CalendarPage(dirty):
Locale data has not been initialized, call initializeDateFormatting(<locale>).

The relevant error-causing widget was: 
  TableCalendar<dynamic> file:///Users/hzkai/Desktop/flutter_learn/lib/calendar/calendar_page.dart:37:18
When the exception was thrown, this was the stack: 
#0      UninitializedLocaleData._throwException (package:intl/src/intl_helpers.dart:80:5)
#1      UninitializedLocaleData.containsKey (package:intl/src/intl_helpers.dart:74:7)
#2      DateFormat.localeExists (package:intl/src/intl/date_format.dart:834:28)
#3      verifiedLocale (package:intl/src/intl_helpers.dart:159:19)
#4      new DateFormat (package:intl/src/intl/date_format.dart:266:19)

**Comment by aleksanderwozniak** [comment]
Check out [this section](https://github.com/aleksanderwozniak/table_calendar#locale) for more info.
