### ISSUE TITLE
No CalendarController on version 3.0.2 to dispose TableCalendar

### ISSUE THREAD

**Issue by alihaider78222** [aleksanderwozniak/table_calendar#602]
In the version 3.0.2. CalendarController is not available for TableCalendar() and then we cannot dispose it like in older version 2.2.3. Kindly fix that.

**Comment by aleksanderwozniak** [comment]
CalendarController has been removed in v3.0.0 - you can find more details [here](https://github.com/aleksanderwozniak/table_calendar/issues/153#issuecomment-772881560).
