### ISSUE TITLE
Some of the dates are greyed out but still clickable

### ISSUE THREAD

**Issue by Riley-Howley** [aleksanderwozniak/table_calendar#604]
![phonescreen](https://user-images.githubusercontent.com/71965268/138848825-5b70ae18-699e-444f-859b-32b0bad9f35e.png)

**Comment by aleksanderwozniak** [comment]
Looks like they just blend with the background. You can change colors with [CalendarStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle-class.html).
