### ISSUE TITLE
Table calendar days of the week are getting cut by the table view

### ISSUE THREAD

**Issue by infinitysush** [aleksanderwozniak/table_calendar#607]
![image](https://user-images.githubusercontent.com/44548333/139600324-9f9f3336-99cc-4a2f-8fe5-c8e939befb6b.png)

As can be seen in the picture, on my phone one plus five the days of the week are getting halved and I cannot find any parameter to fix this. This is the default setting.

**Comment by marwenx** [comment]
Hi @infinitysush ,

were you able to fix this issue? If yes, how?

Thank you!

**Comment by mmakmw** [comment]
@infinitysush ,

we also have this issue. How did you solve it?

**Comment by infinitysush** [comment]
there is a parameter days of the week in the TableCalendar class
daysOfWeekHeight: 20,
Just increase the height. I think this needs to be with media query to accommodate different screen sizes. Strange bug but increasing the height fixed it for me
