### ISSUE TITLE
how can i find out if the day is in the last row of the calendar widget

### ISSUE THREAD

**Issue by ntfnd404** [aleksanderwozniak/table_calendar#608]
![Снимок_экрана_2021-11-01_в_00_55_46_1](https://user-images.githubusercontent.com/3759547/139602625-a1f36216-b807-45c8-a5f6-eb5d11622cf8.png)

**Comment by aleksanderwozniak** [comment]
You could calculate the last day of given month, and based on its `weekday` determine if the day in question is at the last row.
