### ISSUE TITLE
Every monday

### ISSUE THREAD

**Issue by freezethearth** [aleksanderwozniak/table_calendar#61]
What do I have to do to add activity to all the Mondays in a year? I did some research but i think i missed something.

I am really newbie here and hard to read english for me :/

**Comment by aleksanderwozniak** [comment]
As far as this package is concerned, you would need to prepare the data yourself. You can use `List.generate()` to create a list of all Mondays in a year, assign your activity to them, and then pass that to TableCalendar widget.

**Comment by aleksanderwozniak** [comment]
As of v3.0.0 you can also go for this approach: https://github.com/aleksanderwozniak/table_calendar/issues/160#issuecomment-773265340. If you have any further questions, feel free to ask them in #160.
