### ISSUE TITLE
Customize color of each date based on sets of conditions

### ISSUE THREAD

**Issue by oltoch** [aleksanderwozniak/table_calendar#612]
How do one edit colors or styles in general of individual dates of month so that each date or set of dates have different colors based on conditions? Can't seems to be able to access date of month in the calendar builders. See attached picture for clarification
![calendar](https://user-images.githubusercontent.com/35864821/140564969-b6e2a028-332a-46a2-8f80-cf45344a2a2b.png)

**Comment by aleksanderwozniak** [comment]
[This section](https://github.com/aleksanderwozniak/table_calendar#custom-ui-with-calendarbuilders) should be helpful.

**Comment by oltoch** [comment]
I've now solved it with marker builder. Thanks
