### ISSUE TITLE
Markers spanning on multiple days

### ISSUE THREAD

**Issue by Gheo** [aleksanderwozniak/table_calendar#618]
Hi,

I've been playing around with different kind of markers and noticed that there's some use case that is not supported by the calendar, or at least I couldn't find a way on how to do it.
What I'm trying to achieve:
 - I have multiple markers in one day
 - the number of day is aligned on top of the cell
 - the markers are displayed as horizontal lines in a column (so one below each other) (and they fill up the whole width of the cell)
 - some of the markers have to go over multiple days.

For this last point I couldn't find a solution, and I was hoping that some of you can point me to the right direction.

What I've tried:
 - using singleMarkerBuilder -> each marker will be displayed into a Row
 - using markerBuilder and adding markers into a ListView -> could not make the list span over multiple days.

I could actually do something like this but by modifying the table_calendar so that the markers built with singleMarkerBuilder were added to a column instead. But I was wondering if this functionality is already possible in some other way.

![Simulator Screen Shot - iPhone 13 - 2021-11-10 at 12 12 09](https://user-images.githubusercontent.com/3054967/141104950-5d5f4739-6abf-428a-b3c9-a627ef21f721.png)

**Comment by Flavio-Vieirastack** [comment]
hello friend, can you tell me if your events come from an api?

**Comment by Gheo** [comment]
Sorry, I forgot to mention. I am working on the events_example from this repository. So, the events are not coming from an API call.

**Comment by aleksanderwozniak** [comment]
Hi there.

Try placing your `Column` in `markerBuilder`, but wrap it in `Positioned` widget and set the width there - this should do the trick.

**Comment by Gheo** [comment]
> Hi there.
> 
> Try placing your `Column` in `markerBuilder`, but wrap it in `Positioned` widget and set the width there - this should do the trick.

This worked perfectly!
Thanks a lot!

**Comment by garylyq1212** [comment]
Hi, I'm able to span across the container multiple days but not been able to display the event title across. May I know how do u achieve that?
