### ISSUE TITLE
event list fill all calendar dates

### ISSUE THREAD

**Issue by Flavio-Vieirastack** [aleksanderwozniak/table_calendar#619]
I'm trying to add events to the table calendar using a list, but without success because the calendar looks like it's in the photo below:
![Sem título](https://user-images.githubusercontent.com/85948951/141165407-f91ace4a-2718-4bf1-9c68-b0711babf47d.png)

in the documentation they say that the calendar takes a dynamic list, and a function of type date time

```
Events 
The complete example is available here.

You can supply custom events to TableCalendar widget. To do so, use eventLoader property - you will be given a DateTime object, to which you need to assign a list of events.

eventLoader: (day) {
  return _getEventsForDay(day);
},
```
well I have a list of dates coming from an api, which is the one below

`[2021-07-11 00:00:00.000, 2021-07-25 00:00:00.000, 2021-07-26 00:00:00.000, 2021-07-27 00:00:00.000, 2021-09-01 00:00:00.000, 2021-09-01 00:00:00.000, 2021-09-03 00:00:00.000, 2021-09-03 00:00:00.000, 2021-09-22 00:00:00.000, 2021-09-24 00:00:00.000, 2021-10-18 00:00:00.000, 2021-10-21 00:00:00.000]`

this list is in string format so I converted it like this:

```
final events = await _jobsServices.getEvents();
        final eventsConvert = events
            .map((date) => (DateTime.parse(date.dataDoJob)))
            .toList();


        eventsList.assignAll(eventsConvert);
```
the first list called events and the list that receives the data that comes from the api so I converted it to date time format, but as you can see in the photo, all calendar days are marked,

on my calendar widget I put it like this:

```
TableCalendar(
              eventLoader: (day) => controller.eventsList, //THIS IS THE EVENTS
              calendarBuilders: const CalendarBuilders(),
              focusedDay: controller.focusedDay.value,
              firstDay: DateTime(2019),
              lastDay: DateTime(2050),
              headerStyle:
                  const HeaderStyle(formatButtonVisible: false), //WEEK VISIBLE
              locale: 'pt_BR',
              daysOfWeekVisible: true,
              calendarFormat: controller.format.value,
              onFormatChanged: (CalendarFormat _format) =>
                  controller.calendarFormat(_format),
              onDaySelected: (DateTime userSelectedDay, DateTime focusedDay) =>
                  controller.selectedDay(userSelectedDay, focusedDay),
              calendarStyle: CalendarStyle(
                  selectedTextStyle: const TextStyle(color: Colors.white),
                  isTodayHighlighted: true,
                  selectedDecoration: BoxDecoration(
                      color: context.buttomThemeClicled,
                      shape: BoxShape.circle)),
              selectedDayPredicate: (DateTime date) {
                return isSameDay(controller.focusedDay.value, date);
              },
            );
```
sure i'm doing something wrong but i still don't know what
if someone can help me I would appreciate it a lot, I've been at it for days

**Comment by Flavio-Vieirastack** [comment]
Well folks now I'm going to show you the way I found to show events and cards coming from an api using the table calendar.
I don't even need to say that this is the way I found things, feel free to add new things and give tips here. so let's go.

first of all we will show the calendar events, but in this step only the markers, your data coming from the api must contain dates if you are here, in my case the dates come as a String, so let's create the model for them

   ```
 import 'dart:convert';
    
    class EventsModel {
      final String dataDoJob;
      EventsModel({
        required this.dataDoJob,
      });
      
    
      Map<String, dynamic> toMap() {
        return {
          'data_acao': dataDoJob,
        };
      }
    
      factory EventsModel.fromMap(Map<String, dynamic> map) {
        return EventsModel(
          dataDoJob: map['data_acao'],
        );
      }
    
      String toJson() => json.encode(toMap());
    
      factory EventsModel.fromJson(String source) => EventsModel.fromMap(json.decode(source));
    }

```
this is my model, as you can see I'm just getting the dates. Now let's do the get method to retrieve this data from the api, I'm using getConnect but you can use the http client you want.

```
@override
      Future<List<EventsModel>> getEvents() async {
        SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    
        final int? id = sharedPreferences.getInt("idInfluencer");
        final String token = sharedPreferences.getString("token") ?? "";
    
        final Response result = await _restClient.get<List<EventsModel>>(
            "/job_acoes?influenciador_id=${id.toString()}",
            headers: {
              'Content-Type': 'application/json',
              'Accept': 'application/json',
              'Authorization': 'Bearer $token'
            }, decoder: (data) {
          if (data != null) {
            return data
                .map<EventsModel>((event) => EventsModel.fromMap(event))
                .toList();
          }
          return <EventsModel>[];
        });
        if (result.hasError) {
          print(result.statusCode);
          throw "Erro ao buscar dados";
        }
    
        print(result.body);
        print(result.statusCode);
    
        return result.body;
      }
```

Well done that we already have a list of dates in hand, but in my case they are strings so I'll have to convert them, like this:

```
final events = await _jobsServices.getEvents();
            //final dateFormat = DateFormat("yyyy-MM-dd");
            final eventsConvert =
                events.map((date) => (DateTime.parse(date.dataDoJob))).toList();
    
            eventsList.assignAll(eventsConvert);
    
            print("Lista de eventos : $eventsList");
    
            streamController.add(events);
```

on the first line I'm saving the list in a variable called events and right below I'm converting the strings into date time using the map method, And adding them to an empty list which I created then step by step and this: Create an empty list and add the converted data to it as I did above, my empty list is called eventsList
done that we will show this list in the table calendar

```
class CalendarWidget extends GetView<HomeController> {
      const CalendarWidget({Key? key}) : super(key: key);
      @override
      Widget build(BuildContext context) {
        return StreamBuilder<List<EventsModel>>(
            stream: controller.streamController.stream,
            builder: (context, snapshot) {
              return Obx(() {
                return TableCalendar(
                  eventLoader: (day) => controller.eventsList.where((event) => isSameDay(event,day)).toList(), //THIS IS IMPORTANT
           
                  focusedDay: controller.focusedDay.value,
                  firstDay: DateTime(2019),
                  lastDay: DateTime(2050),
                  headerStyle:
                      const HeaderStyle(formatButtonVisible: false), //WEEK VISIBLE
                  locale: 'pt_BR',
                  daysOfWeekVisible: true,
                  calendarFormat: controller.format.value,
                  onFormatChanged: (CalendarFormat _format) =>
                      controller.calendarFormat(_format),
                  onDaySelected: (DateTime userSelectedDay, DateTime focusedDay) =>
                      controller.selectedDay(userSelectedDay, focusedDay),
                  calendarStyle: CalendarStyle(
                      selectedTextStyle: const TextStyle(color: Colors.white),
                      isTodayHighlighted: true,
                      selectedDecoration: BoxDecoration(
                          color: context.buttomThemeClicled,
                          shape: BoxShape.circle)),
                  selectedDayPredicate: (DateTime date) {
                    return isSameDay(controller.focusedDay.value, date);
                  },
                );
              });
            });
      }
    }

```

remembering that i'm using a stateless widget so i need a state manager, and i use getx so it has an obx involving the whole calendar.

in the event loader some people have doubts, you can pass a list or a map on it, in my case I'm working with a list for simplicity's sake, notice that in the event loader I'm doing a simple filtering, comparing the dates of the my calendar with the dates I get from the api, simple isn't it? by doing this your api-based bookmarks will already be shown. Ah, a detail, the stream builder serves to redo my widget whenever there are changes in the api, if you don't know how to work with it, this video will explain: https://www.youtube.com/watch?v=BBelgajHgzY

now let's go to the display part of your events based on days, my events will be displayed on cards like this:
![Sem título](https://user-images.githubusercontent.com/85948951/141511650-1d8e77da-75b3-4e2e-846f-d53925ff7188.png)

so I built it on a separate page from my home, this part is important because your code will be easier and cleaner, with the widget done, we'll show them on screen like this:

  ```
  child: Obx(() {
                              return ListView(
                                scrollDirection: Axis.vertical,
                                children: controller.cards
                                    .map(
                                      (c) => AgendaCards(
                                        bottomPosition: 80,
                                        leftPositioned: 260,
                                        maxRadius: 5,
                                        rightPositioned: 5,
                                        secondMaxradius: 5,
                                        topPositioned: 20,
                                        model: c,
                                      ),
                                    )
                                    .toList(),
                              );
                            }));
```

the widget called calendar cards is nothing more than the card in the photo above, on it I asked for a model called

   ` final JobsDescriptionCardsModel model;`

and called him in the constructor

   ```
 AgendaCards({
        required this.leftPositioned,
        required this.rightPositioned,
        required this.topPositioned,
        required this.bottomPosition,
        required this.maxRadius,
        required this.secondMaxradius,
        required this.model, //HERE
        Key? key,
      }) : super(key: key);
```

so let's create this model

```
class JobsDescriptionCardsModel {
      final String descricaoJob;
      final String dataDoJob;
      final String horarioDoJob;
      final int jobId;
      final String nome;
      JobsDescriptionCardsModel({
        required this.descricaoJob,
        required this.dataDoJob,
        required this.horarioDoJob,
        required this.jobId,
        required this.nome,
      });
      
    
      Map<String, dynamic> toMap() {
        return {
          'descricaoJob': descricaoJob,
          'dataDoJob': dataDoJob,
          'horarioDoJob': horarioDoJob,
          'jobId': jobId,
          'nome': nome,
        };
      }
    
      factory JobsDescriptionCardsModel.fromMap(Map<String, dynamic> map) {
        return JobsDescriptionCardsModel(
          descricaoJob: map['descricao'] ?? "",
          dataDoJob: map['data_acao'] ?? "",
          horarioDoJob: map['hora_inicial_acao'],
          jobId: map['job_acao_id'] ?? 0,
          nome: map['job'] ["cliente"] ["nome"] ?? "",
        );
      }
    
      String toJson() => json.encode(toMap());
    
      factory JobsDescriptionCardsModel.fromJson(String source) => JobsDescriptionCardsModel.fromMap(json.decode(source));
    }
```

and get it on the api

```
@override
      Future<List<JobsDescriptionCardsModel>> getJobsDescrition() async {
        SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    
        final int? id = sharedPreferences.getInt("idInfluencer");
        final String token = sharedPreferences.getString("token") ?? "";
    
        final result = await _restClient.get<List<JobsDescriptionCardsModel>>(
            "/job_acoes?influenciador_id=${id.toString()}",
            headers: {
              'Content-Type': 'application/json',
              'Accept': 'application/json',
              'Authorization': 'Bearer $token'
            }, decoder: (data) {
          if (data != null) {
            return data
                .map<JobsDescriptionCardsModel>(
                    (j) => JobsDescriptionCardsModel.fromMap(j))
                .toList();
          }
    
          return <JobsDescriptionCardsModel>[];
        });
    
        if (result.hasError) {
          throw ("erro ao buscar dados");
        }
        return result.body ?? <JobsDescriptionCardsModel>[];
      }
```

the api gives me a list that is important. With the list in hand, we're going to get into the concepts of the table calendar. To proceed and understand what will be done, I recommend that you watch this video: https://www.youtube.com/watch?v=HKuzPQUV21Y&t=291s

having done the configuration of your calendar, I believe you have noticed that when you click on a date and print the variable that has the date data, you will notice that the table calendar gives you a date time as a return, and if you have rendered it the attention in my model i also have a date coming from the api, knowing that we only need to filter the list coming from the api based on the table calendar data like this:

first create an empty list like we did before and a list that will be filtered:


 ```
//LISTA DE JOBS CARDS
    
      final cards = <JobsDescriptionCardsModel>[].obs;
    
      //LISTA FILTRADA
    
      var cardsFiltered = <JobsDescriptionCardsModel>[];
```


the empty list will be filled with the api data like this:



`final jobsCards = await _jobsServices.getJobsDescrition(`);



and with the populated list in hand we will filter this list based on the api dates, like this:


```
cardsFiltered = jobsCards;
    
            var novaLista = cardsFiltered.where((model) {
              return model.dataDoJob
                  .toString()
                  .contains(focusedDay.value.toString().substring(1, 10));
            });
```


see that first I assign my populated list to a new list, then I filtered this list based on my model only in the part that contains the date that I stringed, comparing with my variable that has the date when I click on it remembers ? also converted to string, as the table calendar gives me the date along with other numbers that I believe are time information I got the data only from index 1 to 10 which will give me exactly the date contained in the variable. With that done, the table calendar has a property called onDaySelected, and it will display our filtered list like this:


  ```
selectedDay(DateTime selectedDayInfo, DateTime focusDayInfo) {
        userSelectedDay.value = selectedDayInfo;
        focusedDay.value = focusDayInfo;
        print(userSelectedDay.value);
        print(focusedDay.value);
    
        print("Lista de eventos 2 ${eventsList}");
    
        var novaLista = cardsFiltered.where((model) {
          return model.dataDoJob
              .toString()
              .contains(focusedDay.value.toString().substring(0, 10));
        });
    
        cards.assignAll(novaLista);
```


I created this separate function in a controller and called it in table calendar like this:


```
 onDaySelected: (DateTime userSelectedDay, DateTime focusedDay) =>
                      controller.selectedDay(userSelectedDay, focusedDay),
```


done that your calendar will already be displaying the default markers and your cards based on the widget you built, remember to pass the data to your cards using the model you requested via the constructor because it contains the api data. I hope I have help and I'm sorry for the google translator english

**Comment by GlauberAlc** [comment]
@Flavio-Vieirastack consegue fazer um vídeo?
No meu não consegui listar por data!

**Comment by Flavio-Vieirastack** [comment]
@GlauberAlc  Basta você pegar os dados da sua api somente as datas dela e fazer uma lista de datas, e no event loader você filtra as datas como eu fiz aqui

`eventLoader: (day) => controller.eventsList.where((event) => isSameDay(event,day)).toList(), //THIS IS IMPORTANT`

**Comment by Ankit0080** [comment]
@Flavio-Vieirastack I am new to flutter  I am having trouble in showing events inside calendar.  I am getting list of events from server . But i am not able to set inside calendar using eventLoader.
Can i do it without Streambuilder..? And how do i do it..?

Json received from server

"event": [
            {
                "eventId": "c3ef3065-edbe-4208-b58c-b7c08bacd9f8",
                "siteId": "fcbc8070-670a-432e-937b-2a2ab0e1ed74",
                "displayName": "Valley Health System Orientation",
                "eventStartDate": "11-01-2021",
                "eventEndDate": "11-01-2021",
                "eventStartTime": "03:30 PM",
                "eventEndTime": "08:29 PM",
                "nextAvailableStartDate": "11-08-2021",
                "nextAvailableEndDate": "11-08-2021",
                "nextAvailableStartTime": "03:30 PM",
                "nextAvailableEndTime": "08:29 PM",
                "type": "Class session",
                "eventData": {
                    "displayName": "Valley Health System Orientation",
                    "discription": "This is the system level orientation session",
                    "attended": "Y",
                    "missedSession": "N",
                    "location": ""
                },
                "evenStartDateTime": "11-01-2021 15:30:00",
                "month": "11",
                "rule": "WeeklyRecurrenceRule"
            },
            {
                "eventId": "e31af7be-8e94-497a-8206-fd346a89e7ed",
                "siteId": "fcbc8070-670a-432e-937b-2a2ab0e1ed74",
                "displayName": "Valley Health Home Health Orientation",
                "eventStartDate": "11-02-2021",
                "eventEndDate": "11-02-2021",
                "eventStartTime": "03:30 PM",
                "eventEndTime": "08:29 PM",
                "nextAvailableStartDate": "11-09-2021",
                "nextAvailableEndDate": "11-09-2021",
                "nextAvailableStartTime": "03:30 PM",
                "nextAvailableEndTime": "08:29 PM",
                "type": "Class session",
                "eventData": {
                    "displayName": "Valley Health Home Health Orientation",
                    "discription": "This is the orientation specific for the department of home health. ",
                    "attended": "Y",
                    "missedSession": "N",
                    "location": ""
                },
                "evenStartDateTime": "11-02-2021 15:30:00",
                "month": "11",
                "rule": "WeeklyRecurrenceRule"
            },
            {
                "eventId": "b2126f12-7183-416b-9451-12e2b33fdd26",
                "siteId": "fcbc8070-670a-432e-937b-2a2ab0e1ed74",
                "displayName": "Documentation & Laptop",
                "eventStartDate": "11-08-2021",
                "eventEndDate": "11-08-2021",
                "eventStartTime": "04:30 PM",
                "eventEndTime": "07:29 PM",
                "nextAvailableStartDate": "11-15-2021",
                "nextAvailableEndDate": "11-15-2021",
                "nextAvailableStartTime": "04:30 PM",
                "nextAvailableEndTime": "07:29 PM",
                "type": "Activity",
                "eventData": {
                    "displayName": "Documentation & Laptop",
                    "discription": "",
                    "attended": "Y",
                    "missedSession": "N",
                    "location": "333 Cork St. Winchester VA"
                },
                "evenStartDateTime": "11-08-2021 16:30:00",
                "month": "11",
                "rule": "WeeklyRecurrenceRule"
            },
            {
                "eventId": "191a8300-5e89-4199-b3ad-44d9edc00955",
                "siteId": "fcbc8070-670a-432e-937b-2a2ab0e1ed74",
                "displayName": "Meds, Modules & Mileage",
                "eventStartDate": "11-11-2021",
                "eventEndDate": "11-11-2021",
                "eventStartTime": "04:30 PM",
                "eventEndTime": "08:29 PM",
                "nextAvailableStartDate": "11-18-2021",
                "nextAvailableEndDate": "11-18-2021",
                "nextAvailableStartTime": "04:30 PM",
                "nextAvailableEndTime": "08:29 PM",
                "type": "Activity",
                "eventData": {
                    "displayName": "Meds, Modules & Mileage",
                    "discription": "",
                    "attended": "Y",
                    "missedSession": "N",
                    "location": "333 Cork St. Winchester VA"
                },
                "evenStartDateTime": "11-11-2021 16:30:00",
                "month": "11",
                "rule": "WeeklyRecurrenceRule"
            }
        ],
Thanks in advanced

**Comment by Ankit0080** [comment]
@Flavio-Vieirastack  I was able to show the events but all the dates are showing events after running this  Just like your problem.
eventLoader: (day) => controller.eventsList.where((event) => isSameDay(event,day)).toList(),
