### ISSUE TITLE
Long press to toggle to Date range selection mode

### ISSUE THREAD

**Issue by moksh-mahajan** [aleksanderwozniak/table_calendar#621]
I want to implement this:
When I long press a date, it should toggle to date range selection mode. 
(I have implemented at this point now)

Now the issue is, when the range selection mode is on, I have to tap on the start date again to make it work. 
Is there a way such that on long press of a date, it should toggle to date range selection mode with the date long pressed on as start date?

**Comment by aleksanderwozniak** [comment]
Sounds like the current default implementation. Check out events example for more info.
