### ISSUE TITLE
How to get first day and last day in displayed calendar ?

### ISSUE THREAD

**Issue by NaokiDohi** [aleksanderwozniak/table_calendar#627]
I want to get the first and last day of the display range from the calendar to trigger the data to be brought from Firestore whenever the display range changes (toggle from 2 weeks to a month or transition to the next month or week). Is this possible? How can I do this?

**Comment by aleksanderwozniak** [comment]
Check out this comment for details: https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620. Closing as a duplicate.

**Comment by NaokiDohi** [comment]
No, This is required for every first and last day of the display screen. With the method you gave me, I can get the first day, but not the last day because it varies from month or week to month or week.
Also, when you move to the next month or week, the focus day is not on the screen, so you can't get either the first or last day, right?

**Comment by aleksanderwozniak** [comment]
> With the method you gave me, I can get the first day, but not the last day because it varies from month or week to month or week.

That's just one example, you can come up with similar solutions for your other needs:
```dart
DateTime lastDayOfMonth(DateTime month) {
    final date = month.month < 12
        ? DateTime.utc(month.year, month.month + 1, 1)
        : DateTime.utc(month.year + 1, 1, 1);
    return date.subtract(const Duration(days: 1));
  }
``` 

> Also, when you move to the next month or week, the focus day is not on the screen, so you can't get either the first or last day, right?

`focusedDay` is always visible on the screen, as it determines which days are currently in view. Also, you get it in the [onPageChanged](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/onPageChanged.html) callback.

**Comment by musthafa1996** [comment]
For anyone still looking for a way to get the visible date range of the TableCalendar, please check this comment
https://github.com/aleksanderwozniak/table_calendar/issues/702#issuecomment-2718023823
