### ISSUE TITLE
Events not loading

### ISSUE THREAD

**Issue by Ankit0080** [aleksanderwozniak/table_calendar#629]
I have followed the gist to show events in calendar for particular month. I am getting dates for a month from backend server. And i added those dates following this  https://gist.github.com/aleksanderwozniak/1367892cbe39c25afda403b2300652ca. But first of all there is no property event in calendar it is showing eventloader which takres list of events for a date. I have one event for one date . Not able to show it inside Calendar

******************** This is my code for getting events from backend***********************

Map<DateTime, CalendarEvents> _apiEvents = {};
void getEventsFromBackend()
{
  _calendareventList = _calendarModel.data.event;
        String startDateFromServer =
            _calendarModel.data.startDate.split(" ")[0];
        _startMonth = int.parse(startDateFromServer.split("-")[0]);
        _startDate = int.parse(startDateFromServer.split("-")[1]);
        _startYear = int.parse(startDateFromServer.split("-")[2]);
      
}

_groupEvents(List<CalendarEvents> eventsList, String presentmonthValue) {
     eventsList.removeWhere((item) => item.month != presentmonthValue);
    eventsList.forEach((appEvent) {
      DateTime date = DateTime.utc(
          int.parse(appEvent.eventStartDate.split(" ")[2]),
          int.parse(appEvent.eventStartDate.split(" ")[0]),
          int.parse(appEvent.eventStartDate.split(" ")[1]));
      _apiEvents[date].add(appEvent);
    });
  }

***************** This is Tablecalendar widget ***********************

TableCalendar<CalendarEvents>(
                              firstDay: DateTime.utc(
                                  _startYear, _startMonth, _startDate),
                              lastDay:
                                  DateTime.utc(_endYear, _endMonth, _endDate),
                              focusedDay: _focusedDay,
                              rowHeight: 45,
                              calendarFormat: _calendarFormat,
                              startingDayOfWeek: StartingDayOfWeek.monday,
                              selectedDayPredicate: (day) {
                                return isSameDay(_selectedDay, day);
                              },
                              onDaySelected: (selectedDay, focusedDay) {
                                print("selected date is " +
                                    selectedDay.toString());
                                if (!isSameDay(_selectedDay, selectedDay)) {
                                  setState(() {
                                    _selectedDay = selectedDay;
                                    _focusedDay = focusedDay;
                                  });
                                }
                              },
                              onPageChanged: (focusedDay) {
                                _focusedDay = focusedDay;

                                presentMonth = focusedDay.month.toString();
                                if (presentMonth.length == 1) {
                                  presentMonth = "0" + presentMonth;
                                }
                                getCalendarEvents();
                                // Helper.showToast(presentMonth);
                              },
                              eventLoader: (dateOFEvents) => _getEventsForDay(
                                  DateTime(
                                      dateOFEvents.month.toString()),
                              locale: 'en_US',
                              calendarStyle: CalendarStyle(
                                  outsideDaysVisible: false,
                                  weekendTextStyle: TextStyle(
                                      color: Colors.red,
                                      fontFamily: 'PoppinsMedium',
                                      fontSize: AppFontSize.font_medium),
                                  defaultTextStyle: TextStyle(
                                      color: Colors.black,
                                      fontFamily: 'PoppinsMedium',
                                      fontSize: AppFontSize.font_medium)),
                              daysOfWeekStyle: DaysOfWeekStyle(
                                weekendStyle: TextStyle(
                                    color: Colors.black,
                                    fontFamily: 'PoppinsMedium',
                                    fontSize: AppFontSize.font_medium),
                                weekdayStyle: TextStyle(
                                    color: Colors.black,
                                    fontFamily: 'PoppinsMedium',
                                    fontSize: AppFontSize.font_medium),
                              ),
                              headerStyle: HeaderStyle(
                                  titleCentered: true,
                                  formatButtonVisible: false,
                                  titleTextStyle: TextStyle(
                                      color: Colors.black,
                                      fontFamily: 'PoppinsMedium',
                                      fontSize: AppFontSize.font_medium)),
                            )),
                       
**********************************Below is requirement*******************************

![image](https://user-images.githubusercontent.com/34130925/143840100-80f56b20-e3b3-4b76-a68e-67a2720f9155.png)

*******************This is what i am getting*******************************

![range error](https://user-images.githubusercontent.com/34130925/144014369-e48296e9-e78e-492e-9230-d6093ec6537a.png)

![calendar_issue](https://user-images.githubusercontent.com/34130925/144003947-4e5246ca-873d-4787-b0b0-bc1d1efb43b8.png)

*************This is my event List loading from backend server*******************************

"event": [
            {
                "eventId": "c3ef3065-edbe-4208-b58c-b7c08bacd9f8",
                "siteId": "fcbc8070-670a-432e-937b-2a2ab0e1ed74",
                "displayName": "Valley Health System Orientation",
                "eventStartDate": "11-01-2021",
                "eventEndDate": "11-01-2021",
                "eventStartTime": "03:30 PM",
                "eventEndTime": "08:29 PM",
                "nextAvailableStartDate": "11-08-2021",
                "nextAvailableEndDate": "11-08-2021",
                "nextAvailableStartTime": "03:30 PM",
                "nextAvailableEndTime": "08:29 PM",
                "type": "Class session",
                "eventData": {
                    "displayName": "Valley Health System Orientation",
                    "discription": "This is the system level orientation session",
                    "attended": "Y",
                    "missedSession": "N",
                    "location": ""
                },
                "evenStartDateTime": "11-01-2021 15:30:00",
                "month": "11",
                "rule": "WeeklyRecurrenceRule"
            },
            {
                "eventId": "e31af7be-8e94-497a-8206-fd346a89e7ed",
                "siteId": "fcbc8070-670a-432e-937b-2a2ab0e1ed74",
                "displayName": "Valley Health Home Health Orientation",
                "eventStartDate": "11-02-2021",
                "eventEndDate": "11-02-2021",
                "eventStartTime": "03:30 PM",
                "eventEndTime": "08:29 PM",
                "nextAvailableStartDate": "11-09-2021",
                "nextAvailableEndDate": "11-09-2021",
                "nextAvailableStartTime": "03:30 PM",
                "nextAvailableEndTime": "08:29 PM",
                "type": "Class session",
                "eventData": {
                    "displayName": "Valley Health Home Health Orientation",
                    "discription": "This is the orientation specific for the department of home health. ",
                    "attended": "Y",
                    "missedSession": "N",
                    "location": ""
                },
                "evenStartDateTime": "11-02-2021 15:30:00",
                "month": "11",
                "rule": "WeeklyRecurrenceRule"
            },
            {
                "eventId": "b2126f12-7183-416b-9451-12e2b33fdd26",
                "siteId": "fcbc8070-670a-432e-937b-2a2ab0e1ed74",
                "displayName": "Documentation & Laptop",
                "eventStartDate": "11-08-2021",
                "eventEndDate": "11-08-2021",
                "eventStartTime": "04:30 PM",
                "eventEndTime": "07:29 PM",
                "nextAvailableStartDate": "11-15-2021",
                "nextAvailableEndDate": "11-15-2021",
                "nextAvailableStartTime": "04:30 PM",
                "nextAvailableEndTime": "07:29 PM",
                "type": "Activity",
                "eventData": {
                    "displayName": "Documentation & Laptop",
                    "discription": "",
                    "attended": "Y",
                    "missedSession": "N",
                    "location": "333 Cork St. Winchester VA"
                },
                "evenStartDateTime": "11-08-2021 16:30:00",
                "month": "11",
                "rule": "WeeklyRecurrenceRule"
            },
            {
                "eventId": "191a8300-5e89-4199-b3ad-44d9edc00955",
                "siteId": "fcbc8070-670a-432e-937b-2a2ab0e1ed74",
                "displayName": "Meds, Modules & Mileage",
                "eventStartDate": "11-11-2021",
                "eventEndDate": "11-11-2021",
                "eventStartTime": "04:30 PM",
                "eventEndTime": "08:29 PM",
                "nextAvailableStartDate": "11-18-2021",
                "nextAvailableEndDate": "11-18-2021",
                "nextAvailableStartTime": "04:30 PM",
                "nextAvailableEndTime": "08:29 PM",
                "type": "Activity",
                "eventData": {
                    "displayName": "Meds, Modules & Mileage",
                    "discription": "",
                    "attended": "Y",
                    "missedSession": "N",
                    "location": "333 Cork St. Winchester VA"
                },
                "evenStartDateTime": "11-11-2021 16:30:00",
                "month": "11",
                "rule": "WeeklyRecurrenceRule"
            }
        ],

Any help would be appreciated. Thanks in advance

**Comment by Ankit0080** [comment]
@aleksanderwozniak How do ishow these events using marker builder

**Comment by micimize** [comment]
@Ankit0080 I believe you have multiple issues, but it is impossible to figure out what's going on in these snippets. Generally, to make it easier to diagnose the issues, try:
1. Debugging each part of your code yourself, eliminating potential bug sources beyond the bounds of this library. I.e, verify your back end fetching and parsing code results in an `Event` list.
1. Simplify the code as much as possible, removing styling, unrelated logic etc (this may help you identify the issue as well).
1. Add full errors and stack traces
1. Using formatting blocks:
    ~~~dart
    ```dart
    /// your cleaned up, commented dart code
    ```
    ~~~
1. Put verbose blocks that add context in [`<details>` tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) so the main issues are front loaded

This will help distill exactly where the problematic code is, both for yourself and others.

To try and answer some of your questions:
1. `eventLoader`'s event type is a user-supplied generic type that is used throughout the component builders for customization
2. My guess is that one of your issues is with trying to rely on [`LinkedHashSet(equals: ...)`](https://api.dart.dev/stable/2.14.4/dart-collection/LinkedHashSet/LinkedHashSet.html) to make `.contains` work the way you want it to, which I don't think it is.

**Comment by Ankit0080** [comment]
@aleksanderwozniak I was able to resolve it using selecteddayPredicates.
