### ISSUE TITLE
No property to modify style of header

### ISSUE THREAD

**Issue by JoachimSall** [aleksanderwozniak/table_calendar#632]
There aren't any properties to modify the style of the calendar header here 
![header_table_calendar](https://user-images.githubusercontent.com/45352720/145061137-e9ed6fc7-68db-402c-9be5-d3f420f9bfd4.png)
:

I tried to look directly for headers properties in TableCalendar class 
![header_properties](https://user-images.githubusercontent.com/45352720/145061228-9d36ff7b-bcef-48bb-85ec-2677572f40b4.png)
:

And in CalendarStyle class :
![header_style_properties](https://user-images.githubusercontent.com/45352720/145061336-c559f992-4eb8-4efb-ae2c-5dd1e5df9d5a.png)

There are none.

It would be nice to be able to modify the color of these headers, if we want to use the calendar on a dark background app.

**Comment by aleksanderwozniak** [comment]
You can use [HeaderStyle](https://pub.dev/documentation/table_calendar/latest/table_calendar/HeaderStyle-class.html) for this.

**Comment by JoachimSall** [comment]
Thanks, in which property of TableCalendar can I call this class ? I don't get how to use it.
