### ISSUE TITLE
How display Data From API

### ISSUE THREAD

**Issue by Jliberatomex** [aleksanderwozniak/table_calendar#633]
Hi i have problem, I want display data from API

It's my code 

      Widget build(BuildContext context) {
         final routeData = ModalRoute.of(context)!.settings.arguments as Map<String, Object>;
          newEma=routeData['email'];
        final newJwt=routeData['jwt']; 
        _obtenerCitas(newEma, newJwt);
        return Theme( 

     data: Theme.of(context).copyWith(scaffoldBackgroundColor: Colors.white),
     child:Scaffold(
      
      backgroundColor: Colors.white30,
      appBar: AppBar(
        iconTheme: const IconThemeData(
          color: Colors.white
        ),
        backgroundColor: Colors.lightBlue.shade900,
        title: Text("Abogados Montes",style: TextStyle(color: Colors.white)),
        centerTitle: true,
        automaticallyImplyLeading: false,
      ),
      body: FutureBuilder<List<Calendario>>(
        future: _obtenerCitas(email, jwt),
        builder: (context,snapshot){
          if(!snapshot.hasData){
            return CircularProgressIndicator();

          }else{
            List<Calendario>? data=snapshot.data; 
      return TableCalendar(
      firstDay: DateTime(1990),
      focusedDay: DateTime(2020),
      lastDay: DateTime(2060),
      calendarFormat: CalendarFormat.month,
      startingDayOfWeek: StartingDayOfWeek.sunday,
      availableGestures: AvailableGestures.all,
      availableCalendarFormats: const {CalendarFormat.month: ''},
      calendarStyle: CalendarStyle(
        outsideDaysVisible: false,
        weekendTextStyle: TextStyle().copyWith(color: Colors.blue[800]),
        holidayTextStyle: TextStyle().copyWith(color: Colors.blue[800]),
      ),
      daysOfWeekStyle: DaysOfWeekStyle(
        weekendStyle: TextStyle().copyWith(color: Colors.blue[600]),
      ),
      headerStyle: HeaderStyle(
        titleCentered: true,
        formatButtonVisible: false,
      ),
      calendarBuilders: CalendarBuilders(
        selectedBuilder: (context, date, _) {
          return FadeTransition(
            opacity: Tween(begin: 0.0, end: 1.0).animate(_animationController!),
            child: Container(
              margin: const EdgeInsets.all(4.0),
              alignment: Alignment.center,
              decoration: BoxDecoration(
                  color: Colors.blue[300],
                  borderRadius: BorderRadius.circular(36.0),
                  border: Border.all(width: 2, color: Colors.blue[300]!)),
              child: Text(
                '${date.day}',
                style: TextStyle().copyWith(
                    fontSize: 20.0,
                    color: Colors.black,
                    fontWeight: FontWeight.bold),
              ),
            ),
          );
        },
        todayBuilder: (context, date, _) {
          return Container(
            margin: const EdgeInsets.all(4.0),
            alignment: Alignment.center,
            decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(36.0),
                border: Border.all(width: 2, color: Colors.white)),
            child: Text(
              '${date.day}',
              style: TextStyle().copyWith(
                  fontSize: 20.0,
                  color: Colors.black,
                  fontWeight: FontWeight.bold),
            ),
          );
        },
        markerBuilder: (context, date, events ) {
          final children = [];

          if (events.isNotEmpty) {
            children.add(
              Positioned(
                child: _buildEventsMarker(date, events),
              ),
            );
          }

        
        },
      ),
      
    );
          
         
          }
           
        }

      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        backgroundColor: Colors.lightBlue.shade900,
        onPressed: () { 
            Navigator.push(context, MaterialPageRoute(builder: (context) => AddEvent()));
         },

      ),
    )
    );
  }

It's my  response from json 

{
    "status": "exito",
    "message": "Trabajos encontrados",
    "calendario": [
        {
            "rowid": "1",
            "fecha": "2021-11-09",
            "duracion_horas": "2",
            "duracion_minutos": "30",
            "descripcion": "Prueba de Trabajo",
            "fk_asuntos": "6",
            "fk_cliente": "1",
            "fk_usuarios": "1",
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "2",
            "fecha": "2021-11-08",
            "duracion_horas": "1",
            "duracion_minutos": "20",
            "descripcion": "Es un trabajo de prueba del dia de ayer ",
            "fk_asuntos": "1",
            "fk_cliente": "3",
            "fk_usuarios": "11",
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "3",
            "fecha": null,
            "duracion_horas": null,
            "duracion_minutos": null,
            "descripcion": null,
            "fk_asuntos": null,
            "fk_cliente": null,
            "fk_usuarios": null,
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "4",
            "fecha": "2021-11-07",
            "duracion_horas": "2",
            "duracion_minutos": "20",
            "descripcion": "Descripcion de Trabajo",
            "fk_asuntos": null,
            "fk_cliente": null,
            "fk_usuarios": null,
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "5",
            "fecha": "2021-11-07",
            "duracion_horas": "2",
            "duracion_minutos": "20",
            "descripcion": "Descripcion de Trabajo",
            "fk_asuntos": null,
            "fk_cliente": null,
            "fk_usuarios": null,
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "6",
            "fecha": "2021-11-07",
            "duracion_horas": "2",
            "duracion_minutos": "20",
            "descripcion": "Descripcion de Trabajo",
            "fk_asuntos": "2",
            "fk_cliente": null,
            "fk_usuarios": null,
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "7",
            "fecha": "2021-11-07",
            "duracion_horas": "2",
            "duracion_minutos": "20",
            "descripcion": "Descripcion de Trabajo",
            "fk_asuntos": "2",
            "fk_cliente": "1",
            "fk_usuarios": null,
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "8",
            "fecha": "2021-11-07",
            "duracion_horas": "2",
            "duracion_minutos": "20",
            "descripcion": "Descripcion de Trabajo",
            "fk_asuntos": "2",
            "fk_cliente": "1",
            "fk_usuarios": "1",
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "9",
            "fecha": "2021-11-07",
            "duracion_horas": "2",
            "duracion_minutos": "20",
            "descripcion": "Descripcion de Trabajo",
            "fk_asuntos": "2",
            "fk_cliente": "1",
            "fk_usuarios": "1",
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "10",
            "fecha": "2021-11-07",
            "duracion_horas": "2",
            "duracion_minutos": "20",
            "descripcion": "Trabajos nuevos",
            "fk_asuntos": "2",
            "fk_cliente": "1",
            "fk_usuarios": "1",
            "borrado": null,
            "borrado_fecha": null
        },
        {
            "rowid": "11",
            "fecha": "2021-11-07",
            "duracion_horas": "2",
            "duracion_minutos": "20",
            "descripcion": "Trabajos nuevos",
            "fk_asuntos": "2",
            "fk_cliente": "1",
            "fk_usuarios": "1",
            "borrado": null,
            "borrado_fecha": null
        }
    ]
}

**Comment by aleksanderwozniak** [comment]
Check out https://github.com/aleksanderwozniak/table_calendar/issues/494#issuecomment-833814090

**Comment by faridistiqlal** [comment]
hello alex, your table calendar is very nice and powerful.  I've looked at the example and the issue of how to display json, but I still don't get it right.  

can you add an example of fetching event from api with json data from link?

![IMG_20220608_150304_708.jpg](https://user-images.githubusercontent.com/34615322/172999974-648d4405-ce36-45b6-abe4-5cb092373e2c.jpg)
