### ISSUE TITLE
Displaying Range in Monthly view

### ISSUE THREAD

**Issue by rocklyve** [aleksanderwozniak/table_calendar#639]
Hey, 
I would like to highlight a special range for an event over multiple days.
Is there a way to handle such a behavior? I tried to modify the Borderradius of every single day in the event range and 'simulate' such a range, but then I have problems with the distance. 

Is there a way to build something like this sketch?

![image](https://user-images.githubusercontent.com/11009552/146905886-a10e7a0a-0523-46a8-b3af-0810e8b57954.png)

Modifying the borderRadius of every event causes a distance between the two events. Is there a way to remove this small distance?

<img width="538" alt="Screenshot 2021-12-21 at 12 22 00" src="https://user-images.githubusercontent.com/11009552/146922039-9ed99e5a-5733-456c-b9f1-0f42c92ce183.png">

**Comment by mahidul-islam** [comment]
Facing the same issue, please let us know if you found a good solution.

**Comment by aleksanderwozniak** [comment]
Hi,

About the hairline gap between two cells - do you also experience this when running the example project and selecting a range? Does it happen on an emulator or a real device?
