### ISSUE TITLE
Multiple colors for markers

### ISSUE THREAD

**Issue by macroday** [aleksanderwozniak/table_calendar#64]
Can you please add support to add multiple colors for the table calendar?

**Comment by aleksanderwozniak** [comment]
So you want to use regular markers, but have each one of them in a different color, right?

For now, you could use `markersBuilder` and map `events` list into a custom Widget -> each with color of your choice.

I'll probably implement this feature for single markers, but it is not in my focus right now.

**Comment by fabianogadenz** [comment]
I did it! I passed a template of my calendar item, containing color ... in the event I can redeem the color.

builders: CalendarBuilders(
        singleMarkerBuilder: (context, date, event) {
          Color cor = Color.fromRGBO(event.color);

          return Container(
            decoration: BoxDecoration(shape: BoxShape.circle, color: cor),
            width: 7.0,
            height: 7.0,
            margin: const EdgeInsets.symmetric(horizontal: 1.5),
          );
        },
      ),

**Comment by fabianogadenz** [comment]
I did it! I passed a template of my calendar item, containing color ... in the event I can redeem the color.

```
builders: CalendarBuilders(
        singleMarkerBuilder: (context, date, event) {
          Color cor = Color.fromRGBO(event.color);
          return Container(
            decoration: BoxDecoration(shape: BoxShape.circle, color: cor),
            width: 7.0,
            height: 7.0,
            margin: const EdgeInsets.symmetric(horizontal: 1.5),
          );
        },
      ),
```

**Comment by bcycgcg** [comment]
thanks for this calendar. very useful. i am looking at example and trying to figure out how to change the markers in the calendar to a number badge to show how many events for that day.

**Comment by aleksanderwozniak** [comment]
@bcycgcg 
Take a look here: https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart#L239

**Comment by amirVirtuenetz** [comment]
> You can add multi marker as below code also you may add some condition as you required:
> 
> ```
> calendarBuilders: CalendarBuilders(
>                             markerBuilder: (BuildContext context, date, events) {
>                               if (events.isEmpty) return SizedBox();
>                               return ListView.builder(
>                                   shrinkWrap: true,
>                                   scrollDirection: Axis.horizontal,
>                                   itemCount: events.length,
>                                   itemBuilder: (context, index) {
>                                     return Container(
>                                       margin: const EdgeInsets.only(top: 20),
>                                       padding: const EdgeInsets.all(1),
>                                       child: Container(
>                                         // height: 7, // for vertical axis
>                                         width: 5, // for horizontal axis
>                                         decoration: BoxDecoration(
>                                             shape: BoxShape.circle,
>                                             color: Colors.primaries[
>                                                 Random().nextInt(Colors.primaries.length)]),
>                                       ),
>                                     );
>                                   });
>                             },
>                           ),
> ```

But how can i load events data from firebase firestore to show specific data on the basis of when event is created?

**Comment by amirVirtuenetz** [comment]
> So you want to use regular markers, but have each one of them in a different color, right?
> 
> For now, you could use `markersBuilder` and map `events` list into a custom Widget -> each with color of your choice.
> 
> I'll probably implement this feature for single markers, but it is not in my focus right now.

How can i show the event when it is created?
i am using firebase to store my tasks and when the calendar show the markers shows how may task or events created on that day and which month is created?
could you please shows me the demo of eventLoader(date) function
