### ISSUE TITLE
color by event type

### ISSUE THREAD

**Issue by cndr** [aleksanderwozniak/table_calendar#641]
It would be great if we could color the dots under the calendar view to the record type. blue dot, green dot etc. 
thank you.

![image](https://user-images.githubusercontent.com/2871165/147549376-33b1e0ff-3593-476e-b531-f705a12a7b53.png)

**Comment by FelipeSantos75** [comment]
https://github.com/aleksanderwozniak/table_calendar/issues/64 
take a look in this. you will be able
