### ISSUE TITLE
how to set certain dates to a different color

### ISSUE THREAD

**Issue by August79** [aleksanderwozniak/table_calendar#642]
hi!
i have a list of holidays dates, what should I use to display them, in a different color, in the calendar like in the picture?

![1201491111088792 5NW02YKsiDYs53wYvnMX_height640](https://user-images.githubusercontent.com/51087813/147608441-28ddef98-80af-4643-8726-8bcc960b46a5.png)

**Comment by aleksanderwozniak** [comment]
You can use the `holidayPredicate` for this:

https://github.com/aleksanderwozniak/table_calendar/blob/3abf0e7f67f2e7069d5869cdbeda9fe2b8048cb4/example/lib/pages/complex_example.dart#L149-L152

**Comment by August79** [comment]
I don't think it suits me, since I get a list of specific dates like ['20 .12.21 ', '1 .12.22'...].
**holidayPredicate** it seems to be for one date only, I can have many dates for a whole year
thank you for the answer

> You can use the `holidayPredicate` for this:
> 
> https://github.com/aleksanderwozniak/table_calendar/blob/3abf0e7f67f2e7069d5869cdbeda9fe2b8048cb4/example/lib/pages/complex_example.dart#L149-L152

> https://github.com/aleksanderwozniak/table_calendar/blob/3abf0e7f67f2e7069d5869cdbeda9fe2b8048cb4/example/lib/pages/complex_example.dart#L149-L152

**Comment by MuhammadSufyanMalik** [comment]
Hi, I have also a list of dates how can I display them with different colors than default.
Thaks

**Comment by aleksanderwozniak** [comment]
You can still use predicates for collections. For example, [multi_example](https://github.com/aleksanderwozniak/table_calendar/blob/3abf0e7f67f2e7069d5869cdbeda9fe2b8048cb4/example/lib/pages/multi_example.dart) uses `selectedDayPredicate` to mark multiple dates as selected. Just check if your collection contains the `day` you get from predicate, but make sure you compare dates correctly (without the time-part of DateTime objects). You'll find more info in the readme.
