### ISSUE TITLE
Getting error for using the table calendar 3.0.3 inside the list view. 'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12: 'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is not true. package:flutter/…/rendering/sliver_fixed_extent_list.dart:1 2  Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

### ISSUE THREAD

**Issue by joy-eiosys** [aleksanderwozniak/table_calendar#643]
my flutter doctor:
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1415], locale en-IN)
    • Flutter version 2.5.3 at C:\flutter_src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\JOY\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\JOY\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (4 available)
    • M2010J19CI (mobile)         • 192.168.0.100:5000 • android-arm64  • Android 10 (API 29)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 96.0.1054.53

! Doctor found issues in 1 category.

--------------------------------------------------------------------------------------------
minimal reproducible code
ListView(
shrinkWrap: true,
children:[
Container(
        height: 70.0,
        child: TableCalendar(
          focusedDay: selectedDay,
          firstDay: DateTime(1990),
          lastDay: DateTime.now(),
          calendarFormat: CalendarFormat.week,
          headerVisible: false,
          startingDayOfWeek: StartingDayOfWeek.sunday,
          daysOfWeekVisible: true,
          daysOfWeekStyle: DailyCalendarStyle().daysOfWeekStyle(),
          //Day Changed
          onDaySelected: (DateTime selectDay, DateTime focusDay) {
            setState(() {
              selectedDay = selectDay;
            });
          },
          selectedDayPredicate: (DateTime date) {
            return isSameDay(selectedDay, date);
          },
          // eventLoader: _getEventsfromDay,
          //To style the Calendar
          calendarStyle: DailyCalendarStyle().calendarStyle(),
          calendarBuilders: CalendarBuilders(
            markerBuilder: (context, date, events) {
              return CalendarDecoration()
                  .markerBuilder(context, date, events, 25.0);
            },
          ),
        ),
      ),
.....other widgets
]
)

**Comment by aleksanderwozniak** [comment]
This seems unrelated to the package. Do you also experience this error when you remove other children from the ListView? I don't get any errors when running the code you've provided.
