### ISSUE TITLE
Get displayed month after onPageChanged 

### ISSUE THREAD

**Issue by raphasauer** [aleksanderwozniak/table_calendar#644]
Hello. Is it possible to get the month in display with the method `onPageChanged`? I.e if I have January in display and tap the back button how do I know I (in dart) that I have December on display? 

Thanks.

**Comment by tamaskan** [comment]
the function includes the new datetime, so you should be able to do: onPageChanged: (myday) {print(myday.month);}

**Comment by raphasauer** [comment]
Thanks for your response. It works.
