### ISSUE TITLE
Any way to show just Month name.

### ISSUE THREAD

**Issue by mjarpitanand** [aleksanderwozniak/table_calendar#646]
![image](https://user-images.githubusercontent.com/14835964/149018501-a6e258ce-1674-496d-8958-943ae34ff81f.png)

**Comment by aleksanderwozniak** [comment]
You can use [titleTextFormatter](https://pub.dev/documentation/table_calendar/latest/table_calendar/HeaderStyle/titleTextFormatter.html) for this.

**Comment by mjarpitanand** [comment]
Not like that, I want to show just this UI, and whole calender view I don't want to show.

**Comment by mjarpitanand** [comment]
Closing this as there is no solution I guess,
