### ISSUE TITLE
verticalSwipe not working

### ISSUE THREAD

**Issue by sekny** [aleksanderwozniak/table_calendar#648]
Hello everyone, 

I'm trying to change from default swipe to vertical swipe(`availableGestures: AvailableGestures.verticalSwipe`) but that option seems not working, is somebody know please help, thank.

**Comment by Splagov** [comment]
Vertical scroll inside SingleChildScrollView not working as well.  (Calendar paced inside SingleChildScrollView, and when try to scroll page at calendar - it is not scrolling).

**Comment by rivetingpeppermint** [comment]
Same for me. Any solutions so far?

**Comment by aleksanderwozniak** [comment]
The built-in vertical swipe is for changing the currently visible calendar format (e.g. from month to week). At this moment TableCalendar can't be scrolled vertically.

**Comment by umair07** [comment]
@aleksanderwozniak  @sekny Still facing this issue Vertical scroll inside SingleChildScrollView not working. is there any solution for this?
