### ISSUE TITLE
Get inital and final page on every page change [URGENT]

### ISSUE THREAD

**Issue by mjarpitanand** [aleksanderwozniak/table_calendar#649]
![image](https://user-images.githubusercontent.com/14835964/149809188-a87db011-571e-4073-8dcb-31f1f6972821.png)

In this image on every page change(arrow click), get a visible initial and final date.

**Comment by aleksanderwozniak** [comment]
Check this for more info: https://github.com/aleksanderwozniak/table_calendar/issues/441#issuecomment-802757620

**Comment by mjarpitanand** [comment]
This comment you shared works well for month implementation, won't WORK FOR TWO WEEKS.

**Comment by abinvp** [comment]
Getting the first and last visible dates on the currently visible page based on the calendar format would be crucial at times. It would be great if this feature can be implemented.

**Comment by mjarpitanand** [comment]
@abinvp I think this library is no use now after null safety they migrated and take our some cruial features.
