### ISSUE TITLE
[CalendarFormat]: Wrong naming

### ISSUE THREAD

**Issue by Sharkigamers** [aleksanderwozniak/table_calendar#650]
Hello,

I am using your package however it seems that there is a wrong naming in your CalendarFormat:

`Map  availableCalendarFormats = const {CalendarFormat.month : 'Month', CalendarFormat.twoWeeks : '2 weeks', CalendarFormat.week : 'Week'}`

![image](https://user-images.githubusercontent.com/49515579/150073479-1c2c8195-47bd-4172-bb04-1e2d382d5028.png)

The `.month` is the `Week`, the `.week` is the `2 weeks` and the `.twoWeeks` is the `Month`

**Comment by ThiagoAnunciacao** [comment]
Same here and same on examples in the README gif's

**Comment by BrunoVieiraL** [comment]
> Hello,
> 
> I am using your package however it seems that there is a wrong naming in your CalendarFormat:
> 
> `Map availableCalendarFormats = const {CalendarFormat.month : 'Month', CalendarFormat.twoWeeks : '2 weeks', CalendarFormat.week : 'Week'}`
> 
> ![image](https://user-images.githubusercontent.com/49515579/150073479-1c2c8195-47bd-4172-bb04-1e2d382d5028.png)
> 
> The `.month` is the `Week`, the `.week` is the `2 weeks` and the `.twoWeeks` is the `Month`

The buttom show's the next format you can disable on " formatButtonShowsNext: false" inside the Header Style

**Comment by ThiagoAnunciacao** [comment]
@BrunoVieiraL  Works for me! Tks a lot.

**Comment by BrunoVieiraL** [comment]
Don't forget closing the issue and good luck on the jorney

**Comment by Sharkigamers** [comment]
> > Hello,
> > I am using your package however it seems that there is a wrong naming in your CalendarFormat:
> > `Map availableCalendarFormats = const {CalendarFormat.month : 'Month', CalendarFormat.twoWeeks : '2 weeks', CalendarFormat.week : 'Week'}`
> > ![image](https://user-images.githubusercontent.com/49515579/150073479-1c2c8195-47bd-4172-bb04-1e2d382d5028.png)
> > The `.month` is the `Week`, the `.week` is the `2 weeks` and the `.twoWeeks` is the `Month`
> 
> The buttom show's the next format you can disable on " formatButtonShowsNext: false" inside the Header Style

This isn't the purpose of the issue.
There is a problem in the variable naming / the use of the variable.
If the .month with his default value 'Month' is displaying 'Week' that means that there is an error in the use of the variable.

**Comment by Sharkigamers** [comment]
So @aleksanderwozniak I don't think that this issue is fixed.

**Comment by aleksanderwozniak** [comment]
@Sharkigamers 
By default, the purpose of this button is to display which format will be visible *after* it is pressed. I understand that for some it might be more intuitive when the button displays the *current* format, which is why `formatButtonShowsNext` property exists. So basically, what @BrunoVieiraL wrote is correct.

`formatButtonShowsNext: false` does not remove the button, it makes it display the current format.

**Comment by Sharkigamers** [comment]
> play

Yes, sorry I just saw it afterwards.
It's not really intuitive to display the next state.
Thank you for your time.
