### ISSUE TITLE
Null check operator used on a null value thrown from page_view.dart

### ISSUE THREAD

**Issue by Yahllil** [aleksanderwozniak/table_calendar#653]
Hello,
I've updated to the latest version of Flutter, and suddenly the calendar crashes when I first open it.
The exception that is being thrown is: `Null check operator used on a null value`, and it seems to be thrown from `page_view.dart` on line 453. In this case, `_chachedPage` is null, but it is treated as non-null, and that's what causes the crash.

Visually, that's what I see until I try to switch to another month of the calendar:
<img width="380" alt="Screen Shot 2022-01-25 at 21 16 36" src="https://user-images.githubusercontent.com/18067403/151044074-7da18a84-ef8e-4f4a-87d2-73948cd77ab9.png">

Is there a way to resolve it in the current version? Thank you!

**Comment by aleksanderwozniak** [comment]
Hi, can you attach an example code + steps on how to reproduce this issue?

**Comment by ebot64** [comment]
Same problem as #709 

`══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was:
  PageView
  PageView:file:///C:/....../pub.dartlang.org/table_calendar-3.0.6/lib/src/widgets/calendar_core.dart:59:21

When the exception was thrown, this was the stack:
#0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455:25)
#1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456:16)
#2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)`

![Screenshot_20220703-192532](https://user-images.githubusercontent.com/10565419/177052693-7b4f7427-ba03-47c8-b387-c8a0afadf3ee.jpg)
