### ISSUE TITLE
Can't edit overscroll color

### ISSUE THREAD

**Issue by sehnryr** [aleksanderwozniak/table_calendar#658]
Hi, I cannot find a way to modify the overscroll color. Is there a way to change it?

![image](https://user-images.githubusercontent.com/40632486/152705821-8d816aec-d2b5-4eae-8226-e331eabef31c.png)

**Comment by aleksanderwozniak** [comment]
Hi there, this is something you will need to change outside of the package, as it is not managed by TableCalendar.
