### ISSUE TITLE
TableCalendar must be wrapped by Material widget (iOS)

### ISSUE THREAD

**Issue by codemewell** [aleksanderwozniak/table_calendar#659]
https://github.com/aleksanderwozniak/table_calendar/blob/129f7b0a01c9d9e6865822cb66ef5e9c61d02a71/lib/src/widgets/custom_icon_button.dart#L24

This problem occurs when calendar is used under Cupertino scaffold tree.

One way is to try use GestureDetector instead of InkWell, I think.

**Comment by aleksanderwozniak** [comment]
Can you check if updated code from `cupertino-button` branch resolves this?
