### ISSUE TITLE
Day calendarFormat

### ISSUE THREAD

**Issue by SenCodeMaker** [aleksanderwozniak/table_calendar#66]
It would be so mush interesting for my app to have a day calendarFormat which plot only on day separated in different hour segments so that each statement is tappable. I would trigger it when the user tap to select one day an this particular view the user can select the hour for his appointment.

**Comment by alekskuzmin** [comment]
@SenCodeMaker I was thinking of requesting a similar thing - do you mean allowing days in week mode to be not square cells but vertical columns?

**Comment by SenCodeMaker** [comment]
Hum yes in a way. I meant that a day would be only a column that you can click to zoom by landing to a view where this particular day is shown with the different hours in multiple segments.

**Comment by chwiz143** [comment]
I image a day view like in Google calendar?
This is something I would like to request too.

@SenCodeMaker 
https://images.app.goo.gl/19ybkf2TBHtEcXEX8

**Comment by SenCodeMaker** [comment]
yeah like that

**Comment by aleksanderwozniak** [comment]
Hmm at this moment I'm not planning on adding something like this. This day view seems to me like a separate widget, just like the event list that is below the calendar in example project, so it might make more sense to develop it outside of the spectrum of TableCalendar.
