### ISSUE TITLE
Does not have scroll controll

### ISSUE THREAD

**Issue by BrayanX44** [aleksanderwozniak/table_calendar#661]
Great job with this package. Thanks a lot, guys.
In a single scroll page i can not get scroll vertically because de calendar has to be scrolled horizontally. Cab you please, add a metodh to control the escroll? could be similar to  the ListView.Builder metodh called physics: NeverScrollableScrollPhysics(), but in such a way that only catch the horizontal scroll and ignore the vertical scroll to the user can to scroll and view all the page. 

Thanks a lot.

**Comment by adimshev** [comment]
+1
I wanna use TableCalendar as sliver inside CustomScrollView (wrap into SliverToBoxAdapter), it works but I can't scroll CustomScrollView by scrolling calendar, only other slivers (including horizontal ListView) trigger scrolling, TableCalendar doesn't. Please fix this.

**Comment by adimshev** [comment]
Fix by adding availableGestures: AvailableGestures.horizontalSwipe
