### ISSUE TITLE
How To Do The Marker Builder That Shows The Number Of Events In The Bottom

### ISSUE THREAD

**Issue by junndobit** [aleksanderwozniak/table_calendar#663]
![flutter calendar builder sample](https://user-images.githubusercontent.com/20215990/156286352-e7f926a0-1b1d-4d63-a5db-87d19c7d9ded.png)

How do I achieve this? I read that it is just a markerbuilder, but I have looked into other issues but I still don't understand how to achieve it. I also see no examples on it.

**Comment by AlexanderWesten** [comment]
Use the option `calendarBuilders` and provide a `markerBuilder`:
```
    return TableCalendar<Event>(
       // ...
      calendarBuilders: CalendarBuilders(
        markerBuilder: (context, day, events) {
          return PositionedDirectional(
            bottom: 0,
            end: 0,
            child: Container(
                color: Colors.amber,
                width: 12,
                height: 12,
                alignment: AlignmentDirectional.bottomEnd,
                child: Center(
                    child: Text(
                  events.length.toString(),
                  style: const TextStyle(fontSize: 10),
                ))),
        );
      }),
    );
```

**Comment by junndobit** [comment]
> Use the option `calendarBuilders` and provide a `markerBuilder`:
> 
> ```
>     return TableCalendar<Event>(
>        // ...
>       calendarBuilders: CalendarBuilders(markerBuilder: (context, day, events) {
>         return events.isNotEmpty
>             ? PositionedDirectional(
>                 bottom: 0,
>                 end: 0,
>                 child: Container(
>                     color: Colors.blue,
>                     width: 14,
>                     height: 14,
>                     alignment: AlignmentDirectional.bottomEnd,
>                     child: Center(
>                         child: Text(
>                       events.length.toString(),
>                       style: const TextStyle(fontSize: 10, color: Colors.white),
>                     ))),
>               )
>             : null;
>       }),
>     );
> ```

Thank you very much!
