### ISSUE TITLE
More Markers

### ISSUE THREAD

**Issue by majandra2404** [aleksanderwozniak/table_calendar#664]
hello, could you help me with something, I need all the event markers on the day to be shown and I see that there is a limit of 4, how can I modify it, thanks for your time and knowledge.

**Comment by AlexanderWesten** [comment]
Use the option `calendarStyle` and provide `markersMaxCount`:

```
    return TableCalendar<Event>(
       // ...
      calendarStyle: CalendarStyle(
          markersMaxCount: 8,
      )
    );
```

But consider adding a marker with a number instead: https://github.com/aleksanderwozniak/table_calendar/issues/663

**Comment by majandra2404** [comment]
Thank you very much for your answer
