### ISSUE TITLE
: Error: Required named parameter 'vsync' must be provided.  return AnimatedSize(

### ISSUE THREAD

**Issue by tuananhbgo** [aleksanderwozniak/table_calendar#665]
I try add TickerProviderStateMixin in table_calendar_base.dart 
class _TableCalendarBaseState extends State<TableCalendarBase>
    with TickerProviderStateMixin {}

and add vsync: this, for AnimatedSize(). It's run, fixed

[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
    • Flutter version 2.0.5 at C:\Users\test\Downloads\flutter_windows_2.0.5-stable\flutter
    • Framework revision adc687823a (11 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\test\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\Users\test\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio1
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 98.0.1108.56

**Comment by tuananhbgo** [comment]
Error: Required named parameter 'vsync' must be provided.
              return AnimatedSize(

**Comment by aleksanderwozniak** [comment]
`vsync` has been deprecated in one of recent versions of Flutter. I would recommend upgrading your Flutter to the newest version (2.10.3), this will fix this issue.
