### ISSUE TITLE
hello, i want to disable the option to click on saturday sunday, what do i need to do to be able to do it?

### ISSUE THREAD

**Issue by 2530442368** [aleksanderwozniak/table_calendar#669]
hello, i want to disable the option to click on saturday sunday, what do i need to do to be able to do it?

**Comment by aleksanderwozniak** [comment]
You can disable weekends by using
```dart
enabledDayPredicate: (day) => !(day.weekday == 6 || day.weekday == 7),
```

Alternatively you could just modify `onDaySelected` in a similar fashion.
