### ISSUE TITLE
Wrong date range for prioritized builder on hot reload

### ISSUE THREAD

**Issue by Dharanipalani** [aleksanderwozniak/table_calendar#671]
I just print the date inside the prioritized builder and it gives the wrong range on hot reload. It would be really helpful for me to achieve the required thing in my project.

**Comment by aleksanderwozniak** [comment]
Can you write some more details on actual behavior vs expected behavior + steps to reproduce?

**Comment by Dharanipalani** [comment]
Hi @aleksanderwozniak,

sorry for the delayed response as I was on vacation I am unable to track this.

Steps to reproduce:
Inside prioritized builder callback just print(day);

expected output: prints all days in the current view including both within and out of range dates -> ex: (staring day in the current month view)27/02/2022, 28/02/2022, 01/03/2022, 02/03/2022, 03/03/2022.....04/04/2022(last day in the current month view).

present output: Prints the days in wrong order like 03/03/2022, 12/03/2022, 21/03/2022...

The above-expected case works fine in the initial build but while hot reloading you will get the issue mentioned in the present output

This will really be helpful to achieve my use case in my project and thanks in advance

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @aleksanderwozniak,

I have attached the image below regarding my feature expectation.
![image](https://user-images.githubusercontent.com/19763272/160083108-90179582-c28d-4a7c-a82b-46a9da5619f6.png)

I have maintained a separate widget for displaying the week number in both month and week views. I have stored the date for every week in the prioritized builder, so when I click on the week number that corresponding entire week should be highlighted. For me, while clicking on the week number I rebuild the calendar widget with highlight builder. Doing this, due to the disordered date stored while rebuilding the highlighting week is also wrong. So, please give me a solution as soon as possible for this will be really helpful.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @aleksanderwozniak,

Any update on this and my project is stuck due to this issue. It will be really helpful if you provide any solution to this.

Thanks,
Dharanitharan. P

**Comment by aleksanderwozniak** [comment]
I would recommend not making any side effects in a build method. In this case you just need to be able to get any day of the given week based on a week number, the rest is rebuilding the widget with a proper `rangeStartDay` and `rangeEndDay`.

**Comment by Dharanipalani** [comment]
Hi @aleksanderwozniak,

I have stored the week number and weekdays details inside the prioritized builder. So, while clicking on the week number widget, I get the wrong date range details. For example, I am clicking on the first-week number, it selects the fourth week, and this is because of the wrong date range am getting in the prioritized builder during the second rebuild of the calendar widget.

 You mentioned like **In this case, you just need to be able to get any day of the given week based on a week number,** this, but for me am not getting any day of that particular week, instead, it getting any day of that month, so I cannot able to select the correct week.

Please do the needful and thanks in advance.

**Comment by aleksanderwozniak** [comment]
> I have stored the week number and weekdays details inside the prioritized builder. So, while clicking on the week number widget, I get the wrong date range details. For example, I am clicking on the first-week number, it selects the fourth week, and this is because of the wrong date range am getting in the prioritized builder during the second rebuild of the calendar widget.

Like I said, making side effects (such as storing a value) inside a build method is incorrect and may lead to unexpected behavior. `prioritizedBuilder` isn't meant for storing values from the callback, it is meant to allow one to provide custom cell widgets.

> You mentioned like In this case, you just need to be able to get any day of the given week based on a week number, this, but for me am not getting any day of that particular week, instead, it getting any day of that month, so I cannot able to select the correct week.

You need to be able to map week number to first day of the week. This is something you need to calculate manually.

Closing as this is not related to TableCalendar's behavior.
