### ISSUE TITLE
Calender animates back to initial month when used in DraggableScrollableSheet

### ISSUE THREAD

**Issue by kamami** [aleksanderwozniak/table_calendar#673]
**Describe the bug**
When chnaging the month of the calendar and dragging the `DraggableScrollableSheet `up or down, the calendar animates back to the inital month.

**To reproduce**
Please include a short code sample that can be used to reproduce the problem.
<details>
<summary>Code sample</summary>

     import 'package:flutter/material.dart';
        import 'package:table_calendar/table_calendar.dart';
        
        class ScrollableSheet extends StatelessWidget {
          ScrollableSheet({Key? key}) : super(key: key);
        
          DraggableScrollableController controller = DraggableScrollableController();
        
          @override
          Widget build(BuildContext context) {
            return DraggableScrollableSheet(
                controller: controller,
                initialChildSize: 0.2,
                minChildSize: 0.2,
                builder: (BuildContext context, ScrollController scrollController) {
                  return Material(
                      color: Colors.grey[200],
                      child: CustomScrollView(controller: scrollController, slivers: [
                        SliverToBoxAdapter(
                            child: TableCalendar(
                          firstDay: DateTime.utc(2010, 10, 16),
                          lastDay: DateTime.utc(2030, 3, 14),
                          focusedDay: DateTime.now(),
                        ))
                      ]));
                });
          }
        }

</details>

1. Drag the sheet up
2. Change the selected month
3. Drag sheet up or down
4. Watch calendar animating back to initial month

**Expected behavior**
No automatic animation while dragging the sheet.

**Output of `flutter doctor`**
Paste the result of this command here.
<details>
<summary>Output</summary>

[√] Flutter (Channel beta, 2.11.0-0.1.pre, on Microsoft Windows [Version 10.0.19042.1526], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.64.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
</details>

**Comment by aleksanderwozniak** [comment]
This happens due to `focusedDay: DateTime.now()` - check out [this section](https://github.com/aleksanderwozniak/table_calendar#updating-focusedday). You will need to update your `focusedDay` accordingly.
