### ISSUE TITLE
Make easier to mix cyclical and one-time events.

### ISSUE THREAD

**Issue by josedavidrp** [aleksanderwozniak/table_calendar#675]
**Is your feature request related to a problem? Please describe.**
After trying lots of ways to make a calendar with both cyclical events and one-time events, I couldn't find a way to do it. If I use the example for the cyclical events I cant show up the one-time events. The only way I could do it was just making the same event in my DB for every day.

**Describe the solution you'd like**
I would like a way to load this two types of events separately with a second eventLoader, maybe called "cyclicalLoader" so I can easily add these cyclical events that have only one entry in my DB with a bool meaning if they're cyclical or not.

**Describe alternatives you've considered**
If the mixing is already easily doable, a new example page showing how to do it.

**Additional context**

**Comment by aleksanderwozniak** [comment]
Have you tried something like this?

```dart
eventLoader: (day) {
  return [
    ..._getEventsForDay(day), // fetch events for a given day
    if (day.weekday == DateTime.sunday) Event('Cyclic event') // cyclic event rule
  ];
},
```

This will display both one-time events, as well as cyclic events for the given day.

**Comment by josedavidrp** [comment]
> Have you tried something like this?
> 
> ```dart
> eventLoader: (day) {
>   return [
>     ..._getEventsForDay(day), // fetch events for a given day
>     if (day.weekday == DateTime.sunday) Event('Cyclic event') // cyclic event rule
>   ];
> },
> ```
> 
> This will display both one-time events, as well as cyclic events for the given day.

Thanks for your quick response. It worked when I added your return in the _getEventsForDay function, in the eventLoader it would show the marker but not the event in the daily event list. 

Unluckily in my case I need to sort the events by its date variable and with this the cyclical events cant be sorted with the one-time ones, they just follow the order from the return and there is no sort function available there.

**Comment by aleksanderwozniak** [comment]
> Thanks for your quick response. It worked when I added your return in the _getEventsForDay function, in the eventLoader it would show the marker but not the event in the daily event list.

That's because the daily event list is a separate widget - you will need to update it accordingly as well.


> Unluckily in my case I need to sort the events by its date variable and with this the cyclical events cant be sorted with the one-time ones, they just follow the order from the return and there is no sort function available there.

You could just make a temporary list with all related events, sort it, and then return it in `eventLoader`.
Something along these lines:

```dart
eventLoader: (day) {
  final events = [
    ..._getEventsForDay(day), // fetch events for a given day
    if (day.weekday == DateTime.sunday) Event('Cyclic event') // cyclic event rule
  ];

  events.sort(); // modify this

  return events;
},
```

**Comment by aleksanderwozniak** [comment]
Glad it's working well!
