### ISSUE TITLE
Is it possible to customize color of chevron buttons ripple effect ?

### ISSUE THREAD

**Issue by Ilya-Vysotsky** [aleksanderwozniak/table_calendar#679]
When i press chevron, then it surrounds with grey ripple effect like icon button. IconButton has highlightColor and splashColor fields which help to customize it press effect. Can i customize chevrons like icon button?

**Comment by aleksanderwozniak** [comment]
Have you tried wrapping `TableCalendar` widget with a `Theme` and providing a modified `ThemeData`?

**Comment by Ilya-Vysotsky** [comment]
Thanks, themeData splashColor and highlightColor fields modify chevrons pressing effect.
