### ISSUE TITLE
Firestore Integration

### ISSUE THREAD

**Issue by josephraj2k16** [aleksanderwozniak/table_calendar#68]
HI, I have your project imported in my app,I am using firestore to fetch events,But the issue iam facing is that,I Dont know how to persist the events into the selected events.can you provide any example??

**Comment by nahid1146** [comment]
Hi, can you show me how are you setting up events list on firestore and how are you fetching that to show in this table calendar plugin? Can you help by providing the code?

**Comment by afuentesdp90** [comment]
Hi! Does anyone know how to implement firestore with table calendar?

**Comment by aleksanderwozniak** [comment]
Selected event list underneath the calendar is actually not a part of the package -> check #278 for more details on how to manage them. 

Closing this - if you have any further questions regarding selected events, feel free to ask them in #278.
