### ISSUE TITLE
Are you considering support for a start date - end date UI

### ISSUE THREAD

**Issue by purgeyao** [aleksanderwozniak/table_calendar#680]
Are you considering support for a start date - end date UI

2022.3.15-2022.4.15

Instead of a natural month, the UI is displayed as follows
15，16，17，18，19，20，21
22，23，24，25，26，27，28
29，30，31，1，2，3
4，5，6，7，8，9，10
11，12，13，14，15

**Comment by aleksanderwozniak** [comment]
Try something like this: https://github.com/aleksanderwozniak/table_calendar/issues/367
