### ISSUE TITLE
First day of week and month in selected state by default

### ISSUE THREAD

**Issue by Dharanipalani** [aleksanderwozniak/table_calendar#681]
For both week view and month view, when I swipe left or right, then the first date should be in the selected state. Is any option there to customize this. I have done this using selectedDayPredicate but for some cases, it is not working properly. For example, I need to right swipe, but before doing a right swipe slightly I swipe to the left and not fully, and then I right swipe then the first day of the week is not selected. Is am doing the right way or any other way to achieve this feature. I have attached the code sample below.

'''
 else if (weekDetails.isNotEmpty) {
 _selectedDay = _selectedDay ?? DateTime.now();
 if (day.isAfter(_selectedDay!)) {
 if (day == 
 weekDetails[0].startDayOfWeek!.add(Duration(days: 7))) {
 _selectedDay = day;
 return isSameDay(_selectedDay, day);
 } else
 return false;
 } else {
 if (day == 
 weekDetails[0].startDayOfWeek!.subtract(Duration(days: 7))) {
 _selectedDay = day;
 return isSameDay(_selectedDay, day);
 } else
 return false;
 }
 }
'''

**Comment by aleksanderwozniak** [comment]
You can use `selectedDayPredicate` to mark the proper day as selected, whereas `onPageChanged` is the place to set that given day.
