### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by gwg-kap-en** [aleksanderwozniak/table_calendar#682]
**Is your feature request related to a problem? Please describe.**
I don't know why this isn't available on flutter web? What's the thing limiting it?
**Describe the solution you'd like**
I would to like to submit a PR to help you with that once I know what the problem is
**Describe alternatives you've considered**
I considered building my own widget to do that but figured contributing it this would be better for the community and faster for me

**Comment by henry2man** [comment]
AFAIK Table Calendar works with Web and Desktop.

The only issue I've found is that the header buttons don't allow you to change the month (nothing happens when you click). But the swipe gesture does work, although on the Web this problem is limiting.

**Comment by aleksanderwozniak** [comment]
Everything should be now working fine with `3.0.6` release.
