### ISSUE TITLE
list of month and year in header style

### ISSUE THREAD

**Issue by PrajwalCarnileo** [aleksanderwozniak/table_calendar#683]
Hey I am having trouble adding dropdown to the list of months and years and getting its value, would appreciate help :)

**Comment by aleksanderwozniak** [comment]
For this you will need to make a custom header widget - full example available here: https://github.com/aleksanderwozniak/table_calendar/blob/999905422ad098f2ad79d3e1099cc05655d778d1/example/lib/pages/complex_example.dart#L109
