### ISSUE TITLE
Events not loading - onDaySelected always receives empty events and holidays

### ISSUE THREAD

**Issue by mbelelebohang-pm** [aleksanderwozniak/table_calendar#684]
**Describe the bug**
@aleksanderwozniak The onDaySelected always receives empty events and holidays

**To reproduce**
I looked at the source code and I found the problem. There is an incomplete code in ```calendar_controller.dart```

    
    DateTime? getEventKey(DateTime day) {
        int index = visibleEvents.keys.toList().indexWhere((holiday) => false);
        return index >= 0 ? visibleEvents.keys.elementAt(index) : null;
    }

The same applies to ```getHolidayKey``` function.

The solution is to fix the ```indexWhere```

    DateTime? getEventKey(DateTime day) {
        int index = visibleEvents.keys.toList().indexWhere(
            (eventDate) => DateUtils.isSameDay(eventDate, day) // <---- Fix
        ); 
        return index >= 0 ? visibleEvents.keys.elementAt(index) : null;
    }

Again, I think the same solution should be applied to the ```getHolidayKey``` function.

**Comment by MbeleLebohang-uct** [comment]
Currently I am solving the problem using inheritance. I defined my own controller.

```
class CustomCalendarController extends CalendarController{
  @override
  DateTime? getEventKey(DateTime day) {
    int index = visibleEvents.keys.toList().indexWhere(
      (eventday) => DateUtils.isSameDay(eventday, day)
    );
    return index >= 0 ? visibleEvents.keys.elementAt(index) : null;
  }

  @override
  DateTime? getHolidayKey(DateTime day) {
    int index = visibleHolidays.keys.toList().indexWhere(
      (holiday) => DateUtils.isSameDay(holiday, day)
    );
    return index >= 0 ? visibleHolidays.keys.elementAt(index) : null;
  }
}
```

I use the controller by declaring the controller as follows.


```
  ...
  late CalendarController _calendarController;

  @override
  void initState() {
    _calendarController = CustomCalendarController();
    super.initState();
  }

  @override
  void dispose() {
    _calendarController.dispose();    
    super.dispose();
  }
  ...

```

**Comment by MbeleLebohang-uct** [comment]
Seems like I am using the old version. sorry

**Comment by aleksanderwozniak** [comment]
That's correct, `CalendarController` has been removed in `3.0.0` version - I would recommend updating to the newest release.
