### ISSUE TITLE
Remove or Change Calendar Format Button

### ISSUE THREAD

**Issue by junndobit** [aleksanderwozniak/table_calendar#686]
Is it possible to display 3 buttons which is "Month", "Week", or "2 weeks" and highlight which one is the current calendar format? Also, is it possible to remove this button completely?
![image](https://user-images.githubusercontent.com/20215990/163669555-5bd4dc1e-68be-4cf5-9328-ab2a04bb9d8c.png)

**Comment by randaomar** [comment]
Yes you can remove the  "2 weeks button"!
just put this to your calendar  
```
TableCalendar(
      availableCalendarFormats:   const {
        CalendarFormat.month: 'Month'
      },
```

**Comment by aleksanderwozniak** [comment]
> Is it possible to display 3 buttons which is "Month", "Week", or "2 weeks" and highlight which one is the current calendar format?

For this you would need to make a custom header widget, as by default only 1 format button is there.

> Also, is it possible to remove this button completely?

Yes, by using `formatButtonVisible: false`

**Comment by SatyaMirthipati** [comment]
This is helpful

**Comment by ariefsn** [comment]
hi, I have question.
how to make the `onFormatChanged` to be working if the `formatButton` is hidden?
seems the `onFormatChanged` only triggered when click the `formatButton`.
