### ISSUE TITLE
How is the second picture implemented?

### ISSUE THREAD

**Issue by misskter** [aleksanderwozniak/table_calendar#688]
What attribute does the second picture use to realize the custom style of event？

**Comment by MilesAdamson** [comment]
I believe it is using `CalendarBuilders` with some combination of `singleMarkerBuilder` or `markerBuilder` for the events, and `selectedBuilder` for the square colored background. That might just be `CalendarStyle` though.

I also wish it had the code there

**Comment by JustMilan** [comment]
Same, I’ve been looking for it, but couldn’t find anything. Once I find out, I’ll let you guys know

**Comment by HamzaMuazzam** [comment]
> What attribute does the second picture use to realize the custom style of event？

you can use this code below.

```
calendarBuilders: CalendarBuilders(markerBuilder:
                (BuildContext context, DateTime datetime, List<Event> list) {
              if (list.isNotEmpty) {
                return Stack(
                  children: [
                    Align(
                      alignment: Alignment.bottomRight,
                      child: Container(
                          color: Colors.black,
                          child: Padding(
                            padding: const EdgeInsets.symmetric(horizontal: 4),
                            child: Text(
                              list.length.toString(),
                              style: TextStyle(
                                  color: Colors.red,
                                  fontWeight: FontWeight.bold),
                            ),
                          )),
                    ),
                  ],
                );
              }
            }),
```

**Comment by aleksanderwozniak** [comment]
You'll want to use [markerBuilder](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarBuilders/markerBuilder.html) for this, with `'${events.length}'` to display the number.

Here's the old code (from v2.3.3) for that picture:

https://github.com/aleksanderwozniak/table_calendar/blob/5721feea4e555af6a8ab6d75f373fba173cd27f1/example/lib/main.dart#L284-L307
