### ISSUE TITLE
Range selection from adjacent months selects the first & last dates.

### ISSUE THREAD

**Issue by ccosnean** [aleksanderwozniak/table_calendar#691]
**Describe the bug**
The described scenarios are UI bugs only. The selected days seem to be correct.

`version 3.0.5`

**To reproduce**
- When selecting the a date range from a prev month the first day of current month also is selected.
- When selecting the a date range from a next month the last day of current month also is selected.
- If you first select a start date from prev month date and end from current it works as expected.
- If you first select a start date from next month date and end from current it works as expected.
- If you select a start date from next month and a end date from prev month the first date is also selected.
- If you select a start date from prev month and a end date from next month the last date is also selected.

<details>
<summary>Screenshots</summary>
<img width="382" alt="Screen Shot 2022-04-28 at 3 08 52 PM" src="https://user-images.githubusercontent.com/22283233/165749498-98db80cd-7281-4779-ad4d-372055f90d14.png">
<img width="379" alt="Screen Shot 2022-04-28 at 3 09 12 PM" src="https://user-images.githubusercontent.com/22283233/165749499-5472ced9-c46f-4c39-aa23-4d0c373f7cdc.png">
<img width="379" alt="Screen Shot 2022-04-28 at 3 09 20 PM" src="https://user-images.githubusercontent.com/22283233/165749504-5b9d0f88-3147-4390-a966-f9e07184bc9f.png">
<img width="378" alt="Screen Shot 2022-04-28 at 3 10 40 PM" src="https://user-images.githubusercontent.com/22283233/165749506-a25c5ee4-5d09-4aae-93cb-350beb7cb6d8.png">
<img width="381" alt="Screen Shot 2022-04-28 at 2 48 23 PM" src="https://user-images.githubusercontent.com/22283233/165749490-a66a6f8f-a708-4c57-826b-f83fab8fa32b.png">
</details>

```dart
// final cs = Theme.of(context).colorScheme;

final a = TableCalendar(
  focusedDay: selectedDate,
  selectedDayPredicate: (day) => day.midnightDaysDiff(selectedDate) == 0,
  currentDay: DateTime.now(),
  firstDay: DateTime.fromMillisecondsSinceEpoch(0),
  lastDay: DateTime.now().add(const Duration(days: 365)),
  sixWeekMonthsEnforced: true,
  calendarFormat: CalendarFormat.month,
  availableCalendarFormats: const {
    CalendarFormat.month: 'Month',
  },
  availableGestures: AvailableGestures.horizontalSwipe,
  rangeSelectionMode: widget.onRangeSelected != null
      ? RangeSelectionMode.enforced
      : RangeSelectionMode.disabled,
  rangeStartDay: rangeStartDate,
  rangeEndDay: rangeEndDate,
  daysOfWeekStyle: DaysOfWeekStyle(
    weekdayStyle: TextStyle(
      color: cs.onSurface,
    ),
    weekendStyle: TextStyle(
      color: cs.primary.withOpacity(0.8),
      fontWeight: FontWeight.w600,
    ),
  ),
  calendarStyle: CalendarStyle(
    disabledTextStyle: TextStyle(
      color: cs.onSurface.withOpacity(0.2),
    ),
    rangeHighlightColor: cs.primary.withOpacity(0.5),
    rangeHighlightScale: 0.8,
    rangeEndDecoration: BoxDecoration(
      color: cs.primary,
      shape: BoxShape.circle,
    ),
    rangeStartDecoration: BoxDecoration(
      color: cs.primary,
      shape: BoxShape.circle,
    ),
    rangeEndTextStyle: TextStyle(
      color: cs.onPrimary,
      fontWeight: FontWeight.bold,
    ),
    rangeStartTextStyle: TextStyle(
      color: cs.onPrimary,
      fontWeight: FontWeight.bold,
    ),
    weekendTextStyle: TextStyle(
      color: cs.primary.withOpacity(0.8),
      fontWeight: FontWeight.w600,
    ),
    todayDecoration: BoxDecoration(
      border: Border.all(color: cs.primary),
      shape: BoxShape.circle,
    ),
    todayTextStyle: TextStyle(
      color: cs.primary,
      fontWeight: FontWeight.w500,
    ),
    selectedDecoration: BoxDecoration(
      color: cs.primary,
      shape: BoxShape.circle,
    ),
    selectedTextStyle: TextStyle(
      color: cs.onPrimary,
      fontWeight: FontWeight.w800,
    ),
    isTodayHighlighted: true,
  ),
);

```

**Comment by aleksanderwozniak** [comment]
Looks like your config is incorrect:

```dart
  focusedDay: selectedDate,
  selectedDayPredicate: (day) => day.midnightDaysDiff(selectedDate) == 0,
```

`focusedDay` is something different than `selectedDate`. Check out [setup guide](https://github.com/aleksanderwozniak/table_calendar#basic-setup) for more details.

You can also try your steps to reproduce on [range_example](https://github.com/aleksanderwozniak/table_calendar/blob/999905422ad098f2ad79d3e1099cc05655d778d1/example/lib/pages/range_example.dart).

**Comment by aleksanderwozniak** [comment]
That's the point, these are not the same. If you apply correct config, you won't be facing errors mentioned before.
