### ISSUE TITLE
how to increase space between the columns after the marker builder because it is  cutting the marker which i have used ?

### ISSUE THREAD

**Issue by harryandroiddev** [aleksanderwozniak/table_calendar#693]
how  to increase the space between the days how it is possible , or how to add more space below the marker ?
![ Screen Shot](https://user-images.githubusercontent.com/57495358/166200681-a166abbe-2a34-452d-910a-65c1b88ec93c.png)

**Comment by aleksanderwozniak** [comment]
You can use [canMarkersOverflow](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarStyle/canMarkersOverflow.html) or [rowHeight](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/rowHeight.html).
