### ISSUE TITLE
How to know when calendar is swiped forward/back

### ISSUE THREAD

**Issue by defemz** [aleksanderwozniak/table_calendar#699]
Please I want to know how to capture/know when calendar is swiped forward/backward when moving/navigating through the months. Any help will be appreciated. Thanks

**Comment by zacherygentry** [comment]
There's a handler for this called `onPageChanged`

**Comment by defemz** [comment]
> There's a handler for this called `onPageChanged`

Thanks for your reply. However 'onPageChanged' handler does not provide a way(AFAIK) to know whether user is swiping forward or backward when moving/navigating through the months. How specifically can this be implemented?

**Comment by zbranevichfinstek** [comment]
> > There's a handler for this called `onPageChanged`
> 
> Thanks for your reply. However 'onPageChanged' handler does not provide a way(AFAIK) to know whether user is swiping forward or backward when moving/navigating through the months. How specifically can this be implemented?

Try to compare the new value with the previous focusDay

**Comment by zacherygentry** [comment]
> > There's a handler for this called `onPageChanged`
> 
> Thanks for your reply. However 'onPageChanged' handler does not provide a way(AFAIK) to know whether user is swiping forward or backward when moving/navigating through the months. How specifically can this be implemented?

What @zbranevichfinstek said. You should set the `focusedDate` with a setState when you use `onPageChanged`. Then just compare the month as the user swipes. As an edge case, be careful handling the January / December swipe correctly.

**Comment by defemz** [comment]
Thanks guys. I got this to work.

**Comment by defemz** [comment]
Thanks guys. This approach solves it for me
