### ISSUE TITLE
Change animation

### ISSUE THREAD

**Issue by pmcarlos** [aleksanderwozniak/table_calendar#7]
What about implementing the calendar animation from week to month for something like this https://github.com/apptreesoftware/flutter_calendar

I think its better looking if the animation goes from top to bottom

**Comment by aleksanderwozniak** [comment]
As of package version `0.3.1` you can select CalendarFormat animation.

I've changed the default animation to slide, so just update the package and you are set!

For more info, please refer here:
https://pub.dartlang.org/documentation/table_calendar/latest/table_calendar/FormatAnimation-class.html

**Comment by pmcarlos** [comment]
Thanks for the active support you are having on this! Congrats
