### ISSUE TITLE
Disable specific date from list

### ISSUE THREAD

**Issue by bogoss95** [aleksanderwozniak/table_calendar#700]
Hi,

I need to disable specifics dates from a list (for example) but in enabledDayPredicate i can't return a list (dynamicly). Do you have any idea how to do it please? Thanks very much

**Comment by RalphMarvin** [comment]
This is a feature I also need

**Comment by aleksanderwozniak** [comment]
Check out https://github.com/aleksanderwozniak/table_calendar/issues/642#issuecomment-1021110887 - pretty much the same idea.
