### ISSUE TITLE
How to get the range of visible dates in a page?

### ISSUE THREAD

**Issue by lemba3** [aleksanderwozniak/table_calendar#702]

**Comment by andrei-bucurei** [comment]
The visible date range is a function of:
 - focusedDay
 - calendarFormat
 - whether the 6-week months are enforced

It looks something like this:

```
void printVisibleDateRange() {
    final isSixWeekMonthEnforced = true;
    final focusedDay = state.focusedDay;
    final calendarFormat = state.calendarFormat;

    var firstVisibleDate = DateTime.now().toUtc();
    var lastVisibleDate = DateTime.now().toUtc();

    final firstDayOfMonth = DateTime.utc(
      focusedDay.year,
      focusedDay.month,
      1,
    );

    final lastDayOfMonth = DateTime.utc(
      focusedDay.year,
      focusedDay.month + 1,
      0,
    );

    final firstVisibleDayOfMonth = DateTime.utc(
      firstDayOfMonth.year,
      firstDayOfMonth.month,
      1 + 1 - firstDayOfMonth.weekday,
    );

    final firstDayOfYear = DateTime.utc(
      focusedDay.year,
      1,
      1,
    );

    // first day of first week of the year
    final w1d1 = DateTime.utc(
      firstDayOfYear.year,
      1,
      1 + 1 - firstDayOfYear.weekday,
    );

    final weekOfYear = (focusedDay.difference(w1d1).inDays / 7).truncate() + 1;

    final weekOfMonth = (focusedDay.difference(firstVisibleDayOfMonth).inDays / 7).truncate() + 1;

    final monthWeekSpan =
        (lastDayOfMonth.difference(firstVisibleDayOfMonth).inDays / 7).truncate() + 1;

    switch (calendarFormat) {
      case CalendarFormat.month:
        firstVisibleDate = DateTime.utc(
          firstDayOfMonth.year,
          firstDayOfMonth.month,
          1 + 1 - firstDayOfMonth.weekday,
        );

        final offset = isSixWeekMonthEnforced && monthWeekSpan < 6 ? 7 * (6 - monthWeekSpan) : 0;
        lastVisibleDate = DateTime.utc(
          lastDayOfMonth.year,
          lastDayOfMonth.month,
          lastDayOfMonth.day + 7 - lastDayOfMonth.weekday + offset,
        );
        break;
      case CalendarFormat.week:
        firstVisibleDate = DateTime.utc(
          focusedDay.year,
          focusedDay.month,
          focusedDay.day + 1 - focusedDay.weekday,
        );

        lastVisibleDate = DateTime.utc(
          firstVisibleDate.year,
          firstVisibleDate.month,
          firstVisibleDate.day + 6,
        );

        break;
      case CalendarFormat.twoWeeks:
        final isEvenWeekOfYear = weekOfYear % 2 == 0;
        final offset = isEvenWeekOfYear ? 7 : 0;

        firstVisibleDate = DateTime.utc(
          focusedDay.year,
          focusedDay.month,
          focusedDay.day + 1 - focusedDay.weekday - offset,
        );

        lastVisibleDate = DateTime.utc(
          firstVisibleDate.year,
          firstVisibleDate.month,
          firstVisibleDate.day + 13,
        );
        break;
    }

    print("");
    print(firstVisibleDate);
    print(lastVisibleDate);
  }
```
Tested with version 3.0.5.
**This function is not very well tested.
Use at your own risk!**

Also, if anyone knows a better, more succint way of doing this, please let us know!

**Comment by nialljawad96** [comment]
> The visible date range is a function of:
> 
> * focusedDay
> * calendarFormat
> * whether the 6-week months are enforced
> 
> It looks something like this:
> 
> ```
> void printVisibleDateRange() {
>     final isSixWeekMonthEnforced = true;
>     final focusedDay = state.focusedDay;
>     final calendarFormat = state.calendarFormat;
> 
>     var firstVisibleDate = DateTime.now().toUtc();
>     var lastVisibleDate = DateTime.now().toUtc();
> 
>     final firstDayOfMonth = DateTime.utc(
>       focusedDay.year,
>       focusedDay.month,
>       1,
>     );
> 
>     final lastDayOfMonth = DateTime.utc(
>       focusedDay.year,
>       focusedDay.month + 1,
>       0,
>     );
> 
>     final firstVisibleDayOfMonth = DateTime.utc(
>       firstDayOfMonth.year,
>       firstDayOfMonth.month,
>       1 + 1 - firstDayOfMonth.weekday,
>     );
> 
>     final firstDayOfYear = DateTime.utc(
>       focusedDay.year,
>       1,
>       1,
>     );
> 
>     // first day of first week of the year
>     final w1d1 = DateTime.utc(
>       firstDayOfYear.year,
>       1,
>       1 + 1 - firstDayOfYear.weekday,
>     );
> 
>     final weekOfYear = (focusedDay.difference(w1d1).inDays / 7).truncate() + 1;
> 
>     final weekOfMonth = (focusedDay.difference(firstVisibleDayOfMonth).inDays / 7).truncate() + 1;
> 
>     final monthWeekSpan =
>         (lastDayOfMonth.difference(firstVisibleDayOfMonth).inDays / 7).truncate() + 1;
> 
>     switch (calendarFormat) {
>       case CalendarFormat.month:
>         firstVisibleDate = DateTime.utc(
>           firstDayOfMonth.year,
>           firstDayOfMonth.month,
>           1 + 1 - firstDayOfMonth.weekday,
>         );
> 
>         final offset = isSixWeekMonthEnforced && monthWeekSpan < 6 ? 7 * (6 - monthWeekSpan) : 0;
>         lastVisibleDate = DateTime.utc(
>           lastDayOfMonth.year,
>           lastDayOfMonth.month,
>           lastDayOfMonth.day + 7 - lastDayOfMonth.weekday + offset,
>         );
>         break;
>       case CalendarFormat.week:
>         firstVisibleDate = DateTime.utc(
>           focusedDay.year,
>           focusedDay.month,
>           focusedDay.day + 1 - focusedDay.weekday,
>         );
> 
>         lastVisibleDate = DateTime.utc(
>           firstVisibleDate.year,
>           firstVisibleDate.month,
>           firstVisibleDate.day + 6,
>         );
> 
>         break;
>       case CalendarFormat.twoWeeks:
>         final isEvenWeekOfYear = weekOfYear % 2 == 0;
>         final offset = isEvenWeekOfYear ? 7 : 0;
> 
>         firstVisibleDate = DateTime.utc(
>           focusedDay.year,
>           focusedDay.month,
>           focusedDay.day + 1 - focusedDay.weekday - offset,
>         );
> 
>         lastVisibleDate = DateTime.utc(
>           firstVisibleDate.year,
>           firstVisibleDate.month,
>           firstVisibleDate.day + 13,
>         );
>         break;
>     }
> 
>     print("");
>     print(firstVisibleDate);
>     print(lastVisibleDate);
>   }
> ```
> 
> Tested with version 3.0.5. **This function is not very well tested. Use at your own risk!**
> 
> Also, if anyone knows a better, more succint way of doing this, please let us know!

Thanks for this - What is the "state" object used at the start of the function referring to/from?

**Comment by lemba3** [comment]
I have found a way out of my problem by using the focusedDay from onPageChanged. But it could have been easier if we could access the range of visible dates directly. Thank you for ur help

**Comment by musthafa1996** [comment]
For anyone still looking for a way to get the visible date range of the `TableCalendar`, I’ve created a utility class that calculates the visible range based on the current `focusedDay`, `CalendarFormat`, and other configurations. 

Here’s the solution:

## 📅 Utility Class

```dart
import 'package:flutter/material.dart';
import 'package:table_calendar/table_calendar.dart';

class CalenderUtils {
  static DateTimeRange getVisibleRangeForFocusDay(
    DateTime focusedDay,
    DateTime firstDay,
    DateTime lastDay,
    CalendarFormat format,
    StartingDayOfWeek startingDayOfWeek,
    bool sixWeekMonthsEnforced,
  ) {
    final pageIndex = getPageIndex(
      firstDay,
      focusedDay,
      format,
      startingDayOfWeek,
      sixWeekMonthsEnforced,
    );
    final baseDay = getBaseDay(
      firstDay,
      lastDay,
      format,
      pageIndex,
    );
    final visibleRange = getVisibleRange(
      format,
      baseDay,
      startingDayOfWeek,
      sixWeekMonthsEnforced,
    );

    return visibleRange;
  }

  static int getPageIndex(
    DateTime firstDay,
    DateTime focusedDay,
    CalendarFormat format,
    StartingDayOfWeek startingDayOfWeek,
    bool sixWeekMonthsEnforced,
  ) {
    final firstDayOfWeek = firstDayOfWeek(firstDay, startingDayOfWeek);

    switch (format) {
      case CalendarFormat.month:
        return (focusedDay.year - firstDay.year) * 12 +
            (focusedDay.month - firstDay.month);
      case CalendarFormat.twoWeeks:
        return ((focusedDay.difference(firstDayOfWeek).inDays) / 14).ceil() - 1;
      case CalendarFormat.week:
        return ((focusedDay.difference(firstDayOfWeek).inDays) / 7).ceil() - 1;
    }
  }

  static DateTime getBaseDay(
    DateTime firstDay,
    DateTime lastDay,
    CalendarFormat format,
    int pageIndex,
  ) {
    DateTime day;

    switch (format) {
      case CalendarFormat.month:
        day = DateTime.utc(firstDay.year, firstDay.month + pageIndex);
        break;
      case CalendarFormat.twoWeeks:
        day = firstDay.add(Duration(days: pageIndex * 14));
        break;
      case CalendarFormat.week:
        day = firstDay.add(Duration(days: pageIndex * 7));
        break;
    }

    if (day.isBefore(firstDay)) return firstDay;
    if (day.isAfter(lastDay)) return lastDay;
    return day;
  }

  static DateTimeRange getVisibleRange(
    CalendarFormat format,
    DateTime baseDay,
    StartingDayOfWeek startingDayOfWeek,
    bool sixWeekMonthsEnforced,
  ) {
    switch (format) {
      case CalendarFormat.month:
        return daysInMonth(baseDay, startingDayOfWeek, sixWeekMonthsEnforced);
      case CalendarFormat.twoWeeks:
        return daysInTwoWeeks(baseDay, startingDayOfWeek);
      case CalendarFormat.week:
        return daysInWeek(baseDay, startingDayOfWeek);
    }
  }

  static DateTimeRange daysInWeek(
    DateTime day,
    StartingDayOfWeek startingDayOfWeek,
  ) {
    final firstDay = day.subtract(Duration(days: (day.weekday + 7 - startingDayOfWeek.index) % 7));
    return DateTimeRange(start: firstDay, end: firstDay.add(const Duration(days: 6)));
  }

  static DateTimeRange daysInTwoWeeks(
    DateTime day,
    StartingDayOfWeek startingDayOfWeek,
  ) {
    final firstDay = day.subtract(Duration(days: (day.weekday + 7 - startingDayOfWeek.index) % 7));
    return DateTimeRange(start: firstDay, end: firstDay.add(const Duration(days: 13)));
  }

  static DateTimeRange daysInMonth(
    DateTime day,
    StartingDayOfWeek startingDayOfWeek,
    bool sixWeekMonthsEnforced,
  ) {
    final firstDay = DateTime.utc(day.year, day.month);
    final lastDay = DateTime.utc(day.year, day.month + 1).subtract(const Duration(days: 1));
    return DateTimeRange(start: firstDay, end: lastDay);
  }
}
```

## 🚀 Usage Example

```
TableCalendar(
  firstDay: widget.firstDay,
  lastDay: widget.lastDay,
  focusedDay: _focusedDay,
  calendarFormat: widget.calendarFormat,
  onPageChanged: (focusedDay) {
    final visibleRange = CalenderUtils.getVisibleRangeForFocusDay(
      focusedDay,
      widget.firstDay,
      widget.lastDay,
      widget.calendarFormat,
      StartingDayOfWeek.monday,
      false,
    );

    print('Visible Range: ${visibleRange.start} - ${visibleRange.end}');
  },
);
```

This method allows you to:
- Get the visible days based on the current format (month, two weeks, week)
- Handle custom starting days of the week
- Enforce six-week months if needed

Hope this helps anyone facing the same issue! Let me know if you have any questions or want to refine the logic further. 😊
