### ISSUE TITLE
Issue in Release Mode

### ISSUE THREAD

**Issue by Nuhail1** [aleksanderwozniak/table_calendar#709]
The calendar is fine in debug mode , when I run in release mode I got this error and grey screen. Please help
Latest Flutter Version 
**Error**
 Null check operator used on a null value
I/flutter (22413): #0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455)
I/flutter (22413): #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456)
I/flutter (22413): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
and more...

**Comment by aleksanderwozniak** [comment]
Please fill out the bug report form with steps on how to reproduce your issue.

**Comment by ebot64** [comment]
Same problem as #653 

`══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was:
  PageView
  PageView:file:///C:/....../pub.dartlang.org/table_calendar-3.0.6/lib/src/widgets/calendar_core.dart:59:21

When the exception was thrown, this was the stack:
#0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455:25)
#1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456:16)
#2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)`

![Screenshot_20220703-192532](https://user-images.githubusercontent.com/10565419/177052693-7b4f7427-ba03-47c8-b387-c8a0afadf3ee.jpg)

**Comment by ig4ever** [comment]
it happens too me, please explain how to solve this??
