### ISSUE TITLE
Increase the gesturedetector target size

### ISSUE THREAD

**Issue by byronferguson** [aleksanderwozniak/table_calendar#71]
The current target is limited to the child text, but you'd expect all/most of the "painted" area of selected days to be targetable on other dates.

**Comment by byronferguson** [comment]
`dayHitTestBehavior: HitTestBehavior.translucent,`

This seems to provide the behavior I was looking for, is this the correct solution?

**Comment by aleksanderwozniak** [comment]
Yes, that's correct, but I would suggest going with `dayHitTestBehavior: HitTestBehavior.opaque` unless you have another `GestureDetector` nested inside a day cell.
