### ISSUE TITLE
No callback or listener for swiper gestures (onVerticalSwipe or onHorizontalSwipe)

### ISSUE THREAD

**Issue by Bikuta-victor1** [aleksanderwozniak/table_calendar#714]
I need to be able to update external states of the app from the table calendar widget.

I tried using the onPanUpdate Method in the GestureDetector Class, but it wasn't able to detect any gestures.

**Comment by aleksanderwozniak** [comment]
Using `availableGestures: AvailableGestures.none` will disable the internal gestures. You can then add `GestureDetector` as a parent widget to catch gestures.
