### ISSUE TITLE
onVisibleDaysChanged not available ?

### ISSUE THREAD

**Issue by ed-lot** [aleksanderwozniak/table_calendar#726]
Hello guys,

I just migrate to null safety and onVisibleDaysChanged is not available ? it's normal ?

I dont know other user use the calendar but.... how am I supposed to update the display between two date ranges now ? knowing that obviously I have to make an API call to get the events between these two dates.

I really have to create an algorithm to retrieve the first and last date generated by eventLoader() when the date changes ? juste to take the fist and last date displayed ?

Thanks for help

**Comment by ed-lot** [comment]
So i found solution (i only use week view) :

```
  onPageChanged: (date) {
    this.focusDay = date;
    DateTime firstDayOfWeek = date.subtract(Duration(days: date.weekday - 1));
    DateTime lastDayOfWeek = firstDayOfWeek.add(Duration(days: 8));
    DateTime startDate = getStartOfDate(firstDayOfWeek);
    DateTime endDate = getStartOfDate(lastDayOfWeek);
    _homeStore.refreshEvents(begin: startDate, end: endDate).then((result) {
      if (result.isError()) {
        ToastHelper.fromError(result.error);
      }
    });
  },
```

**Comment by musthafa1996** [comment]
For anyone still looking for a way to get the visible date range of the TableCalendar, please check this comment
https://github.com/aleksanderwozniak/table_calendar/issues/702#issuecomment-2718023823
