### ISSUE TITLE
can not change Selected Day Color 

### ISSUE THREAD

**Issue by yeminsoe** [aleksanderwozniak/table_calendar#730]
selectedTextStyle: TextStyle(
      fontSize: ScreenUtil().setSp(smallFont()),
      fontWeight: FontWeight.bold,
      color: COLORS.transport_h2_color,
    ),
    selectedDecoration: BoxDecoration(
      color: COLORS.transport_call_btn,
      shape: BoxShape.circle,
    ),
I used like above , but not work for me

**Comment by aleksanderwozniak** [comment]
Try adding this in the [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/pages/basics_example.dart) and see if it works there.
