### ISSUE TITLE
Can the leftchervon icon customized with customized widget?

### ISSUE THREAD

**Issue by jinfagang** [aleksanderwozniak/table_calendar#733]
Not just icon , but replace it with customized widget？

**Comment by aleksanderwozniak** [comment]
Yes, you can use any `Widget` for this - #606

**Comment by jinfagang** [comment]
@aleksanderwozniak hello. the icon can be replaced, but can not using customized widget with press function. It doesn't exposed.

**Comment by aleksanderwozniak** [comment]
You can follow the custom header approach to get this behavior to work, you just need to get the `pageController` from the calendar: 
https://github.com/aleksanderwozniak/table_calendar/blob/cfdc5b5ce6d2aa40c03fb8db8f9372145ab2bd21/example/lib/pages/complex_example.dart#L156
https://github.com/aleksanderwozniak/table_calendar/blob/cfdc5b5ce6d2aa40c03fb8db8f9372145ab2bd21/example/lib/pages/complex_example.dart#L124-L129
