### ISSUE TITLE
(SOLVED) 2 weeks one week and one month is not working correct 

### ISSUE THREAD

**Issue by sergedahdouh** [aleksanderwozniak/table_calendar#734]
import 'package:table_calendar/table_calendar.dart';
import 'package:intl/date_symbol_data_local.dart';

class TableRangeExample extends StatefulWidget {
  const TableRangeExample({
    Key? key,
    this.width,
    this.height,
  }) : super(key: key);

  final double? width;
  final double? height;

  @override
  _TableRangeExampleState createState() => _TableRangeExampleState();
}

class _TableRangeExampleState extends State<TableRangeExample> {
  CalendarFormat _calendarFormat = CalendarFormat.month;
  RangeSelectionMode _rangeSelectionMode = RangeSelectionMode
      .toggledOn; // Can be toggled on/off by longpressing a date
  DateTime _focusedDay = DateTime.now();
  DateTime? _selectedDay;
  DateTime? _rangeStart;
  DateTime? _rangeEnd;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TableCalendar(
        locale: 'fr_FR',
        firstDay: DateTime.utc(2010, 10, 16),
        lastDay: DateTime.utc(2030, 3, 14),
        focusedDay: _focusedDay,
        selectedDayPredicate: (day) => isSameDay(_selectedDay, day),
        rangeStartDay: _rangeStart,
        rangeEndDay: _rangeEnd,
        calendarFormat: _calendarFormat,
        rangeSelectionMode: _rangeSelectionMode,
        onDaySelected: (selectedDay, focusedDay) {
          if (!isSameDay(_selectedDay, selectedDay)) {
            setState(() {
              _selectedDay = selectedDay;
              _focusedDay = focusedDay;
              _rangeStart = null; // Important to clean those
              _rangeEnd = null;
              _rangeSelectionMode = RangeSelectionMode.toggledOff;
               FFAppState().rangeStart = _rangeStart;
            	FFAppState().rangeEnd = _rangeEnd;
            });
          }
        },
        onRangeSelected: (start, end, focusedDay) {
          setState(() {
            _selectedDay = null;
            _focusedDay = focusedDay;
            _rangeStart = start;
            _rangeEnd = end;
            _rangeSelectionMode = RangeSelectionMode.toggledOn;
            FFAppState().rangeStart = _rangeStart;
            FFAppState().rangeEnd = _rangeEnd;
            print(_rangeEnd);
          });
        },
        onFormatChanged: (format) {
          if (_calendarFormat != format) {
            setState(() {
              _calendarFormat = format;
            });
          }
        },
        onPageChanged: (focusedDay) {
          _focusedDay = focusedDay;
        },
      ),
    );
  }
}

I have the following code when i press 2 weeks it give one month when i press month is give me 2 weeks can you please help me

**Comment by pc3p0** [comment]
Have you investigated the `headerStyle` property of `TableCalendar`?

By default, the format button shows the next `CalendarFormat` that will be applied, not the current one:
```
/// Controls the text inside FormatButton.
/// * `true` - the button will show next CalendarFormat
/// * `false` - the button will show current CalendarFormat
final bool formatButtonShowsNext;
```

Try setting `headerStyle` to `headerStyle: const HeaderStyle(formatButtonShowsNext: false)`.
