### ISSUE TITLE
Manage Day width

### ISSUE THREAD

**Issue by uriparadeda** [aleksanderwozniak/table_calendar#735]
Sorry I'm newbie on flutter and maybe this is obvious, but i can't reach a suitable answer.

I'm Customizing several CalendarBuilders, to modify the UI of the days.

I can modify the height of the day container. But I don't know how to manage the width. I assume the width of each day is set according the device screen size.

Now, I don't know how to create simple Container according to the established sizes of the parent container. For example a container like the original one, a simple circle shape with a simple color, but according to the width, will be enough to understand it.
![Captura de Pantalla 2022-09-22 a les 11 03 43](https://user-images.githubusercontent.com/77615771/191706335-0202ed58-b080-4d41-aefe-486c4ac3284b.png)

**Comment by aleksanderwozniak** [comment]
You can wrap `TableCalendar` with `SizedBox` and set the width there. Then cell width is `parentWidth / 7`.

**Comment by sagnik-sanyal** [comment]
Hi @aleksanderwozniak cant we customise the cell width like in a horizontal calendar if we want to show only 3 dates consecultively instead of 7 is it possible ?
