### ISSUE TITLE
Custom Header

### ISSUE THREAD

**Issue by saurabhdhingra** [aleksanderwozniak/table_calendar#738]
Hi I want to move the header to the appBar. Is there a way to do that ?
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-10-28 at 17 09 14](https://user-images.githubusercontent.com/75309640/198579892-f618fd25-727d-4d07-bde5-fd62b9d6034e.png)

**Comment by aleksanderwozniak** [comment]
Yes, you can implement a custom header. Check out [complex_example](https://github.com/aleksanderwozniak/table_calendar/blob/cfdc5b5ce6d2aa40c03fb8db8f9372145ab2bd21/example/lib/pages/complex_example.dart) to get started.
