### ISSUE TITLE
Days are not scrollable on web

### ISSUE THREAD

**Issue by MihailovDev** [aleksanderwozniak/table_calendar#739]
Hello, I am using this for my flutter app and am now trying to create a web app out of it. 
Everything works fine on mobile but the days are not scrollable when i try it on the web, I cannot get any error.  I will post my code here and screen shots.

This is how i build the calendar:

`Widget buildCalendar(ScheduleViewModel scheduleViewModel) {

  return TableCalendar(
    locale: scheduleViewModel.locale,
    headerVisible: false,
    firstDay: scheduleViewModel.kFirstDay,
    lastDay: scheduleViewModel.kLastDay,
    focusedDay: scheduleViewModel.focusedDate,
    eventLoader: (date) =>
        scheduleViewModel.getEventsForDay(date.day, date.year),
    onCalendarCreated: (_) =>
        scheduleViewModel.loadSlots(scheduleViewModel.selectedDate),
    calendarBuilders: CalendarBuilders(
      todayBuilder: (context, date, select) {
        return Container(
          decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: Colors.white,
              border: Border.all(color: figmaGreen, width: 1)),
          width: calendarItemSize,
          height: calendarItemSize,
          margin: const EdgeInsets.symmetric(horizontal: 1.5),
          child: Center(
              child: Text(date.day.toString(),
                  style: const TextStyle(
                      color: figmaGreen, fontWeight: FontWeight.bold))),
        );
      },
      defaultBuilder: (context, date, select) {
        return Container(
          decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: Colors.white,
              border: Border.all(color: figmaGreen, width: 1)),
          width: calendarItemSize,
          height: calendarItemSize,
          margin: const EdgeInsets.symmetric(horizontal: 1.5),
          child: Center(
              child: Text(date.day.toString(),
                  style: const TextStyle(
                      color: figmaGreen, fontWeight: FontWeight.bold))),
        );
      },
      outsideBuilder: (context, date, select) {
        return Container(
          decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: Colors.white,
              border: Border.all(color: Colors.black12, width: 1)),
          width: calendarItemSize,
          height: calendarItemSize,
          margin: const EdgeInsets.symmetric(horizontal: 1.5),
          child: Center(
              child: Text(date.day.toString(),
                  style: const TextStyle(
                      color: Colors.black12, fontWeight: FontWeight.bold))),
        );
      },
      disabledBuilder: (context, date, select) {
        return Container(
          decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: Colors.white,
              border: Border.all(color: Colors.black12, width: 1)),
          width: calendarItemSize,
          height: calendarItemSize,
          margin: const EdgeInsets.symmetric(horizontal: 1.5),
          child: Center(
              child: Text(date.day.toString(),
                  style: const TextStyle(
                      color: Colors.black12, fontWeight: FontWeight.bold))),
        );
      },
      selectedBuilder: (context, date, select) {
        return Container(
          decoration:
              const BoxDecoration(shape: BoxShape.circle, color: figmaGreen),
          width: calendarItemSize,
          height: calendarItemSize,
          margin: const EdgeInsets.symmetric(horizontal: 1.5),
          child: Center(
              child: Text(select.day.toString(),
                  style: const TextStyle(
                      color: Colors.white, fontWeight: FontWeight.bold))),
        );
      },
      markerBuilder: (context, date, event) {
        if (event.isNotEmpty) {
          return Container(
            decoration:
                const BoxDecoration(shape: BoxShape.circle, color: figmaOrange),
            width: 7.0,
            height: 7.0,
            margin: const EdgeInsets.symmetric(horizontal: 1.5),
          );
        }
      },
    ),
    calendarFormat: scheduleViewModel.calendarFormat,
    selectedDayPredicate: (day) {
      return isSameDay(scheduleViewModel.selectedDate, day);
    },
    onDaySelected: (selectedDay, focusedDay) {
      if (!isSameDay(scheduleViewModel.selectedDate, selectedDay)) {
        if (_isBeforeMonth(selectedDay, focusedDay) ||
            _isAfterMonth(selectedDay, focusedDay)) return;
        scheduleViewModel.setSelectedDateAndFocusedDate(
            selectedDay, focusedDay);
      }
    },
    onPageChanged: (focusedDay) {
      scheduleViewModel.selectedDate = focusedDay;
      scheduleViewModel.focusedDate = focusedDay;
      scheduleViewModel.setLabel(
          DateFormat('MMMM, yyyy', scheduleViewModel.locale)
              .format(focusedDay));
      scheduleViewModel.refreshSlots();
      scheduleViewModel.numOfEvents = [];
      scheduleViewModel.setNumOfEvents();
    },
  );
}`

This is how it looks on mobile:
[device-2022-11-01-134956.webm](https://user-images.githubusercontent.com/43584323/199226382-b277d3b4-e960-4a37-bb32-f18ae7df23e9.webm)

However on web i cannot scroll it. 

Can you help? 

Thanks

**Comment by aleksanderwozniak** [comment]
Hi, I assume you are using mouse input for the web. Check out this Flutter doc - https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag.
