### ISSUE TITLE
small dots and holidays

### ISSUE THREAD

**Issue by bahaTRKGLU** [aleksanderwozniak/table_calendar#74]
this study is very nice, great and good. thanks a lot very much.

How do I remove small dots that indicate the number of events below the date?

I do not see the days of holidays in the calendar defined at the beginning of the page?
I can see events but I can't see holidays

final Map<DateTime, List> _holidays = {
  DateTime(2019, 1, 1): ['New Year\'s Day'],
  DateTime(2019, 1, 6): ['Epiphany'],
  DateTime(2019, 2, 14): ['Valentine\'s Day'],
  DateTime(2019, 4, 21): ['Easter Sunday'],
  DateTime(2019, 4, 22): ['Easter Monday'],
 DateTime(2019, 6, 23): ['my birthday'],
};

**Comment by bahaTRKGLU** [comment]
remove dots 

calendarStyle: CalendarStyle(
        markersMaxAmount: 0,

**Comment by aleksanderwozniak** [comment]
**Holidays** are marked with red color by default. Check out Valentine's Day for example - should be in red despite being in the middle of the week.

To remove event markers (aka. dots) simply do not pass any **events** into `TableCalendar` widget.

If for some reason you want to pass events, but do not want to see event markers, then using `markersMaxAmount: 0` is a valid solution.
