### ISSUE TITLE
UTC / Local DateTime inconsistency

### ISSUE THREAD

**Issue by ioma8** [aleksanderwozniak/table_calendar#741]
**Describe the bug**  
Throught the library there are incosistent usages of dateTime with either isUtc=true or isUtc=false.

**Example:**  
```
DateTime normalizeDate(DateTime date) {
  return DateTime.utc(date.year, date.month, date.day);
}
```
- focusedDay, firstDay, lastDay are in constructor 'force' converted to UTC with the above method. I say 'force' converted because the local date is not actually converted, it is just casted as UTC even when its not. From this it would seem that inside the library you would work with all times in this specific format and return it as before.
- But other places do not do the same. Eg the params 'rangeStartDay' and 'rangeEndDay' are not converted through the function normalizeDate, but inside the code are compare with the 'normalized' values!
- Also when returning, the dates (in callbacks like 'selectedDayPredicate', 'onDaySelected, 'onPageChanged') are not converted back! So you falsely 'convert' local input dates to UTC, without actually converting them (not changing the actual value) but when outputting the values you do not do the opposite so users determine its been converted to UTC by getting the value of isUTC prop, but its false, cause the local value has not been actually converted to UTC (local). Its local time just with utc flag. But user mislead that it is in UTC would convert it to local which would give them _bad_ dateTime.

**Why is this problem**  
Apart from obvious incosistency which is bad looking it has few big drawbacks. Mainly that when comparing two dates (eg in 'selectedDayPredicate') sometimes only the beginnings of days are compared. That means 0 hours 0 minutes in the morning. But when the local timezone is eg -1 or more, the day converted to UTC would be actually the previous day, so some implementations of isSameDay or other functions would not return true.

I had to hack a lot to be able to use the library in my application with getting consistent results. Basically normalizing all inputs / outputs of the library and making sure I am in all places working in the same realms of DateTime in types: local, UTC, fakeUTC (as returned by normalizeDate method).

**Proposed solutions**  
Either:  
1. Keep using internally the 'fake' UTC values, but at all places, normalize **ALL** input props AND _unnormalize_ all the returned values (meaning in callbacks).
_or - and I think this should be preferable:_  
2. Remove all internal convertings from utc, to utc, etc and just use 'local' timezone in all places. Also remove the 'fake' UTC converting done by method  'normalizeDate'.

**Comment by aleksanderwozniak** [comment]
DateTimes are getting truncated on purpose, as for a calendar only dates matter (same goes for callbacks). Time actually can cause troubles due to daylight saving offsets. More details here: #393 #544

> * But other places do not do the same. Eg the params 'rangeStartDay' and 'rangeEndDay' are not converted through the function normalizeDate, but inside the code are compare with the 'normalized' values!

Fair enough. For now this should solve it: `_rangeStart = normalizeDate(date);`

What exactly did you have to hack to get consistent results? Apart from manually normalizing date range selection, making use of `isSameDay` to compare two DateTimes should already cover most cases.
