### ISSUE TITLE
weekNumbersVisible is not working

### ISSUE THREAD

**Issue by taqi92** [aleksanderwozniak/table_calendar#742]
**Describe the bug**
I want to remove the week number so i write weekNumbersVisible = false but it still shows the weekNumbersVisible

**To reproduce**
TableCalendar(
            firstDay: DateTime.utc(2010, 10, 16),
            lastDay: DateTime.utc(2030, 3, 14),
            focusedDay: DateTime.utc(year, month, date),
            weekNumbersVisible: false,
            headerVisible: true,
          ),

1. Go to '.Table calender'
2. write 'weekNumbersVisible = false'

**Expected behavior**
weekNumbersVisible shouldn't be visible

**Screenshots**
![Screen Shot 2022-11-15 at 5 28 45 PM](https://user-images.githubusercontent.com/18645814/201908709-de6a9a19-abf8-4f83-ab44-d40b3620cd2b.png)

**Output of `flutter doctor`**

[✓] Flutter (Channel stable, 3.3.2, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by aleksanderwozniak** [comment]
Are you sure you mean "week numbers"? Those are correctly invisible in the attached screenshot. You might be looking for [daysOfWeekVisible](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/daysOfWeekVisible.html) instead.
