### ISSUE TITLE
change calendar structure

### ISSUE THREAD

**Issue by bahaTRKGLU** [aleksanderwozniak/table_calendar#75]
I want the days to be on top of how I can change the structure of the calendar as follows.
<img width="298" alt="Ekran Resmi 2019-06-28 00 40 32" src="https://user-images.githubusercontent.com/30449075/60302980-ebd26600-993d-11e9-956f-c9086d306e4f.png">
<img width="316" alt="Ekran Resmi 2019-06-28 00 40 03" src="https://user-images.githubusercontent.com/30449075/60302985-eecd5680-993d-11e9-9685-fe36a3cebcd0.png">

**Comment by aleksanderwozniak** [comment]
You can use `headerVisible: false` and add your own header below `TableCalendar` widget.
