### ISSUE TITLE
Can we add background style for the days. ? 

### ISSUE THREAD

**Issue by phanindravarma412** [aleksanderwozniak/table_calendar#754]
<img width="389" alt="Screenshot 2022-12-27 at 12 15 01 PM" src="https://user-images.githubusercontent.com/54481207/209623663-7db92c54-fc81-4a05-8557-14baedbde839.png">

**Comment by aleksanderwozniak** [comment]
Yes, please check the [API docs](https://pub.dev/documentation/table_calendar/latest/table_calendar/table_calendar-library.html) for more info.
