### ISSUE TITLE
Not compatible with Intl 0.18.0

### ISSUE THREAD

**Issue by Paroca72** [aleksanderwozniak/table_calendar#755]
Hello

If I update Intl package to the new version 0.18.0 I got an error.

`Because table_calendar 3.0.8 depends on intl ^0.17.0 and no versions of table_calendar match >3.0.8 <4.0.0, table_calendar ^3.0.8 requires intl ^0.17.0.`

Thanks

**Comment by aleksanderwozniak** [comment]
Updated in 3.0.9 release
