### ISSUE TITLE
Change the text on the Header for formatButton based on Locale

### ISSUE THREAD

**Issue by shriharip** [aleksanderwozniak/table_calendar#76]
Thanks for this awesome package. I want to update the headerText for formatButton based on the locale. 
currently, it is set as 
this.availableCalendarFormats = const {
      CalendarFormat.month: 'Month',
      CalendarFormat.twoWeeks: '2 weeks',
      CalendarFormat.week: 'Week',
    },

But the text Month, week, etc. are different in some locale. I hope I am clear or let me know if I am missing something.

**Comment by aleksanderwozniak** [comment]
From [README](https://github.com/aleksanderwozniak/table_calendar#specifying-a-language):

> Note, that if you want to change the language of FormatButton's text, you have to do this yourself. Use availableCalendarFormats property and pass the translated Strings there. Use i18n method of your choice.

You need to read about localization in Flutter, e.g. [here](https://flutter.dev/docs/development/accessibility-and-localization/internationalization)

Then, just substitute Strings in `availableCalendarFormats`:
``` dart
availableCalendarFormats: const {
    CalendarFormat.month: <Localized String for month>,
    CalendarFormat.twoWeeks: <Localized String for two weeks>,
    CalendarFormat.week: <Localized String for week>,
},
```

**Comment by shriharip** [comment]
Thanks. For the reply.

I had tried passing them there but was not showing up on my devices.

Now seeing your response. I tried them again and restarted the app from the start and it is working fine.
