### ISSUE TITLE
Year list picker and month list picker

### ISSUE THREAD

**Issue by szuwest** [aleksanderwozniak/table_calendar#765]
sometimes I need to jump to someday long ago. Now I have to scroll a long time to find it. It is not easy to do that.
If it can show year list picker and month picker(or event day picker), and it will jump to the year or month that I select. That's cool.

**Comment by aleksanderwozniak** [comment]
You can just rebuild the TableCalendar widget with updated `focusedDay` value. Here is a snippet from an example project that will jump to today's date when a button is tapped:

https://github.com/aleksanderwozniak/table_calendar/blob/05db2a2024a78f5ade30eb7b87b0037a829f8a8a/example/lib/pages/complex_example.dart#L110-L115

**Comment by OzanTaskiran** [comment]
@aleksanderwozniak this would just jump to the current date. What he want's is the following:

Many users have to scroll back quite a long time to click on a date in 2017, for example. Is there a way to open a view where you can select a year and the calendar jumps directly to that year?

**Comment by aleksanderwozniak** [comment]
Same concept applies. Add a button (for example in a custom header widget) that will show a year selector, then update the `focusedDay` property with selected year.

**Comment by OzanTaskiran** [comment]
But in my opinion, that would not be the right way. It should be part of the package to take the burden off the developer. 

On the other hand, you could build in your own selection for the year and then work with the focusedDay, as you already mentioned. However, this would be a rather unattractive variant, as one would actually want to "cover" the body of the calendar with the view for the year selection (as with the Material DatePicker, for example).

You can take a look at this here:  https://api.flutter.dev/flutter/material/showDatePicker.html

This could certainly be tricked with a stack and a transition effect, but should still be implemented in the package. You could send a flag to activate or deactivate it (showYearSelection, for example) and have it set to false by default to remain consistent with the package.

**Comment by szuwest** [comment]
> But in my opinion, that would not be the right way. It should be part of the package to take the burden off the developer.
> 
> On the other hand, you could build in your own selection for the year and then work with the focusedDay, as you already mentioned. However, this would be a rather unattractive variant, as one would actually want to "cover" the body of the calendar with the view for the year selection (as with the Material DatePicker, for example).
> 
> You can take a look at this here: https://api.flutter.dev/flutter/material/showDatePicker.html
> 
> This could certainly be tricked with a stack and a transition effect, but should still be implemented in the package. You could send a flag to activate or deactivate it (showYearSelection, for example) and have it set to false by default to remain consistent with the package.

You said what I want to say
