### ISSUE TITLE
Range selection by swiping

### ISSUE THREAD

**Issue by nicky-t** [aleksanderwozniak/table_calendar#767]
**Is your feature request related to a problem? Please describe.**
I would like to accomplish this by swiping from a long tap when selecting a range of dates.

**Describe the solution you'd like**
I want to achieve the above.

**Describe alternatives you've considered**
There are two patterns of solutions.
The first is to increase the number of TableCalender properties and return a function that can do so.
We could use something like GestureDetector's onLongPressMoveUpdate to get both date and position.
Second, optionally be able to override the GesturerDetector used in TableCalender's dayBuilder. Currently, GestureDetector does not work well with the following code.
```
GestureDetector(
  beha
  child: TableCalender(
       firstDay: DateTime(2010, 1, 1),
       lastDay: DateTime(2030, 12, 31),
       focusedDay: focusedDay,

      // Whatever it is, it doesn't work.
      dayHitTestBehavior: HitTestBehavior.translucent
    )
)
```
```
dayBuilder: (context, day, focusedMonth) {
              return GestureDetector(
                behavior: widget.dayHitTestBehavior,
                onTap: () => _onDayTapped(day),
                /* onLongPress: () => _onDayLongPressed(day), */
                child: _buildCell(day, focusedMonth),
              );
            },
```
Commenting out onLongPress as above successfully detected the longTap event by the parent GestureDetector.
A setting that allows onLongPress to be null would solve this problem.

**Additional context**
Thank you Great package!
Sorry if there are any mistakes as this is translated English.

**Comment by aleksanderwozniak** [comment]
You can implement a calendar widget with custom gesture handling on top of `TableCalendarBase` (instead of `TableCalendar`). Give it a try, you'll have much more freedom with how you interact with it.

**Comment by nicky-t** [comment]
Problem solved.
Thank you.

**Comment by ChangDaeJeon** [comment]
I also want exactly the same functionality as the questioner wants.  If the issue is resolved, do you have an example?
