### ISSUE TITLE
Title and icons placement

### ISSUE THREAD

**Issue by buraktahap** [aleksanderwozniak/table_calendar#776]
Is it possible to add a feature for change the placements of title and icons. I want to place icons on the right and title on the left . When I looked in the source code they are defined in a row and I can't place the icons on the right with margin or padding. Most of the people use their phones with right hand and its better user experience that reaching the icons with only right hand fingers easily.

**Comment by buraktahap** [comment]
As I see you can only customize the title in header with calendarBuilders: CalendarBuilders(headerTitleBuilder(){}); . Look at here https://github.com/aleksanderwozniak/table_calendar/blob/master/lib/src/widgets/calendar_header.dart header basically wrapped by a Row and its only customize the right chevron, left chevron and format buttons visibilty. Another way to customize the header is with headerStyle: parameter. Yet with that you can only customize the visibility, paddings icons etc. because this just for the styling. Let me know if you know atoher way to customize the header.

**Comment by buraktahap** [comment]
Sorry I closed by mistake.

**Comment by buraktahap** [comment]
As I see you can only customize the title in header with calendarBuilders: CalendarBuilders(headerTitleBuilder(){}); . Look at here https://github.com/aleksanderwozniak/table_calendar/blob/master/lib/src/widgets/calendar_header.dart header basically wrapped by a Row and its only customize the right chevron, left chevron and format buttons visibilty. Another way to customize the header is with headerStyle: parameter. Yet with that you can only customize the visibility, paddings icons etc. because this just for the styling. Let me know if you know atoher way to customize the header.

**Comment by aleksanderwozniak** [comment]
@buraktahap 
You can implement a CustomHeader widget similarly to the [example project](https://github.com/aleksanderwozniak/table_calendar/blob/103bcb623521b10303e05724feb82649ceee9e78/example/lib/pages/complex_example.dart#L110).
