### ISSUE TITLE
Selecting last day of the month animates whole page

### ISSUE THREAD

**Issue by Sadoge** [aleksanderwozniak/table_calendar#79]
When selecting the last day of the month, it animates as if it were gonna switch to the next month but then stays on the same month. I think it has something to do with the setSelectedDay in the CalendarLogic.

**Comment by oli06** [comment]
Hi @Sadoge,
I'm facing the same issue. Have you fixed this by your own?

**Comment by Sadoge** [comment]
I was only able to fix it by forking the repository and then changing the code of the Calendar Logic, and adding the whole thing to my project.

**Comment by aleksanderwozniak** [comment]
Oops! Thanks for the report!

Fixed with #81 - simply update package to version `1.2.5`
