### ISSUE TITLE
Can the arrow icon be changed ?

### ISSUE THREAD

**Issue by dimas96maulana** [aleksanderwozniak/table_calendar#799]
is it possible to customize the right arrow icon and left arrow icon to have a background, or change the icon to what we want?

![image](https://github.com/aleksanderwozniak/table_calendar/assets/78490592/c715af00-0ae7-4d4a-b0a8-9762a8f7f739)

**Comment by pmatatias** [comment]
Of course.

You can customize the `HeaderStyle`. 
both `rightChevronIcon` and `leftChevronIcon` are Widgets. it's also possible to use image widget like example below.

![image](https://github.com/aleksanderwozniak/table_calendar/assets/33835308/a69b6da0-adfb-4300-86c3-69942aef6fb3)

```dart
TableCalendar<SalesPlanEvent>(
  firstDay: kFirstDay,
  lastDay: kLastDay,
  focusedDay: _focusedDay,
  headerStyle: HeaderStyle(
    formatButtonVisible: false,
    titleCentered: true,
    leftChevronIcon: const Card(
      color: Colors.indigo,
      child: Icon(
        Icons.local_fire_department,
        color: Colors.amber,
      ),
    ),
    rightChevronIcon: Image(
      image: Image.network(
              "https://cdn-icons-png.flaticon.com/512/3050/3050520.png")
          .image,
      width: 24,
      height: 24,
    ),
  ),
....
```
