### ISSUE TITLE
New feature : choose first day in the calendar

### ISSUE THREAD

**Issue by BenoitVerstraete** [aleksanderwozniak/table_calendar#8]
Hi,

First of all, thank you for this wonderful package !

I would like to define the first day displayed in the calendar (switching from "sunday" to "monday"). Do you plan to implement this feature in the future ?

Thank you

**Comment by aleksanderwozniak** [comment]
Thanks :)

I've added `StartingDayOfWeek` enum to package version `0.3.1`. You can now use it to specify week format.

https://pub.dartlang.org/documentation/table_calendar/latest/table_calendar/StartingDayOfWeek-class.html

**Comment by benoitverstraete** [comment]
Thanks @aleksanderwozniak, it works like a charm !
