### ISSUE TITLE
Disable days

### ISSUE THREAD

**Issue by oli06** [aleksanderwozniak/table_calendar#80]
Thanks for this plugin! It's great.

Is there currently a way to define disabled / unavailable days which are inside the min-max date range? E.g I want to disable all sundays.

As an example: The material `
showDatePicker()` function provides a function to disable specific days: 
```dart
selectableDayPredicate: (date) {
            if (date.weekday == DateTime.sunday) {
              return false;
            } else {
              return true;
            }
          },
```

Is there a way to do this in `table_calendar`?

**Comment by aleksanderwozniak** [comment]
Currently there is no such feature. 

It sounds interesting - I'll surely add it.

**Comment by oli06** [comment]
Since I need this feature more or less in the next days, I'll probably implement it by myself.

**Comment by aleksanderwozniak** [comment]
That's even better - go for it :)
