### ISSUE TITLE
UI/UX for localized weeks is off

### ISSUE THREAD

**Issue by praveengitsit** [aleksanderwozniak/table_calendar#800]
I am using the Swahili locale ( `locale: 'sw'` below) with the Table Calendar, and it messes with the UI/UX for how the weeks are padded/margined in the calendar.

Here's the sample code:

```
TableCalendar(
              focusedDay: _focusedDay,
              firstDay: _firstDay,
              lastDay: _lastDay,
              locale: 'sw',
              calendarBuilders: CalendarBuilders(
                /// any calendar builder will do
              ),
          );
```

**Screenshots**
<img width="354" alt="Screenshot 2023-06-15 at 11 09 00" src="https://github.com/aleksanderwozniak/table_calendar/assets/45666428/8c2b3773-4a46-4998-8442-1e992a00348e">

Is there any ongoing PR for this? Maybe I can try and contribute to this

**Comment by aleksanderwozniak** [comment]
Looks like the text is too long and doesn't fit. You could try changing the TextStyle to make it take less space or adjust the `dowTextFormatter` to use a different formatting.

```dart
daysOfWeekStyle: DaysOfWeekStyle(
  weekdayStyle: TextStyle(fontSize: 10),
  weekendStyle: TextStyle(fontSize: 10),
),
```
