### ISSUE TITLE
We need the ability to select the first day of the week (for example, Monday or Sunday).

### ISSUE THREAD

**Issue by Ararat22891** [aleksanderwozniak/table_calendar#806]
The calendar by default considers Sunday as the first day of the week, although it is necessary to have the ability to programmatically set, for example, Monday.

**Comment by developersatisa** [comment]
Yo can use startingDayOfWeek: StartingDayOfWeek.monday,

**Comment by tom-trix** [comment]
It works. Issue may be closed
