### ISSUE TITLE
How to Change the Text Style of DayOfWeek?

### ISSUE THREAD

**Issue by yongrokkwon** [aleksanderwozniak/table_calendar#808]
I am testing various languages for multilingual support. Unfortunately, in some languages, the DayOfWeek text is getting cut off on the screen (for example, only half of 'S' in 'Sun' is visible). I have attempted to modify the Style, but there doesn't seem to be a way to alter the text style of DayOfWeek. Is there a feature available to make such changes?

**Comment by ncdm-stldr** [comment]
Don't know which version you are using but `TableCalendar` does have parameters `daysOfWeekStyle` and `daysOfWeekHeight`.
Does it not work to solve your problem?
