### ISSUE TITLE
new calendarbuilder

### ISSUE THREAD

**Issue by limdnas** [aleksanderwozniak/table_calendar#83]
i need add new calendar builder to add the ability to add color to a series of days that are repeated in a pattern. it would be a new type of event that changes the background color of the days just as selectedDayBuilder does.

**Comment by limdnas** [comment]
return TableCalendar(
      calendarController: _calendarController,
      events: _events,
      holidays: _holidays,
****events: _another****


here how i can get this?

**Comment by aleksanderwozniak** [comment]
You can use existing `CalendarBuilders` for that - check if a `day` matches your pattern, then decorate it accordingly.
