### ISSUE TITLE
missing onVisibleDaysChanged

### ISSUE THREAD

**Issue by bertuz** [aleksanderwozniak/table_calendar#838]
**Describe the bug**
According to the [documentation](https://pub.dev/packages/table_calendar/versions/3.0.9/changelog), the `onVisibleDaysChanged` callback should be there, but once installed via pub.get it's not. Apparently, `onFormatChanged` is

**Comment by aleksanderwozniak** [comment]
`onVisibleDaysChanged` has been removed a long time ago. I'd recommend checking out [setup guide](https://github.com/aleksanderwozniak/table_calendar?tab=readme-ov-file#basic-setup), [examples](https://github.com/aleksanderwozniak/table_calendar/tree/master/example/lib/pages) and maybe [migration guide](https://github.com/aleksanderwozniak/table_calendar/issues/153#issuecomment-772881560).
