### ISSUE TITLE
Not compatible with intl 0.19.0

### ISSUE THREAD

**Issue by robsonsilv4** [aleksanderwozniak/table_calendar#841]
Same issue as opened before, for the version 0.18.0 #755 

```
Because table_calendar 3.0.9 depends on intl ^0.18.0 and no versions of table_calendar match >3.0.9 <4.0.0, table_calendar ^3.0.9 requires intl ^0.18.0.
So, because example depends on both intl ^0.19.0 and table_calendar ^3.0.9, version solving failed.
```

[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2 23C64 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)

**Comment by dnkoulouris** [comment]
A temporary solution is to add a dependency override to your `pubspec.yaml` file.
Add it between your last dependency and the `flutter:` line, like this:
```
dependency_overrides:
  intl: ^0.19.0

```

**Comment by aleksanderwozniak** [comment]
Updated in v3.1.0
