### ISSUE TITLE
Line separator between month name and daysOfWeek

### ISSUE THREAD

**Issue by LorenzoCutrupi** [aleksanderwozniak/table_calendar#850]
Hi, my queestion is very simple.
I want to achieve this:
![image](https://github.com/aleksanderwozniak/table_calendar/assets/80067619/39eb0cfb-e3fb-4779-a0b7-e186db926f87)
But currently I have this:
![image](https://github.com/aleksanderwozniak/table_calendar/assets/80067619/97afaa3d-ed44-4e79-87f5-50ebcf7da454)
How can I add the white horizontal line between the name of the month and the days of the week?

**Comment by RaadShariat** [comment]
You can define the `TableCalendar` header style by setting the `headerStyle` property. If you want the divider between the header and the rest of the calendar, you may specify the `decoration` as a `BoxDecoration` and set the bottom border.
