### ISSUE TITLE
Please upgrade intl

### ISSUE THREAD

**Issue by alexaungmyooo** [aleksanderwozniak/table_calendar#853]
Because table_calendar 3.0.9 depends on intl ^0.18.0 and no versions of table_calendar match >3.0.9 <4.0.0, table_calendar ^3.0.9 requires intl ^0.18.0.
So, because thitsarparami depends on both intl ^0.19.0 and table_calendar ^3.0.9, version solving failed.

**Comment by aleksanderwozniak** [comment]
Updated in v3.1.0
