### ISSUE TITLE
Is this repo abandoned? Recommended alternatives?

### ISSUE THREAD

**Issue by bdelate** [aleksanderwozniak/table_calendar#854]
It looks like this repo has been abandoned since the latest commit or version update has been over 1 year ago.
Looking at the forks there doesn't appear to be any others which have taken over the reigns.

This seemed to be the most popular Flutter calendar package available, however adopting it now is a no go since it is unmaintained.

Having searched for alternatives, I can't seem to find any solid options which are well maintained. Any recommendations would really help.

**Comment by Sun3** [comment]
I would love also to see that this repo is not abandoned, it's a great calendar.

**Comment by aleksanderwozniak** [comment]
No, not at all. Perhaps there were no version updates for a while, but that doesn't necessarily mean that project is abandoned. And it's been up to date with latest Flutter SDK for the whole time.

Bear in mind I'm doing this in my free time, which is of course limited. It's only natural that sometimes other projects require more attention. You can always help out - for example by addressing unresolved issues or reporting encountered bugs.
