### ISSUE TITLE
incompatible with flutter_localizations

### ISSUE THREAD

**Issue by richertc** [aleksanderwozniak/table_calendar#856]
Because app depends on flutter_localizations from sdk which depends on intl 0.18.1, intl 0.18.1 is required.
So, because app depends on intl 0.19.0, version solving failed.

I would argue that flutter_localizations is a decently used dependency. So it would be much appreciated if that could work together.

**Comment by brixxnatt** [comment]
Any fix of this ??

**Comment by aleksanderwozniak** [comment]
From the looks of it `intl` is one of the [pinned packages](https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages) that are tied to a specific Flutter SDK version. This issue will be solved once there is a Flutter release that pins `intl` to 0.19.0.

Right now as a workaround you could use dependency override, or simply downgrade `table_calendar` to 3.0.9.
```yaml
dependency_overrides:
  intl: ^0.18.1
```
