### ISSUE TITLE
Weekly Calendar format does not support overlapping of two months

### ISSUE THREAD

**Issue by PandukaBWedisinghe** [aleksanderwozniak/table_calendar#860]
**Describe the bug**
I am using calendar weekly format, and I want to use it over two months. For instance from 27th Feb 2024, to 4th March 2024.
When I set starting and ending dates as mentioned above, set my own `selectedBuilder`, `defaultBuilder`, the Calendar does not behave as expected. It shows clear split over two months.

**Expected behavior**
Calendar should not distinguish between two months. I kindly expect some assistance here. Thank you!

**Screenshots**

https://github.com/aleksanderwozniak/table_calendar/assets/148055900/a98b5f4f-9ea2-4ce9-aee3-82d6e4a2acb0

**Comment by aleksanderwozniak** [comment]
You can use `outsideBuilder` for this.
