### ISSUE TITLE
Customizing Date Format When Setting Locale to 'ko_KR'

### ISSUE THREAD

**Issue by jimmyjung** [aleksanderwozniak/table_calendar#863]
Hello~

If I set **locale to 'ko_KR'**, dates in the calendar will be displayed with a '일' appended to them.
ex. 1일, 2일, 3일

![cal](https://github.com/aleksanderwozniak/table_calendar/assets/7288946/3627a49c-ef5f-408f-8445-0c9a6baaff67)

I want to set the header to 'ko_KR' to display the day of the week in Korean, and remove the '일' from the date.

Thank you.

**Comment by synstin** [comment]
I agree, I'm getting that letter and it's preventing me from upgrading the version.

**Comment by aleksanderwozniak** [comment]
Hey, thanks for reporting this. I'll add a proper solution with next release, but for now as a workaround you can just use version 3.1.0.

**Comment by jimmyjung** [comment]
> Hey, thanks for reporting this. I'll add a proper solution with next release, but for now as a workaround you can just use version 3.1.0.

Thanks!

I temporarily fixed the issue with the code below
- To set locale : 'en_US'
- To set dowTextFormatter and titleTExtFormatter to ko_KR

```
TableCalendar(
  locale: 'en_US', 
  daysOfWeekStyle: DaysOfWeekStyle(
    dowTextFormatter: (date, locale) => DateFormat.E('ko_KR').format(date)[0],
	...
  ),
  headerStyle: HeaderStyle(
    titleTextFormatter: (date, locale) => DateFormat('yyyy년 M월', 'ko_KR').format(date),
    ...
  ),
  ...
```
