### ISSUE TITLE
No option for removing cell text localization

### ISSUE THREAD

**Issue by Tasuku24** [aleksanderwozniak/table_calendar#868]
I've been using this widget with the localization set to 'ja_JP.'
When I changed the version of table_calendar from 3.1.0 to 3.1.1, the letter '日' was displayed in all the cells which isn't ideal for my application's overall design.
It would help if you implemented an option where you can toggle the text localization on and off in the future version.

<img src="https://github.com/aleksanderwozniak/table_calendar/assets/86112012/5be5026c-9e7c-4140-852a-0ae474105c4c" width="50%" />
<img src="https://github.com/aleksanderwozniak/table_calendar/assets/86112012/5cd3e22c-6c08-426b-98c5-cd6e3530d357" width="50%" />

**Comment by Somtobro** [comment]
Bro, totally random but, any idea on how to implement day to day swiping?
