### ISSUE TITLE
UI issues in Calendar which has holiday list

### ISSUE THREAD

**Issue by R1235** [aleksanderwozniak/table_calendar#87]
HI,
I did git clone and just ran the example code. it's working good.
But when I uncommented _buildTableCalendarWithBuilders(), and commented _buildTableCalendar(), am getting errors in the App for the months( Jan, Feb, Apr) which have holidays as mentioned in the code.
I have attached screenshots also.Please help me to fix this issue.
TIA.
![device-2019-07-31-112715](https://user-images.githubusercontent.com/10954347/62187545-59334580-b387-11e9-839b-989222fcaeee.png)
![device-2019-07-31-112741](https://user-images.githubusercontent.com/10954347/62187546-59cbdc00-b387-11e9-87b9-0ce0c5abeea4.png)
![device-2019-07-31-112755](https://user-images.githubusercontent.com/10954347/62187547-59cbdc00-b387-11e9-8ce2-a1add015eb64.png)

**Comment by elrafal** [comment]
In calendar.dart file should be "visibleHolidays" instead of "visibleEvents" in line:
final holidays = holidayKey != null ? widget.calendarController.visibleEvents[holidayKey] : [];
like this:
final holidays = holidayKey != null ? widget.calendarController.visibleHolidays[holidayKey] : [];

**Comment by aleksanderwozniak** [comment]
Good catch guys, thanks!
I'll update the package today.

**Comment by aleksanderwozniak** [comment]
Fixed in version `2.0.1` :)

**Comment by R1235** [comment]
@elrafal  Thank you for the reply.

**Comment by R1235** [comment]
@aleksanderwozniak  Thank you... let me try it.
