### ISSUE TITLE
how i can change selected date from other action, not click the date

### ISSUE THREAD

**Issue by stevanus1997** [aleksanderwozniak/table_calendar#88]

**Comment by pvsvamsi** [comment]
Assign the new dateTime to the selectedDay parameter (Table Calendar 1.2.5) or initialSelectedDay parameter (Table Calendar 2.0.0)

**Comment by aleksanderwozniak** [comment]
You can use [Calendar Controller](https://pub.dev/documentation/table_calendar/latest/table_calendar/CalendarController-class.html):
```dart
_calendarController.setSelectedDay(DateTime(2019, 7, 10), runCallback: true);
```
