### ISSUE TITLE
New feature : dayBuilder to customize Day Widget

### ISSUE THREAD

**Issue by benoitverstraete** [aleksanderwozniak/table_calendar#9]
Hi,

Do you plan to implement a new feature that allow the developer to customize the widget displayed for days (like special bullet, different color depends on condition, etc.) ?

For example: 
```
dayBuilder: (BuildContext context, DateTime day) { 
 return Text('Test'); 
}
```

Thanks a lot !

Ben

**Comment by aleksanderwozniak** [comment]
Definitely! I've had something like this in mind even before I started working on the package.

I do, however, need to think it through. I consider exposing some internal logic APIs to further enhance the builders. We will see how it goes.

**Comment by pmcarlos** [comment]
> Hi,
> 
> Do you plan to implement a new feature that allow the developer to customize the widget displayed for days (like special bullet, different color depends on condition, etc.) ?
> 
> For example:
> 
> ```
> dayBuilder: (BuildContext context, DateTime day) { 
>  return Text('Test'); 
> }
> ```
> Thanks a lot !
> 
> Ben

this can help https://pub.dartlang.org/packages/flutter_clean_calendar

**Comment by aleksanderwozniak** [comment]
@benoitverstraete 
I've added a whole set of custom Builders. You should check out version `1.0.0`!

As always, it might be beneficial to visit [API docs](https://pub.dartlang.org/documentation/table_calendar/latest/table_calendar/table_calendar-library.html), and/or look at [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart).

**Comment by sharpsan** [comment]
There is a `weekendBuilder` but not a `weekdayBuilder`.  I see there is a `dayBuilder` builder, but this overwrites all other builders, including `outsideWeekendDayBuilder` and so on.
