### ISSUE TITLE
selectedDay events not loading on init

### ISSUE THREAD

**Issue by traceyjas** [aleksanderwozniak/table_calendar#90]
When the page is loaded if the current day has events it does not load them until i tap on the day. How can i load the events on initial load without tapping?

**Comment by viniciuscrp** [comment]
I've had done a workaround for this, I don't know if you can apply this to your project but what I did was this
`class _EventScreenState extends State<EventScreen>
    with TickerProviderStateMixin {
  CalendarController _calendarController;
  AnimationController _animationController;
  List _selectedEvents;
  DateTime _selectedDay;
  Map<DateTime, List> _events;
  bool isLoading = true;

  @override
  void initState() {
    super.initState();
    getEvents().then((data) {
      if (data != null) {
        setState(() {
          // Get the current date 
          _selectedDay = new DateTime.now();
          // Mapped my events using a custom generated date(key) which ignores hour, minutes, seconds, milliseconds and microseconds
          _events = groupBy(data, (obj) => DateTime(obj.date.year, obj.date.month, obj.date.day));
          // Select events using the same key format as used above
          _selectedEvents = _events[DateTime(_selectedDay.year, _selectedDay.month, _selectedDay.day)] ?? [];
          isLoading = false;
        });
      } else {
        setState(() {
          _events = {};
          _selectedEvents = [];
          isLoading = false;
        });
      }
    });
    _calendarController = CalendarController();
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 300),
    );
    _animationController.forward();
  }`

**Comment by traceyjas** [comment]
Thanks I'll try it and see if it works

**Comment by aleksanderwozniak** [comment]
@traceyjas 
You can follow the example project:
```dart
@override
void initState() {
  super.initState();
  final _selectedDay = DateTime.now();

  _events = {
    _selectedDay.subtract(Duration(days: 30)): ['Event A0', 'Event B0', 'Event C0'],
    _selectedDay.subtract(Duration(days: 27)): ['Event A1'],
    _selectedDay.subtract(Duration(days: 20)): ['Event A2', 'Event B2', 'Event C2', 'Event D2'],
    _selectedDay.subtract(Duration(days: 16)): ['Event A3', 'Event B3'],
    _selectedDay.subtract(Duration(days: 10)): ['Event A4', 'Event B4', 'Event C4'],
    _selectedDay.subtract(Duration(days: 4)): ['Event A5', 'Event B5', 'Event C5'],
    _selectedDay.subtract(Duration(days: 2)): ['Event A6', 'Event B6'],
    _selectedDay: ['Event A7', 'Event B7', 'Event C7', 'Event D7'],
    _selectedDay.add(Duration(days: 1)): ['Event A8', 'Event B8', 'Event C8', 'Event D8'],
    _selectedDay.add(Duration(days: 3)): Set.from(['Event A9', 'Event A9', 'Event B9']).toList(),
    _selectedDay.add(Duration(days: 7)): ['Event A10', 'Event B10', 'Event C10'],
    _selectedDay.add(Duration(days: 11)): ['Event A11', 'Event B11'],
    _selectedDay.add(Duration(days: 17)): ['Event A12', 'Event B12', 'Event C12', 'Event D12'],
    _selectedDay.add(Duration(days: 22)): ['Event A13', 'Event B13'],
    _selectedDay.add(Duration(days: 26)): ['Event A14', 'Event B14', 'Event C14'],
  };

  _selectedEvents = _events[_selectedDay] ?? [];
...
```

`_selectedEvents` will contain the events that you want

**Comment by sigano08** [comment]
Vinícius, estou criando meu primeiro projeto e estou com esse mesmo problema no meu calendário..
Eu coloco ele para aparecer somente no formato mensal, mas todos os eventos que crio aparentemente são salvos no formato semanal. Não entendo porque isso acontece... quando seleciono um dia com o calendário no formato semanal todos os eventos desse dia aparecem, mas quando faço a mesma coisa usando o formato mensal é como se não houvesse evento criado.

**Comment by sigano08** [comment]
@viniciuscrp , estou criando meu primeiro projeto e estou com esse mesmo problema no meu calendário..
Eu coloco ele para aparecer somente no formato mensal, mas todos os eventos que crio aparentemente são salvos no formato semanal. Não entendo porque isso acontece... quando seleciono um dia com o calendário no formato semanal todos os eventos desse dia aparecem, mas quando faço a mesma coisa usando o formato mensal é como se não houvesse evento criado.
